### ISSUE TITLE
Unable to install my package

### ISSUE THREAD

**Issue by italomaia** [luarocks/luarocks#1010]
I'm unable to install my package. If I try to install it 
```
italomaia@me ~> luarocks install --local lua_fun 0.4-1
Installing https://luarocks.org/lua_fun-0.4-1.rockspec

Error: Couldn't extract archive /tmp/luarocks_luarocks-source-lua_fun-0.4-1-7286607/lua_fun: unrecognized filename extension
```
What could be causing it?

**Comment by daurnimator** [comment]
There is an issue with the rockspec: `source.url` should be a download archive url. That rockspec currently has:
```
    url = "https://github.com/italomaia/lua_fun",
```

If you intended it to be downloaded with git, you should use a scheme of `git+https://`
