### ISSUE TITLE
Unzip not found on FreeBSD

### ISSUE THREAD

**Issue by kdbeall** [luarocks/luarocks#1022]
When `unzip` is installed through `pkg` on FreeBSD, luarocks incorrectly detects `unzip` as not installed. A workaround is described [here](http://lua.2524044.n2.nabble.com/LuaRocks-3-0-4-on-FreeBSD-unzip-not-found-td7684719.html).

**Comment by kdbeall** [comment]
Steps to reproduce:

    vagrant init freebsd/FreeBSD-11.2-RELEASE
    vagrant up
    vagrant ssh

**Comment by hishamhm** [comment]
@kdbeall As stated in that link, `unzip` in FreeBSD does not offer any way for us to test-run the command and make it return success (`0`) (help returns error (`1`), no version flag). 

We do the test run to provide users with a nicer error message when `unzip` is not available (and to do some baseline checking that the program we're calling works like the one we are expecting to call — in that regard, the code is doing what it's supposed to, as it detected that the `unzip` there is not the one we tested LuaRocks with).

Is `unzip` always preinstalled in FreeBSD base systems? If so we could just skip that test on FreeBSD.

**Comment by kdbeall** [comment]
@hishamhm unzip has been always preinstalled in FreeBSD base systems since 8. So, it should be safe to simply skip the unzip.

**Comment by siffiejoe** [comment]
Or we could ship a minimal zip-compressed string, dump it into a temporary file, and run unzip on it.

**Comment by hishamhm** [comment]
@siffiejoe that could work but sounds like overkill, especially at runtime.

**Comment by kdbeall** [comment]
@hishamhm it would probably be easiest to simply check if the platform is FreeBSD

**Comment by kdbeall** [comment]
I'd put in a PR request myself, but I'm unfortunately not super familiar with Lua :(

**Comment by kdbeall** [comment]
Thanks @hishamhm!
