### ISSUE TITLE
luarocks bundle export

### ISSUE THREAD

**Issue by nicopace** [luarocks/luarocks#1023]
Hi folks,
Thanks for a so good platform!
Have a question regards systems that can't use luarocks (like embedded devices).
A lot of libraries are starting to support luarocks, and while this is amazing some of the architectures lua runs don't have the ability to run it (the payload maybe too heavy). One of these cases are the OpenWRT environment, were the routers that are lua enabled can't use it.
One way of giving support for these environments (and so many others like little embedded devices) would be for luarocks to build one single lua output file with all the modules in it, in a similar fashion as what javascript bundlers do (like rollup, webpack, browserify and others).
This things basically get a set of libraries on one end, and export one single file on the other end.
Is this possible with LuaRocks? and if not, could this be possible? 
Thanks again!

**Comment by nicopace** [comment]
To deepen the explaination, we are trying to use [busted](https://luarocks.org/modules/olivine-labs/busted} inside OpenWRT.
We did some attempts to do that following [this amazing suggestion](https://leafo.net/guides/customizing-the-luarocks-tree.html), and got actually almost there.
The only complication was that the library had C external dependencies that were not binary compatible across architectures (I am using x86-64 and the target architecture is mips).
It still sounds a very compelling use case for any library that has no C extension, or even to cross compile it may mean that a lot of embedded devs would be including it inside luarocks too (and doing their bundles in here).

**Comment by daurnimator** [comment]
A bundler is a very different beast to a cross compiler.

For the former, check out [squish](http://matthewwild.co.uk/projects/squish/home) or [luacc](https://github.com/mihacooper/luacc).

**Comment by nicopace** [comment]
I agree... thanks for the suggestion!
I actually got quite far from what I expected... but the only dependency that has a C extension is [luafilesystem](https://github.com/keplerproject/luafilesystem) and it has [a lua-only implementation](https://github.com/sonoro1234/luafilesystem), but this one has no luarocks rockspec, so I can't install it over there and thus don't know how to tackle it.

I will dig into this deeper later if possible... and report back here so if someone stumbles over the same rock they have some feedback.

For now, thank you for this amazing tool!
