### ISSUE TITLE
How to tell luarocks which generator should be use instead of the default generator when using CMake?

### ISSUE THREAD

**Issue by tan-wei** [luarocks/luarocks#1025]
[lrdb](https://github.com/satoren/LRDB) uses `CMake` to build native codes. However, `CMake` uses default generator `VS 2019` instead of `VS 2017` which is used by `Luarocks`. So it will failed because my `Luarocks` works with x86, not the default x64 for `VS 2019`.

How do I tell `Luarocks` or `CMake` the right generator? Thanks!

**Comment by tan-wei** [comment]
Maybe modifying `cfg.lua` is a solution.
Adding
```lua
defaults.cmake_generator = "Visual Studio 15 2017"
```
under the corresponding platform works well.

So is there any other solutions?

**Comment by hishamhm** [comment]
With the latest LuaRocks, simply type:

`luarocks config cmake_generator "Visual Studio 15 2017"`

all entries from `defaults` in `cfg.lua` can be edited like this.

**Comment by tan-wei** [comment]
@hishamhm That's convenient! Thanks very much.
