### ISSUE TITLE
Advice to speed up nix luarocks updater

### ISSUE THREAD

**Issue by teto** [luarocks/luarocks#1027]
follow up of https://github.com/luarocks/luarocks/issues/743.

Sicne you seemed interesting in our use of luarocks in nix, here is some feedback/question:
The support of luarocks packages into nix has kept improving so that I've been able to convert more and more manual nix packages to generated nix packages. 
My problem right now is that the process to generate the packages is slow. Rather than looking at the code, I wondered if you had any idea how to speed up this ?
Basically we have an updater https://github.com/NixOS/nixpkgs/blob/master/maintainers/scripts/update-luarocks-packages that takes as input a list of packages https://github.com/NixOS/nixpkgs/blob/master/maintainers/scripts/luarocks-packages.csv .
It calls my (ugly) fork https://github.com/teto/luarocks/tree/nix (just adds a `nix` command that outputs nix code) on each package of the list to generate
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/lua-modules/generated-packages.nix

The problem is that on every call it downloads something from the server (the manifest?). Is there an option to cache the results ? or maybe I should download them in advance and specify local manifests ?

**Comment by hishamhm** [comment]
There should be a cache for the manifest. Something in your environment may
be causing it to not br picked up. Predownloading the repo into a local
manifest should also work, might be easier than trying to figure the cache
out.

>

**Comment by teto** [comment]
I had a look I think it's my code that fetches rock files unconditionnaly. I should fetch them only if their version is new.
sry for the noise.

**Comment by teto** [comment]
is there a native API to cache rock/rockspec ? or should I implement it myself ?

**Comment by hishamhm** [comment]
> is there a native API to cache rock/rockspec ?

I'm not sure exactly what you mean, but no, only manifests are cached, not rocks/rockspecs.
