### ISSUE TITLE
Make install should always use phony targets

### ISSUE THREAD

**Issue by craigbarnes** [luarocks/luarocks#1038]
The makefile currently specifies files for installation as individual "normal" targets, for example:

```make
$(DESTDIR)$(bindir)/luarocks: $(builddir)/luarocks
        mkdir -p "$(@D)"
        $(INSTALL) "$<" "$@"
```

...but there's a reason almost no one uses normal targets for installation like this -- it fails to install if the target is newer than the dependency (which can and does happen for various reasons) and also becomes extremely buggy if [`.DELETE_ON_ERROR`](https://www.gnu.org/software/make/manual/html_node/Special-Targets.html) is ever enabled (which the `make` manual [recommends](https://www.gnu.org/software/make/manual/html_node/Errors.html)).

The only correct way to install built files is to use one or more phony targets that run the commands one-by-one _unconditionally_, e.g.:

```make
install: all
	mkdir -p '$(DESTDIR)$(bindir)/'
	$(INSTALL) '$(builddir)/luarocks' '$(DESTDIR)$(bindir)/luarocks'
	# etc....

.PHONY: install
```

**Comment by blueyed** [comment]
Yes, also just noticed this.. installing 3.1.3 over 2.4.4 will not update all files, resulting in a broken installation.

**Comment by craigbarnes** [comment]
I guess the workaround is to use `make -B`.

**Comment by blueyed** [comment]
Does not work:
```
Please run the ./configure script before building.

make[1]: *** No rule to make target 'config.unix', needed by 'luarocks'.  Stop.
```

**Comment by craigbarnes** [comment]
Ah yeah, that looks like another bug in the makefile then. It uses a target (`config.unix`) with no dependencies to determine whether or not `configure` has been run -- but assuming a target never gets rebuilt because it has no dependencies is clearly broken.
