### ISSUE TITLE
Error when trying to install anything (Lua 5.4)

### ISSUE THREAD

**Issue by Dude112113** [luarocks/luarocks#1060]
```
C:\Users\dude112113>luarocks install luasocket
Installing https://luarocks.org/luasocket-3.0rc1-2.src.rock

Error: LuaRocks 3.1.3 bug (please report at https://github.com/luarocks/luarocks/issues).
Arch.: win32-x86
C:\Program Files (x86)\LuaRocks\lua\luarocks\rockspecs.lua:108: attempt to compare two table values
stack traceback:
        C:\Program Files (x86)\LuaRocks\lua\luarocks\rockspecs.lua:108: in method 'format_is_at_least'
        C:\Program Files (x86)\LuaRocks\lua\luarocks\rockspecs.lua:145: in function 'luarocks.rockspecs.from_persisted_t
able'
        C:\Program Files (x86)\LuaRocks\lua\luarocks\fetch.lua:232: in function 'luarocks.fetch.load_local_rockspec'
        (...tail calls...)
        C:\Program Files (x86)\LuaRocks\lua\luarocks\cmd\build.lua:79: in function <C:\Program Files (x86)\LuaRocks\lua\
luarocks\cmd\build.lua:61>
        (...tail calls...)
        C:\Program Files (x86)\LuaRocks\lua\luarocks\cmd\build.lua:182: in function 'luarocks.cmd.build.command'
        (...tail calls...)
        [C]: in function 'xpcall'
        C:\Program Files (x86)\LuaRocks\lua\luarocks\cmd.lua:450: in function 'luarocks.cmd.run_command'
        C:\Program Files (x86)\LuaRocks\luarocks.lua:36: in main chunk
        [C]: in ?
```

same with `luarocks install lpeglabel`

Im using `Lua 5.4` and it was working for `Lua 5.3` fine.

**Comment by daurnimator** [comment]
This seems to be caused by Lua 5.4 not falling back to `__lt` for a less-than-equal operation.

**Comment by Dude112113** [comment]
So would this be a bug with `Lua 5.4`? as i did not read anything about `__lt` changing.

**Comment by daurnimator** [comment]
https://github.com/lua/lua/commit/8c8a91f2ef7acccb99e3737913faad8d48b39571

**Comment by Dude112113** [comment]
Ahh now i got it, and i got `__lt` to error after reading that.
Soo... i guess i will just have to wait on a fix for luarocks?

**Comment by daurnimator** [comment]
> Soo... i guess i will just have to wait on a fix for luarocks?

Yep. If you're in a coding mood, the fix should be adding a `__le` metamethod to src/luarocks/core/vers.lua

**Comment by Dude112113** [comment]
after a quick read of how exactly `__le` would work without the metamethod `__le` and just implemented that.
`src/luarocks/core/vers.lua` ln`59`
```lua
    -- @param v1 table: version table to compare.
    -- @param v2 table: version table to compare.
    -- @return boolean: true if v1 is considered lower than or equal to v2.
    __le = function(v1, v2)
        return not (v2 < v1)
    end,
```

i don't really know how to do a pull-request or what-not and i have not tested on other versions.

**Comment by hishamhm** [comment]
> i don't really know how to do a pull-request or what-not and i have not tested on other versions.

@Dude112113 You might want to give this a try: [How to make a pull request on GitHub - a quick tutorial](http://hisham.hm/2016/01/01/how-to-make-a-pull-request-on-github-a-quick-tutorial/) and make your first code contribution! :)

**Comment by Dude112113** [comment]
since this i have made a fair few pull requests, i just forgot about this issue but just check my email and remembered this so i made that PR

**Comment by hishamhm** [comment]
Thank you for the patch!!
