### ISSUE TITLE
Not able to install kong-plugin-jwt-keycloak with LuaRocks version 5.1

### ISSUE THREAD

**Issue by aarti-stack** [luarocks/luarocks#1061]
I am trying to install kong-plugin-jwt-keycloak plugin with luarocks-3.1.3-win32.zip (legacy Windows package, includes Lua 5.1). 
Tried with all the availalable version of plugin but none of them works.

Following is the error while installing plugin:
C:\WINDOWS\system32>luarocks install kong-plugin-jwt-keycloak-1.0.0-1
kong-plugin-jwt-keycloak-1.0.0-1 not found for Lua 5.1.
Checking if available for other Lua versions...
Checking for Lua 5.2...
Checking for Lua 5.3...
Checking for Lua 5.4...

Error: No results matching query were found for Lua 5.1.

**Comment by hishamhm** [comment]
@aarti-stack Are you trying to run Kong on Windows??

**Comment by hishamhm** [comment]
In any case, the package and version number should be separate:

```
luarocks install kong-plugin-jwt-keycloak 1.0.0-1
```

**Comment by aarti-stack** [comment]
> In any case, the package and version number should be separate:
> 
> ```
> luarocks install kong-plugin-jwt-keycloak 1.0.0-1
> ```



> @aarti-stack Are you trying to run Kong on Windows??

I am trying to run on Windows

**Comment by aarti-stack** [comment]
i did tried to run the command as mentioned above but i received the following error:
C:\tmp\luarocks-3.1.3-win32>luarocks install kong-plugin-jwt-keycloak 1.0.3-1
Installing https://luarocks.org/kong-plugin-jwt-keycloak-1.0.3-1.rockspec

Error: This rockspec for kong-plugin-jwt-keycloak does not support mingw, mingw32, win32, windows platforms.

**Comment by hishamhm** [comment]
It's exactly what it says: This rockspec for kong-plugin-jwt-keycloak does not support mingw, mingw32, win32, windows platforms.
