### ISSUE TITLE
404 when following link to download 3.2.1

### ISSUE THREAD

**Issue by RussellHaley** [luarocks/luarocks#1085]
Hi, 

I get a 404 when trying to download the latest release from the download page here:
https://github.com/luarocks/luarocks/wiki/Download

The link is https://luarocks.github.io/luarocks/releases/luarocks-3.2.1.tar.gz

A review of the releases page shows there is no file:
https://luarocks.github.io/luarocks/releases/

Thanks
Russ

**Comment by daurnimator** [comment]
I think it just some amount of time to get uploaded after the release.
