### ISSUE TITLE
luarocks and config file

### ISSUE THREAD

**Issue by teto** [luarocks/luarocks#1086]
With the new release of luarocks, I've updated my fork and how nixpkgs converts luarocks packages into nix packages.
One thing I realized is that you can't override the configuration file from the command line.
You have to export LUAROCKS_CONFIG. I would prefer a flag since that makes the usage of a specific config more explicit.
Also, right now user config is in $HOME/.luarocks. Supporting the XDG spec would be cleaner. aka installing config in $XDG_CONFIG_HOME/luarocks (that I could share via my dotfiles) and the cache in $XDG_CACHE_HOME/luarocks (that I can prune easily).

thanks for your work on luarocks.

**Comment by hishamhm** [comment]
@teto A patch for this is welcome!
