### ISSUE TITLE
Use standard variables for `configure` script

### ISSUE THREAD

**Issue by namandixit** [luarocks/luarocks#1087]
GNU Configure defines a lot of [default variables](https://www.gnu.org/prep/standards/html_node/Directory-Variables.html) and [flags](http://bluefish.openoffice.nl/manual/ch02s05.html) to allow customizing the installation (bindir, etc.). However, Luarocks only uses the `prefix` and `sysconfdir` variables.

I have a very specialized installation setup for my tools -- for example, the binaries for x64 Linux go into `{prefix}/bin/linux/x64`, etc. With a properly written configure script, I can easily change the installation paths to suit my workflow. However, because Luarocks doesn't allow it, I are unable to use it.

Will it be possible to support the configure variables properly in order to enable installation customization?

**Comment by daurnimator** [comment]
> Will it be possible to support the configure variables properly in order to enable installation customization?

I think I'd be happy to accept a PR that added it.

**Comment by daurnimator** [comment]
Note that our makefile already accepts [`datadir`](https://github.com/luarocks/luarocks/blob/83093e7da7f789f0f7d3a6784597cbbed09c73e0/GNUmakefile#L4) [`bindir`](https://github.com/luarocks/luarocks/blob/83093e7da7f789f0f7d3a6784597cbbed09c73e0/GNUmakefile#L5) and a few others.

**Comment by namandixit** [comment]
> I think I'd be happy to accept a PR that added it.

Sure, I would be happy to help. From what I can see, all the `configure` script does is create a `config.unix` file with a bunch of variable definitions which then gets included in the `GNUmakefile`. That is all, right?

**Comment by namandixit** [comment]
I managed to make it work using the Makefile's variables, closing...
