### ISSUE TITLE
Batch scripts are not self-contained

### ISSUE THREAD

**Issue by cloewen8** [luarocks/luarocks#1094]
# Issue
When installing either *busted* or *ldoc*, their batch scripts are not self-contained, preventing them from being included in version control without either,
- every user having the exact same versions of each dependency in the same place (very unlikely),
- or the batch scripts need to be modified to use environment variables in un-escaped scripts.

# Solution
The best solution, for me, would be to remove any dependence on the LuaRocks installation and make any references to files within the same tree relative using the `%~dp0` environment variable. `LUAROCKS_SYSCONFDIR` really should be a system environment variable (not defined in every script) if it is ever needed.

I would be willing to work on a pull request for this if I can figure out how to make this change and this is not just a bug with my configuration.

## Temporary workaround
I chose to manually edit the batch scripts in the mean time. The basics steps:
- In any Lua code, I switch out double quoted strings for bracket strings, which allow for back-slashes without requiring escaping.
- Whenever I find any reference to the repository, I replace it with `%CD%` (which is the current working directory, which is fine for my use case, since it will always be the repository).
- Neither of the rocks depend on `LUAROCKS_SYSCONFDIR`, so I removed it entirely.

**Comment by hishamhm** [comment]
> When installing either busted or ldoc, their batch scripts are not self-contained, preventing them from being included in version control

I'm not sure I follow: those generated files are _not meant_ to be included in version control: instead, they are generated upon installation. Think of them as the executables produced by building Busted with `luarocks install busted`. You should be version-controlling your source tree, and not the rocks pulled by LuaRocks — those should be pulled as `dependencies` (or `build_dependencies`, or `test_dependencies`) when your project is built/installed.

**Comment by cloewen8** [comment]
My mistake, I did not think of this strategy of having a rock configuration specify what was required (even though I do this for every other package manager). I still feel like it is a bit deceiving calling rocks self-contained, if this is not a concern feel free to close this issue. I'm no longer concerned.
