### ISSUE TITLE
Question about rockspec-format docs, in particular to build.install

### ISSUE THREAD

**Issue by imolein** [luarocks/luarocks#1097]
Hi,

reading the rockspec-format docs, about `build.install` confused me a bit. It says:

> **build.install** (table) - For packages which don't provide means to install modules and expect the user to copy the .lua or library files by hand to the proper locations.

I understand this part as you can define there modules, but they're not installed/copied during `luarocks install`, instead expecting the user to copy the files by itself. But the second sentence after this one says:

> Each category is itself a table, where the array part is a list of filenames to be copied.

So the files are getting installed/copied after all? So what does the first sentence mean?

And if files defined in `build.install` get copied, what is the difference to the `modules` table of the `build`-backend `builtin`? Which is the preferred way to use, if I have a pure Lua module, for which I want to write a rockspec?

thanks

**Comment by hishamhm** [comment]
> And if files defined in build.install get copied, what is the difference to the modules table of the build-backend builtin?

For Lua files it works out the same. `build.install.bin` is useful for installing scripts. `build.install` for Lua files is older than the `builtin` backend, and was kept around for backward compatibility reasons.

>  Which is the preferred way to use, if I have a pure Lua module, for which I want to write a rockspec?

The `builtin` backend is preferred!

Hope that clarifies things!

**Comment by imolein** [comment]
Yes, thanks a lot! :)
