### ISSUE TITLE
"make" flag "--deps-only" still install the rock itself

### ISSUE THREAD

**Issue by Tieske** [luarocks/luarocks#1098]
Using LuaRocks `3.1.2`:
```
luarocks make --deps-only
```
will accept the flag, but will still install the rock itself as well

```
luarocks install <full-spec-name> --deps-only
```

does work as expected.

**Comment by pauloue** [comment]
Do you mean `--only-deps`? I don't think that flag was ever supposed to work with the make command because make only builds from the current directory.

**Comment by Tieske** [comment]
That's exactly why I tried it. It didn't give me an error, but also didn't work.

I use it for test purposes, to install dependencies before I run the tests against the local source code. Since its automated, I'd rather skip an extra script to collect the filename required when using `LuaRocks install `.

**Comment by hishamhm** [comment]
It would make sense for the flag to work with `luarocks make`, meaning "please install the dependencies specified in the rockspec in the current directory"

**Comment by hishamhm** [comment]
Latest luarocks now gives a proper error message (thanks to argparse integration) so the bug described here no longer happens. Will open a separate feature request entry for adding `luarocks make --only-deps`
