### ISSUE TITLE
Can't run any luarocks command

### ISSUE THREAD

**Issue by liamaharon** [luarocks/luarocks#1117]
Followed the instructions here: https://github.com/luarocks/luarocks/wiki/Installation-instructions-for-Unix

running `luarocks` with or without any additional arguments throws an error:
```
liam@sleeper:~$ luarocks
/usr/local/bin/lua: /usr/local/share/lua/5.3/luarocks/cmd.lua:441: attempt to call a nil value (field 'init')
stack traceback:
        /usr/local/share/lua/5.3/luarocks/cmd.lua:441: in function 'luarocks.cmd.run_command'
        /usr/local/bin/luarocks:38: in main chunk
        [C]: in ?
```

I tried adding `fs_use_modules = false` to `~/.luarocks/config.lua` and `/usr/local/etc/luarocks/config-5.3.lua` but it doesn't change the behaviour 

I'm using Ubuntu 19.10

Thanks in advance

**Comment by daurnimator** [comment]
What version of luarocks are you using?

**Comment by liamaharon** [comment]
Hi @daurnimator, `lua -v` indicates I'm using v5.3.4.

**Comment by liamaharon** [comment]
Oops, sorry I missread your question. The version of `luarocks` I'm using is 3.2.1.

**Comment by daurnimator** [comment]
I can't see how `fs.init` can possibly be `nil`... https://github.com/luarocks/luarocks/blob/62e705b9f7374dd12dadc993c6b2b2cacd855ac8/src/luarocks/fs.lua#L86

Can you check that your `luarocks/fs.lua` matches the one in the repository? And not e.g. left over from some older installation?

**Comment by liamaharon** [comment]
you were bang on the money, this was my `/usr/local/share/lua/5.3/luarocks/fs.lua` file
https://gist.github.com/liamaharon/b4f9e049cb4cc4aeb310b39a58c495d0

I removed `/usr/local/share/lua/5.3/luarocks` and ran the installation again, looks like it's working now! :tada: 

Thank you for you help!  

 I'm surprised that `luarocks` wasn't able to overwrite the previous installation, is that expected behaviour?
