### ISSUE TITLE
Error when trying to install luasec

### ISSUE THREAD

**Issue by StefanSchroeder** [luarocks/luarocks#1118]
Because I was receiving tlsv1 errors when trying to install the package "zipwriter", I wanted to install "luasec" as this was reported as the fix. I am getting this error:

D:\src\Binaries-LuaDist-batteries-0.9.8-Windows-x86\bin>luarocks install luasec
Installing http://www.luarocks.org/repositories/rocks/luasec-0.9-1.src.rock...
Using http://www.luarocks.org/repositories/rocks/luasec-0.9-1.src.rock... switching to 'build' mode

Error: LuaRocks 2.0.10 bug (please report at luarocks-developers@lists.sourceforge.net).
...indows-x86\bin\..\lib\lua\luarocks\build\builtin.lua:189: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
        [C]: in function 'pairs'
        ...indows-x86\bin\..\lib\lua\luarocks\build\builtin.lua:189: in function 'run'
        ...-0.9.8-Windows-x86\bin\..\lib\lua\luarocks\build.lua:204: in function 'build_rockspec'
        ...-0.9.8-Windows-x86\bin\..\lib\lua\luarocks\build.lua:286: in function <...-0.9.8-Windows-x86\bin\..\lib\lua\luarocks\build.lua:276>
        (tail call): ?
        (tail call): ?
        (tail call): ?
        (tail call): ?
        (tail call): ?
        [C]: in function 'xpcall'
        ...Windows-x86\bin\..\lib\lua\luarocks\command_line.lua:151: in function 'run_command'
        :22: in main chunk
        [C]: ?

D:\src\Binaries-LuaDist-batteries-0.9.8-Windows-x86\bin>

**Comment by hishamhm** [comment]
@StefanSchroeder LuaRocks 2.0.10 is a very old version which is no longer supported. Please consider upgrading! 

"Binaries-LuaDist-batteries" is not an official package from the LuaRocks project, so unfortunately I'm unable to assist in what are the specific steps for upgrading that particular bundle. You may want to contact the maintainers directly.

**Comment by StefanSchroeder** [comment]
Thanks
