### ISSUE TITLE
Windows 10 install.bat doesn't work

### ISSUE THREAD

**Issue by mattarod** [luarocks/luarocks#1119]
I am unable to get LuaRocks to install on a Windows 10 system. I have made a significant effort to troubleshoot the issue on my own to no avail. I suspect I am overlooking something obvious but after hours of effort I can't figure out what. It seems to me that either **the install script is broken in multiple ways**, or **the installation instructions are missing vital information.**

I am following [these instructions.](https://github.com/luarocks/luarocks/wiki/Installation-instructions-for-Windows)

I downloaded the latest all-in-one Windows package, luarocks-3.2.1-win32.zip.

### ISSUE 1

If I double click install.bat, or even if I right-click and run it as administrator, the window opens and instantly closes before I have a chance to read it.  **The batch file should have a pause command  at the end so I can read the error message.** Alternatively, **if the batch file expects the user to run it from cmd rather than by double clicking an icon in the Windows GUI, the directions should say so.** They don't.

### ISSUE 2

So I ran cmd as an administrator and tried to run the script that way. I got this error message, even though I was running as admin.

```
C:\Users\matta\Downloads\luarocks-3.2.1-win32>rem=rem --[[--lua
LuaRocks 3.2.x installer.

========================
== Checking system... ==
========================

No administrative privileges detected and cannot auto-elevate. Please run with admin privileges or use the /NOADMIN switch

Failed installing LuaRocks. Run with /? for help.
```

The issue is that **the script somehow fails to realize it has admin rights, and erroneously aborts.**

### ISSUE 3

Okay, so even though the script failed to recognize it had admin rights somehow, but it suggested trying to run it with /NOADMIN, so let's try that.

So the script successfully performs the system check, but when it tries to install LuaRocks, this happens...

```
============================
== Installing LuaRocks... ==
============================


Installing LuaRocks in C:\Program Files (x86)\LuaRocks...
'.\win32\tools\mkdir' is not recognized as an internal or external command,
operable program or batch file.

Failed installing LuaRocks. Run with /? for help.
```

The mkdir executable provide in the package at the given path is called mkdir.exe, not simply mkdir. 
So I decided to just fix the install script myself. I went into the install.bat file and made the following changes:

Line 83: change "mkdir" to "mkdir.exe"

Then it fails with this error message:

```
Installing LuaRocks in C:\Program Files (x86)\LuaRocks...
'XCOPY' is not recognized as an internal or external command,
operable program or batch file.

Failed installing LuaRocks. Run with /? for help.
```

So at line 1001, I change XCOPY to XCOPY.exe. After this, installation succeeds.

So the issue is **the install batch file can't find mkdir or XCOPY because they have the .exe extension which the install script is missing.**

### ISSUE 4

After kludging the installation into working, **luarocks fails with different error messages when trying to install most packages**.

```
C:\Users\matta\Downloads\luarocks-3.2.1-win32>luarocks install luarocks
Installing http://luarocks.org/repositories/rocks/luarocks-3.2.1-1.src.rock...

Error: C:\Users\matta\AppData\Local\Temp\luarocks_luarocks-3.2.1-1-3278/luarocks-3.2.1-1.rockspec: Unknown field test

C:\Users\matta\Downloads\luarocks-3.2.1-win32>luarocks install lua-cjson
Installing http://luarocks.org/repositories/rocks/lua-cjson-2.1.0.6-1.src.rock...
cl /MD /O2 -c -Folua_cjson.obj -IC:/Program Files (x86)/Lua/5.1/include lua_cjson.c -DDISABLE_INVALID_NUMBERS -DUSE_INTERNAL_ISINF
'cl' is not recognized as an internal or external command,
operable program or batch file.

Error: Build error: Failed compiling object lua_cjson.obj

C:\Users\matta\Downloads\luarocks-3.2.1-win32>luarocks install luafilesystem
Installing http://luarocks.org/repositories/rocks/luafilesystem-1.7.0-2.src.rock...
cl /MD /O2 -c -Fosrc/lfs.obj -IC:/Program Files (x86)/Lua/5.1/include src/lfs.c
'cl' is not recognized as an internal or external command,
operable program or batch file.

Error: Build error: Failed compiling object src/lfs.obj

C:\Users\matta\Downloads\luarocks-3.2.1-win32>luarocks install dkjson
Installing http://luarocks.org/repositories/rocks/dkjson-2.5-2.src.rock...
'7z' is not recognized as an internal or external command,
operable program or batch file.

Error: Failed extracting dkjson-2.5.tar.gz
```

And so on.

**Comment by hishamhm** [comment]
@mattarod sorry for the troubles and thank you for the detailed reports!

**ISSUE 1**

I updated the intro section of https://github.com/luarocks/luarocks/wiki/Installation-instructions-for-Windows — let me know if it reads better! (and feel free to make changes, it's a wiki!)

**ISSUE 2**

I have no idea what might have caused that — I lack the Windows knowledge. @Tieske, any idea?

**ISSUE 3**

I thought that spelling out `.EXE` was not necessary in batch files! (At least that's my recollection ever since MS-DOS days). Has anything on that regard changed, or do you have any particular configuration on your machine that affects this?

**ISSUE 4**

```
Error: C:\Users\matta\AppData\Local\Temp\luarocks_luarocks-3.2.1-1-3278/luarocks-3.2.1-1.rockspec: Unknown field test
```

This one is very odd, I can't reproduce it (on Linux at least). By any chance, do you have any older version of LuaRocks installed in your system as well?

```
'cl' is not recognized as an internal or external command,
operable program or batch file.
```

This means it failed to find the C compiler. The fact that it is searching for `cl` means that `INSTALL.BAT` configured your LuaRocks to use Microsoft Visual Studio as a C compiler. Is that correct, do have that installed? If so, running `luarocks` from the Visual Studio Developer Prompt should fix this (I added such instructions in the wiki page).

```
'7z' is not recognized as an internal or external command,
operable program or batch file.
```

This looks related to the fact that commands without `.EXE` are not being found in your system (the above `cl` error might be it as well).

-----

If you have Visual Studio, could you give the all-in-one `luarocks.exe` binary a try from the MSVC Developer Prompt? It might give you a smoother experience than this legacy all-in-one package. I wish to eventually retire the `INSTALL.BAT`-based package and replace it with `luarocks.exe` — existing users are used to the batch installer quirks, but I'd like to eventually get to a smooth out-of-the-box experience with `luarocks.exe` — every bit of feedback helps, thank you so much!

**Comment by mattarod** [comment]
Hello @hishamhm! Thank you for your quick reply and your help!

Re: issue 1:

Thanks.  I didn't feel confident in my ability to add correct information to the wiki, as I'm struggling to even get this running.

Your new text about needing a C compiler from either MINGW or Visual Studio is very very helpful; thank you.

Re: issue 2 and 3:

I had no knowledge or memory of having ever altered any setting on my system that would force me to require explicitly including the .exe file extension when invoking executables from the command line. However, I have a habit of figuring out problems on my own _after_ getting so frustrated I ask for help, and this time around was no exception.

**My PATH and PATHEXT environment variables were set incorrectly.** I don't remember doing it and it was probably a long time ago, but nonetheless, they were set wrong and that was the source of the problem. [This page](https://www.computerhope.com/issues/ch000088.htm) lists default values for these variables. My PATH variable had several values I had added manually for other unrelated programming tasks, but were missing the three default paths listed there.  Second, PATHEXT is the Windows environment variable that permits executable files to be invoked without their file extension, and mine was entirely unset. I restored the default values, including the .exe extension, and now both issues 2 and 3 are resolved. My apologies for reporting issues that were my own fault.

Re: issue 4:

The inability to find 7z was also related to my PATHEXT environment variable. dkjson now installs.

Thank you for the answer relating to the missing C compiler. I'll look into getting one installed and configured so Lua can find it.

**Comment by mattarod** [comment]
While the issue is resolved, I have one more point of feedback.

If you want people to just download luarocks.exe instead of the legacy all-in-one package, edit the wiki to give instructions on how to install and set up luarocks via the luarocks.exe download. I chose the all-in-one package because there were no instructions on the other release.

**Comment by Ismoh** [comment]
@mattarod 
How did you install it in detail?
The windows documentation isn't that nice. Looks like there is no --verbose on windows?
Doesn't matter what I try, I always get 
> The system cannot find the path specified.
Which path?!
Would be awesome to have a better documentation on this @hishamhm

**Comment by mattarod** [comment]
This was two years ago and I gave up on the project I was planning to do. I don't remember a thing. Sorry.

**Comment by Ismoh** [comment]
No Problem

**Comment by Ismoh** [comment]
@hishamhm I can approve that this is working fine with 3.1.9 latest version.
I've done this:
https://github.com/luarocks/luarocks/wiki/Installation-instructions-for-Windows#making-a-self-contained-installation

Works fine! Fyi
