### ISSUE TITLE
Mac OS 10.15.2 unable to open the archive "luarocks-3.2.1.tar.gz"

### ISSUE THREAD

**Issue by lgb1234a** [luarocks/luarocks#1126]
Executed `tar zxpf luarocks-3.2.1.tar.gz` as the docs showing.
Error reported like `tar: Error opening archive: Unrecognized archive format`.
I tried to open this archive manually but made no effect.
Whats wrong with my operation? Thx for any help.

**Comment by hishamhm** [comment]
@lgb1234a From which URL did you get this file? What do you get when you type `file luarocks-3.2.1.tar.gz` ?

**Comment by lgb1234a** [comment]
> @lgb1234a From which URL did you get this file? What do you get when you type `file luarocks-3.2.1.tar.gz` ?

I've tried installing it by `brew install luarocks`, it was useful.
The package unzipped with error downloaded by `wget  https://luarocks.org/releases/luarocks-3.2.1.tar.gz` as the [docs](https://luarocks.org/) showing.
