### ISSUE TITLE
install all dependencies from a file

### ISSUE THREAD

**Issue by Ara4Sh** [luarocks/luarocks#1127]
Dear All,

Can we install the required rocks from a file? like Gemfile or requirements.txt 
also something like pip freeze will be very helpful

**Comment by Tieske** [comment]
Isn't that what a LuaRocks `rockspec` file is? a text file specifying what to install? including dependencies?

**Comment by hishamhm** [comment]
@Ara4Sh You can use `luarocks build --only-deps` to build only the dependencies of a rockspec.

We don't have an exact equivalent to `pip freeze` (though you can do `luarocks list --porcelain` to get a scriptable list of installed packages), but in the current master (next LuaRocks release coming soon), we have dependency lockfiles, so you can do the following:

* when developing a Lua module, you can use `luarocks make --pin` to create a `luarocks.lock` dependency lockfile which pins the dependencies to exact versions (including any recursive dependencies).
* If you commit this file, whoever uses your repo will use these frozen dependency versions when calling `luarocks build`, unless they call `--pin` themselves to override it.
* when installing a Lua module (with `luarocks install` or `luarocks build`, you can use `--pin` too. If you later pack this into a `.rock` file with `luarocks pack`, the lockfile will be used whenever that `.rock` file is installed.

**Comment by Ara4Sh** [comment]
@Tieske @hishamhm Thank you very much I will take a look around rockspec and will wait for luarocks next release 👍
