### ISSUE TITLE
config-5.1.lua is not properly built

### ISSUE THREAD

**Issue by MinchukSergei** [luarocks/luarocks#1128]
Should be
variables = {
    MSVCRT = 'MSVCR80',
    LUALIB = 'lua5.1.lib',
    CC = [[C:\MinGW\bin\gcc.exe]],
    MAKE = nil,  -- not found by installer,
    RC = [[C:\MinGW\bin\windres.exe]],
    LD = [[C:\MinGW\bin\gcc.exe]],
    AR = [[C:\MinGW\bin\ar.exe]],
    RANLIB = [[C:\MinGW\bin\ranlib.exe]],
}

instead of
variables = {
    MSVCRT = 'MSVCR80',
    LUALIB = 'lua5.1.lib',
    CC = [[C:\MinGW\bin\gcc.exe]],
    MAKE = nil  -- not found by installer,
    RC = [[C:\MinGW\bin\windres.exe]],
    LD = [[C:\MinGW\bin\gcc.exe]],
    AR = [[C:\MinGW\bin\ar.exe]],
    RANLIB = [[C:\MinGW\bin\ranlib.exe]],
}

comma missing (near MAKE = nil) or appears in incorrect place

**Comment by hishamhm** [comment]
Fixed by @InEdited in #1129 :)
