### ISSUE TITLE
luarocks unpack croissant fails

### ISSUE THREAD

**Issue by edrx** [luarocks/luarocks#1132]
If I run this

    rm -Rv   /tmp/rock/
    mkdir    /tmp/rock/
    cd       /tmp/rock/
    luarocks unpack croissant

I get this error (in the last line):

    Cloning into 'croissant'...
    remote: Enumerating objects: 29, done.        
    remote: Counting objects: 100% (29/29), done.        
    remote: Compressing objects: 100% (26/26), done.        
    remote: Total 29 (delta 1), reused 13 (delta 0), pack-reused 0        
    Receiving objects: 100% (29/29), 365.72 KiB | 936.00 KiB/s, done.
    Resolving deltas: 100% (1/1), done.
    Error: Failed copying unpacked rockspec into unpacked source directory.

but installing croissant works - if I do

    luarocks --local install croissant

the messages are:

    Installing https://luarocks.org/croissant-0.0.1-6.rockspec
    Cloning into 'croissant'...
    remote: Enumerating objects: 29, done.        
    remote: Counting objects: 100% (29/29), done.        
    remote: Compressing objects: 100% (26/26), done.        
    remote: Total 29 (delta 1), reused 13 (delta 0), pack-reused 0        
    Receiving objects: 100% (29/29), 365.72 KiB | 952.00 KiB/s, done.
    Resolving deltas: 100% (1/1), done.
    
    croissant 0.0.1-6 depends on lua >= 5.1 (5.3-1 provided by VM)
    croissant 0.0.1-6 depends on sirocco >= 0.0.1-5 (0.0.1-5 installed)
    croissant 0.0.1-6 depends on hump >= 0.4-2 (0.4-2 installed)
    croissant 0.0.1-6 depends on lpeg >= 1.0.1-1 (1.0.2-1 installed)
    croissant 0.0.1-6 depends on argparse >= 0.6.0-1 (0.7.0-1 installed)
    croissant 0.0.1-6 depends on compat53 >= 0.7-1 (0.7-1 installed)
    croissant 0.0.1-6 is now installed in /home/edrx/.luarocks (license: MIT/X11)

I'm on a Debian box using luarocks from git instead of the Debian package for luarocks.

**Comment by daurnimator** [comment]
I'm unable to replicate your issue.

**Comment by edrx** [comment]
Ouch =(

Can you replicate the errors that I described here?
http://lua-users.org/lists/lua-l/2020-01/msg00114.html

**Comment by hishamhm** [comment]
@edrx No, `luarocks unpack` works fine here, for both `croissant` and `stacktraceplus`.

Could you post the output you get from running `luarocks unpack --verbose croissant`? Please try it with the latest version of LuaRocks.
