### ISSUE TITLE
eval command is not running

### ISSUE THREAD

**Issue by aashimgarg** [luarocks/luarocks#1136]
eval command which is mentioned in the readme is giving an error.

**Comment by hishamhm** [comment]
> eval command which is mentioned in the readme

Which readme? README.md does not mention `eval`.

>  is giving an error.

which error?

**Comment by aashimgarg** [comment]
Sorry it is mentioned in the wiki.

**Comment by hishamhm** [comment]
Where exactly? Could you post a link to the relevant wiki page here? Thanks
