### ISSUE TITLE
Error: The source and destination are the same files

### ISSUE THREAD

**Issue by osch** [luarocks/luarocks#1147]
If using the *builtin* build type for installing pure lua packages the error *The source and destination are the same files* is triggered under Linux if the source file specified in the rockspec does not exist. (I verified this with Luarocks version 3.2.1)

See:
https://github.com/luarocks/luarocks/blob/7c70a3208dcab7a9e568ede2a30b870ce0d96a20/src/luarocks/fs/lua.lua#L398-L400

If source and destination files do not exist, the inode comparison

```lua
lfs.attributes(src, "ino") == lfs.attributes(dest, "ino")
```
is true, because both values are `nil == nil`

see also #1062

**Comment by hishamhm** [comment]
Thanks for reporting. Does this still happen with the latest version 3.3.0?

**Comment by hishamhm** [comment]
Ah, so you mean that we get the incorrect error message, in the sense that it reports "are the same file" when it should report "source doesn't exist", right?

Would this be a fix?

```diff
diff --git a/src/luarocks/fs/lua.lua b/src/luarocks/fs/lua.lua
index 6028a925..c5cebd2f 100644
--- a/src/luarocks/fs/lua.lua
+++ b/src/luarocks/fs/lua.lua
@@ -380,6 +380,20 @@ function fs_lua.remove_dir_tree_if_empty(d)
    end
 end
 
+local function are_the_same_file(f1, f2)
+   if f1 == f2 then
+      return true
+   end
+   if cfg.is_platform("unix") then
+      local i1 = lfs.attributes(f1, "ino")
+      local i2 = lfs.attributes(f2, "ino")
+      if i1 ~= nil and i1 == i2 then
+         return true
+      end
+   end
+   return false
+end
+
 --- Copy a file.
 -- @param src string: Pathname of source
 -- @param dest string: Pathname of destination
@@ -395,7 +409,7 @@ function fs_lua.copy(src, dest, perms)
    if destmode == "directory" then
       dest = dir.path(dest, dir.base_name(src))
    end
-   if src == dest or (cfg.is_platform("unix") and lfs.attributes(src, "ino") == lfs.attributes(dest, "ino")) then
+   if are_the_same_file(src, dest) then
       return nil, "The source and destination are the same files"
    end
    local src_h, err = io.open(src, "rb")
```
```
