### ISSUE TITLE
Could not find unzip

### ISSUE THREAD

**Issue by Barf-Vader** [luarocks/luarocks#1152]
I'm trying to install Luarocks but I get:
```
 Could not find 'unzip'.
 Make sure it is installed and available in your PATH.
```
when I try to run the `./configure && make && sudo make install` command.

**Comment by hishamhm** [comment]
Well, make sure the `unzip` command is installed in your system and available in your PATH! :) What operating system are you using? There should be a command to install additional packages (e.g. `apt install unzip` on Ubuntu Linux, or `brew install unzip` on a Mac if you have [Homebrew](https://brew.sh)). Once you install `unzip` by whatever means this dependency will be solved and the `configure` script will move forward.

Hope this helps!

**Comment by Barf-Vader** [comment]
Thanks a lot!
