### ISSUE TITLE
Unable to make luarocks-3.3.1 with a fresh install of lua-5.3.5

### ISSUE THREAD

**Issue by Richard092345** [luarocks/luarocks#1153]
Hi. I installed lua-5.3.5 in /usr and then started the install of luarocks-3.3.1 and I get the following message when doing "make" in the luarocks-3.3.1 directory.

Your version of Lua does not support io.popen, which is required by LuaRocks. Please check your Lua installation.

io.popen() is defined if I start lua and print(io.popen) does not return nil. So I looked for dandling directories from prior installs of lua and luarocks and I removed everything I found was left over including luajit (/etc/luarocks, /usr/share/{lua,luarocks})

I am still getting that same error when doing "make" and "make" stops wihout completing.

Does someone have any clue as to what is happening.

**Comment by hishamhm** [comment]
Did you run `configure` first?

**Comment by Richard092345** [comment]
Thanks for the answer. I am used to install packages but I am lost here!.

Yes I did run configure and configure finds lua. The failure occurs during the "make" while running "luarocks init".  I noticed that that scripts looks for .lua files in src but there are none there; the .lua files are in src/luarocks.

Before getting into that problem I had replaced an old luajit install with lua-5.3.5. I had installed luarocks before while running luajit and it worked for the luajit configuration.

I reinstalled lua-5.3.5 as I realized there was a problem with the library search paths and I finally solved the lua install issues after I realized I had to edit the lua-5.3.5/src/luaconf.h file to set the same paths there as the ones I give in the "make" directive.  Now lua is installed correctly in /usr.  There is no other version of Lua or Luajit leftover in /usr or /usr/local. or /opt. There is no environment variable referring to lua other than LUA_INIT that points to my local config file for lua-5.3.5.

The only other thing that might confuse luarocks is that I run a "multilib" Slackware Linux but I would not have been able to run luarocks with luajit as I did.  So I discard that as a factor.

Here is copy of what I get when I run configure and make.

pkg:/sa705/live/pkg/wa.d/luarocks-3.3.1$ ./configure --prefix=/usr                

Configuring LuaRocks version 3.3.1...

Lua version detected: 5.3                                                         
Lua interpreter found: /usr/bin/lua                                               
lua.h found: /usr/include/lua.h                                                   
unzip found in PATH: /usr/bin                                                     

Done configuring.

LuaRocks will be installed at......: /usr                                         
LuaRocks will install rocks at.....: /usr                                         
LuaRocks configuration directory...: /etc/luarocks                                
Using Lua from.....................: /usr                                         

* Type make and make install:                                                     
  to install to /usr as usual.                                                    
* Type make bootstrap:                                                            
  to install LuaRocks into /usr as a rock.                                        

pkg:/sa705/live/pkg/wa.d/luarocks-3.3.1$ make                                     
mkdir -p "build"
rm -f src/luarocks/core/hardcoded.lua
echo "#!/bin/sh" > luarocks-admin
mkdir -p "build"
mkdir -p "build"
echo "unset LUA_PATH LUA_PATH_5_2 LUA_PATH_5_3 LUA_PATH_5_4 LUA_CPATH LUA_CPATH_5_2 LUA_CPATH_5_3 LUA_CPATH_5_4" >> luarocks-admin
(printf '#!/usr/bin/lua\n'\
'package.loaded["luarocks.core.hardcoded"] = { '\
"$([ -n "" ] && printf 'FORCE_CONFIG = true, ')"\
'SYSCONFDIR = [[/etc/luarocks]] }\n'\
'package.path=[[/usr/share/lua/5.3/?.lua;]] .. package.path\n'\
'local list = package.searchers or package.loaders; table.insert(list, 1, function(name) if name:match("^luarocks%%.") then return loadfile([[/usr/share/lua/5.3/]] .. name:gsub([[%%.]], [[/]]) .. [[.lua]]) end end)\n'; \
tail -n +2 src/bin/luarocks \
)> "build/luarocks"
(printf '#!/usr/bin/lua\n'\
'package.loaded["luarocks.core.hardcoded"] = { '\
"$([ -n "" ] && printf 'FORCE_CONFIG = true, ')"\
'SYSCONFDIR = [[/etc/luarocks]] }\n'\
'package.path=[[/usr/share/lua/5.3/?.lua;]] .. package.path\n'\
'local list = package.searchers or package.loaders; table.insert(list, 1, function(name) if name:match("^luarocks%%.") then return loadfile([[/usr/share/lua/5.3/]] .. name:gsub([[%%.]], [[/]]) .. [[.lua]]) end end)\n'; \
tail -n +2 src/bin/luarocks-admin \
)> "build/luarocks-admin"
echo 'LUAROCKS_SYSCONFDIR="/etc/luarocks" LUA_PATH="/sa705/live/pkg/wa.d/luarocks-3.3.1/src/?.lua;;" exec "/usr/bin/lua" "/sa705/live/pkg/wa.d/luarocks-3.3.1/src/bin/luarocks-admin" --project-tree="/sa705/live/pkg/wa.d/luarocks-3.3.1/lua_modules" "$@"' >> luarocks-admin
chmod +rx ./luarocks-admin
mkdir -p .luarocks
cp ./build/config-5.3.lua .luarocks/config-5.3.lua
rm -f src/luarocks/core/hardcoded.lua
echo "#!/bin/sh" > luarocks
echo "unset LUA_PATH LUA_PATH_5_2 LUA_PATH_5_3 LUA_PATH_5_4 LUA_CPATH LUA_CPATH_5_2 LUA_CPATH_5_3 LUA_CPATH_5_4" >> luarocks
echo 'LUAROCKS_SYSCONFDIR="/etc/luarocks" LUA_PATH="/sa705/live/pkg/wa.d/luarocks-3.3.1/src/?.lua;;" exec "/usr/bin/lua" "/sa705/live/pkg/wa.d/luarocks-3.3.1/src/bin/luarocks" --project-tree="/sa705/live/pkg/wa.d/luarocks-3.3.1/lua_modules" "$@"' >> luarocks
chmod +rx ./luarocks
./luarocks init
Your version of Lua does not support io.popen,
which is required by LuaRocks. Please check your Lua installation.
make: *** [GNUmakefile:57: luarocks] Error 1

**Comment by hishamhm** [comment]
There might be something going on in your system which makes the code at ./src/luarocks/cmd.lua, line 32, to fail:

https://github.com/luarocks/luarocks/blob/master/src/luarocks/cmd.lua#L31-L42

What happens if you run `print(pcall(io.popen, ""))` from your Lua interpreter? You could also sprinkle some `print` statements to `cmd.lua` to help debug what's going on (`print(arg[-1])` should return the name of the Lua interpreter, just to confirm that it is calling the right one).

**Comment by Richard092345** [comment]
Thanks very much. Indeed print(pcall(io.popen, "")) returns "false   'popen' not supported
". I will investigate as you suggest.

**Comment by Richard092345** [comment]
After getting Lua up and running including the support for popen on my rooted Android phone (with CCTOOLS) I realize there is an issue with the installation of Lua on my Linux box. Same script on both machines (different default paths though).  That is definitely not a Luarocks issue. Sorry for posting here.  Lua should be an easy install but surprisingly it gives me some problems!
