### ISSUE TITLE
Failed unpacking rock file

### ISSUE THREAD

**Issue by Diamonde123** [luarocks/luarocks#1158]
I have Win10 
And can't install faketorio
`C:\Program Files (x86)\Lua\5.1>luarocks.bat install faketorio
Installing http://luarocks.org/repositories/rocks/faketorio-1.6.0-1.src.rock...

Error: Failed unpacking rock file: C:\Users\mihas\AppData\Local\Temp\luarocks_luarocks-rock-faketorio-1.6.0-1-3966/faketorio-1.6.0-1.src.rock`

**Comment by hishamhm** [comment]
Is this the latest version of LuaRocks? (3.3.1)

Also, can you run it with the `--verbose` flag to give us more info on what failed?

**Comment by Diamonde123** [comment]
> Also, can you run it with the `--verbose` flag to give us more info on what failed?
After seting verbose true I tried to solve the problem myself again. I just needed to install mingw32, git for windows, and add them to PATH. Thank you for help
