### ISSUE TITLE
Rockspec description.summary is not getting updated

### ISSUE THREAD

**Issue by keyur9** [luarocks/luarocks#1164]
Initially, the rockspec had a summary inside the description section and it was already published with version 1.0.0. I could see the summary on the module page on the luarocks.

Now, I've made the changes in the package, bump the version and updated the summary. After uploading the package, I couldn't see the summary updated on the module page but when I see the rockspec, it has the updated summary.

Is there any way to update the summary on the module page?

Thank you,

**Comment by hishamhm** [comment]
> Is there any way to update the summary on the module page?

Yes, click the "Edit" link when logged in as the owner of the module.

For issues with the behavior of the luarocks.org website, please open an issue at https://github.com/luarocks/luarocks-site/issues instead. Thank you!
