### ISSUE TITLE
Luarocks standalone creates luarocks.bat instructing lua to run luarocks.exe

### ISSUE THREAD

**Issue by gustavooavila** [luarocks/luarocks#1174]
I installed lua 5.3 by downloading the standalone luabinaries and manually creating the include folder with headers from lua source files.
After setting the system Path and forcing my way through `luarocks init` by setting the variables using `luarocks LUA_INCDIR=C:\Lua\5.3\inc`.
I finally got the `lua.bat` and `luarocks.bat` files to be created on my project folder...
But the luarocks.bat file created instructs lua to run luarocks.exe, I really don't know how to phrase that better, so here is the created file:

```
@echo off
setlocal
set "LUAROCKS_SYSCONFDIR=C:\Program Files/luarocks"
"C:\Lua\5.3\bin\lua53.exe" -e "package.path=\"C:\\Lua\\5.3\\lua\\?.lua;C:\\Lua\\5.3\\lua\\?\\init.lua;C:\\Lua\\5.3\\?.lua;C:\\Lua\\5.3\\?\\init.lua;C:\\Lua\\5.3\\..\\share\\lua\\5.3\\?.lua;C:\\Lua\\5.3\\..\\share\\lua\\5.3\\?\\init.lua;.\\?.lua;.\\?\\init.lua;C:\\Users\\Shadownrun\\AppData\\Roaming/luarocks/share/lua/5.3/?.lua;C:\\Users\\Shadownrun\\AppData\\Roaming/luarocks/share/lua/5.3/?/init.lua\";package.cpath=\"C:\\Lua\\5.3\\?.dll;C:\\Lua\\5.3\\..\\lib\\lua\\5.3\\?.dll;C:\\Lua\\5.3\\loadall.dll;.\\?.dll;C:\\Users\\Shadownrun\\AppData\\Roaming/luarocks/lib/lua/5.3/?.dll\"" "C:\Lua\5.3\luarocks.exe" --project-tree C:\Users\Shadownrun\Documents\lua\windowsControl/lua_modules %*
exit /b %ERRORLEVEL%
``` 

If I try to run the bat file I get this error:
```
C:\lua\5.3\bin\lua53.exe: C:\Lua\5.3\bin\luarocks.exe:1: syntax error near '<\144>'
````

**Comment by gustavooavila** [comment]
I removed all the lua command from the batch and it works fine

**Comment by hishamhm** [comment]
@gustavooavila Thank you for the report and the confirmation that removing the interpreter call fixes it! I merged a fix so that it will stop inserting the interpreter when using the binary.
