### ISSUE TITLE
permissions

### ISSUE THREAD

**Issue by papperboy3498** [luarocks/luarocks#1176]
while I was trying to install nngraph, I came across an issue. The error I got was
> Error: Your user does not have write permissions in /usr/local/lib/luarocks/rocks 
> -- you may want to run as a privileged user or use your local tree with --local.

what should I do in order to fix this?

**Comment by hishamhm** [comment]
If you want to install in /usr/local/lib, you need to run as a privileged user, with the sudo command, something like:

```
sudo luarocks install nngraph
```

If you do not have or do not want to use superuser privileges, you can use the `--local` flag and this will install in your `$HOME/.luarocks` folder instead:

```
luarocks install nngraph --local
```

but then the module won't be found by the default Lua paths. You can do

```
eval $(luarocks path)
```

to enable those paths temporarily in your shell, or add this command to your [user profile configuration](https://www.tecmint.com/understanding-shell-initialization-files-and-user-profiles-linux/) to have it load when you login.

**Comment by papperboy3498** [comment]
after that, I keep getting the error

> Error: No results matching query were found.
