### ISSUE TITLE
luarocks doesn't work since website is down

### ISSUE THREAD

**Issue by chekalsky** [luarocks/luarocks#1177]
Hi!

Looks like https://luarocks.org/ isn't working

**Comment by leafo** [comment]
We're aware, trying to get it back up. Domain related issue. If you need to access the website in the meantime you can set your hosts file to temporarily point at the IP address: 45.33.61.132

The command line tool should automatically fall back to a mirror and still work as far as I know.

This URL can be used as a mirror: https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master

**Comment by nhartland** [comment]
The fall back mirror appears to be being picked up, but it looks like there might be some difference in the manifest? I'm seeing some commands failing where they didn't earlier today. For example trying to install `loverocks` is giving me:

```
Warning: Failed searching manifest: Failed fetching manifest for https://luarocks.org - Failed downloading https://luarocks.org/manifest - /tmp/luarocks_local_cache-LfCGGl/https___luarocks.org/manifest
Installing https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/loverocks-0.2.1-1.src.rock

Error: Could not satisfy dependency etlua ~> 1.3: No results matching query were found.
Missing dependencies for loverocks 0.2.1-1:
   etlua ~> 1.3 (not installed)
   argparse ~> 0.5 (not installed)
   loadconf >= 0.3.4, < 0.4 (not installed)
```

Which was working earlier today. Not an urgent problem by any means but maybe a useful FYI.

**Comment by leafo** [comment]
It's back up now.

**Comment by leafo** [comment]
> The fall back mirror appears to be being picked up, but it looks like there might be some difference in the manifest

I just checked the manifest and I see etlua there. What version of lua were you installing for?

**Comment by leafo** [comment]
@nhartland 

> The fall back mirror appears to be being picked up, but it looks like there might be some difference in the manifest

I just checked the manifest and I see etlua there. What version of lua were you installing for?

**Comment by nhartland** [comment]
It was lua5.1, specifically this dockerfile:
    https://github.com/nhartland/love-build/blob/dev/Dockerfile

stopped building while luarocks.org was down. That's running a pretty old version
of luarocks though, so maybe it was just referencing an old manifest or something.

In any case, it's building fine now with the site back up, thanks!

**Comment by Tieske** [comment]
The backup servers don't seem to work. We also experienced a failure; on a private repo. 

Anything we can do about it?

**Comment by leafo** [comment]
@Tieske I have a feeling the issue is with the luarocks tool not knowing how to fall back to another manifest when installing dependencies, since installing directly from that manifest appears to work correctly.

**Comment by Tieske** [comment]
It's in a private repo here: https://travis-ci.com/github/Kong/kong-plugin-opaque-token/jobs/318608289#L378 ( @hishamhm has access)

```
Error: Could not fetch rock file: Error fetching file: Failed downloading https://luarocks.org/luacheck-0.20.0-1.src.rock - luacheck-0.20.0-1.src.rock
```
This was using LuaRocks `3.2.1`.

Now starting to doubt whether it was related, since it was a development build, it installed a bunch of rocks, and only 1 failed. But maybe the fall-backs are not up-to-date and some rocks/specs are missing? This is a bigger snippet, showing the failure, in between successful installs;

```
busted 2.0.rc13-0 depends on dkjson >= 2.1.0 (not installed)

Installing https://luarocks.org/dkjson-2.5-2.src.rock

dkjson 2.5-2 is now installed in /usr/local (license: MIT/X11)

busted 2.0.rc13-0 depends on say >= 1.3-0 (not installed)

Installing https://luarocks.org/say-1.3-1.rockspec

say 1.3-1 is now installed in /usr/local (license: MIT <http://opensource.org/licenses/MIT>)

busted 2.0.rc13-0 depends on luassert >= 1.7.8-0 (not installed)

Installing https://luarocks.org/luassert-1.8.0-0.rockspec

luassert 1.8.0-0 is now installed in /usr/local (license: MIT <http://opensource.org/licenses/MIT>)

busted 2.0.rc13-0 depends on lua-term >= 0.1-1 (not installed)

Installing https://luarocks.org/lua-term-0.7-1.rockspec

gcc -O2 -fPIC -I/usr/local/openresty/luajit/include/luajit-2.1 -c core.c -o core.o

gcc -shared -o term/core.so core.o

lua-term 0.7-1 is now installed in /usr/local (license: MIT/X11)

busted 2.0.rc13-0 depends on mediator_lua >= 1.1.1-0 (not installed)

Installing https://luarocks.org/mediator_lua-1.1.2-0.rockspec

mediator_lua 1.1.2-0 is now installed in /usr/local (license: MIT <http://opensource.org/licenses/MIT>)

busted 2.0.rc13-0 is now installed in /usr/local (license: MIT <http://opensource.org/licenses/MIT>)

luacheck 0.20.0 not found, installing via luarocks...

Installing https://luarocks.org/luacheck-0.20.0-1.src.rock

Error: Could not fetch rock file: Error fetching file: Failed downloading https://luarocks.org/luacheck-0.20.0-1.src.rock - luacheck-0.20.0-1.src.rock

lua-llthreads2 0.1.5 not found, installing via luarocks...

Installing https://luarocks.org/lua-llthreads2-0.1.5-1.src.rock

gcc -O2 -fPIC -I/usr/local/openresty/luajit/include/luajit-2.1 -c src/l52util.c -o src/l52util.o -DLLTHREAD_MODULE_NAME=llthreads2 -I/usr/include

gcc -O2 -fPIC -I/usr/local/openresty/luajit/include/luajit-2.1 -c src/llthread.c -o src/llthread.o -DLLTHREAD_MODULE_NAME=llthreads2 -I/usr/include

gcc -shared -o llthreads2.so src/l52util.o src/llthread.o -L/usr/lib -Wl,-rpath,/usr/lib -lpthread

lua-llthreads2 0.1.5-1 is now installed in /usr/local (license: MIT/X11)

Installing https://luarocks.org/busted-htest-1.0.0-2.src.rock

busted-htest 1.0.0-2 is now installed in /usr/local (license: MIT)

Removing intermediate container e3948b72a4e1
```

**Comment by leafo** [comment]
I verified that it was the issue I suspected, I created another issue specifically for it: #1179

**Comment by Tieske** [comment]
Thx @leafo  👍
