### ISSUE TITLE
--pack-binary-rock is ignored in build.type "command"

### ISSUE THREAD

**Issue by p01arbear** [luarocks/luarocks#1178]
https://github.com/luarocks/luarocks/wiki/make
```
If --pack-binary-rock is passed, the rock is not installed
```

luarocks/make.lua
```lua
   if flags["pack-binary-rock"] then
        return pack.pack_binary_rock(rspec.name, rspec.version, build.build_rockspec, rockspec, false, true, deps.get_deps_mode(flags))
```
luarocks/build.lua
```lua
--- Build and install a rock given a rockspec.
function build.build_rockspec(rockspec_file, need_to_fetch, minimal_mode, deps_mode, build_only_deps)
    ...
    ok, build_type = pcall(require, "luarocks.build." .. build_spec.type)
    ok, err = build_type.run(rockspec)
end
```
luarocks/build/command.lua
```lua
   if build.install_command then
      util.printout(build.install_command)
      if not fs.execute(build.install_command) then
         return nil, "Failed installing."
      end
   end
```

**Comment by hishamhm** [comment]
Not sure I understand. What is the behavior you are observing, from a CLI point of view, and what is the behavior you expected?

**Comment by p01arbear** [comment]
`luarocks make/build --pack-binary-rock` calls `build.install_command` command to run to install the package.
But according to the purpose of  `--pack-binary-rock` it must not do that.

**Comment by hishamhm** [comment]
@p01arbear Ah, I understand the confusion now. Using `--pack-binary-rock` does build and install _in a temporary location_, and use that to pack a binary rock. It is not installed in your local/system trees. So yes, it is working as expected!
