### ISSUE TITLE
fix bug ssl/https.lua:66: interrupted!

### ISSUE THREAD

**Issue by BarnameESF** [luarocks/luarocks#1189]
Hello.
I work with Lua 5.2 and use luarocks-2.2.2 and Ubuntu 16.04.
Sometimes the following error occurs when running my code:

`/usr/local/share/lua/5.2/ssl/https.lua:66: interrupted!`

Please advise me how to fix this problem.

**Comment by hishamhm** [comment]
LuaRocks 2.2.2 is very old! Please try running a more recent version. Feel free to reopen if the problem persists with the latest version.
