### ISSUE TITLE
unable to update external_deps_dirs through config command

### ISSUE THREAD

**Issue by fastcoding** [luarocks/luarocks#1192]
Luarock's default config contains 3 items - "/usr/local", "/usr", "/" . That will make troubles when cross-compiling C codes for embeded device.  Because they reference to host libraries.

It seems Luarocks doesn't provide a way to update such table item in its config. 

For example, if I run :

`luarocks config external_deps_dirs.1 /path/to/my/toolchain/sysroot`

I got a new item in config file:
{  
    "/usr/local", "/usr", "/" ,
    ["1"]="/path/to/my/toolchain/sysroot"
}
This is not expected result.

**Comment by hishamhm** [comment]
Please use the following (note the quotes to prevent your shell from doing any special handling of the characters)

```
luarocks config 'external_deps_dirs[1]' "/foo"
```

**Comment by fastcoding** [comment]
cool, it works! thanks for help.
