### ISSUE TITLE
Luarocks lint doesn't check for description

### ISSUE THREAD

**Issue by alerque** [luarocks/luarocks#1205]
Running `luarocks lint` on a rockspec that doesn't have a description field should produce a lint error, not die completely:

```
$ luarocks lint blah.rockspec

Error: LuaRocks 3.3.1 bug (please report at https://github.com/luarocks/luarocks/issues).
Arch.: linux-x86_64
/usr/share/lua/5.3/luarocks/cmd/lint.lua:42: attempt to index a nil value (field 'description')
stack traceback:
        /usr/share/lua/5.3/luarocks/cmd/lint.lua:42: in function 'luarocks.cmd.lint.command'
        (...tail calls...)
        [C]: in function 'xpcall'
        /usr/share/lua/5.3/luarocks/cmd.lua:620: in function 'luarocks.cmd.run_command'
        /usr/bin/luarocks:38: in main chunk
        [C]: in ?
```

**Comment by daurnimator** [comment]
@hishamhm I assume that `load_local_rockspec` was meant to fail if `description` was missing?

**Comment by hishamhm** [comment]
> @hishamhm I assume that load_local_rockspec was meant to fail if description was missing?

I guess that would cause a breaking change if we did this at this point. Making `lint` fail gracefully (or not even fail if `description` is optional, I don't recall the details) sounds like a better idea.
