### ISSUE TITLE
What happened to --versioned-rocks-dir ... ?

### ISSUE THREAD

**Issue by LiamFry** [luarocks/luarocks#1208]
How can I possibly manage rocks for Lua 5.1, 5.2, and 5.3 if I can't install LuaRocks for each version of the Lua VM?
I've recently upgraded from 2.4.4 to 3.3.1 and this slapped me in the face.

**Comment by LiamFry** [comment]
Well color me confused. I appears that LuaRocks now pays attention to the version of the active Lua VM. I don't see this explained clearly or explicitly in any docs or change logs, but that's how it appears to be.

**Comment by daurnimator** [comment]
It also now has a `--lua-version` argument
