### ISSUE TITLE
How to change the location of the user config file

### ISSUE THREAD

**Issue by rekaerst** [luarocks/luarocks#1219]
Sorry if this is the wrong place for questions.
I would like to change location of the user config file from the default $HOME/.luarocks/config-5.3.lua to $XDG_CONFIG_HOME/luarocks/config-5.3.lua. I can't find any helpful information about how to achieve this from the manual pages and help outputs. How can I change the location of the user config file?
Thanks in advance.

**Comment by rekaerst** [comment]
Thanks, but, where to define the variable?
I tried to define it in /usr/local/etc/luarocks/config-5.3.lua
```lua
-- LuaRocks configuration

rocks_trees = {
   { name = "user", root = home .. "/.local/share/luarocks" };
   { name = "system", root = "/usr/local" };
}
lua_interpreter = "lua5.3";
variables = {
   LUA_DIR = "/usr";
   LUA_BINDIR = "/usr/bin";
   LUAROCKS_CONFIG = "/home/arthur/.config/luarocks/config-5.3.lua"
}
```
and with the environment variable 
```bash
export LUAROCKS_CONFIG=/home/arthur/.config/luarocks/config-5.3.lua
```
but luarocks' output is still:
```
Configuration:
   Lua version: 5.3

   Configuration files:
      System  : /usr/local/etc/luarocks/config-5.3.lua (ok)
      User    : /home/arthur/.luarocks/config-5.3.lua (not found)

   Rocks trees in use:
      /home/arthur/.luarocks ("user")
      /usr/local ("system")
```

**Comment by speccius** [comment]
Solution still unknown on windows

**Comment by hishamhm** [comment]
setting the LUAROCKS_CONFIG environment variable should work on Windows as well.

**Comment by speccius** [comment]
Not on my machine(tm), luarocks ignores it

**Comment by hishamhm** [comment]
I'm not sure of the details pertaining to specific versions of Windows, but you may want to try to set the environment variable globally, since depending on how you installed LuaRocks, the launcher script escalates its own privileges.
