### ISSUE TITLE
bug in install.bat, produces invalid luarocks.bat and luarocks-admin.bat under certain conditions

### ISSUE THREAD

**Issue by dirkstff** [luarocks/luarocks#1232]
The bug was introduced by commit 04513372d7d5859ea865252095c3b5ce0762228f. Now, if `vars.COMPILER_ENV_CMD == ""`, which it can very well be, the line `$COMPILER_ENV_CMD >NUL` resolves to ` >NUL`, which is a cmd syntax error. Accordingly, luarocks.bat and luarocks-admin.bat fail.

**Comment by hishamhm** [comment]
@dwenegar Looks like the issue was introduced by your PR — could you take a look at this, please? Thanks!
