### ISSUE TITLE
Windows 10: Compiling with llvm-mingw and lld: LuaRocks 3.0.3 works, 3.4.0 does not.

### ISSUE THREAD

**Issue by RussellHaley** [luarocks/luarocks#1237]
Hi Hisham, 

I'm compiling on Windows with llvm-mingw. The peculiar thing about the llvm toolchain is that `lld` the linker does not support linking directly to a shared object (DLL) in windows. In LuaRocks (and Lua), that GNU "DLL linking" feature is used quite a bit. I was able to work around that problem in LuaRocks 3.0.3 by changing the config file to list *.lib files first, but that feature stopped working some time back. I've tested with 3.4.0 and I cannot compile with clang/lld.

Here is my test. I installed my latest WinLua package, which includes Luarocks 3.0.3 and a custom luarocks config file. Here is the config file:

```
rocks_trees = {
	{
			name = "user",
			root = "home..[[/luarocks]]"    --< ha ha totally broken. I just noticed that!!!
		},
	{
			name = "system",
			root = "C:/Program Files (x86)/WinLua/Lua/5.3/"
		}
}
variables = {
	LUA_LIBDIR = "C:/Program Files (x86)/WinLua/Lua/5.3/bin/",
	LUA_INCDIR = "C:/Program Files (x86)/WinLua/Lua/5.3/include/",
	LUALIB = "lua53.lib",
	CC = "wlc32.exe",
	LD = "wlc32.exe"
}
external_deps_dirs = {
	"C:/Program Files (x86)/WinLua/WLC/i686-w64-mingw32/"
}
external_deps_patterns = {
	bin = {
			"?.exe",
			"?.bat"
		},
	lib = {
			"lib?.a",
			"lib?.dll.a",
			"?.dll.a",
			"?.lib",
			"lib?.lib"
		},
	include = {
			"?.h"
		}
}
verbose = false-- set to 'true' to enable verbose output
```

 I downloaded Luarocks 3.4.0 and did a comparison. First I installed Chronos with Luarocks 3.0.3, then I removed it. I changed luarocks to 3.4.0 and repeated the test and chronos failed to build (linking failed).

```
     Directory: C:\Program Files (x86)\WinLua\LuaRocks\bin

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        11/14/2020  11:38 PM                3.0.3
d-----        11/14/2020  11:50 PM                3.4.0


PS C:\Program Files (x86)\WinLua\LuaRocks\bin> cp .\3.0.3\*.exe .
PS C:\Program Files (x86)\WinLua\LuaRocks\bin> luarocks remove chronos

Error: Could not find rock 'chronos' in C:/Program Files (x86)/WinLua/Lua/5.3
PS C:\Program Files (x86)\WinLua\LuaRocks\bin> luarocks install chronos
Installing https://luarocks.org/chronos-0.2-4.src.rock

wlc32.exe -O2 -c -o src/chronos.o -IC:/Program Files (x86)/WinLua/Lua/5.3/include/ src/chronos.c
wlc32.exe -shared -o chronos.dll src/chronos.o C:/Program Files (x86)/WinLua/Lua/5.3/bin/lua53.lib -lm
chronos 0.2-4 is now installed in C:/Program Files (x86)/WinLua/Lua/5.3 (license: MIT/X11)

PS C:\Program Files (x86)\WinLua\LuaRocks\bin> luarocks remove chronos
Checking stability of dependencies in the absence of
chronos 0.2-4...

Removing chronos 0.2-4...
Removal successful.
PS C:\Program Files (x86)\WinLua\LuaRocks\bin> cp .\3.4.0\*.exe .
PS C:\Program Files (x86)\WinLua\LuaRocks\bin> .\luarocks.exe --version
luarocks 3.4.0
LuaRocks main command-line interface

PS C:\Program Files (x86)\WinLua\LuaRocks\bin> luarocks install chronos
Warning: Lua 5.3 interpreter not found at C:\Program Files (x86)\WinLua\LuaRocks

Modules may not install with the correct configurations. You may want to configure the path prefix to your build of Lua 5.3 using

   luarocks config --local lua_dir <your-lua-prefix>

Installing https://luarocks.org/chronos-0.2-4.src.rock

chronos 0.2-4 depends on lua >= 5.1 (5.3-1 provided by VM)
wlc32.exe -O2 -c -o src/chronos.o -IC:/Program Files (x86)/WinLua/Lua/5.3/include/ src/chronos.c
wlc32.exe -shared -o chronos.dll src/chronos.o C:/Program Files (x86)/WinLua/Lua/5.3/bin/lua53.dll -lm
lld-link: error: C:\Program Files (x86)\WinLua\Lua\5.3\bin\lua53.dll: bad file type. Did you specify a DLL instead of an import library?
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)

Error: Build error: Failed compiling module chronos.dll
PS C:\Program Files (x86)\WinLua\LuaRocks\bin>
```

This tells me there is some sort of regression in LuaRocks that assumes *.dll and ignores the config file? Or is there anything else you could suggest? 

My website http://www.winlua.net has an older llvm-mingw toolchain that installs luarocks. It could be used for testing if needs be?  Let me know what I can do (though I suspect you know which code to diff between 3.0.3 and 3.4.0 to see what changed in configuration)? I'm going to look at getting Luarocks to build again (but need sleep first!).

Thanks Hisham!
Russell

**Comment by RussellHaley** [comment]
As an addendum, I'm creating a compiler for specific use with LuaRocks on Windows.  I'm calling it WinLua Compiler - Tiny edition. I've just pared down llvm-mingw to a 52 Mb zip file that installs to 180 Mb. I can compile luasocket with LR 3.0.3 (though I need to patch the rockspec).  

http://winlua.net/downloads/wlc-tiny-2011a-BETA.zip - Includes compiler and a config file for luarocks. 

I'm trying to get the compiler down to 150 Mb for a 100:1 ration with Lua (bin + headers) on Windows. I will optimize the build size in CMake and there is a 6 MB tool I can possibly remove (ranlib and ar at the same binaries but act differently when renamed).

The target audience is people that don't really care about C, but want the cool modules and don't want to install 20GB of Visual Studio[1]. I'd say 180 *Megabytes* is a pretty good improvement! There is no point in installing debuggers and things if people are never going to use it. I'll prepare an installer containing Lua, LuaRocks, and WLC-tiny. it so that all the paths and what-not are properly specified. 

As soon as I can get a current LuaRocks working with clang/lld (I'm fine with custom config files!) then I'd like to announce the compiler on the lua mailing list for testing. 

Cheers,
Russ

[1] Mingw is considerably larger and is too complicated to understand for the average Windows user that's looking into Lua. I know this as an above-average Windows user that had to learn to use mingw.

**Comment by siffiejoe** [comment]
@RussellHaley I've done something similar a few years ago using hand-picked components of MinGW. The installer was 37 MB, so MinGW is not necessarily that big. Obviously it's out of date now, and I don't have a Windows machine at home anymore. But maybe you can find some inspirations. Link is here: https://github.com/siffiejoe/prg-lr4win

**Comment by RussellHaley** [comment]
@siffiejoe Ha ha. I often find myself re-treading your steps. You seem to have been quite prolific at one time (perhaps still are?). I don't even know you but your almost like an old friend. :-)

**Comment by siffiejoe** [comment]
@RussellHaley The next Lua workshop appears to be in my home country, so I have little excuse not going. Maybe we'll meet there. Unfortunately my active Lua days are mostly over. I still lurk the mailing list and keep some of my more useful Lua experiments up and running, but I don't have time for much more.

Back to LuaRocks on Windows: Having a compiler is great but doesn't give you much more than luafilesystem and luasocket. Most C modules require external libraries. Back in the day, I tried to integrate binary repositories, but then you run into issues with different MS visual runtime versions. Today, I'd try using one of the more popular source code repositories (e.g. Conan and/or vcpkg).

**Comment by RussellHaley** [comment]
I might try to attend remotely this year if they have a remote option. Attending in person isn't really possible even without covid due to family obligations. 

So step 1 is to fix this infernal problem with LuaRocks. This has been plaguing me for some time but I haven't tracked it down; I only get spurts of time to work on these things and LuaRocks has been low on that priority until recently. 

My next step was to try cross building all the LuaRocks modules: I have a 32 core server that I want to set up to cross build everything (e.g. build server). I am already cross building the llvm compiler, libressl and some other applications, so I think I am in good shape once I get this linking issue solved.  This will be a multi-step process that I am hoping will inform further decisions about how to get binary rocks into the wild.

Since I am using llvm-mingw and only supporting Windows 10, I don't foresee having the same runtime problems that you were probably dealing with, but I am speculating at this point. I don't know *what* kinds of problems I will have, and that's the whole point of doing it! Ha ha. 

I need to get to work so we can continue this later. I really appreciate your input. Thanks Phillip!

**Comment by RussellHaley** [comment]
@siffiejoe  Currently clang is compiled with static libraries, which I understand increases the size of overall file, but also improves the compile efficiency. There are options to compile it with -dynlib (one large dynamic library) or as separate shared objects. I tried -dynlib but it was ignored because that apparently doesn't work on Windows. I'll look at the shared object option soon. Anyways, I should stop fussing and start looking at luarocks code. :-)

**Comment by RussellHaley** [comment]
Okay, well I found the solution. I realized that the ?.lib pattern was in the middle of the external_dep_patterns list, so I moved it to the top and that was enough to get LuaRocks 3.4.0 to link "correctly". So, perhaps it has something to do with the list merging?

Well, once again sorry for the noise. My shame is only masked by my joy of being able to complete my installers!

**Comment by RussellHaley** [comment]
@siffiejoe "Today, I'd try using one of the more popular source code repositories (e.g. Conan and/or vcpkg)."

Interestingly I want to go a different way: I want to integrate the LuaRocks functionality into the xmake build system. It's one of the coolest build systems I found and it's lua based. 

Thanks everyone!

**Comment by siffiejoe** [comment]
@RussellHaley 
> Since I am using llvm-mingw and only supporting Windows 10, I don't foresee having the same runtime problems that you were probably dealing with, but I am speculating at this point. I don't know what kinds of problems I will have, and that's the whole point of doing it!

Microsoft used to change the C runtime with every released Visual C compiler, and MinGW used yet another (older) runtime version. So you'd have to make sure, that the binary repository you chose used the same C runtime version as your compiler. I'm not up to speed about the current state of Microsoft runtimes and llvm-mingw, so I don't know if there could be issues (with binary repositories).

> I want to integrate the LuaRocks functionality into the xmake build system.

This is basically the LuaDist approach: build and maintain separate build scripts for the external dependencies. This is a lot of work, and it didn't work out for LuaDist. I think it could actually work today because CMake -- which is the build system chosen by LuaDist -- is more and more becoming the default build system for C and C++ based projects.

**Comment by RussellHaley** [comment]
> Microsoft used to change the C runtime with every released Visual C compiler, and MinGW used yet another (older) runtime version.

My understanding is that the "runtime situation" has changed somewhat. Microsoft has 'promised' not to change the C runtime anymore. It's been stable now for three Visual Studio versions. My understanding is the mingw64 project has been greatly improving the C runtime. Also the variant I am using uses an updated ABI that includes some things that were excluded from mingw32 by default. 

Regardless of MS 'promises' I don't want to ship a runtime, so mingw64 suites me fine. 

> This is basically the LuaDist approach: build and maintain separate build scripts for the external dependencies. This is a lot of work, and it didn't work out for LuaDist. I think it could actually work today because CMake -- which is the build system chosen by LuaDist -- is more and more becoming the default build system for C and C++ based projects.

@ruki has already built a "recipe" package system into the xmake build tool and has a number of pre-requisites like pcre, zlib and so forth.  That means we could either: a) call xmake from luarocks to build and install a package or b) integrate luarocks into xmake? 

I'm noodling on the idea over here:  https://github.com/xmake-io/xmake/issues/1043
