### ISSUE TITLE
YAJL_INCLUDE required but not respected for lua-yajl

### ISSUE THREAD

**Issue by vadi2** [luarocks/luarocks#1239]
When installing [lua-yajl](https://github.com/brimworks/lua-yajl), it appears that YAJL_INCLUDE is required by LuaRocks before compilation can even begin - but once provided, it is not actually used for compilation, resulting in a build failure. Passing in LUA_INCDIR as well works though.

This is using v3.3.1 (latest doesn't work because of the [.bat bug](https://github.com/luarocks/luarocks/issues/1232))

**Comment by siffiejoe** [comment]
This is a problem in the lua-yajl rockspec. LuaRocks checks the existence of headers and libraries for you and creates variables with the corresponding paths, but the rockspec author is responsible for passing those variables to the build system. See the example [here](https://github.com/luarocks/luarocks/wiki/Creating-a-rock#building-a-module). The [rockspec for lua-yajl](https://github.com/brimworks/lua-yajl/blob/master/rockspecs/lua-yajl-2.0-1.rockspec) does not do that.

@luarocks/team-luarocks 
One could think/talk about LuaRocks passing those variables automatically (maybe only if there are no incdirs/libdirs specified?) ...

**Comment by vadi2** [comment]
For anyone else looking, this is still an issue:

```
LIBRARY_PATH=/opt/homebrew/Cellar/yajl/2.1.0/lib C_INCLUDE_PATH=/opt/homebrew/Cellar/yajl/2.1.0/include luarocks --local install lua-yajl
```
