### ISSUE TITLE
upload error

### ISSUE THREAD

**Issue by huifer** [luarocks/luarocks#1243]
```
Configuration:
   Lua version: 5.1
```

Error: A JSON library is required for this command. Failed loading 'cjson', 'dkjson', and 'json'. Use 'luarocks search <partial-name>' to search for a library and 'luarocks install <name>' to install one.

**Comment by daurnimator** [comment]
That error seems pretty explanatory to me; what else should we do?

**Comment by huifer** [comment]
This problem occurs when I execute the lualocks upload command again. The versions of 5.1, 5.2 and 5.3 have been changed

**Comment by huifer** [comment]
cjson dkjson json i can not found

**Comment by hishamhm** [comment]
Run `luarocks install dkjson` then try uploading again

**Comment by huifer** [comment]
Use it later. I'm trying again

**Comment by siiky** [comment]
I was surprised and confused by this same error message because `luarocks install` failed for both `cjson` and `json`.

(sorry to nekro)

**Comment by lggruspe** [comment]
I think I'm running into the same problem. `luarocks install dkjson` installs `dkjson` inside `./lua_modules` of my project's directory, but when I run `luarocks upload`, it can't find `dkjson`. Running `luarocks --tree lua_modules upload` didn't work either.

What worked for me was installing `djkson` in my local tree before uploading.

```
luarocks install --local dkjson
luarocks upload
```

platform: linux
luarocks version: 3.9.2
