### ISSUE TITLE
LUA_LIBDIR is unset when using make build backend

### ISSUE THREAD

**Issue by gnarz** [luarocks/luarocks#1257]
I have a fresh install of lua 5.4.2 and luarocks 3.5.0 on a fresh install of linux MiNT 20.04. No other lua or luarocks versions are or were installed. When attempting to build my rocks, which use the make backend, with luarocks, I noticed that the LUA_LIBDIR variable is empty when luarocks calls make. The relevant output from the verbose luarocks log looks like this:

fs.execute("make ", "LUA_INCDIR=/usr/local/include", "CFLAGS=-O2 -fPIC", "LUA_BINDIR=/usr/local/bin", "LUA_LIBDIR=", "LIBFLAG=-shared", "CC=gcc")
fs.Q("LUA_INCDIR=/usr/local/include")
fs.Q("CFLAGS=-O2 -fPIC")
fs.Q("LUA_BINDIR=/usr/local/bin")
fs.Q("LUA_LIBDIR=")
fs.Q("LIBFLAG=-shared")
fs.Q("CC=gcc")
fs.execute_string("make  'LUA_INCDIR=/usr/local/include' 'CFLAGS=-O2 -fPIC' 'LUA_BINDIR=/usr/local/bin' 'LUA_LIBDIR=' 'LIBFLAG=-shared' 'CC=gcc'")

You will notice that both LUA_INCDIR and LUA_BINDIR are set, just LUA_LIBDIR is empty. This is reproducible with the sample Makefile and rockspec from here: https://github.com/luarocks/luarocks/wiki/Creating-a-Makefile-that-plays-nice-with-LuaRocks

**Comment by imolein** [comment]
I just noticed the same, while I tried to install the `pulseaudio` module using luarocks 3.9.1 and lua 5.4.4.

**Comment by siffiejoe** [comment]
On Linux (and I think a few other Unixes) binary extension modules must not be linked with the Lua library. The `lua` executable reexports the Lua API to them. So the `LUA_LIBDIR` and `LUALIB` variables are not needed.

**Comment by tobil4sk** [comment]
It would be helpful if this was mentioned in the wiki: https://github.com/luarocks/luarocks/wiki/Creating-a-Makefile-that-plays-nice-with-LuaRocks
