### ISSUE TITLE
typing `luarocks` in command line opens luarocks.lua in Visual Studio Code?

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [luarocks/luarocks#1258]
Really weird problem. Today I installed LuaRocks as described in the windows guide. I then set my PATHS, as recommended by the install output. I tried to install my first rock and was surprised to see this in my console along with Visual Studio Code opening:

```
C:\Users\Proto\Code\game\item_protocol>luarocks install lunajson

C:\Users\Proto\Code\game\item_protocol>
[main 2021-01-08T21:04:47.555Z] update#setState idle
(node:10148) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Users\Proto\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-sqlite3\build\Release\sqlite.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:10148) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Users\Proto\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:22540) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Users\Proto\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
```

I just tried typing `luarocks` into my console and the same happens: luarocks.lua is opened in my code editor, Visual Studio Code.
I have no clue how this has happened.

**Comment by TheMaverickProgrammer** [comment]
I took out `PATHEXT: .LUA` as recommended from my environment variable and I was able to execute luarocks commands. Leaving this here as a bug report.

**Comment by daurnimator** [comment]
There is nothing that luarocks can do here: this is how window's cmd.exe works when you have `PATHEXT` set up like that.

**Comment by TheMaverickProgrammer** [comment]
it was recommended by luarocks install output. that's confusing

**Comment by daurnimator** [comment]
> it was recommended by luarocks install output.

What was?

**Comment by TheMaverickProgrammer** [comment]
to setup PATHEXT in this manner
