### ISSUE TITLE
http://www.luarocks.org is down

### ISSUE THREAD

**Issue by dawidstefaniak** [luarocks/luarocks#1273]
Hi,

http://www.luarocks.org seems to give 502 Bad Gateway error for any page I request. I think the server may be down so I just want to report it to you so you can solve it quickly.

**Comment by daelvn** [comment]
Hello,

The [LuaRocks site](https://github.com/luarocks/luarocks-site) is currently under maintenance due to an unexpected issue. It should be up shortly, though.

**Comment by leafo** [comment]
The site is back up but still noticing some issues with installation of some modules. I'll post an update when it's resolved.

**Comment by leafo** [comment]
Everything should be functioning as intended right now, sorry for the extended issues. Turns out having the luarocks website depend on luarocks to install dependencies didn't work out the greatest. There are still a few more things I need to look into but I'll do it during non-work hours.
