### ISSUE TITLE
Building pure-lua rocks fails if header files not available

### ISSUE THREAD

**Issue by daurnimator** [luarocks/luarocks#1275]
Trying to build pure lua rocks shouldn't fail if the lua header is not installed. 

We currently fail due to the unconditional call to `deps.check_lua_incdir` https://github.com/luarocks/luarocks/blob/007078e85fbf0d9d2e6d4d0390d622654e42ee49/src/luarocks/build.lua#L114

**Comment by Zash** [comment]
The Prosody plugin installer uses luarocks behind the scene to install primarily pure Lua modules. Needing to have development headers available makes this awkward for our users, especially as they often end up with e.g. Lua 5.1 development headers but need headers for 5.2 (this is of course distribution package management issue). Not needing the headers would make things a lot easier.

**Comment by ABelliqueux** [comment]
Just had an issue with the prosody plugin installer complaining about this in Debian. 
FWIW an while waiting for a fix, I had to install the liblua dev version corresponding to the one on my system:

`sudo apt-get install liblua$(lua -v | awk '{print $2}' | awk -F. '{print$1"."$2}')-dev`

Maybe this will help someone else getting rid of the issue.
