### ISSUE TITLE
Svn fetcher incorrectly checks for svn tool availability

### ISSUE THREAD

**Issue by daa** [luarocks/luarocks#1280]
Currently it passes ``"--version"`` argument where tool name is expected and ``"Subversion"`` name where argument is expected: https://github.com/luarocks/luarocks/blob/e93778d4e0ec16e3358cff35ab79a497d52e8609/src/luarocks/fetch/svn.lua#L23
And it results in the error when trying to use svn source url:
```
Error: 'svn' program not found. Make sure --version is installed and is available in your PATH (or you may want to edit the 'variables.--VERSION' value in file .....
```

**Comment by daurnimator** [comment]
Looks like this was introduced from the beginning (c9b7f0bc5453251730c73040904a17a8fd32eef3)
