### ISSUE TITLE
Crossed module files getting deleted on install

### ISSUE THREAD

**Issue by leafo** [luarocks/luarocks#1291]
So I don't know if this is formally supported, but I would expect it to.

Lets say we have two rocks, `lapis` and `lapis-exceptions`:

`lapis` installs modules named like:

* `lapis`
* `lapis.application`
* `lapis.db.model`

`lapis-exceptions` installs modules named like:

* `lapis.exceptions`
* `lapis.exceptions.model`

Note that the module names cross, so they share directories when installed. I would expect installing/removing/updating one of them individually would not touch the files belonging to the other.

I've recreated a scenario where updating `lapis` deletes all the files in the lapis directory that were inserted by other installed rocks. I've included my entire luarocks tree (as a git repository) in this zip: [test-tree.zip](https://github.com/luarocks/luarocks/files/6175093/test-tree.zip)

Extract the tree to a directory, then run the command:

```
luarocks install --tree=location-of-tree --lua-version=5.1 lapis
```
(I also put a script, `breakme.sh`, that runs that command with the current directory as the tree)

Then run a git status in the tree to see what files are removed.

* all the files included in `share/lua/5.1/lapis/` that aren't directly part of lapis are removed, although the rocks are still installed according to the manifest
* `bin/lapis` is removed (despite having just installing lapis), a versioned `bin/lapis_1_8_3_1-lapis` is created though

Any modified files in `share/lua/5.1/lapis` are not an issue, since the version being installed and the version already in that tree are slightly different.

**Comment by hishamhm** [comment]
I haven't had the chance to run the repro yet, but just from reading the
description it definitely sounds like a regression. I'm almost ready to
push a new release, I'll make sure to get the fix for this included.

**Comment by hishamhm** [comment]
All right, I tried to reproduce it on current `master` using your zip and following the instructions, but it worked correctly (`lapis` updated to 1.8.3, `bin/lapis` was updated, `lapis/exceptions/*` were not deleted). I will push a new release of LuaRocks, and let's see if you can still reproduce it on your end with the latest code.

**Comment by leafo** [comment]
Just for confirmation, I'm on 

luarocks --version
/usr/bin/luarocks 3.5.0
LuaRocks main command-line interface

Installed via arch linux

**Comment by hishamhm** [comment]
@leafo Good news, I have reproduced it with a vanilla install of LuaRocks 3.5.0 using `breakme.sh` and can no longer reproduce it doing the same with a vanilla install of the upcoming LuaRocks 3.6.0. :+1: 

Thanks for the detailed report and test case!
