### ISSUE TITLE
[Win] Luarocks 3.5.0 does not respect default-lua-version

### ISSUE THREAD

**Issue by gustavo-nramires** [luarocks/luarocks#1293]
Hi, I have luarocks configured with `luarocks config lua_version 5.4` which 
(1) generates `default-lua-version.lua` at `%appdata%/luarocks` as well as 
(2) write `lua_version = "5.4"` to my `config-5.4.lua` file
However, when I run `luarocks`, it still shows the errors of `config-5.3.lua` (not found). It would be great if it autodetected the version without needing to set --lua-version 5.4 every time. Thank you

**Comment by gustavo-nramires** [comment]
It appears we could insert the home directory in the check of default-lua-version, by inserting `table.insert(dirs, cfg.homeconfdir)` into line 238 of `/src/luarocks/cmd.lua`

**Comment by Taswen** [comment]
You can execute command `luarocks config --scope system  lua_version 5.4` in cmd under administrator rights to set default version of lua. It  will write `lua_version = "5.4"` to `C:/Program Files/luarocks/config-5.4.lua` that actually decides which version of lua to use.

**Comment by hishamhm** [comment]
@gustavo-nramires fixed via a modified version of your PR! thank you!
