### ISSUE TITLE
Assertion error at dependency resolution

### ISSUE THREAD

**Issue by hoylemd** [luarocks/luarocks#1295]
I went to install `luacheck` via luarocks on my Apple Silicon laptop, with

```
luarocks install luacheck
```

And this was the result (a bit of the preamble omitted, as it seems to be successfully installing dependencies)

```
Error: LuaRocks 3.6.0 bug (please report at https://github.com/luarocks/luarocks/issues).
Arch.: macosx-x86_64
...ew/Cellar/luarocks/3.6.0/share/lua/5.4/luarocks/deps.lua:245: assertion failed!
stack traceback:
        [C]: in function 'assert'
        ...ew/Cellar/luarocks/3.6.0/share/lua/5.4/luarocks/deps.lua:245: in function 'luarocks.deps.fulfill_dependency'
        ...ew/Cellar/luarocks/3.6.0/share/lua/5.4/luarocks/deps.lua:337: in function 'luarocks.deps.fulfill_dependencies'
        ...w/Cellar/luarocks/3.6.0/share/lua/5.4/luarocks/build.lua:138: in upvalue 'process_dependencies'
        ...w/Cellar/luarocks/3.6.0/share/lua/5.4/luarocks/build.lua:379: in function 'luarocks.build.build_rockspec'
        ...llar/luarocks/3.6.0/share/lua/5.4/luarocks/cmd/build.lua:74: in function <...llar/luarocks/3.6.0/share/lua/5.4/luarocks/cmd/build.lua:51>
        (...tail calls...)
        ...llar/luarocks/3.6.0/share/lua/5.4/luarocks/cmd/build.lua:154: in function 'luarocks.cmd.build.command'
        (...tail calls...)
        [C]: in function 'xpcall'
        ...rew/Cellar/luarocks/3.6.0/share/lua/5.4/luarocks/cmd.lua:662: in function 'luarocks.cmd.run_command'
        /opt/homebrew/bin/luarocks:38: in main chunk
```

**Comment by hishamhm** [comment]
Thanks for reporting! Are you able to reproduce it with `--verbose` and post the full output in a gist? It would be useful to know at which dependency it failed.

**Comment by hoylemd** [comment]
Sure, here it is: https://gist.github.com/hoylemd/84757f5b2e7abc9592eca72941f6073e

I did that with `luarocks install luacheck --verbose > lr.out` and `lr.out` is that gist.

**Comment by hishamhm** [comment]
@hoylemd oh, that's interesting. Looking at the gist, the installation of luacheck worked this time around.

**Comment by hishamhm** [comment]
Unfortunately I'm unable to reproduce it on my end. I'll keep this open in case someone else hits the same issue and is able to reproduce it and provide more info.

**Comment by hoylemd** [comment]
...so it did! That's strange. Maybe whatever was broken got fixed!  Love it when that happens :p. Here's hoping you can close this soon!

**Comment by hishamhm** [comment]
Closing since we haven't heard of others going through the same.
