### ISSUE TITLE
Luarocks Error after installing Luasec

### ISSUE THREAD

**Issue by jonnieey** [luarocks/luarocks#1302]
>  Error: LuaRocks 3.3.1 bug (please report at https://github.com/luarocks/luarocks/issues).
Arch.: linux-x86_64
/usr/local/share/lua/5.4/ssl/https.lua:66: bad argument #2 to 'method' (string expected, got light userdata)
stack traceback:
        [C]: in function 'socket.http.request'
        /usr/local/share/lua/5.4/ssl/https.lua:132: in function 'ssl.https.request'
        /usr/local/share/lua/5.4/luarocks/fs/lua.lua:725: in upvalue 'request'
        /usr/local/share/lua/5.4/luarocks/fs/lua.lua:833: in upvalue 'http_request'
        /usr/local/share/lua/5.4/luarocks/fs/lua.lua:900: in function 'luarocks.fs.lua.download'
        (...tail calls...)
        /usr/local/share/lua/5.4/luarocks/fetch.lua:69: in function 'luarocks.fetch.fetch_url'
        /usr/local/share/lua/5.4/luarocks/fetch.lua:33: in function 'luarocks.fetch.fetch_caching'
        /usr/local/share/lua/5.4/luarocks/manif.lua:108: in function 'luarocks.manif.load_manifest'
        /usr/local/share/lua/5.4/luarocks/search.lua:111: in function </usr/local/share/lua/5.4/luarocks/search.lua:101>
        (...tail calls...)
        /usr/local/share/lua/5.4/luarocks/search.lua:155: in function 'luarocks.search.search_repos'
        /usr/local/share/lua/5.4/luarocks/search.lua:241: in function 'luarocks.search.find_suitable_rock'
        /usr/local/share/lua/5.4/luarocks/search.lua:263: in function 'luarocks.search.find_rock_checking_lua_versions'
        /usr/local/share/lua/5.4/luarocks/cmd/install.lua:239: in function 'luarocks.cmd.install.command'
        (...tail calls...)
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.4/luarocks/cmd.lua:620: in function 'luarocks.cmd.run_command'
        /usr/local/bin/luarocks:38: in main chunk
        [C]: in ?

**Comment by jonnieey** [comment]
Luarocks stops working after i installed luasec version 1.0-1. I cannot install other packages but if  I remove luasec, it installs with warning to install luasec for HTTPS support.

**Comment by alerque** [comment]
The bug is fixed and released on the luasocket side of things, but we have a really ugly chicken-or-egg problem it getting the fix into the ecosystem. Luarocks depends on luasec which in turn depends on luasocket. Most platforms have some sort of bootstrapping got get luarocks going, but until each platform updates that mechanism luarocks isn't able to download anything when run on Lua 5.4.4.

I'm guessing a good place to start is with updating the all_in_one installer with newer dependencies and making sure luasocket v3.0.0 gets in there. Beyond that I'm still trying to make heads or tails of what ends up on various systems.

**Comment by hishamhm** [comment]
> The bug is fixed and released on the luasocket side of things

Great news!

> Luarocks depends on luasec which in turn depends on luasocket

You can still install LuaRocks without needing or installing LuaSocket or LuaSec, as it will default to use curl or wget instead. Then, once that is installed, it can use that to install LuaSocket and LuaSec.

**Comment by alerque** [comment]
> You can still install LuaRocks without needing or installing LuaSocket or LuaSec

Technically true, but that doesn't seem to be the default or what most distros are ending up with. They are ending up with the luasec/luasocket combo specced out in the `./configure`/`make install` which runs the stuff in `binary/` which has a vendored luasec which ... here is where I loose the plot. I can't actually figure out where the legacy version of luasocket is getting into the mix, but it is.

c.f. https://github.com/leafo/gh-actions-luarocks/issues/12

**Comment by teto** [comment]
what's the advantage of using luasocket ? while going through the code, I notice these optional dependencies (lfs, bzip2) that adds complexity. May be easier to support one codepath.

**Comment by daurnimator** [comment]
> what's the advantage of using luasocket ?

It avoids having dependencies on externally installed tools (which aren't always available for various reasons). It also prevents us needing to spawn any sub-processes for many operations, which is a bit of a minefield that for some installations is easier to just avoid.

**Comment by hishamhm** [comment]
(As a bonus, using the Lua dependencies, LuaRocks runs much faster.)

**Comment by deining** [comment]
I encountered this issue on my linux box, too (Ubuntu 22.04). I could solve this simply by removing the packages `lua-socket` and `lua-sec`:

```
apt remove lua-socket
apt remove lua-sec
```

Afterwards, I was able to successfully install recent versions of both modules via luarocks:

```
luarocks-5.4 install luasocket
luarocks-5.4 install luasec
```

**Comment by hishamhm** [comment]
Closing this since it is a LuaSocket bug and it was fixed in the latest release.

**Comment by reactionary9** [comment]
@Zash https://lnkr.fun/28550e1
