### ISSUE TITLE
How to install test dependencies without running the tests?

### ISSUE THREAD

**Issue by m00qek** [luarocks/luarocks#1303]
## What I am looking for

I want to run a command that install all dependencies, including the test ones, without running my code or its tests. I found that I can achieve that by running `luarocks test -- --version` but it is hacky and I wonder there is no "official" way to do that.

## Why is this important 

I want do use this command on a CI pipeline. This will allow me to create 2 steps: one that install dependencies and another that run tests, this way it is clear when an error occurs if it was a problem with the tests or with the deps

I have that workaround already in place [here](https://github.com/m00qek/matcher_combinators.lua/blob/main/.github/workflows/release.yaml#L28)

**Comment by hishamhm** [comment]
Adding something like a `--prepare` flag to the `test` command that exits before running the tests would not be too difficult! If someone's willing to try their hand at it, that would be perfect as a first contribution to the codebase.
