### ISSUE TITLE
luarocks.fs.execute_env does not work properly on windows

### ISSUE THREAD

**Issue by khvzak** [luarocks/luarocks#1307]
Hello,
In the [`luarocks.fs.execute_env`](https://github.com/luarocks/luarocks/blob/master/src/luarocks/fs/lua.lua#L97) function, `envstr` concatenation probably should use separator depending on Unix/Windows.
The current version on windows produces a command like:
```
SET ENV1=val1\
SET ENV2=val2\
command
```
And seems everything after the first `SET` is ignored.
I believe this could be fixed by using `&&` separator on windows.

I used `execute_env` in my library and it didn't pass tests on windows. Fixed by re-implementing `execute_env`: https://github.com/khvzak/luarocks-build-rust-mlua/commit/484f5e0c486a0c7b0185c192c78a0caf64f3466c

**Comment by hishamhm** [comment]
Thank you for the report! Would you like to submit a PR fixing the behavior? I can help out with the tests. Since I don't have a running Windows system, it's better if changes in the Windows are done by someone running it.

**Comment by hishamhm** [comment]
I don't know what happened to [0810eb8](https://github.com/luarocks/luarocks/commit/0810eb8ad185d496a51aaf398527bcddec0052f9) which caused it to get dropped, but this is now fixed by https://github.com/luarocks/luarocks/pull/1569
