### ISSUE TITLE
Failed setting permission exec for all

### ISSUE THREAD

**Issue by mal4ishka** [luarocks/luarocks#1312]
I'm running x64 Windows 8.1.
I'm using:

```
lua -v
Lua 5.3.6  Copyright (C) 1994-2020 Lua.org, PUC-Rio
```

```
luarocks --version
luarocks 3.7.0
```

And when I try to install lfs, I receive such error:

```
luarocks install luafilesystem
Installing https://luarocks.org/luafilesystem-1.8.0-1.src.rock

Error: Could not fetch rock file: Failed creating temporary directory luarocks-rock-luafilesystem-1.8.0-1: Failed setting permission exec for all
```

I'm running cmd/Developer Command Promt/Powershell with admin rights and everywhere getting this error.
Could you please help me with this issue?
Thanks.

PS tested on other mashine running Windows 10, and problem is still the same.

**Comment by hishamhm** [comment]
Hard to tell! Could you run the output of running `luarocks install luafilesystem --verbose` on a Gist?

pinging @moteus, since you're running LR on Windows: any idea of what could be the cause?

**Comment by mal4ishka** [comment]
https://gist.github.com/mal4ishka/9a25fb66f06555f6b8399bd6d03189be

**Comment by moteus** [comment]
In my LuaRocks I see no usege of the `iacls` for the temporary directory. This is my [output](https://gist.github.com/moteus/de73bc50b10807359d0fb810c20bca83) fot the LuaFIleSystem install.
LuaRocks downloads it like 
```
os.execute:     C: & cd "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC" & "C:\luaenv\x64\luarocks\tools\mkdir.exe" -p  "C:\Users\alexey\AppData\Local\Temp\luarocks_luarocks-rock-luafilesystem-1.8.0-1-4614"
os.execute:     C: & cd "C:\Users\alexey\AppData\Local\Temp\luarocks_luarocks-rock-luafilesystem-1.8.0-1-4614" & "curl" -k -f -L --user-agent "LuaRocks/dev win32-x86_64 via curl" --connect-timeout 30 "https://luarocks.org/luafilesystem-1.8.0-1.src.rock" > "C:\Users\alexey\AppData\Local\Temp\luarocks_luarocks-rock-luafilesystem-1.8.0-1-4614\luafilesystem-1.8.0-1.src.rock" 2> NUL
os.execute:     C: & cd "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC" & "C:\luaenv\x64\luarocks\tools\mkdir.exe" -p  "C:\Users\alexey\AppData\Local\Temp\luarocks_luafilesystem-1.8.0-1-4931"
os.execute:     C: & cd "C:\Users\alexey\AppData\Local\Temp\luarocks_luafilesystem-1.8.0-1-4931" & "C:\luaenv\x64\luarocks\tools\7z.exe" -aoa x "C:\Users\alexey\AppData\Local\Temp\luarocks_luarocks-rock-luafilesystem-1.8.0-1-4614\luafilesystem-1.8.0-1.src.rock"
```

PS. I see a lot of `invalidcommandname` commands. But I think it so do of fake command.

**Comment by maikgreubel** [comment]
I have the same issue, but on a german edition of windows 10. icacls depends on os language. Maybe a change from "Everyone:(RX)" to "*S-1-1-0:(RX)" fix that language dependent part.

**Comment by hishamhm** [comment]
> I have the same issue, but on a german edition of windows 10. icacls depends on os language. Maybe a change from "Everyone:(RX)" to "*S-1-1-0:(RX)" fix that language dependent part.

sounds like a good idea! @moteus, what do you think?

**Comment by sewbacca** [comment]
Having the same issue and the workarround mentioned by @maikgreubel doesn't work for me.

**Comment by hishamhm** [comment]
Doing some archaeology:

In commit 694c437b00e300c138382ab8679723d7f10e68e8 from April 2021 (#1256) @moteus changed it from `*S-1-1-0` to `Everyone`.

In commit 914a2b7503b15c40894ac9efb8f33352f1a75cd1 back in November 2018, @THE-FYP changed it from `Everyone` to `*S-1-1-0`.

The code using `Everyone` was originally written in July 2018 by @georgeroman in commit 1b3b6525a4313404af84fce0fbbc29695e664f73.

So, should we revert back to `*S-1-1-0`? I have no Windows knowledge about this to make a proper judgement.

**Comment by moteus** [comment]
I did not remember why  i did this.
This commit ment to be about user names only if I remember correctly

**Comment by hishamhm** [comment]
all right, let's revert that `Everyone` then!

**Comment by moteus** [comment]
I can not find where this finction are called.

**Comment by deining** [comment]
I ran into the same issue on a German Windows 10 instance:

```
os.execute:     icacls "C:\Users\xxx\AppData\Local\Temp\luarocks_luarocks-rockspec-csv2tensor-0.2-0-2246" /inheritance:d /grant:r Everyone:(RX)
Everyone: No mapping between account names and security IDs was done.
```

I can run this command successfuly as soon as I replace `Everyone` with `*S-1-1-0`:

```
c:\> icacls "C:\Users\xxx\AppData\Local\Temp\luarocks_luarocks-rockspec-csv2tensor-0.2-0-6732" /inheritance:d /grant:r *S-1-1-0:(RX)
processed file: C:\Users\xxx\AppData\Local\Temp\luarocks_luarocks-rockspec-csv2tensor-0.2-0-6732
Successfully processed 1 files; Failed processing 0 files
```
 
> all right, let's revert that `Everyone` then!

Yes, please!
