### ISSUE TITLE
Install problem on windows 10

### ISSUE THREAD

**Issue by deb75** [luarocks/luarocks#1313]
Hello,

I installed luarocks in self contained mode on windows 10. The installation process succeeded,
but when I launch `luarocks.lua` I get : 
```
      LUA_LIBDIR : D:\xxx\Documents\utils\msys64\mingw64\lib (not found)
                   ****************************************
                   Use the command

                      luarocks config variables.LUA_LIBDIR <dir>

                   to fix the location
                   ****************************************
```

It does no find the lua library directory although it does exist and contains `liblua.a` and `liblua.dll.a`

What's the matter ?

**Comment by deb75** [comment]
It works if I set LUA_LIBDIR to `D:\xxx\Documents\utils\msys64\mingw64\bin`

**Comment by hishamhm** [comment]
Thanks for the feedback! Did running the command `luarocks config variables.LUA_LIBDIR D:\xxx\Documents\utils\msys64\mingw64\bin` as suggested by the tool itself fix your setup, then?

**Comment by deb75** [comment]
Thanks for your answer.

I did not try but, the result should be the same as my hand modification.

That is to note, I could install `luarocks` directly through mingw64, there is a package however, I hardly ever managed
to make `luarocks` work this way. That is way, I came up with the standalone windows 10 installation.

Regards
