### ISSUE TITLE
Uninstalling lua and luarocks

### ISSUE THREAD

**Issue by vaibhav-75007** [luarocks/luarocks#1317]
I installed lua and luarocks when i thought that i need it. But i dont use it anymore, i want to uninstall it, i tried searching in google how to uninstall, but i didnt find a proper solution.
I installed lua and luarocks in the following method =>
![image](https://user-images.githubusercontent.com/52103891/124385074-dc870f80-dcf1-11eb-9976-09228e45641f.png)
Please Help me!!

**Comment by daurnimator** [comment]
`sudo make uninstall` (assuming you have the original folder available)

**Comment by vaibhav-75007** [comment]
> `sudo make uninstall` (assuming you have the original folder available)

What do you mean by original folder??
the one after extracting the tar.gz

**Comment by daurnimator** [comment]
The same folder where you originally ran `sudo make install`.

**Comment by vaibhav-75007** [comment]
I ran `sudo make install` twice, once for installing lua 5.3.5 and the other for installing luarocks 3.3.1

**Comment by vaibhav-75007** [comment]
![image](https://user-images.githubusercontent.com/52103891/124386105-54573900-dcf6-11eb-8f7d-b9284d951847.png)


> The same folder where you originally ran `sudo make install`.

you mean this folder??
@daurnimator

**Comment by vaibhav-75007** [comment]
Nevermind, I went in the folders where i ran `sudo make install` and ran `sudo apt uninstall`. And it worked
Thx for responding so quickly!!
