### ISSUE TITLE
Difference in `path an path --lr-path`

### ISSUE THREAD

**Issue by arkt8** [luarocks/luarocks#1351]
- **Platform:** Linux (Debian 11)
- **LuaRocks version:**   /usr/bin/luarocks 3.7.0

## The misbehavior

**_Scenario 1:_**
When using `LUAROCKS_CONFIG` environment variable, `luarocks path` returns `LUA_PATH`  and `LUA_CPATH`  in different directories order of the ones returned with `luarocks path --lr-path` and `luarocks path --lr-path`

**_Scenario 2: Common `luarocks init`_**

Starting a directory configuration with `luarocks init` and don't using the `LUAROCKS_CONFIG` variable, both `LUA_PATH`, `LUA_CPATH` and `--lr-path`, `--lr-cpath` returns in the expected correct order.

**_Scenario 3: `LUAROCKS_CONFIG` after `luarocks init`_**

If you point `LUAROCKS_CONFIG` variable to the `./.luarocks/config-5.4.lua` file, it works as expected... maybe as it is the default name it is ignored?

If you rename `.luarocks` folder to other name, then the problem occurs again:

```
mkdir /tmp/test
cd /tmp/test
luarocks init
mv /tmp/test/.luarocks /tmp/test/.lr
LUAROCKS_CONFIG=/tmp/test/.lr/config-5.4.lua LUAROCKS_CONFIG_5_4=/tmp/test/.lr/config-5.4.lua luarocks path
LUAROCKS_CONFIG=/tmp/test/.lr/config-5.4.lua LUAROCKS_CONFIG_5_4=/tmp/test/.lr/config-5.4.lua luarocks --lr-path
LUAROCKS_CONFIG=/tmp/test/.lr/config-5.4.lua LUAROCKS_CONFIG_5_4=/tmp/test/.lr/config-5.4.lua luarocks --lr-cpath
```

## Original reproduction steps

The lines below show how I discovered the inconsistent behavior.

When I run: `LUAROCKS_CONFIG=/home/dev/lua/test/.luaenv/config-5.4.lua LUAROCKS_CONFIG_5_4=/home/dev/lua/test/.luaenv/config-5.4.lua luarocks path`

Outputs:
```
export LUA_PATH='/usr/share/lua/5.4/?.lua;/usr/local/share/lua/5.4/?.lua;/usr/local/share/lua/5.4/?/init.lua;/usr/local/lib/lua/5.4/?.lua;/usr/local/lib/lua/5.4/?/init.lua;/usr/share/lua/5.4/?/init.lua;./?.lua;./?/init.lua;/home/dev/lua/test/.luaenv/share/lua/5.4/?.lua;/home/dev/lua/test/.luaenv/share/lua/5.4/?/init.lua;/home/thadeu/.luarocks/share/lua/5.4/?.lua;/home/thadeu/.luarocks/share/lua/5.4/?/init.lua'
export LUA_CPATH='/usr/local/lib/lua/5.4/?.so;/usr/lib/x86_64-linux-gnu/lua/5.4/?.so;/usr/lib/lua/5.4/?.so;/usr/local/lib/lua/5.4/loadall.so;./?.so;/home/dev/lua/test/.luaenv/lib/lua/5.4/?.so;/home/thadeu/.luarocks/lib/lua/5.4/?.so'
export PATH='/home/dev/lua/test/.luaenv/bin:/home/thadeu/.luarocks/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games'
```

When I run
`LUAROCKS_CONFIG=/home/dev/lua/test/.luaenv/config-5.4.lua LUAROCKS_CONFIG_5_4=/home/dev/lua/test/.luaenv/config-5.4.lua luarocks path --lr-path`

Outputs: `/home/dev/lua/test/.luaenv/share/lua/5.4/?.lua;/home/dev/lua/test/.luaenv/share/lua/5.4/?/init.lua;/home/thadeu/.luarocks/share/lua/5.4/?.lua;/home/thadeu/.luarocks/share/lua/5.4/?/init.lua;/usr/share/lua/5.4/?.lua;/usr/share/lua/5.4/?/init.lua`

When I run
`LUAROCKS_CONFIG=/home/dev/lua/test/.luaenv/config-5.4.lua LUAROCKS_CONFIG_5_4=/home/dev/lua/test/.luaenv/config-5.4.lua luarocks path --lr-cpath`

Outputs: `/home/dev/lua/test/.luaenv/lib/lua/5.4/?.so;/home/thadeu/.luarocks/lib/lua/5.4/?.so;/usr/lib/lua/5.4/?.so`
## The configuration file

Since the intention is not to use default configuration, I couldn't figure out how to reproduce this with the standard configuration...

My `/home/dev/lua/test/.luaenv/config-5.4.lua`

```lua
arch = 'linux-x86_64'                          
lua_interpreter = "lua5.4"
rocks_trees = {
   {  name = "project",
      root = "/home/dev/lua/test/.luaenv"
   },
   {  name = "user",
      root = "/home/thadeu/.luarocks"
   },
   {  name = "system",
      root = "/usr"
   },
}
```
Note that both `/home/dev` and `/home/thadeu` belongs to the sabe Linux user with the same permissions

**Comment by thadeudepaula** [comment]
The first insight I have on this is the LUAROCKS_CONFIG variable is not being considered with the same priority when calling `luarocks path` and `luarocks --lr-*`. To simplify and make it consistent, the shell exporting code could be generated directly from the `--lr-*` output instead of being generated apart with duplicity.

**Comment by hishamhm** [comment]
Thank you for the detailed report! I'll look into it.

**Comment by hishamhm** [comment]
The behavior difference here is intentional: `--lr-path` and `--lr-cpath` provide only the entries derived from the `rocks_trees` list, so that the user can prepend or append it to the rest of their configuration at will.

I'm adding a new flag `--full` that provides the behavior you expected, while keeping backwards compatibility.
