### ISSUE TITLE
Remove logiceditor.com as a default rock server

### ISSUE THREAD

**Issue by bbblitz** [luarocks/luarocks#1354]
logiceditor.com is included in the list of default mirrors [here](https://github.com/luarocks/luarocks/blob/d4e82aae9f411d5d2cac10f7e043a0c3c6180eb1/src/luarocks/core/cfg.lua#L193). It is included with it's http:// protocol, not http**s**://, this is "obviously wrong" in a package manager where arbitrary code is downloaded, compiled, and sometimes run. In addition, the https certificate luarocks.logiceditor.com currently serves was last valid May 14, 2018. I suggest removing logiceditor.com from the default list of rocks_servers and allowing users to add it back in their individual config.lua if they want it.

**Comment by hishamhm** [comment]
Thanks for the report! Let's ping the maintainer of the logiceditor.com mirror:

Hi @agladysh, is the mirror being kept up to date? @bbblitz is reporting issues with the certificate as well. Are there plans to provide the mirror over https with a current certificate, or should we drop it from the default list? Thanks in advance!

**Comment by hishamhm** [comment]
All right, so let's remove it from the default mirror list since it is http:// and the https:// certificate is presenting issues. We can reinstate it once the certificate issues are sorted!

**Comment by agladysh** [comment]
Hmm. Yes, please remove it. Sorry about that.
