### ISSUE TITLE
LUALIB Config Variable Doesn't Seem to Affect What Dll File LuaRocks is Looking For

### ISSUE THREAD

**Issue by khartsookCA** [luarocks/luarocks#1357]
- **Platform:** Windows
- **LuaRocks version:** 3.7.0
- **Configuration file:** https://pastebin.com/XRci1zzE
- **Lua directory contents:** https://pastebin.com/kC4MxRzU (see line 7)

- **`luarocks --verbose` output from when the issue occurred:** https://pastebin.com/qPbYgiXY (see line 149)
- **`luarocks config` output from when the issue occurs:** https://pastebin.com/KriyRgxs (see lines 160 and 164)

- **Description:**
  - Summary: luarocks will find a dll named lua5.3.dll but not named lua5.3.5.dll regardless of my LUALIB config setting
  - Ultimately the issue I'm having is that even though Luarocks is identifying that I've set my LUALIB name to match my dll (`lua5.3.5.dll`), it fails to find the dll
    - `luarocks` output Configuration section includes`LUA_LIBDIR : C:\lua\5.3.5\bin (not found)`
  - **Key thing that indicates that LuaRocks may be ignoring my LUALIB setting**: Renaming the dll to `lua5.3.dll` resolves this issue even when LUALIB is set to `lua5.3.5.dll` and shows as such in the config output
  - Steps I took to find this issue:
    - Downloaded and compiled Lua 5.3.5 using https://blog.spreendigital.de/2019/06/25/how-to-compile-lua-5-3-5-for-windows/
    - Moved the .h files to C:\lua\5.3.5\include, the created .exe and .dll files to C:\lua\5.3.5\bin, and the .lib files to C:\lua\5.3.5\lib
      - See the attached Lua directory contents pastebin for a full directory listing
    - Downloaded LuaRocks 3.7.0 binary and put it with my lua binaries
    - Executed `luarocks config` to see what variables needed to be configured, and did so in my C:\Users\<username>\AppData\Roaming\luarocks\config-5.3.lua file (see the attached Configuration file pastebin, specifically that LUALIB is set to lua5.3.5.dll, which is the name of my dll)
    - Executed `luarocks` (or other commands such as `luarocks install luafilesystem`) and saw that it was still reporting issues with finding the lib
      - `luarocks` output Configuration section includes`LUA_LIBDIR : C:\lua\5.3.5\bin (not found)`
      - `luarocks install luafilesystem` gives `Error: Failed finding Lua library. You may need to configure LUA_LIBDIR.`

I think this is pretty thorough but I'm happy to give more info, just let me know and thanks for your hard work on LuaRocks!

**Comment by hishamhm** [comment]
@khartsookCA thanks for the report! I opened a PR attempting to fix the issue.
