### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by Wangmd1994** [luarocks/luarocks#1361]
- **Platform:Linux.

- **LuaRocks version:3.2.1
   **Lua version:5.1

- **Configuration file:**
  - luarocks: config.unix $(builddir)/config-$(LUA_VERSION).lua
	mkdir -p .luarocks
	cp $(builddir)/config-$(LUA_VERSION).lua .luarocks/config-$(LUA_VERSION).lua
	rm -f src/luarocks/core/hardcoded.lua
	echo "#!/bin/sh" > luarocks
	echo "unset LUA_PATH LUA_PATH_5_2 LUA_PATH_5_3 LUA_PATH_5_4 LUA_CPATH LUA_CPATH_5_2 LUA_CPATH_5_3 LUA_CPATH_5_4" >> luarocks
	echo 'LUAROCKS_SYSCONFDIR="$(luarocksconfdir)" LUA_PATH="$(CURDIR)/src/?.lua;;" exec "$(LUA)" "$(CURDIR)/src/bin/luarocks" --project-tree="$(CURDIR)/lua_modules" "$$@"' >> luarocks
	chmod +rx ./luarocks
	./luarocks init

- **LuaRocks output from when the issue occurred:Luarocks output Illegal instruction from run ./luarocks init
 

- **Description:**
  - I input ./configure and make,first it's successed when I input ./configure，but it‘s failed when I input make.

**Comment by hishamhm** [comment]
"Illegal instruction" definitely means an issue with your Lua interpreter, not with LuaRocks. LuaRocks when built from source like this only ships pure-Lua code, so any binary issues come from the binaries being exercised by it in your system, namely the Lua interpreter or any other third party tools that it invokes.

You can check this by running it using `strace -f` to see the forked subprocesses and check which one is crashing.
