### ISSUE TITLE
unzip detected as unviable on DragonFly bsd 

### ISSUE THREAD

**Issue by Vertecedoc4545** [luarocks/luarocks#1363]
### Please read the following before submitting:
- Please do NOT submit bug reports for questions. Ask questions in the [Gitter
  chat-room](https://gitter.im/luarocks/luarocks).
- Please do NOT submit duplicate bug reports. Look through the [issue
  tracker](https://github.com/luarocks/luarocks/issues) before submitting.

### Please fill out the following:
- **Platform:**
  - Dragonlybsd

- **LuaRocks version:**
  - `usr/local/bin/luarocks53 3.7.0¨
  - ¨/usr/local/bin/luarocks54 3.7.0¨

- **Configuration file:**
  - defaulf

- **LuaRocks output from when the issue occurred:**
  fs.unzip("/tmp/luarocks_luarocks-rock-penlight-1.11.0-1-6ETGlY/penlight-1.11.0-1.src.rock")
fs.is_tool_available("unzip -n", "unzip", "--help")

Error: Failed unpacking rock file: /tmp/luarocks_luarocks-rock-penlight-1.11.0-1-6ETGlY/penlight-1.11.0-1.src.rock: 'unzip -n' program not found. Make sure unzip is installed and is available in your PATH (or you may want to edit the 'variables.UNZIP' value in file '/usr/local/etc/luarocks/config-5.4.lua')

- **Description:**
  - make an draginflybsd installation and install lua53-luarocks or whatever lua version then any luarocks(version of lua) install (any package) like `luarocks53 install ldoc`
  

- *IS THE SAME ISSUE AS [HERE](https://github.com/luarocks/luarocks/pull/1028/commits/ef0cb9d12712f17970c86ef2645340f59dc2d779)* but on dragonfly instead of freebsd

**Comment by Vertecedoc4545** [comment]
the portability problem is that the dragonfly bsd binary files start whit the same hexadecimal characters as the linux ones so i could implement the same solution as the other bsd systems that is implemented on the luarocks library.
also sysdetect.detect() of the luarock library located on /usr/local/share/lua/53/luarocks/ returns linux as system.
so the unzip no located problem occurs because tries to do all the proces as it was linux

**Comment by hishamhm** [comment]
Thanks for the report! You're right, this can be addressed by adding a `dragonflybsd.lua` file similar to `freebsd.lua` and by adding DragonFlyBSD support in the sysdetect module — I'm not sure what is the proper method to detect a DragonFlyBSD binary.

**Comment by hishamhm** [comment]
@Vertecedoc4545 can you send me a downloadable link to the smallest DragonflyBSD binary you can find? (something like `/bin/true`, or the result of compiling `int main() { return 0; }`)

**Comment by Vertecedoc4545** [comment]
sure

**Comment by Vertecedoc4545** [comment]
[less.zip](https://github.com/luarocks/luarocks/files/8175881/less.zip)

**Comment by hishamhm** [comment]
@Vertecedoc4545 thanks! to confirm, `zip` and `unzip` are installed in a default DragonFly installation?

**Comment by Vertecedoc4545** [comment]
i think no
