### ISSUE TITLE
make clean fails on linux builds

### ISSUE THREAD

**Issue by kapouer** [luarocks/luarocks#1368]
Linux debian bookworm, building luarocks 3.8.0.

It would be nice if windows-clean target did not fail.

**Comment by hishamhm** [comment]
Sorry, I cannot reproduce it. both `make clean` and `make windows-clean` do not fail on my end. In any case, `windows-clean` is only used when cross-compiling Windows binaries; that requires a particular setup of dependencies. `make clean` is the one intended for Linux users in general.
