### ISSUE TITLE
Do we have a solution to install Luarocks under MIPS architecture?

### ISSUE THREAD

**Issue by daputaowang** [luarocks/luarocks#1369]
I tried to install Luarocks on MIPS architecture but failed,Is it that Luarocks itself does not support the MIPS architecture?

**Comment by daurnimator** [comment]
failed how?

**Comment by hishamhm** [comment]
I'm pretty sure I ran LuaRocks on MIPS before, a long time ago when I did some work on embedded systems. There's even an entry for `mips` in the luarocks sysdetect module. Clarifying which issues you're hitting would help, they might not be LuaRocks-related — several users have reported issues with `illegal instruction` errors which turn out to be issues with the way the Lua interpreter itself is built.

**Comment by XVilka** [comment]
@hishamhm @daurnimator judging from [this neovim issue](https://github.com/neovim/neovim/issues/16490) it's this:
```
Error: LuaRocks 3.8.0 bug (please report at https://github.com/luarocks/luarocks/issues).
Arch.: linux-mips
...-0.6.0/.deps/usr/share/lua/5.1/luarocks/manif/writer.lua:100: attempt to index field 'dependencies' (a nil value)
stack traceback:
	...-0.6.0/.deps/usr/share/lua/5.1/luarocks/manif/writer.lua:398: in function 'deploy_files'
	.../neovim-0.6.0/.deps/usr/share/lua/5.1/luarocks/build.lua:442: in function 'do_build'
	...vim-0.6.0/.deps/usr/share/lua/5.1/luarocks/cmd/build.lua:154: in function 'command'
	...i/neovim-0.6.0/.deps/usr/share/lua/5.1/luarocks/deps.lua:237: in function 'fulfill_dependency'
	...i/neovim-0.6.0/.deps/usr/share/lua/5.1/luarocks/deps.lua:336: in function 'fulfill_dependencies'
	.../neovim-0.6.0/.deps/usr/share/lua/5.1/luarocks/build.lua:138: in function 'process_dependencies'
	.../neovim-0.6.0/.deps/usr/share/lua/5.1/luarocks/build.lua:379: in function 'do_build'
	...vim-0.6.0/.deps/usr/share/lua/5.1/luarocks/cmd/build.lua:154: in function <...vim-0.6.0/.deps/usr/share/lua/5.1/luarocks/cmd/build.lua:117>
	[C]: in function 'xpcall'
	...xi/neovim-0.6.0/.deps/usr/share/lua/5.1/luarocks/cmd.lua:666: in function 'run_command'
	...usr/lib/luarocks/rocks-5.1/luarocks/3.8.0-1/bin/luarocks:35: in main chunk
	[C]: at 0x5555577abbb8
ninja: build stopped: subcommand failed.
make: *** [Makefile:107：deps] 错误 1
```

**Comment by daurnimator** [comment]
We'd at least need the command being invoked.

That doesn't look like an issue *installing* luarocks as much as using luarocks to install something else.

**Comment by hishamhm** [comment]
I'm pretty certain this is a LuaJIT bug on MIPS (LoongArch specifically).
https://github.com/luarocks/luarocks/issues/1553 is the same. I pushed #1572 as a possible mitigation, but I don't know if that will work around it. If the issue remains, feel free to reopen.
