### ISSUE TITLE
Wiki Being Compromised

### ISSUE THREAD

**Issue by ChrisKader** [luarocks/luarocks#1371]
The wiki pages need to be restricted to require approval before changes are posted. Links on the installation pages are being changed to malware downloads.

**Comment by daurnimator** [comment]
I've restricted editing to those with push access. Still need to go through and revert their edits.

**Comment by daurnimator** [comment]
Looks like it was just the one page left compromised. Reverted.

**Comment by daurnimator** [comment]
Thanks for the report!
