### ISSUE TITLE
specify git repo as dependency

### ISSUE THREAD

**Issue by jtarchie** [luarocks/luarocks#138]
I am going to my Ruby programmer hat on here.

In a `Gemfile` when specifying a gem you can say to load it directly from a git repo.

``` ruby
source "https://rubygems"

gem "awesome", git: "https://github.com/gems/awesome"
```

While using the awesome [buildpack](https://github.com/leafo/heroku-buildpack-lua) for Heroku, you can actually specify HTTP location (maybe git?) for a rockspec.

``` lua
-- my_app.rockspec
dependencies = {
  "xavante >= 2.2.1",
  "http://moonscript.org/rocks/moonscript-dev-1.src.rock",
  "cosmo"
}
```

Is this functionality that we could add to Luarocks core? I'd be willing to do a pull request for the feature, but wanted to ask if this was a desired feature from anyone else.

**Comment by geoffleyland** [comment]
I realise this is an old issue, but I agree that this would be a nice feature.  As you say, Hisham, not for publish rocks, but handy for systems that use rocks for deployment.

**Comment by hishamhm** [comment]
Well, If you're making your custom setup, you could just as well use `--server` (or `--only-server` even) to point to your own repo.

**Comment by geoffleyland** [comment]
Fair call.  Turns out that the trick to getting one of the dependencies installed on Heroku (pgsql) was passing in PQ_INCDIR, which is definitely out of scope for Luarocks, so perhaps deploying is just a different thing.

**Comment by rosshadden** [comment]
There are many lua libraries which are not published to luarocks.  If we could use git uris for dependencies, we could actually import the modules.  Instead of having to resort to really bad alternatives, which is currently necessary.

**Comment by hishamhm** [comment]
@rosshadden If we added git uris for dependencies, module authors would have even less incentive to contribute to luarocks.org.

Why not just write a rockspec and publish it in LuaRocks? (Open source licenses give you every right to!) Many rockspecs in the repo were not uploaded by the module's original authors, including high-profile examples such as LPeg. The #1 downloaded module in the repo, LuaSec, was uploaded by me _years_ ago. Only a couple of weeks ago, the original author contacted me about it, and I asked him to create a luarocks.org account and I transferred rock ownership to him. 

Alternatively, often, simply asking the module author to contribute to luarocks.org works. If they don't have a rockspec available, they are usually happy to receive a contribution! I introduced many people to LuaRocks this way. It's a great way to help building the ecosystem. :)

**Comment by rosshadden** [comment]
Thanks for your thorough response.  I work/live/breathe in the nodejs ecosystem, and I guess have thus been comparing `luarocks` to `npm` (if subconsciously).  `npm` does allow git URIs, supporting the `#` operator to specify specific commits, tags, or branches.  This feature does not at all detract from the community, as it is never the primary way of naming dependencies (which would be semver).  It is merely an alternative for situations that call for it, such as stubborn/inactive authors, or (more commonly) using unpublished or even private versions of our own projects.

Just some food for thought.  I cannot make a strong case for this, other than saying it would be incredibly convenient---especially in the bootstrapping phase of projects.  I understand your fear of diminishing incentives, but I think at a certain point you have to just trust in the community to establish their own best-practices based on the available tools.

It seems like the lua community tends to be content 'vendoring', which is the act of adding other author's scripts directly to their own projects.  I think this is a terrible idea, and almost certainly why something like `luarocks` was created in the first place.  Ultimately we both want that to go away.  I think the OP's request will help it go away in situations where it's not as clear-cut as the default workflow.

Thank you for your time!
