### ISSUE TITLE
Conflicting feature between `luarocks built` (builtin) and `luarocks init`

### ISSUE THREAD

**Issue by MunifTanjim** [luarocks/luarocks#1382]
### Please fill out the following:
- **Platform:**
  - Linux

- **LuaRocks version:**
  - `/tmp/luver_current_581592_1640508377_wmt/bin/luarocks 3.8.0`

- **Description:**
  - `luarocks build` for `type = "builtin"` copies files from `./lua` directory ([source](https://github.com/luarocks/luarocks/blob/91b25d87b1852f0066e6875efe0bce7438ea1fb1/src/luarocks/build/builtin.lua#L357-L362)). The wiki says:
    > To make writing rocks for projects with a common directory layout even easier, the "builtin" build type recursively copies all files and directories it finds in a folder called "./lua" (if it exists) to the same place as other Lua files.
  - `luarocks init` creates a `./lua` launcher script. The wiki says:
    > creating lua and luarocks launcher scripts in the current directory that are hardcoded to use the project tree
  - That two feature is kinda conflicting, if you have one you can't have another.
  
Can we move the `lua` and `luarocks` launcher scripts into a different directory? Maybe `./scripts/{lua,luarocks}`?

**Comment by hishamhm** [comment]
@MunifTanjim the feature for auto-copying a `lua` directory is very old and kept around for backwards compatibility only. If you're using `rockspec_format = "3.0"`, you can use the `src` folder and `builtin` will autodetect any `.lua` files inside it.

What is the side effect you are experiencing? Is LuaRocks trying to copy the `./lua` script as if it was a directory?

**Comment by MunifTanjim** [comment]
> If you're using rockspec_format = "3.0", you can use the src folder and builtin will autodetect any .lua files inside it.

Nice! I'll try it out.

> What is the side effect you are experiencing? Is LuaRocks trying to copy the ./lua script as if it was a directory?

No, it's not doing anything like that.

I just reported it because I noticed this conflicting behavior (i.e. you can have only one of those behavior, not both).

Also, I'm working on this project https://github.com/MunifTanjim/lua-evdev, and wanted to know if it's possible for `luarocks init` to put the generated `lua` and `luarocks` scripts under the `scripts` folder.

**Comment by hishamhm** [comment]
> Also, I'm working on this project https://github.com/MunifTanjim/lua-evdev, and wanted to know if it's possible for luarocks init to put the generated lua and luarocks scripts under the scripts folder.

Not currently, unfortunately. But since it uses only absolute paths, you should be able to move them there manually if you prefer. Note however that these wrappers contain installation-specific paths, so they should not be committed to your project, but instead always generated in the user's system.

**Comment by MunifTanjim** [comment]
Thanks! Got it! This issue can be closed.

Off-topic question:

If I open a PR to make`skiplist` (https://github.com/luarocks/luarocks/blob/8dae2fce37b75c9c5eefb334b12cd2359ba48d7e/src/luarocks/build/builtin.lua#L71-L77) configurable, would it be acceptable?

I'm thinking about either a `.luarocksignore` file or a `.build.ignore` key in rockspec. 🤔

**Comment by hishamhm** [comment]
> would it be acceptable?

Yes, it would! I think a `.build.ignore` field would work best, but note that it would be silently ignored by older LuaRocks versions.
