### ISSUE TITLE
question about the "validate-args-1.5.4-1.rockspec" 

### ISSUE THREAD

**Issue by yuekunjava** [luarocks/luarocks#1387]
we found that some code snippet contains some description about "validate-args-1.5.4-1.rockspec" ,it's under GPL-3 license, but i do not find any invoking point about this package in the source code of luarocks，what‘s
the relationship between “validate-args” and “luarocks”？Do we need to fulfill the open source obligations specified in the GPL-3 license if we use luarocks？ thanks！

**Comment by daurnimator** [comment]
The field in the rockspec specifies that the validate-args code is under a GPL-3 license. That code is *not* provided with luarocks (either in the repository or distributed forms).
