### ISSUE TITLE
fatal: remote error:    The unauthenticated git protocol on port 9418 is no longer supported.

### ISSUE THREAD

**Issue by tommy-mor** [luarocks/luarocks#1388]
for a rock of the shape:

```
source = {
   url = "git://github.com/slembcke/debugger.lua.git",
}
```
https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git

any ideas for a workaround for existing rocks besides just updating them?

**Comment by hishamhm** [comment]
Please update to the latest version of LuaRocks, which does auto translate
github links to https.
