### ISSUE TITLE
Windows install instructions are lacking

### ISSUE THREAD

**Issue by nfearnley** [luarocks/luarocks#1391]
I am attempting to install luarocks on windows.
I am following the instructions here: http://luarocks.org/en/Installation_instructions_for_Windows

At the top of the documentation is the following text:
> if you already have a Lua installation, the single binary package which you can use: get the latest windows-32.zip file here, unpack it and you'll have a luarocks.exe ready to use.

I already have lua installed, so I'm following these instructions and the rest of the documentation is irrelevant.

These instructions make it unclear where I'm expected to unpack the executables.
* Should I be creating a new directory to hold the luarocks executables and manually adding it to my path?
* Should I be copying them into some folder in my existing lua installation?

I can't find any information other than "unpack these and you're done".

**Comment by hishamhm** [comment]
Hi, thanks for the feedback!

> Should I be creating a new directory to hold the luarocks executables and manually adding it to my path?
> Should I be copying them into some folder in my existing lua installation?

Either should work, as long as you can get <tt>luarocks</tt> in your PATH. The documentation doesn't go in details because there are many ways you can install Lua itself. In any case, I tried to add some more info to the documentation page.
