### ISSUE TITLE
Error when requiring a dll file

### ISSUE THREAD

**Issue by L3G5ND** [luarocks/luarocks#1401]
## Issue
- **Description:**
  - I installed Lua-cURL and when I require it I get an error from a dll file that is required inside of the module.

- **Error**
```
C:\Lua51\lua5.1.exe: error loading module 'lcurl' from file 'C:\Lua51\systree\lib\lua\5.1\lcurl.dll':
        The specified module could not be found.

stack traceback:
        [C]: ?
        [C]: in function 'require'
        C:\Lua51\systree\share\lua\5.1\curl.lua:11: in main chunk
        [C]: in function 'require'
        main.lua:3: in main chunk
        [C]: ?
```

- **File Containing the Error**
  - `lcurl.dll`

- **Code**
  - Main File
    - ```local curl = require("cURL")```
  - Required Module (Module Making the Error)
```
local curl = require "lcurl" -- dll file containing the error
local impl = require "cURL.impl.cURL"

return impl(curl)
```
  - Require Causing the Error
    - `local curl = require "lcurl" --the dll file`
  

## Luarocks Info
- **Platform:**
  - Windows

- **LuaRocks version:**
  - `3.8.0`

- **C compiler**
  - Mingw-32

- **Configuration file:**
```
rocks_trees = {
    { name = [[user]],
         root    = home..[[/luarocks]],
    },
    { name = [[system]],
         root    = [[C:\Lua51\systree]],
    },
}
variables = {
    --MSVCRT = 'MSVCR80',
    LUALIB = 'lua5.1.lib',
}
verbose = false   -- set to 'true' to enable verbose output
```

## Installation Info (Probably not really important)
- **cURL Version**
  - Windows 32 bit (https://curl.se/windows/)
  
- **Install Command**
  - `luarocks install lua-curl CURL_INCDIR=C:\curl-7.82.0-win32-mingw\include CURL_LIBDIR=C:\curl-7.82.0-win32-mingw\lib`
  - Yes, it successfully installs

- **Lua-cURL Version**
  - scm-0 DEV

### Any information I missed? Tell me.

**Comment by hishamhm** [comment]
This does not look like a confirmed bug, but most likely a configuration issue.

It looks like `luarocks install lua-curl` worked but your Lua interpreter is failing to find the DLL.

Just to confirm, is there a `lcurl.dll` built in your system? The folder where it is needs to be in the "C package path" for your Lua interpreter. You can check how your C package path looks like by running `print(package.cpath)` from Lua (and `print(package.path)` without the "c" to print the package path for `*.lua` files).

Running `luarocks path` from the command prompt will print you environment variable commands that can be used to set the package paths.

**Comment by hishamhm** [comment]
In this case LuaRocks seems to have done its job. Not sure what's going on when require fails. Perhaps that DLL is trying to find the libcurl DLL and failing? On Unix, one could check that running `ldd` on that file, but I don't have enough Windows knowledge to diagnose that scenario.
