### ISSUE TITLE
"'pwd' is not recognized as an internal or external command, operable program or batch file."

### ISSUE THREAD

**Issue by MillzyDev** [luarocks/luarocks#1404]
I installed luarocks with the scoop 'lua-for-windows' package.
When I run `luarocks install luafilesystem`: I get this error: `'pwd' is not recognized as an internal or external command,
operable program or batch file.`
I am unsure of the cause, since i can run `pwd` in the same developer powershell instance as when i run `luarocks install luafilesystem` and it works fine.
![image](https://user-images.githubusercontent.com/64277238/160924791-eb4a0873-20f3-48ca-9a96-19f66828b92d.png)

**Comment by hishamhm** [comment]
> I installed luarocks with the scoop 'lua-for-windows' package.

What version of LuaRocks is this? `luarocks --version` should inform you.

> I am unsure of the cause, since i can run pwd in the same developer powershell instance as when i run luarocks install luafilesystem and it works fine.

Sounds like LuaRocks wasn't installed correctly. Here are some things you can try:

* use the official [all-in-one executable binariy for Windows]https://github.com/luarocks/luarocks/wiki/Download)
* as a workaround, try `luarocks config variables.PWD "echo %%cd%%"` (I believe the percent-sign needs to be doubled in CMD.EXE, not sure about Powershell; if that doesn't work, try `luarocks config variables.PWD "echo %cd%"`, but run `luarocks config variables.PWD` to check that it was set to `echo %cd%`)

**Comment by hishamhm** [comment]
Scoop provides a [separate package for LuaRocks](https://scoop.sh/#/apps?q=luarocks), which should not have this problem (see #1501).
