### ISSUE TITLE
prompt install done, but file not found of lua alien

### ISSUE THREAD

**Issue by robertlzj** [luarocks/luarocks#1407]
- **Platform:**
  - Windows 10-64 bit

- **LuaRocks version:**
  - 3.0.2 .exe

- **Configuration file:**
  - [luarocks config](https://gist.github.com/robertlzj/2b4e49cb3eaae7b0d598d6c45bb92d96)

- **LuaRocks output from when the issue occurred:**
  - [luarocks install short output](https://gist.github.com/robertlzj/3747e3ba896dda5a720bd008392bcb10)
  - [LuaRocks verbose output](https://gist.github.com/robertlzj/712b4cf23679af6e588dbf9cd9090f3b)

- **Description:**
  - `luarocks.exe install --verbose alien`
  - prompt `alien 0.7.1-2 is now installed in c:\programfiles\zerobranestudio\ (license: MIT/X11)`
  but the folder only contain `.rockspec` and `doc`, not the `dll` modules (default `lib\lua\5.3`).
  sometimes those file is missing too.
  - also prompt followed by other lib dependencies error message`
Missing dependencies for lua-websockets v2.2-1:
   luabitop (not installed)` (`luabitop` is a lua5.1 lib, which my configure is lua5.3 here)
  - could see new folder `bin`/`conf` etc create and remove flash.
  - tried `make`, `build`, and with `--keep`, with _administrator_.

**Comment by robertlzj** [comment]
Same problem occurred when compile manually using MSYS/mingw32 in linking phase, finally get some prompt.
I'm not familiar with it, may lib from different compile base? I will check it later.

**Comment by robertlzj** [comment]
The issue still exist.
Maybe I use wrong libs, like x64/AMD..?

But currently, I use `luarocks install https://raw.githubusercontent.com/moteus/alien/master/rockspecs/alien-scm-0.rockspec FFI_LIBDIR=.. FFI_INCDIR=...` to success build and install.

Although the latest alien release in _github_ is [0.7.1](https://github.com/mascarenhas/alien/releases/tag/v0.7.1)?
Version of official alien in _luarocks_ is outdated - 0.7.0. Use `luarocks search alien` to check.
Above 'rockspec' is a [branch](https://github.com/mascarenhas/alien/issues/53) with some ahead commit.

BTW, the building process from luarocks is:
```shell
mingw32-gcc -O2 -c -o src/alien.o -I<LUA_INCDIR> src/alien.c -DFFI_BUILDING -DWINDOWS -I<FFI_INCDIR>

mingw32-gcc -shared -o alien_c.dll src/alien.o -L<FFI_LIBDIR> -lffi -L<LUA_LIBDIR> -llua53 -lm
```
Which could build manually using MinGW-W64 x32.

**Comment by hishamhm** [comment]
This looks like an issue with the alien rockspec, and not with LuaRocks. You should try reporting to the Alien project itself.
