### ISSUE TITLE
[Windows] Luarocks 3.9.0 Single executable does nothing

### ISSUE THREAD

**Issue by nightlyherb** [luarocks/luarocks#1412]
- **Platform:** Windows (Windows 11)

- **LuaRocks version:** 3.9.0, single executable binary

- **Configuration file:** None

- **LuaRocks output from when the issue occurred:**
  - `luarocks --verbose` does nothing and exits

- **Description:**
  - Download https://luarocks.github.io/luarocks/releases/luarocks-3.9.0-windows-64.zip
      - 64bit link, but both 32 and 64 bit executables have this bug.
  - Running `luarocks` from the command line launches a new window that disappears immediately and luarocks exits.
  - Version 3.8.0 is not affected.

**Comment by hishamhm** [comment]
@nightlyherb Thank you for the report! I'll look into it.

**Comment by s0alqasim1d** [comment]
Hi I had the same issue:

- **Platform:**
  - Windows 11

- **LuaRocks version:**
  - 3.9.0, single executable binary installed via scoop

- **Configuration file:**
  https://gist.github.com/s0alqasim1d/03864f7852facf03bb348bcad46a0ad7

- **LuaRocks output from when the issue occurred:**
  - A cmd window opens and closes very quickly.

- **Description:**
  1- Had lua installed via scoop
  2- Had luarocks installed via scoop
  3- Tried to install a package --> bunch of cmd windows opening and closing rapidly
  4- Tried to run any luarocks command --> no console output, just cmd window pops and closes

Indeed 3.8.0 is working fine

**Comment by hishamhm** [comment]
@s0alqasim1d @nightlyherb Please let me know if these binaries work; I uploaded them to my personal website — if they work, I'll push them as official builds:

https://hisham.hm/tmp/luarocks-3.9.0-windows-32.zip
https://hisham.hm/tmp/luarocks-3.9.0-windows-64.zip

Thank you!

**Comment by s0alqasim1d** [comment]
@hishamhm I tried both 32 and 64, and both work.
![image](https://user-images.githubusercontent.com/43882930/166502686-80202a1f-2aa5-44a9-b205-c81ee3bc4bdc.png)

Great job!

**Comment by hishamhm** [comment]
Thank you for the quick feedback @s0alqasim1d !
