### ISSUE TITLE
fresh luarocks install cant install rocks

### ISSUE THREAD

**Issue by TECHOPC** [luarocks/luarocks#1422]
### Please fill out the following:
- **Platform:**
  - Linux.

- **LuaRocks version:**
  - `luarocks --3.9.0` http://luarocks.github.io/luarocks/releases/luarocks-3.9.0.tar.gz

- **Configuration file:**

Configuration:
   Lua:
      Version    : 5.4
      Interpreter: /usr/bin/lua5.4 (ok)
      LUA_DIR    : /usr (ok)
      LUA_BINDIR : /usr/bin (ok)
      LUA_INCDIR : /usr/local/include (ok)
      LUA_LIBDIR :  (not found)

   Configuration files:
      System  : /usr/local/etc/luarocks/config-5.4.lua (ok)
      User    : /home/techo/.luarocks/config-5.4.lua (not found)
      Project :
      /mnt/c/Users/leont/Downloads/luarocks-3.9.0/./.luarocks/config-5.4.lua
      (ok)

   Rocks trees in use:
      /mnt/c/Users/leont/Downloads/luarocks-3.9.0/./lua_modules ("project")
      /home/techo/.luarocks ("user")
      /usr/local ("system")

- **LuaRocks output from when the issue occurred:**
  Error: LuaRocks 3.9.0 bug (please report at https://github.com/luarocks/luarocks/issues).
Arch.: linux-x86_64
/usr/share/lua/5.4/ssl/https.lua:66: bad argument #2 to 'method' (string expected, got light userdata)
stack traceback:
        [C]: in function 'socket.http.request'
        /usr/share/lua/5.4/ssl/https.lua:132: in function 'ssl.https.request'
        /usr/local/share/lua/5.4/luarocks/fs/lua.lua:739: in upvalue 'request'
        /usr/local/share/lua/5.4/luarocks/fs/lua.lua:837: in upvalue 'http_request'
        /usr/local/share/lua/5.4/luarocks/fs/lua.lua:914: in function 'luarocks.fs.lua.download'
        (...tail calls...)
        /usr/local/share/lua/5.4/luarocks/fetch.lua:154: in function 'luarocks.fetch.fetch_url'
        /usr/local/share/lua/5.4/luarocks/fetch.lua:50: in function 'luarocks.fetch.fetch_caching'
        /usr/local/share/lua/5.4/luarocks/manif.lua:108: in function 'luarocks.manif.load_manifest'
        /usr/local/share/lua/5.4/luarocks/search.lua:111: in function </usr/local/share/lua/5.4/luarocks/search.lua:101>
        (...tail calls...)
        /usr/local/share/lua/5.4/luarocks/search.lua:155: in function 'luarocks.search.search_repos'
        /usr/local/share/lua/5.4/luarocks/search.lua:241: in function 'luarocks.search.find_suitable_rock'
        /usr/local/share/lua/5.4/luarocks/search.lua:263: in function 'luarocks.search.find_rock_checking_lua_versions'
        /usr/local/share/lua/5.4/luarocks/cmd/install.lua:246: in function 'luarocks.cmd.install.command'
        (...tail calls...)
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.4/luarocks/cmd.lua:667: in function 'luarocks.cmd.run_command'
        /usr/local/bin/luarocks:38: in main chunk
        [C]: in ?

- **Description:**
  - sudo luarocks install (any lib)

**Comment by hishamhm** [comment]
You need to use LuaSec 1.1.0 with Lua 5.4. To work around this, use `luarocks config fs_use_modules false`. After upgrading `luasec`, you can switch this back to `luarocks config fs_use_modules true`. You might have to upgrade `luasocket` as well.

Feel free to reopen if the problem persists.
