### ISSUE TITLE
How to install Luarocks on windows machine

### ISSUE THREAD

**Issue by awa5114** [luarocks/luarocks#1423]
I tried to install  Luarocks using `install.bat` on a windows machine but got an error:

> Could not find Lua. See /? for options for specifying the location of Lua, or installing a bundled copy of Lua 5.1

So then I tried `install.bat /LUA C:\Users\aa\Desktop\SETUPS\luarocks-3.9.0-win32\win32\lua5.1\`

I still got the same error. 

How do I install lua + luarocks ?

**Comment by hishamhm** [comment]
For using the bundled installation, the option would be `/L`; to use `/LUA` you need to provide your own copy of Lua, which is probably what you want if you intend to compile C extensions (the version of Lua needs to be binary-compatible with your C compiler). More information here: https://github.com/luarocks/luarocks/wiki/Installation-instructions-for-Windows

**Comment by awa5114** [comment]
I ran `install.bat /L` like you mentioned and here is the output I got:

```
============================
== LuaRocks is installed! ==
============================


You may want to add the following elements to your paths;
Lua interpreter;
  PATH     :   C:\Program Files (x86)\LuaRocks
  PATHEXT  :   .LUA
LuaRocks;
  PATH     :   C:\Program Files (x86)\LuaRocks
  LUA_PATH :   C:\Program Files (x86)\LuaRocks\lua\?.lua;C:\Program Files (x86)\LuaRocks\lua\?\init.lua
Local user rocktree (Note: %APPDATA% is user dependent);
  PATH     :   %APPDATA%\LuaRocks\bin
  LUA_PATH :   %APPDATA%\LuaRocks\share\lua\5.1\?.lua;%APPDATA%\LuaRocks\share\lua\5.1\?\init.lua
  LUA_CPATH:   %APPDATA%\LuaRocks\lib\lua\5.1\?.dll
System rocktree
  PATH     :   C:\Program Files (x86)\LuaRocks\systree\bin
  LUA_PATH :   C:\Program Files (x86)\LuaRocks\systree\share\lua\5.1\?.lua;C:\Program Files (x86)\LuaRocks\systree\share\lua\5.1\?\init.lua
  LUA_CPATH:   C:\Program Files (x86)\LuaRocks\systree\lib\lua\5.1\?.dll

Note that the %APPDATA% element in the paths above is user specific and it MUST be replaced by its actual value.
For the current user that value is: C:\Users\aa\AppData\Roaming.
```
If I open up a new (Powershell) terminal and type `lua` or `luarocks` followed by Enter, I get nothing.

Also, do I really have to update all those environment variables manually? Seems a little error-prone?

**Comment by awa5114** [comment]
@hishamhm  just for your information, I haven't been able to find many users who have succeeded in installing luarocks for windows and gotten it to work. Here's some examples:

- https://stackoverflow.com/questions/62343295/setting-up-luarocks-on-windows-10
- https://stackoverflow.com/questions/60761358/how-to-install-luarocks-for-windows-10
- https://stackoverflow.com/questions/39990449/using-luarocks-in-windows
- https://stackoverflow.com/questions/67373071/i-cant-set-up-luarocks-on-windows-10

In the words of a community member from the `pandoc` mailing list:

> I haven’t had much luck with luarocks on windows either, and would also love to hear about successfull approaches.
