### ISSUE TITLE
I can't install Luacov because I don't have permission

### ISSUE THREAD

**Issue by SyntixTheReal** [luarocks/luarocks#1424]
So when I run the luacov install command via luarock (`luarocks install luacov
`) it says the following error: `Error: Your user does not have write permissions in /usr/local/lib/luarocks/rocks
-- you may want to run as a privileged user or use your local tree with --local.` I am completely new to Ubuntu and Luarock aswsell so I don't know what I can do against it. I read through some old articles aswell but none of them helped me. Can someone maybe explain how one can fix this error?

**Comment by SyntixTheReal** [comment]
This is my configuration apparently:
`CONFIGURATION
        Lua version: 5.3
        Configuration files:
                System: /etc/luarocks/config.lua (ok)
                User  : /home/###/.luarocks/config-5.3.lua (not found)

        Rocks trees in use:
                /home/###/.luarocks
                /usr/local`

**Comment by SyntixTheReal** [comment]
FIXED IT!

Type in `sudo` infront of your command line so it has full permission access. (As I mentioned I am new so I didn't know this)

**Comment by alerque** [comment]
Yes, using `sudo` is one solution. Just be aware this gives it permission to mess with files in your system root, something most Linux distributions prefer to be reserved for the system package manager. That may be fine for your use case, but in the event it is not (or you are on a system where your user does not *have* sudo access) then you can also use `luarocks --local install` to install just to your own user. Then in your shell rc file you can add `eval $(luarocks --local path)` to enable Lua to find things in your user as well as the system default.
