### ISSUE TITLE
Can't exit REPL with CTRL+Z

### ISSUE THREAD

**Issue by ChildishGiant** [luarocks/luarocks#1426]
### Please fill out the following:
- **Platform:**
  - Linux

- **LuaRocks version:**
  - N/A, installed binary tool

- **Configuration file:**
  - Default

- **Description:**
  - When in repl (`yue`) Ctrl+z prints a replacement character instead of pausing the job 
![image](https://user-images.githubusercontent.com/13716824/179754115-d61165bf-6f9d-411b-8ba3-dae17f632729.png)

**Comment by ChildishGiant** [comment]
Maybe related, ctrl+d only ends the process if there's nothing typed on the line already

**Comment by hishamhm** [comment]
This program "yue" is not part of LuaRocks. You should probably report at https://github.com/pigpigyyy/Yuescript
