### ISSUE TITLE
I cant install luarocks

### ISSUE THREAD

**Issue by ZeroXiphYT** [luarocks/luarocks#1430]
### Please read the following before submitting:
- Please do NOT submit bug reports for questions. Ask questions in the [Gitter
  chat-room](https://gitter.im/luarocks/luarocks).
- Please do NOT submit duplicate bug reports. Look through the [issue
  tracker](https://github.com/luarocks/luarocks/issues) before submitting.

### Please fill out the following:
- **Platform:**
MacOS.

- **LuaRocks version:**
  - `I dont have luarocks`

- **Configuration file:**
  - Please try to produce with the default configuration.
  - If you cannot reproduce with the default configuration, please try to find
    the minimal configuration to reproduce.
  - Upload the config to a pastebin such as gist.github.com.

- **LuaRocks output from when the issue occurred:**
  - Use the `--verbose` flag.

- **Description:**
  I was trying to install luarocks by using brew install luarocks but when I do that I get this fatal: Could not resolve HEAD to a revision
Warning: No available formula with the name "luarocks".
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

**Comment by hishamhm** [comment]
This is not a luarocks bug. Please report to Homebrew if you are having issues with their distribution.
