### ISSUE TITLE
Add installed package to rockspec on install 

### ISSUE THREAD

**Issue by jorgeluisrezende** [luarocks/luarocks#1432]
- **Description:**
  When we use other package manage like npm there is a flag `--save` that saves the package automatic on package.json for exemple, would be nice to have a similar flag to do it in luarocks to save the dependency in rockspec

**Comment by alerque** [comment]
One issue with implementing this is that unlike ecosystems like npm where `package.json` is in an extremely limiting format that can easily be machine manipulated, the rockspec is actually a Lua file and could have comments, functions, string operations, etc. Automatically rewriting it would blow these sorts of things away.

**Comment by hishamhm** [comment]
Thanks for the feedback, but indeed this won't be implemented due to the reasons described by @alerque above.
