### ISSUE TITLE
kong plugin install

### ISSUE THREAD

**Issue by Yang-XL** [luarocks/luarocks#1440]
root@mosi:/usr/local/lib/luarocks/rocks-5.1/kong-plugin-hello-world/0.1-1# luarocks make 

kong-plugin-hello-world 0.1-1 depends on lua ~> 5.1 (5.1-1 provided by VM)

Error: LuaRocks 3.8.0 bug (please report at https://github.com/luarocks/luarocks/issues).
Arch.: linux-x86_64
/usr/local/share/lua/5.1/luarocks/fs/unix.lua:50: attempt to index a nil value
stack traceback:
        /usr/local/share/lua/5.1/luarocks/fs/linux.lua:8: in function 'is_dir'
        /usr/local/share/lua/5.1/luarocks/fs/lua.lua:183: in function 'dir'
        /usr/local/share/lua/5.1/luarocks/fs/lua.lua:167: in function 'list_dir'
        /usr/local/share/lua/5.1/luarocks/repos.lua:51: in function 'get_installed_versions'
        /usr/local/share/lua/5.1/luarocks/repos.lua:677: in function 'delete_version'
        /usr/local/share/lua/5.1/luarocks/build.lua:394: in function 'build_rockspec'
        /usr/local/share/lua/5.1/luarocks/cmd/make.lua:130: in function </usr/local/share/lua/5.1/luarocks/cmd/make.lua:79>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/luarocks/cmd.lua:666: in function 'run_command'
        /usr/local/bin/luarocks:38: in main chunk
        [C]: at 0x00404e20

**Comment by hishamhm** [comment]
@Yang-XL Can you upgrade LuaRocks to the latest version and see if the problem persists?
