### ISSUE TITLE
"Failed producing checksum: no MD5 checker tool available, please install md5sum, openssl or md5 in your system" but a md5 checker is installed.

### ISSUE THREAD

**Issue by MiguelEXE** [luarocks/luarocks#1443]
### Please fill out the following:
- **Platform:**
  - Windows

- **LuaRocks version:**
  - C:\Program Files (x86)\LuaRocks\luarocks.lua 3.9.1

- **Configuration file:**
  - https://pastebin.com/9hrFyMTv

- **LuaRocks output from when the issue occurred:**
  - https://pastebin.com/XhTiv9K6

- **Description:**
  - Open command prompt in administrator mode, enter in the %userprofile% (home directory) and run `luarocks install argparse`

Video: (problem)
https://user-images.githubusercontent.com/52385139/190881133-b405dd93-1cb7-45c2-a414-477873429e88.mp4

Video: (verbose)

https://user-images.githubusercontent.com/52385139/190881280-4217dbfe-7d7e-4964-91a3-b635b68920d4.mp4

Image: (tools)
![image](https://user-images.githubusercontent.com/52385139/190881317-119d69f0-0492-4475-bd57-93b8cccfad2f.png)

**Comment by aflyingdoge** [comment]
i also meet this problem, do u fix it?

**Comment by vaanwd** [comment]
There is no fix for this?

**Comment by NickGrease** [comment]
Same problem.

**Comment by alerque** [comment]
Possibly a duplicate of #1001.

**Comment by benpinpop** [comment]
Encountering the same issue, even though there's an md5 checker. I'm attempting to install luasocket. Is there any information I can provide about my system to help fix this?
![image](https://user-images.githubusercontent.com/103378040/236219129-17ae0f7c-f032-4324-bfa8-6a991b13ca50.png)

**Comment by pyorokun7** [comment]
So, this issue has been around for nearly a year, is still present in 3.9.2, but seems fixed.

Is there a workaround I can do as an user, should I downgrade to 3.8.0 or is there a timeline for a release that include the fix?

**Comment by roman-orekhov** [comment]
@pyorokun7 
Replace this line 

> https://github.com/luarocks/luarocks/blob/9a3c5a879849f4f411a96cf1bdc0c4c7e26ade42/src/luarocks/fs/lua.lua#L129

with these
```Lua
         local tool_cmd_no_args_normalized = dir.path(tool_cmd_no_args)
         local fd = io.open(tool_cmd_no_args_normalized, "r")
```

(I don't remember where I got this fix)

**Comment by pyorokun7** [comment]
Thanks, @roman-orekhov

That change indeed allowed me to install htmlparser.

**Comment by mb6ockatf** [comment]
i also got this error. the thing is, it works ok on my linux system, but inside alpine docker container it returns this error
