### ISSUE TITLE
Provide docker image for arm64v8 (Apple Silicon)

### ISSUE THREAD

**Issue by jottr** [luarocks/luarocks#1444]
```
$ uname -m 
arm64

$ docker run -i --rm ghcr.io/lunarmodules/luacheck
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

Please add `arm64` to the build matrix and publish the image to ghcr. Thanks!

**Comment by alerque** [comment]
I think you've filed this issue on the wrong repository, try https://github.com/lunarmodules/luacheck

**Comment by jottr** [comment]
Whoops. Wrong tab.  Will move the issue. Sorry for the noise.
