### ISSUE TITLE
mainfest was breaked

### ISSUE THREAD

**Issue by fesily** [luarocks/luarocks#1447]
### Please read the following before submitting:
- Please do NOT submit bug reports for questions. Ask questions in the [Gitter
  chat-room](https://gitter.im/luarocks/luarocks).
- Please do NOT submit duplicate bug reports. Look through the [issue
  tracker](https://github.com/luarocks/luarocks/issues) before submitting.

### Please fill out the following:
- **Platform:**
  - Linux and MacOS.

- **LuaRocks version:**
/opt/homebrew/bin/luarocks 3.9.1
LuaRocks main command-line interface

- **Description:**
Warning: Failed searching manifest: Failed loading manifest for https://luarocks.org: Error loading file: [string "/var/cache/luarocks/https___luarocks.org/manifest-5.1"]:14995: '(' expected near '='

line: 14995
```lua
   function = {
      ['1.0-1'] = {
         {
            arch = "rockspec"
         }, {
            arch = "src"
         }
      },
      ['1.1-1'] = {
         {
            arch = "rockspec"
         }, {
            arch = "src"
         }
      }
   }
```
function is a keyword

**Comment by UrNightmaree** [comment]
Sorry for the problem, I'm the author of the `Function` package. This problem should be fixed if Luarocks does sanatize or properly escape user data before writing it.

**Comment by UrNightmaree** [comment]
The bug has been fixed, I renamed the package into `Function.lua`. You can now continue to install Luarocks packages.

**Comment by hishamhm** [comment]
This is odd. The LuaRocks CLI tool does sanitize keywords: https://github.com/luarocks/luarocks/blob/master/src/luarocks/persist.lua#L49-L72
And so does the LuaRocks website, apparently: https://github.com/luarocks/luarocks-site/blob/master/ext/luarocks/persist.lua

In any case, if this is the manifest file coming from the server, the issue should be posted to https://github.com/luarocks/luarocks-site instead.
