### ISSUE TITLE
luarocks install lapis fails.

### ISSUE THREAD

**Issue by r0b0t-0** [luarocks/luarocks#1458]
I have been trying to install Lapis for hours on an M2 MacBook Air. I have confirmed that openssl is installed and in usr/local/include as well as ssl.h installed in usr/local/libs.

I tried luarocks install luaossl CRYPTO_ DIR=/usr/local as well as other folders up and down this path.

I continue to get the following error saying that CRYPTO.h is not found and ssl.h is not found. Of course the below libs are also not found.

Hope someone can helpout.

Last login: Fri Nov 11 19:29:55 on ttys001
(base) robot_o@Olivers-MacBook-Air ~ % luarocks install lapis
Installing https://luarocks.org/lapis-1.10.0-1.src.rock
Missing dependencies for lapis 1.10.0-1:
   luaossl (not installed)
   pgmoon (not installed)

lapis 1.10.0-1 depends on lua (5.4-1 provided by VM)
lapis 1.10.0-1 depends on ansicolors (1.0.2-3 installed)
lapis 1.10.0-1 depends on date (2.2-2 installed)
lapis 1.10.0-1 depends on etlua (1.3.0-1 installed)
lapis 1.10.0-1 depends on loadkit (1.1.0-1 installed)
lapis 1.10.0-1 depends on lpeg (1.0.2-1 installed)
lapis 1.10.0-1 depends on lua-cjson (2.1.0.10-1 installed)
lapis 1.10.0-1 depends on luaossl (not installed)
Installing https://luarocks.org/luaossl-20220711-0.src.rock

Error: Failed installing dependency: https://luarocks.org/luaossl-20220711-0.src.rock - Could not find header file for CRYPTO
  No file openssl/crypto.h in /usr/include
  No file openssl/crypto.h in /include
  No file openssl/crypto.h in /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
  No file openssl/crypto.h in /usr/local/opt/include
You may have to install CRYPTO in your system and/or pass CRYPTO_DIR or CRYPTO_INCDIR to the luarocks command.
Example: luarocks install luaossl CRYPTO_DIR=/usr/local

**Comment by daurnimator** [comment]
> ssl.h installed in usr/local/libs.

that doesn't sound right....

What do you get when you run: `find /usr -name crypto.h`

**Comment by r0b0t-0** [comment]
![Screenshot 2022-11-15 at 6 11 40 PM](https://user-images.githubusercontent.com/22569173/202051660-05483ad4-ed4f-434d-a26f-4fed54df66b1.png)
![Screenshot 2022-11-15 at 6 06 06 PM](https://user-images.githubusercontent.com/22569173/202051678-a965bc14-e112-470d-a565-6ba538f2c1a4.png)
![Screenshot 2022-11-15 at 6 06 44 PM](https://user-images.githubusercontent.com/22569173/202051698-7d81ff07-7cfb-4340-833e-c7391f28bf5d.png)

**Comment by r0b0t-0** [comment]
Added screen shots to help. I have both Crypto.h and SSL.h from previous installations. I have put the file exactly where luarockt is looking for it and still I get an error.

**Comment by daurnimator** [comment]
Looks like you'd need to run `luarocks install luaossl CRYPTO_DIR=/usr/local/openssl`

**Comment by siffiejoe** [comment]
> Looks like you'd need to run `luarocks install luaossl CRYPTO_DIR=/usr/local/openssl`

I think it's rather `luarocks install luaossl CRYPTO_INCDIR=/usr/local/`. The rockspec is searching for `openssl/crypto.h`, so the include directory should be `/usr/local` so that both combined give the real location of the header file. Since there is no `include` path component in the absolute path of `crypto.h`, we can't use the `CRYPTO_DIR` shortcut, because that assumes the standard UNIX subdirectory layout of `include`, `bin`, and `lib`. Speaking of `lib`, we probably also need `CRYPTO_LIBDIR` because I suspect that the shared library will also be in a weird location.

**Comment by hishamhm** [comment]
Indeed, custom dependency locations can be configured with `CRYPTO_LIBDIR` and `CRYPTO_INCDIR`.
