### ISSUE TITLE
WARN  "current_version" will be deprecated. Please change your code/manifest to use "Select-CurrentVersion"

### ISSUE THREAD

**Issue by lobanov4real** [luarocks/luarocks#1473]
### Please read the following before submitting:
- Please do NOT submit bug reports for questions. Ask questions in the [Gitter
  chat-room](https://gitter.im/luarocks/luarocks).
- Please do NOT submit duplicate bug reports. Look through the [issue
  tracker](https://github.com/luarocks/luarocks/issues) before submitting.

### Please fill out the following:
- **Platform:**
  - Windows.

- **LuaRocks version:**
  - `luarocks --3.9.2`

- **Configuration file:**
  - I have default [config](https://gist.github.com/lobanov4real/07fb1c17e5ade54c0c90653e030203dd#file-gistfile1-txt) file without any changes.

- **LuaRocks output from when the issue occurred:**
  - Use the `--verbose` flag.

- **Description:**
  - Install luarocks by scoop in powershell.
  - Update luarocks by scoop in powershell.
  - Get warning

**Comment by siffiejoe** [comment]
Seems to be a (known and fixed) issue with Scoop: https://github.com/ScoopInstaller/Scoop/issues/4534

**Comment by lobanov4real** [comment]
Thank you, @siffiejoe!

**Comment by niheaven** [comment]
Fixed in https://github.com/ScoopInstaller/Main/commit/8730cb9c714798a34e7a7e8b7e8c951fdd892f7f
