### ISSUE TITLE
Can't install mpack with MacOS 13.0.1

### ISSUE THREAD

**Issue by davidc538** [luarocks/luarocks#1474]
MacOS 13.0.1
LuaRocks 3.9.1 (installed via homebrew)
I haven't modified the default config and don't know where to find it.
```
% luarocks install mpack
Installing https://luarocks.org/mpack-1.0.9-0.src.rock

env MACOSX_DEPLOYMENT_TARGET=11.0 gcc -O2 -fPIC -I/usr/local/opt/lua/include/lua5.4 -c lmpack.c -o lmpack.o
lmpack.c:721:3: error: implicitly declaring library function 'snprintf' with type 'int (char *, unsigned long, const char *, ...)' [-Werror,-Wimplicit-function-declaration]
                snprintf(errmsg, 50, "can't serialize object of type %d", type);
                ^
lmpack.c:721:3: note: include the header <stdio.h> or explicitly provide a declaration for 'snprintf'
1 error generated.

Error: Build error: Failed compiling object lmpack.o
```
I don't know where to find the lmpack.c file so I can't see if stdlib.h is included conditionally or what is going on. I've attached the output of `luarocks install mpack --verbose`
[luarocks_install_mpack.txt](https://github.com/luarocks/luarocks/files/10193312/luarocks_install_mpack.txt)

**Comment by hishamhm** [comment]
@davidc538 This is an issue with the module, not with LuaRocks. Please contact the module maintainers!
