### ISSUE TITLE
Allow combining `upload` with `--local`

### ISSUE THREAD

**Issue by redcatbear** [luarocks/luarocks#1487]
### Situation

Often during development it is more convenient to use the `--local` switch in order to use the local Luarocks package cache of an individual user instead of the global one on the machine. In fact, it might be the only option if the developer does not have administrative privileges on the development machine or VM.

The `upload` command requires a JSON library to work and raises an error if that library is not available. The message is quite clear and descriptive and looks like this:

```
Error: A JSON library is required for this command. Failed loading 'cjson', 'dkjson', and 'json'. Use 'luarocks search <partial-name>' to search for a library and 'luarocks install <name>' to install one.
```

Now, if the user can't install said library, either due to the lack of admin privileges or because the user wants to keep every change in package contained to the local package cache, it would be ideal if the library could be taken from the local cache by issuing the following command:

```sh
luarocks --local upload <rocksepc> --api-key=<redacted>
```

Unfortunately, while there is no error message, the `--local` switch does not seem to affect the `upload` command.

### Desired enhancement

- Take the required JSON library from the user's local package cache when `upload` is combined with `--local`
   or
- Alternatively bundle a JSON library with luarocks

### Environment

This behavior was tested with:

- Luarocks 3.8.0
- Lua 5.4.4
- Linux 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Tieske** [comment]
the way I typically use local is to have the local tree in my path first, and then the system tree. Then this should work out of the box no?

also the --local flag is used for rock operations to indicate which tree to use. This changes that to mean which tree luarocks should use to "run itself". I think that's confusing for users.

**Comment by redcatbear** [comment]
@Tieske , I see your point and that sounds logical to me.

My `LUA_PATH` contains among other entries `/home/<username>/.luarocks/share/lua/5.4/?.lua` and if I list this path I see entries for JSON libraries:

```
cjson (dir)
dkjson.lua
```

So my first impression is, Luarocks should work. I am a bit puzzled now, why it still reports a missing library. Should Luarocks respect the search path, or am I overlooking something fundamental here?

**Comment by hishamhm** [comment]
@redcatbear Thank you for the report! 

> Alternatively bundle a JSON library with luarocks

I will do this — in LuaRocks 4, we will vendor-in its dependencies.

In the mean time, if you're on Linux x86-64 or Windows, the all-in-one binary already bundles them: https://luarocks.github.io/luarocks/releases/

**Comment by redcatbear** [comment]
Thanks for the answer, @hishamhm . The bundled version will fix the issue in an elegant way.

I will try out the all-in-one binary with the next release of one of my projects.

Btw, I wanted to say thank you for all the work that went into LuaRocks. This is a milestone in the Lua ecosystem and I think that Open Source developers should get the recognition for their contribution to a happy and productive developer community!

You can close this ticket, the problem is solved.

**Comment by redcatbear** [comment]
I tried the all-in-one binary and it works like a charm. Problem solved. Thanks a lot!
