### ISSUE TITLE
Failed to unpack rock file

### ISSUE THREAD

**Issue by yrifl** [luarocks/luarocks#1494]
```
$ luarocks install http
Installing http://luarocks.org/repositories/rocks/http-0.4-0.all.rock...

Error: Failed unpacking rock file: C:\Users\USERNAME\AppData\Local\Temp\luarocks_luarocks-rock-http-0.4-0-603
9/http-0.4-0.all.rock
```
I'm using Windows 10, Lua 5.1, Luarocks (Latest 3.9.2).

I have installed unzip (from an old issue when i search on google). I have search for latest issues on `Failed to unpack rock file` in this repo, but no help. I have checked if there is something missing and uses `--verbose` but nothing. What should i do?

I hope someones helps.

**Comment by daurnimator** [comment]
lua-http doesn't work on windows anyway

**Comment by hishamhm** [comment]
Not a lot an info to go by on this one, it could be several things. If this is still an issue and you can provide a full `--verbose` output, feel free to reopen.
