### ISSUE TITLE
Installing luasql.oci8 in my debian 11(bullseyes) version but got the error

### ISSUE THREAD

**Issue by ayuraj736** [luarocks/luarocks#1502]
Warning: Failed searching manifest: Failed extracting manifest file: failed extracting /home/ajain/.cache/luarocks/https___luarocks.org/manifest-5.2.zip

Error: LuaRocks dev bug (please report at https://github.com/luarocks/luarocks/issues).
Arch.: linux-x86_64
/usr/local/share/lua/5.2/luarocks/fs/lua.lua:797: attempt to perform arithmetic on a nil value
stack traceback:
        /usr/local/share/lua/5.2/luarocks/fs/lua.lua:797: in function 'http_request'
        /usr/local/share/lua/5.2/luarocks/fs/lua.lua:886: in function 'download'
        /usr/local/share/lua/5.2/luarocks/fetch.lua:42: in function 'fetch_url'
        /usr/local/share/lua/5.2/luarocks/manif.lua:82: in function 'fetch_manifest_from'
        /usr/local/share/lua/5.2/luarocks/manif.lua:125: in function 'load_manifest'
        /usr/local/share/lua/5.2/luarocks/search.lua:111: in function </usr/local/share/lua/5.2/luarocks/search.lua:101>
        (...tail calls...)
        /usr/local/share/lua/5.2/luarocks/search.lua:155: in function 'search_repos'
        /usr/local/share/lua/5.2/luarocks/search.lua:253: in function 'find_suitable_rock'
        /usr/local/share/lua/5.2/luarocks/cmd/install.lua:250: in function </usr/local/share/lua/5.2/luarocks/cmd/install.lua:220>
        (...tail calls...)
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.2/luarocks/cmd.lua:468: in function 'run_command'
        /usr/local/bin/luarocks:38: in main chunk
        [C]: in ?

### 
- **Platform:**
  - Debian 11 (bullseyes) version

- **LuaRocks version:**
  - `luarocks5.2

.

**Comment by ayuraj736** [comment]
can anyone please reply on this

**Comment by hishamhm** [comment]
This was already fixed in e9156c8ab6bc8b7f4c0e9d2e706131bc89bec57e. Please upgrade LuaRocks.
