### ISSUE TITLE
Transfer ownsership of lua-resty-cookie from cloudflare to utix

### ISSUE THREAD

**Issue by utix** [luarocks/luarocks#1504]
Hi,

after several exchanges Cloudflare has confirmed that they won't update anymore lua-resty-cookie

Today the package cannot be used anymore
A solution was proposed by Kong:
https://github.com/cloudflare/lua-resty-cookie/pull/50

I have done the modification to fix this and pushed the same version (0.1.0-1), the fix of path (0.1.0-2) and create a new release with the new feature (0.2.0).

**Comment by hishamhm** [comment]
@utix sure, I can do the transfer. Could I get a confirmation via email to hisham@luarocks.org from someone at Cloudflare of their intent, as a formality?
