### ISSUE TITLE
luarocks cannot find external dependencies on NixOS

### ISSUE THREAD

**Issue by mrcjkb** [luarocks/luarocks#1505]
### Please fill out the following:
- **Platform:**
  - Linux (NixOS 22.11).

- **LuaRocks version:**
  - `3.9.1`

- **Configuration file:**
```
-- LuaRocks configuration

rocks_trees = {
   { name = "user", root = home .. "/.luarocks" };
   { name = "system", root = "/nix/store/78zihw35z1swv43kjy61kl0cg5blxcji-luarocks-3.9.1" };
}
lua_interpreter = "lua";
variables = {
   LUA_DIR = "/nix/store/k2faidw0mcjyj3wqcicbvpjd2ig1pym7-lua-5.2.4";
   LUA_BINDIR = "/nix/store/k2faidw0mcjyj3wqcicbvpjd2ig1pym7-lua-5.2.4/bin";
}
```
- **LuaRocks output from when the issue occurred:**
```console
luarocks test --local --verbose > out.log
Error: Failed installing dependency: https://luarocks.org/busted-2.1.2-3.src.rock - Failed installing dependency: https://luarocks.org/luasystem-0.2.1-0.src.rock - Could not find library file for RT
  No file librt.a in /usr/local/lib
  No file librt.a in /usr/local/lib64
  No file librt.so in /usr/local/lib
  No file librt.so in /usr/local/lib64
  No file matching librt.so.* in /usr/local/lib
  No file matching librt.so.* in /usr/local/lib64
  No file librt.a in /usr/lib
  No file librt.a in /usr/lib64
  No file librt.so in /usr/lib
  No file librt.so in /usr/lib64
  No file matching librt.so.* in /usr/lib
  No file matching librt.so.* in /usr/lib64
  No file librt.a in /lib
  No file librt.a in /lib64
  No file librt.so in /lib
  No file librt.so in /lib64
  No file matching librt.so.* in /lib
  No file matching librt.so.* in /lib64
You may have to install RT in your system and/or pass RT_DIR or RT_LIBDIR to the luarocks command.
Example: luarocks install luasystem RT_DIR=/usr/local
```
[out.log](https://github.com/luarocks/luarocks/files/11366692/out.log)

- **Description:**
  Run with the `luarocks-test` branch of https://github.com/nvim-neorocks/luarocks-tag-release on NixOS.
  The problem is that the locations in which luarocks searches for external dependencies do not exist on NixOS. 
  For example, on my machine, librt.so is installed in `/nix/store/0z5kcds7b6qmm373s3b5w9ykvqbgw87i-glibc-2.37-8`
  A workaround is to run `luarocks test --local RT_DIR=/nix/store/0z5kcds7b6qmm373s3b5w9ykvqbgw87i-glibc-2.37-8`, but this is not scalable (as it will fail with the next external dependency). It will also break as soon as `glibc` is updated and its nix store path changes.
  
Related:  https://github.com/NixOS/nixpkgs/issues/229291
  
I think a potential solution would be for luarocks also search in  `LD_LIBRARY_PATH`, which could be set in a nix environmennt that uses luarocks.

**Comment by hishamhm** [comment]
This is a NixOS-specific configuration issue, please report to the distro downstream.

LuaRocks has several config entries to adjust its binary lookup path to many platforms: run `luarocks config` and check the options `external_deps_dirs`, `external_deps_patterns`,  `external_deps_subdirs` and `external_lib_extension`.

If NixOS uses a custom LD_LIBRARY_PATH, it should probably also set custom paths for LuaRocks too.

If the configuration flexibility of LuaRocks still proves insufficient, feel free to open a new issue!
