### ISSUE TITLE
Wrong `include` directory is used

### ISSUE THREAD

**Issue by Majixed** [luarocks/luarocks#1511]
Hello, I was trying to compile neovim to use on a 32-bit linux system with musl, and I got this error while luarocks was installing dependencies:
```
Error: Failed installing dependency: https://luarocks.org/luasystem-0.2.1-0.src.rock - Build error: Failed compiling object src/core.o

luasystem 0.2.1-0 depends on lua >= 5.1 (5.1-1 provided by VM)
/home/username/github/musl-cross-make/output/bin/i386-linux-musl-gcc -O2 -fPIC -I/home/username/github/neovim/.deps/usr/include/luajit-2.1 -c src/core.c -o src/core.o -I/usr/include
ninja: build stopped: subcommand failed.
make: *** [Makefile:99: deps] Error 1
```
I assume this happens because `-I/usr/include` is used whereas it should be `-I/home/username/github/musl-cross-make/output/i386-linux-musl/include`. Is there a way to instruct it to use this directory instead?

**Comment by Majixed** [comment]
Hi, thanks for the response. Apologies I wasn't able to reply earlier. I currently do not have access to this machine, but I will let you know if it works when I do.

**Comment by hishamhm** [comment]
LuaRocks has several config entries to adjust its binary lookup path to many platforms: run `luarocks config` to dump your current configuration and check the options `external_deps_dirs`, `external_deps_patterns`, `external_deps_subdirs` and `external_lib_extension`.

If you are cross-compiling, you want to change those settings in your LuaRocks config file (run `luarocks` with no arguments to check the path of your config files)
