### ISSUE TITLE
Wrong example in luarocks test wiki page

### ISSUE THREAD

**Issue by Jummit** [luarocks/luarocks#1518]
The last example on [this page](https://github.com/luarocks/luarocks/wiki/test#command-test-type) is incorrect, it should be `command = "make test"` instead of `script = "make test"`.

**Comment by MartinHelmut** [comment]
Took me a bit to figure that out as well 😅 Sadly I see no way to contribute to a GitHub wiki with a PR, otherwise I would love to as other parts of the wiki could be improved as well. Any of the contributors a good idea regarding this?

**Comment by hishamhm** [comment]
@MartinHelmut Thanks for the initiative! From a quick search looks like there's no easy way to do this with a PR, so we could do it the old-fashioned way:

1. `git clone https://github.com/luarocks/luarocks.wiki.git`
2. Make and commit your changes locally
3. Prepare one or more patch files:
    1. If you made several nicely separated commits and you think the commit history would help me review, then do: `git format-patch origin`, this will create a bunch of `*.patch` files, one for each commit
   2. If you didn't keep a tidy commit history, just do `git diff origin > mypatch.patch`, it's fine
4. Email them to me at hisham@luarocks.org (as one or more attachments) and I'll review and merge

**Comment by MartinHelmut** [comment]
@hishamhm Sounds like a plan! 💪🏻 I think I'll go for the by-commit approach, that should also make it easier for you to decide if you want to add a change or not. I'll go through what I wrote down already the next days and will email you soon 🤞🏻

Not to forget, thanks for updating the `luarocks test` wiki.
