### ISSUE TITLE
use emmylua to provide more typesafety

### ISSUE THREAD

**Issue by teto** [luarocks/luarocks#1530]
### Please fill out the following:
Several projects I know of (https://github.com/nvim-neorocks/luarocks-tag-release, https://github.com/neovim/neovim/) use emmylua in comments, It helps check some type safety with native lua, e.g, you can be warned when using a number as string etc.
Since there are already a great deal of comments in luarocks, changing them to emmylua format can be gradual, while helping detect some bugs.

**Comment by teto** [comment]
I was notified that https://luals.github.io/wiki/annotations/ forked emmylua (a priori not active anymore) and that neovim was using this new system (called "luacats"). I believe some people would be interested in lending a hand (https://github.com/nvim-neorocks/rocks.nvim folks mostly). @hishamhm  what do you think ?

**Comment by Tieske** [comment]
@teto have a look at [Teal](https://github.com/teal-language/tl) of which @hishamhm happens to be the author

**Comment by teto** [comment]
@Tieske I already had a look at teal but the tradeoff complexity vs advantages was not worth it for me. It makes things more complex while not providing enough typechecking. I tested luau a bit https://luau-lang.org/ that worked better for me.

Anyway I dont think any of these propositions is in scope because too complex (rewrite luarocks in rust at this stage), the advantage of emmylua/luacats is that the conversion of the database is backwards compatible AND incremental, the types live in comments. The only downside I see is the churn, which is ok since luarocks doesn't have a crazy activity.

**Comment by hishamhm** [comment]
@teto I don't think I have said it publicly it anywhere, but my intention is to port LuaRocks to Teal. I understand it is a significant undertaking, but having control of both sides of the equation should allow me to tailor one to the other more easily (i.e. add any missing features to Teal that prove important for the porting).

For that reason I have somewhat halted new development on LuaRocks and I've been focusing on feature work for Teal. 

> It makes things more complex while not providing enough typechecking

I'm curious: what are the things you found missing? I'd appreciate more feedback on your impressions!

**Comment by teto** [comment]
thanks for the update. Is there a working teal codebase already ? I am a bit anxious because it feels like you do a lot and creating a new language while rewriting luarocks looks too much for amy human being.
Adding luacats comments wouldn't change the codebase, just making typecheck on current codebase easier so it might still be worth it.

> I'm curious: what are the things you found missing? I'd appreciate more feedback on your impressions!

I really wish I could provide good feedback but my experience was short (not because I disliked teal but I wanted a quick feel for it) and I dont remember it much. What I remember is the generation of types, committing them, the addition of a new layer of tools like a teal lsp, compiler, this all felt like a lot of complexity for little typesafety (granted I come from a haskell background). Not even getting sum types was sad. I felt like emmylua/luacats could get me the same without the whole machinery, remaining in native lua.
For a point of comparison I tried fennel and got the same feeling. Recently I tried luau https://luau-lang.org/ and it felt more approachable. Also it has a company behind it and is already used widely so I feel more confident using it.

@lewis6991 tried to rewrite packer.nvim in teal but eventually gave up. He might have some more elaborate feedback too (sry to drag you into this xD).

Once again thanks for everything you do.

**Comment by hishamhm** [comment]
@teto Thanks for reporting on your experiences!

> thanks for the update. Is there a working teal codebase already ?

Not yet!

> I am a bit anxious because it feels like you do a lot and creating a new language while rewriting luarocks looks too much for amy human being.

Thank you for your concern. :) It's not meant to be a massive rewrite but more of a transition, and [I hope to get some help!](http://www.lua.inf.puc-rio.br/gsoc/ideas2024.html#luarocks-teal)

In any case, I'm going to close this particular issue since adopting emmylua is not the way I'm going to go. But thanks again!!

**Comment by lewis6991** [comment]
> @lewis6991 tried to rewrite packer.nvim in teal but eventually gave up. He might have some more elaborate feedback too (sry to drag you into this xD).

I succeeded, unfortunately Teal didn't gain enough momentum (feature wise or adoption), the tooling was basically non-existent, and it didn't check as much as LuaLS (specifically `nil`), so I decided to port everything back to Lua and adopt LuaCATs annotations instead.

There were other reasons I could expand upon, but that's the crux of it.
