### ISSUE TITLE
Manual install and install.bat failing to properly install luarocks

### ISSUE THREAD

**Issue by The-Lord-of-Owls** [luarocks/luarocks#1537]
- **Platform:** Windows 10

- **LuaRocks version:** 3.9.2

- **Description:** Unable to install manually or with install.bat

When attempting to do a manual install by downloading from [here](http://luarocks.github.io/luarocks/releases) I am given only a luarocks.exe and luarocks-admin.exe file. When placing these into C:\lua\luarocks\ I opened a cmd window to that directory and ran >luarocks

What happened next is it spits out a list of commands followed by some configuration text. however the file paths listed in the configuration text are pointing to C:\Program Files (x86)\luarocks and to appdata\roaming under my user folder.

Assuming that I installed things incorrectly I started over with the install.bat file inside the "C:\lua\luarocks\" folder instead. However when running install.bat from the CMD window, I get:
```
rem=rem --[[--lua
The system cannot find the path specified.
```
I'm unsure how to procceed as there is nothing about this mentioned in the [docs](https://github.com/luarocks/luarocks/wiki/Installation-instructions-for-Windows)

- **Conclusion:** The docs are incorrect, the install.bat file is not written properly or something is missing from the 3.9.2 release zip file and resulting in the inability to install onto windows.

**Comment by geniuszxy** [comment]
You should download this package: [luarocks-3.9.2-win32.zip](http://luarocks.github.io/luarocks/releases/luarocks-3.9.2-win32.zip) (legacy Windows package, includes Lua 5.1)
