### ISSUE TITLE
Error: Unknown protocol git+https

### ISSUE THREAD

**Issue by JokeVallen** [luarocks/luarocks#1538]
![image](https://github.com/luarocks/luarocks/assets/101782215/41e75359-fa57-436e-b5d6-f15f7936e36e)

**Comment by Tieske** [comment]
@JokeVallen please do not post errors as images

**Comment by hishamhm** [comment]
git+https is available since LuaRocks 2.2.2, from 2015. This must be a very old version. Please upgrade. Feel free to reopen in the problem persists with the latest version.
