### ISSUE TITLE
luarocks install doesn't respect rocks_trees config

### ISSUE THREAD

**Issue by mrcjkb** [luarocks/luarocks#1539]
- **Platform:**
  - Linux (NixOS).

- **LuaRocks version:**
  - `3.9.1`

- **Configuration file:**
```lua
rocks_trees = {
  { 
    ["name"] = "some_rock",
    ["rocks_dir"] = "/some/local/path/some_rock-<version>-rocks",
    ["root"] = "/some/local/path",
  },
}
```

- **LuaRocks output from when the issue occurred:**

```console
       > Warning: Failed searching manifest: Failed downloading https://luarocks.org/manifest-5.1 - failed downloading https://luarocks.org/ma
nifest-5.1
       > Warning: Failed searching manifest: Failed downloading https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master
/manifest-5.1 - failed downloading https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/manifest-5.1
       > Warning: Failed searching manifest: Failed downloading https://luafr.org/luarocks/manifest-5.1 - failed downloading https://luafr.org
/luarocks/manifest-5.1
       >
       > Error: No results matching query were found for Lua 5.1.
       > To check if it is available for other Lua versions, use --check-lua-versions.

```

- **Description:**

I am trying to set up a sandboxed integration test in which I shell out to `luarocks`.
To prevent `luarocks` from trying to fetch the packages from luarocks.org, I have set the local paths to the rocks, using the `rocks_trees` config.
This works for `luarocks test`, which will find test dependencies in the `rocks_trees` config and use those as the source. But `luarocks install` still tries to fetch the packages from luarocks.org.

**Comment by hishamhm** [comment]
> But luarocks install still tries to fetch the packages from luarocks.org.

`rocks_trees` configuration is about local rocks trees, containing installed rocks. For the configuration of where luarocks gets its packages from, you need to edit `rocks_servers`. Hope that clarifies!
