### ISSUE TITLE
[BUG]: `Invalid cross-device link` on latest luarocks

### ISSUE THREAD

**Issue by vhyrro** [luarocks/luarocks#1559]
### Please fill out the following:
- **Platform:**
  - Linux

- **LuaRocks version:**
  - Luarocks commit `89daf1f1588189f0fedc0b050408d785729a6833` (currently latest master)

- **Configuration file:**
  - Not applicable

- **LuaRocks output from when the issue occurred:**
```
Installing rocks.nvim failed: ln: failed to create hard link '/home/vhyrro/.local/share/nvimrocks/rocks/lockfile.luarocks' => '/tmp/lua_8wwINH': Invalid cross-device link

Error: command 'install' requires exclusive access to /home/vhyrro/.local/share/nvimrocks/rocks - failed to force the lock: File exists
```

- **Description:**
  - This error occurs whenever attempting to install the latest release of luarocks. The reason seems to be that luarocks is attempting to create a hard symlink for the lockfile. Hard symlinks fail to work e.g when the source file and the target file are on different partitions, which appears to be the case for me at least :)

    A solution would be to pass the `-s` flag to `ln` in order to create a soft link instead, fixing the problems with cross-device links. The error occurs no matter whether the `--force-lock` flag is passed or not. For more info see e.g. <https://unix.stackexchange.com/questions/79132/invalid-cross-device-link-while-hardlinking-in-the-same-file-system>

**Comment by andreidmt** [comment]
Same issue here. I have a custom installation on a different partition.
