### ISSUE TITLE
luarocks on Win 11 - configuration error

### ISSUE THREAD

**Issue by c-h-r-i-s-t-i-a-n** [luarocks/luarocks#1560]
So, I try to get this running on Windows 11.

lua53.exe is installed in \apps\lua. I created the directories _lib_ and _inc_ there.

Did a _luarocks config variables.LUA_INCDIR C:\apps\lua\inc_ , same for LUA_LIBDIR.

But luckrocks does not recognize those settings:

```
Configuration:
   Lua:
      Version    : 5.3
      Interpreter: C:\apps\lua/lua53.exe (ok)
      LUA_DIR    : C:\apps\lua (ok)
      LUA_BINDIR : C:\apps\lua (ok)
      LUA_INCDIR : C:\apps\lua\inc (not found)
                   ****************************************
                   Use the command
                      luarocks config variables.LUA_INCDIR <dir>
                   to fix the location
                   ****************************************
      LUA_LIBDIR : C:\apps\lua\lib (not found)
                   ****************************************
                   Use the command
                      luarocks config variables.LUA_LIBDIR <dir>
                   to fix the location
                   ****************************************
```

Bug or User Error ? 

Thanks.

**Comment by c-h-r-i-s-t-i-a-n** [comment]
Could this be the cause: 

```
Checking your Lua installation ...
Error: Failed finding Lua header files. You may need to install them or configure LUA_INCDIR.

```

**Comment by justdie386** [comment]
Luarocks doesn't take care  of the header files for lua, on windows the only thing you can do is download the source code for your lua version, and copy certain files such as lauxlib.h, luaconf.h, lualib.h, and lua.hpp to the C:\apps\lua\inc folder

**Comment by Tieske** [comment]
you can use [LuaWinMake](https://github.com/Tieske/luawinmake) to build and install Lua on Windows, it will include the header files etc.

**Comment by hishamhm** [comment]
> Bug or User Error ?

The latest code in `master` includes better diagnostic messages to make it clearer which case it is!

Apart from that, it's what @Tieske and @justdie386 mentioned: your best bet is to get Lua development files from elsewhere and then point LuaRocks to them (as you did with `luarocks config`). Just make sure that your LUA_INCDIR contains lua.h and friends, and your LUA_LIBDIR contains the proper Lua lib for your C compiler (usually something like lua54.lib, or the like -- each Lua distro has its own naming convention... LuaRocks pretty much tries them all!)
