### ISSUE TITLE
Luarocks 3.9.2 fails to install binary rock

### ISSUE THREAD

**Issue by orelmaliach** [luarocks/luarocks#1564]
**Platform:** Ubuntu (amd64)
**LuaRocks version:** 3.9.2
**Configuration file**: https://pastebin.com/quqE8G7H

**LuaRocks output from when the issue occurred:**
```
#9 [ 5/11] RUN for rock in /opt/kong/custom-plugins/*.all.rock; do luarocks install $rock; done
#9 0.859 Warning: Lua 5.1 interpreter not found at /usr/local/openresty/luajit
#9 0.859 
#9 0.859 Modules may not install with the correct configurations. You may want to configure the path prefix to your build of Lua 5.1 using
#9 0.859 
#9 0.859    luarocks config --local lua_dir <your-lua-prefix>
#9 0.859 
#9 0.861 
#9 0.861 Error: LuaRocks 3.9.2 bug (please report at https://github.com/luarocks/luarocks/issues).
#9 0.861 Arch.: linux-x86_64
#9 0.861 /usr/local/share/lua/5.1/luarocks/fs/unix/tools.lua:197: umask -S: Cannot allocate memory
#9 0.861 stack traceback:
#9 0.861 	/usr/local/share/lua/5.1/luarocks/fs/unix/tools.lua:197: in function '_unix_umask'
#9 0.861 	/usr/local/share/lua/5.1/luarocks/fs/unix.lua:201: in function '_unix_moderate_permissions'
#9 0.861 	/usr/local/share/lua/5.1/luarocks/fs/unix/tools.lua:229: in function 'set_permissions'
#9 0.861 	/usr/local/share/lua/5.1/luarocks/fs/lua.lua:363: in function 'make_dir'
#9 0.861 	/usr/local/share/lua/5.1/luarocks/fetch.lua:308: in function 'fetch_and_unpack_rock'
#9 0.861 	/usr/local/share/lua/5.1/luarocks/cmd/install.lua:97: in function 'install_binary_rock'
#9 0.861 	/usr/local/share/lua/5.1/luarocks/cmd/install.lua:194: in function </usr/local/share/lua/5.1/luarocks/cmd/install.lua:190>
#9 0.861 	[C]: in function 'xpcall'
#9 0.861 	/usr/local/share/lua/5.1/luarocks/cmd.lua:672: in function 'run_command'
#9 0.861 	...cal/lib/luarocks/rocks-5.1/luarocks/3.9.2-1/bin/luarocks:35: in main chunk
#9 0.861 	[C]: at 0x55ea6fe73450
```

**Verbose output:** https://pastebin.com/LRhQkGxA

**Description:**
1. I'm building a rock for a custom plugin for Kong with a rockspec (https://pastebin.com/vC0emM0P) by running `luarocks make --pack-binary-rock`.
2. I'm running `docker build` using a Dockerfile to build an image based on `library/kong:3.5.0-ubuntu`.
3. As part of Dockerfile, I'm copying the rock to the container that's being built.
4. In same Dockerfile I'm trying to install the rock using `luarocks install <make-output>.all.rock`.
5. The installation fails of course with the above output that suggested I open this issue.

The installation seems to fail in triggering `umask -S` for some reason. If I run `docker run -it --entrypoint /bin/bash library/kong:3.5.0-ubuntu`, I can run `umask -S` with no issue (output is `u=rwx,g=rx,o=rx`).

This exact procedure was working fine with our previous Kong version 3.1.1, which is using luarocks 3.9.1 if I'm not mistaken. The same procedure is working fine even with Kong 3.5.0 (and Luarocks 3.9.2) when making the rock on my local workstation (Mac M1 arm64), and building same Dockerfile.
So it's failing on our Jenkins host basically. I'm now trying to reproduce the issue in a simpler way, without docker in docker and potentially without Kong as well.
Meanwhile I thought I'll open the issue if anything stands out to you.

Cheers, Or.

**Comment by hishamhm** [comment]
The `Cannot allocate memory` error hints that this is a lower-level issue; your container is probably hitting some hard resource limit, such as memory size or number of subprocesses. My only suggestion is to check your Jenkins limits.  Unfortunately I can't provide any more guidance, as I don't see nothing LuaRocks specific here other than a process getting an OS error when failing to fork a `popen()`.
