### ISSUE TITLE
Not importing modules

### ISSUE THREAD

**Issue by wer310** [luarocks/luarocks#1566]
Platform: Linux
Luarocks version: 5.1
I want to import `luasql-sqlite3` with `require`... Not working.

**Comment by alerque** [comment]
This is not much to go on. Can you show the Lua code of your actual require statement? And at that point what is the `package.path`? And how exactly did you install luaqsl? And does is show up when you list packages installed via luarocks?

**Comment by wer310** [comment]
1. У меня в коде только оператор `require("luasql-sqlite3")`
2. В `package.path` нету
3. Да отображается

**Comment by wer310** [comment]
@alerque

**Comment by hishamhm** [comment]
This is not a LuaRocks issue, but a LuaSQL question. Please check out the LuaSQL documentation for instructions on how to use it.
