### ISSUE TITLE
luarocks/cmd.lua:738: attempt to concatenate a table value (field 'root_dir')

### ISSUE THREAD

**Issue by daurnimator** [luarocks/luarocks#1626]
### Please read the following before submitting:
- Please do NOT submit bug reports for questions. Ask questions in the [Gitter
  chat-room](https://gitter.im/luarocks/luarocks).
- Please do NOT submit duplicate bug reports. Look through the [issue
  tracker](https://github.com/luarocks/luarocks/issues) before submitting.

### Please fill out the following:
- **Platform:**
  - Linux

- **LuaRocks version:**
  - `luarocks --version`
  - `/usr/bin/luarocks 3.10.0`

- **Configuration file:**
  - Please try to produce with the default configuration.
  - If you cannot reproduce with the default configuration, please try to find
    the minimal configuration to reproduce.
  - Upload the config to a pastebin such as gist.github.com.

- **LuaRocks output from when the issue occurred:**
```
$ cd $(mktemp -d)
/tmp/tmp.ZMLTE9m7MQ ~/src/PKGBUILDS/lua-dkjson
$ tar -xvf ~/src/PKGBUILDS/lua-dkjson/dkjson-2.7.tar.gz 
dkjson-2.7
dkjson-2.7/dkjson-2.6-1.rockspec
dkjson-2.7/dkjson.lua
dkjson-2.7/jsontest.lua
dkjson-2.7/readme.txt
dkjson-2.7/speedtest.lua
dkjson-2.7/versions.txt
$ cd dkjson-2.7/
$ luarocks make --lua-version=5.1 --pack-binary-rock --deps-mode=none dkjson-2.7-1.rockspec --verbose
fs.current_dir()
fs.current_dir()
fs.is_superuser()
fs.current_user()
fs.lock_access("/usr", nil)
fs.make_dir("/usr")
/usr/bin/lua5.4: /usr/share/lua/5.4/luarocks/cmd.lua:738: attempt to concatenate a table value (field 'root_dir')
stack traceback:
	/usr/share/lua/5.4/luarocks/cmd.lua:738: in function 'luarocks.cmd.run_command'
	/usr/bin/luarocks:38: in main chunk
	[C]: in ?
```

- **Description:**
  - Attempted to build dkjson release

**Comment by hishamhm** [comment]
#1622 will fix this!

**Comment by hishamhm** [comment]
Actually, it needs some extra tweaks. On the way!
