### ISSUE TITLE
luarocks pack creates macosx-x86_64.rock entry on m1 mac

### ISSUE THREAD

**Issue by mrcjkb** [luarocks/luarocks#1630]
- **Platform:**
  - MacOS (M1) .

- **LuaRocks version:**
  - 3.9.1

- **Configuration file:**
  - Default configuration file

- **LuaRocks output from when the issue occurred:**
  - Use the `--verbose` flag.

https://github.com/nvim-neorocks/rocks-binaries/actions/runs/7918737290/job/22186115005#step:14:9

- **Description:**

- On an M1 macos device (the `macos14` GitHub runner), build a binary rock ([toml-edit](https://luarocks.org/modules/neorg/toml-edit)).
- Run `luarocks pack toml-edit`

Expected;

- It creates a `.macosx-aarch64.rock`

Actual:

- It creates a `.macosx-x86_32.rock`

but the binary is compiled for aarch64, resulting in the following error when trying to use it on an x86_32 MacOS device:

```
Async task failed without callback: The coroutine failed with this mess
age:
error loading module 'toml_edit' from file '/Users/oguz/.local/share/nvim/rocks/lib/lua/5.1/toml_edit.so':
dlopen(/Users/oguz/.local/share/nvim/rocks/lib/lua/5.1/toml_edit.so, 6): no suitable image found. Did find:
/Users/oguz/.local/share/nvim/rocks/lib/lua/5.1/toml_edit.so: mach-o, but wrong architecture
/Users/oguz/.local/share/nvim/rocks/lib/lua/5.1/toml_edit.so: mach-o, but wrong architecture
```

**Comment by hishamhm** [comment]
This is fixed in LuaRocks 3.10!
