### ISSUE TITLE
install a luarock in Debian wsl2

### ISSUE THREAD

**Issue by konstantinosDMS** [luarocks/luarocks#1631]
Windows 11 - WL2 - Debian

/usr/local/bin/luarocks 3.10.0

-- LuaRocks configuration

rocks_trees = {
   { name = "user", root = home .. "/.luarocks" };
   { name = "system", root = "/usr/local" };
}
variables = {
   LUA_DIR = "/usr";
   LUA_INCDIR = "/usr/local/include";
   LUA_BINDIR = "/usr/bin";
   LUA_VERSION = "5.4";
   LUA = "/usr/bin/lua5.4";
}

luarocks install luaposix
/usr/bin/lua5.4: /usr/local/share/lua/5.4/luarocks/cmd.lua:738: attempt to concatenate a table value (field 'root_dir')
stack traceback:
        /usr/local/share/lua/5.4/luarocks/cmd.lua:738: in function 'luarocks.cmd.run_command'
        /usr/local/bin/luarocks:38: in main chunk
        [C]: in ?

These are the results when i am trying to intall a rock from the server

**Comment by konstantinosDMS** [comment]
Run as sudo

**Comment by hishamhm** [comment]
This is a duplicate of #1626. The fix will be present in the next release!
