### ISSUE TITLE
3.10.0 release build paralyzation issue

### ISSUE THREAD

**Issue by chenrui333** [luarocks/luarocks#1638]
👋 looks like there is some build parallelization issue with 3.10.0 release build

```
  echo "unset LUA_PATH LUA_PATH_5_2 LUA_PATH_5_3 LUA_PATH_5_4 LUA_CPATH LUA_CPATH_5_2 LUA_CPATH_5_3 LUA_CPATH_5_4" >> luarocks-admin
  install: ./build/config-5.4.lua: No such file or directory
  make: *** [install-config] Error 71
```

see build log in here, https://github.com/Homebrew/homebrew-core/actions/runs/8208660378/job/22452665344
relates to https://github.com/Homebrew/homebrew-core/pull/165391

**Comment by hishamhm** [comment]
Hi! Thanks for reporting, but the LuaRocks makefile was not designed for parallel invocation. Also, it "builds" really fast (it is pure Lua and just copies a few files around) so there's no gain in running it in parallel. So in effect unfortunately this is a "wont fix". Just run `make` as normal and you'll be fine.

**Comment by chenrui333** [comment]
yeah, make sense 👍

**Comment by alerque** [comment]
Many distros are setting `MAKEFLAGS+=--jobs=$(proc)` or similar by default now for package build environments and some even for user environments.

I think it would make sense to add a mitigation to the Makefile.

```makefile
# This makefile has known race conditions that will fail if targets are run in parallel.
# Force at least GNU Make 4.3+ to only use a single job to run targets in serial order.
MAKEFLAGS += --jobs=1
```

This only works in GNU Make 4.3+. It will be ignored in older versions of make that already setup the job server by the time they parse the Makefile. But in 4.3 plus it actually does parse and respond to this early enough to be able to override the value from inside the Makefile.

But here's the thing: many/most of the distros that are aggressively setting defaults to parallel builds are also the ones that have a fresh enough GNU Make for this to work.

**Comment by Sharparam** [comment]
Just ran into this issue as well, when installing via `mise`. As mentioned, my default `MAKEFLAGS` sets `--jobs=$(nproc)` so the `make bootstrap` of Luarocks fails.

This should _at the very least_ be mentioned in the documentation here: https://github.com/luarocks/luarocks/wiki/Installation-instructions-for-Unix and in the README as well.

But ideally the override as mentioned above should be put in place in the makefile, why is this not being considered?
