### ISSUE TITLE
`sudo luarocks install` right after `configure && make && sudo make install` targets the local project dir

### ISSUE THREAD

**Issue by hishamhm** [luarocks/luarocks#1639]
From https://github.com/luarocks/luarocks/issues/1425#issuecomment-1988648753 reported by @kjcole :

> I just installed this on Linux following the Quick Start instructions, and had the same thing happen: The instructions end with sudo luarocks install luasocket which created ~/Downloads/luarocks-3.10.0/lua_modules and populated it with files owned by root.
>
> (I'm on an up-to-date Pop! OS 22.04 LTS system with a fresh install of the Lua 5.4 Debian from the Pop! OS / Ubuntu repositories. And it probably goes without saying that I was running the command from the ~/Downloads/luarocks-3.10.0 directory, which is where one would typically end up if following the Quick Start directions.)

**Comment by kjcole** [comment]
@hishamhm If I understand things correctly -- which I often do not -- the goal would be to have the option of not using "`sudo`" on the "`luarocks`" commands and having stuff installed to `~/.luarocks/` in that situation? If that's the case I'll probably use symlinks to put stuff in `~/.local/bin/luarocks` and `~/.local/lib/luarocks` -- or whatever parallel makes sense -- instead.

**Comment by hishamhm** [comment]
@kjcole more or less -- LuaRocks has a mode where you can run `luarocks init` in a folder and it creates a `./lua` and `./luarocks` wrapper that is configured to run locally to that folder (something like an npm project folder or a Python virtualenv). The Makefile was doing that on the sources dir by default, and #1640 removes that.
