### ISSUE TITLE
I can't build mime during luasocket installing

### ISSUE THREAD

**Issue by Enem-20** [luarocks/luarocks#1644]
Platform: Windows
LuaRocks version: 3.10.0

Configuration file was built by command:
`./configure --lua-suffix=jit --with-lua=$luaJITDir --with-lua-include=$luaJITDir/include/luajit-2.1 --with-lua-interpreter=luajit-2.1.1707061634.exe`

Verbosed output of the build in the attached file:
[verbosedBuild.txt](https://github.com/luarocks/luarocks/files/14585426/verbosedBuild.txt)

I've tried to install other mingw versions for compilation. Unfortunetely the issue still appears. Feel free to ask questions about my setup. I am not a professional in this matter and I hope you will be able to direct my thoughts in the right direction.

**Comment by hishamhm** [comment]
Please try the newly released LuaRocks 3.11 and let us know if the issue still persists!

**Comment by Enem-20** [comment]
> Please try the newly released LuaRocks 3.11 and let us know if the issue still persists!

I've tried this release, but I still gets this issue. Luarocks was compiled when I comment assert in 883 line of install.bat file. Probabl this is a problem? Also I've compiled luasocket by changing config-5.1.lua: MSVCRT = "m" to MSVCRT = "ucrt". After that I got 64 bit luasocket in my build folder, but It doesn't work cause this problem:
error loading module 'socket.core' from file '../share/lua/5.1/socket.lua':
        %1 is not a valid Win32 application.

stack traceback:
        [C]: at 0x7ff85ee62d10
        [C]: in function 'require'
        ../share/lua/5.1/socket.lua:12: in main chunk
        [C]: in function 'require'
        .\main.lua:4: in main chunk
        [C]: in function 'require'
        stdin:1: in main chunk
        [C]: at 0x7ff793cd2120
All libraries are 64-bit as the luajit

**Comment by Enem-20** [comment]
Ok, I've fixed this issue by replacing .lua extension in a package.cpath inside my script

**Comment by hishamhm** [comment]
Oh, ok, so it was a configuration issue on your end — good to know! Thanks for reporting back, that allows us to close this.
