### ISSUE TITLE
when using luarocks3.11 config,it goes wrong

### ISSUE THREAD

**Issue by JokerSora** [luarocks/luarocks#1652]
- **Platform:**
  - Windows1021H2

- **LuaRocks version:**
  - `luarocks -3.11`

- **Configuration file:**
variables = {
   LUA = "D:\\LuaDist\\bin\\lua.exe",
   LUA_BINDIR = "D:\\LuaDist\\bin",
   LUA_DIR = "D:\\LuaDist\\bin",
   LUA_LIBDIR = "D:\\LuaDist\\bin"
}

- **LuaRocks output from when the issue occurred:**
 luarocks config lua_dir D:\LuaDist\bin

- **Description:**
```
 Error: LuaRocks 3.11.0 bug (please report at https://github.com/luarocks/luarocks/issues).
Arch.: win32-x86_64 (fs_use_modules = true) (binary)
[string "src/luarocks/cmd/config.lua"]:256: bad argument #1 to 'for iterator' (table expected, got nil)
stack traceback:
        [C]: in function 'next'
        [string "src/luarocks/cmd/config.lua"]:256: in upvalue 'report_on_lua_libdir_config'
        [string "src/luarocks/cmd/config.lua"]:345: in function 'luarocks.cmd.config.command'
        (...tail calls...)
        [C]: in function 'xpcall'
        [string "src/luarocks/cmd.lua"]:765: in function 'luarocks.cmd.run_command'
        [string "luarocks"]:34: in main chunk
        [C]: in ?
```

**Comment by hishamhm** [comment]
Thanks for the report! 

Does the issue only happen when the config file exists? Does it still happen if it does not contain these variables?

As a workaround, does `luarocks config lua_dir D:\LuaDist` (without the `\bin`) work?
