### ISSUE TITLE
Purl specification for Lua (Sofwtare supply chain)

### ISSUE THREAD

**Issue by LaurentGoderre** [luarocks/luarocks#1664]
There is work being done to generate Software Bill Of Material (SBOM) for Docker image containing Lua packages (https://github.com/anchore/syft/pull/2613). As part of this effort, there is a PR to add Lua package type to the Purl specification.  We would appreciate your feedback

https://github.com/package-url/purl-spec/pull/297

**Comment by hishamhm** [comment]
@LaurentGoderre thank you for the ping! I left a comment there.
