### ISSUE TITLE
transfer ownership of lua-vips to a new maintainer

### ISSUE THREAD

**Issue by jcupitt** [luarocks/luarocks#1665]
Hello everyone,

I'm the author of lua-vips, a binding for the libvips image processing library:

https://luarocks.org/modules/jcupitt/lua-vips

I'm no longer using Lua much (sadly), so @rolandlo has very kindly agreed to take over the project.

He's prepared a new version with some great new features and fixes, and now needs to upload a new rock. I was doing uploads with a private luarocks account, but this won't work now that he's taken over the project.

We'd like to transfer module ownership to a new `lua-vips` user which we can pass between maintainers now and in the future. What's the best way to do this?

**Comment by rolandlo** [comment]
Just to clarify, I have already created the `lua-vips` account https://luarocks.org/modules/lua-vips to which the project should be transferred.

**Comment by hishamhm** [comment]
@jcupitt The transfer is done! 

@rolandlo Thank you for having the account ready :)

**Comment by jcupitt** [comment]
Thank you @hishamhm !
