### ISSUE TITLE
assertation failed on 883 line during installing from install.bat

### ISSUE THREAD

**Issue by Enem-20** [luarocks/luarocks#1671]
Plarform: Windows 11
luarocks 3.10.0-3.11.0

I use this batch file to install luarocks from cmake:

```
set script_dir=%CD%
set luarocksDir=%script_dir%/external/luarocks
cd %luarocksDir%
echo %script_dir%
set luarocksBuild=%script_dir%/build/luarocks
echo %luarocksBuild%

set script_build="%script_dir%/build"
set script_include="%script_dir%/build/include"
set script_lib="%script_dir%/build/lib"
set script_bin="%script_dir%/build/bin"
set script_buildLuarocks="%script_dir%/build/luarocks"

call install.bat /F /LUA %script_build% /INC %script_include% /LIB %script_lib% /BIN %script_bin% /MW /NOADMIN /P %script_buildLuarocks%
echo %CD%
cd %luarocksBuild%
call luarocks.bat config variables.MSVCRT ucrt
```

This is 883 line in install.bat file that emits assert:

```
assert(vars.LUA_DIR)
```

This is expected behavior regarding the code. 
There is two places where vars.LUA_DIR could be specified:
1. 663 line - vars.LUA_DIR = directory. Could be specified if one of vars.LUA_BINDIR, vars.LUA_LIBDIR, vars.LUA_INCDIR isn't set. As you can see not true for me.
2. 868 line - vars.LUA_DIR = vars.PREFIX. Could be specified if /L argument provided. Again itsn't my choice.
Regarding this information assertation at 883 line is inevitable. If I just comment this line - works properly. I want to use this repo as submodule in my project and don't want to fork the repo or something like that. Maybe I'm doing something wrong? Please, help me with that.

Also the last one line in my scrpit is needed for my mingw version. I suppose it could be a parameter provided to install.bat from command prompt.

**Comment by hishamhm** [comment]
@Enem-20 should be fixed in `master` now. Feel free to reopen if the problem persists.

> Also the last one line in my scrpit is needed for my mingw version. I suppose it could be a parameter provided to install.bat from command prompt.

PRs welcome :)

**Comment by Enem-20** [comment]
> @Enem-20 should be fixed in `master` now. Feel free to reopen if the problem persists.
> 
> > Also the last one line in my scrpit is needed for my mingw version. I suppose it could be a parameter provided to install.bat from command prompt.
> 
> PRs welcome :)

Thank you for your prompt response! I'll try your solution as soon as I get to work)
