### ISSUE TITLE
Latest lua 5.4.7 RC breaks luarocks configure grep for installed headers

### ISSUE THREAD

**Issue by ferdnyc** [luarocks/luarocks#1685]
- **Platform:**
  - Linux

- **LuaRocks version:**
  - 3.11.1

- **Configuration file:**
  - cannot install

- **LuaRocks output from when the issue occurred:**
  - cannot install

- **Description:**

As [reported on the lua mailing list](https://groups.google.com/g/lua-l/c/xqy9tf9dASQ) by **sur-behoffski**, Lua 5.4.7 (as of the lua-5.4.7-rc3 release candidate) changes the format of the version `#defines` in `lua.h` in a way that breaks the simplistic `grep` in luarocks' `configure` script.

Previously, the `lua.h` header contained a line similar to:

```c
#define LUA_VERSION_NUM 504
```

which matched the 'configure' script's check:

https://github.com/luarocks/luarocks/blob/a51f0bfdfe940200fe77db43103e3065a1cfb030/configure#L431-L441

But `lua-5.4.7-rc3` changes that `#define` to:

```c
#define LUA_VERSION_NUM (LUA_VERSION_MAJOR_N * 100 + LUA_VERSION_MINOR_N)
```

which the `grep` fails to match.

**Comment by CDSoft** [comment]
Hello,

I once used the C preprocessor for this kind of problem.

E.g.:
```sh
( cat lua.h; echo LUA_VERSION_NUM ) | cpp | tail -1 | bc
```
prints `504`

**Comment by hishamhm** [comment]
Thanks @ferdnyc for the report and @CDSoft for the suggestion!

**Comment by hishamhm** [comment]
Per #1686:

> Lua 5.4.7-rc4 was released, which reverted the change in lua.h. (It was not just LuaRocks; apparently various tools reported issues with the change in lua.h.)
> 
> I am going to close this without applying, since I do not find it worth it to add logic just for a shortlived rc3.

Thanks again @ferdnyc for the report and thoughtful feedback.
