### ISSUE TITLE
Cannot upload src rock on 3.11+: API Error

### ISSUE THREAD

**Issue by sewbacca** [luarocks/luarocks#1687]
**Environment**
  - Platform: Windows
  - luarocks v3.11.0 and v3.11.1

**Reproduce:**
  - Upload any rock using `luarocks upload <rockspec>`
  - Observe this error
```
[POST via luasec] /upload ... 
200
Sending ~\Projects\sfs\sfs-0.1.1-1.src.rock ...
[POST via luasec] /upload_rock/144 ... 
400
fs.change_dir_to_root()
fs.delete("C:\\msys64\\tmp\\luarocks_pack-sfs-0.1.1-1-6272060")
Error: API Failed: Filename must be in format `sfs-VERSION.ARCH.rock`
```

**Note:**
- It still uploads the rockspec
- Works under luarocks v3.9.2

**Comment by hishamhm** [comment]
@sewbacca can you give #1689 a try and let me know if that fixes the issue? Thank you!!

**Comment by sewbacca** [comment]
Tested on MSYS2/MinGW, works as expected 👍🏼

**Comment by hishamhm** [comment]
@sewbacca thanks for testing!!

**Comment by mbartlett21** [comment]
@hishamhm 
Are you happy to do a release of luarocks that includes this fix?
