### ISSUE TITLE
Request : helper to trigger a luarock's module from python

### ISSUE THREAD

**Issue by sosie-js** [luarocks/luarocks#1694]
### Please fill out the following:
- **I want to trigger a luarock's module from python**
  -I have a script that dumps vars from Lua side into a config file  to make them available on python side

Hello, I build [a lua rock package and pushed it](https://luarocks.org/modules/sosie-js/peagisub) following [the wonderful article of martin fieber](https://martin-fieber.de/blog/lua-project-setup-with-luarocks/#installing-lua). 

I found now very complicated to pass the env of luarocks from lua to python  to be able to generate the config file on lua side I need on the python side . My os env is not only linux but also Win and Mac.

This will aready works only on unix;
`eval "$(luarocks path --bin)" && lua -l peagisub -e `'os.exit()'`

Is there an other mechanism or session way?

**Comment by sosie-js** [comment]
Problem solved,maybe a wrapper luarorckrun ?

```
import pexpect

import os

child = pexpect.spawn('luarocks path --bin')
LUA_PATH=child.readline()
os.environ['LUA_PATH']=LUA_PATH.decode().split("'")[1]
LUA_CPATH=child.readline()
os.environ['LUA_CPATH']=LUA_CPATH.decode().split("'")[1]
PATH=child.readline()
"""
os.environ['PATH']=LUA_PATH.decode().split("'")[1]
"""
child.close()

import subprocess

result = subprocess.check_output(['lua', '-l', 'peagisub', '-e', 'os.exit()'])
print(result)
```

**Comment by sewbacca** [comment]
What you want to do instead of loading your script as a module is to run it as a command. Set `main.lua` as [a command](https://github.com/luarocks/luarocks/wiki/Rockspec-format#command) in your rockspec instead of a module and then execute `peagisub` as if it was another program (with the correct `PATH`) variable set.

To load environment variables on windows, you need to run this:
```
luarocks path --bin > __temp_env.cmd
__temp_env.cmd
del __temp_env.cmd
```
Your python script looks cleaner though. I dunno if on windows the path variable is escaped with single quotes or rather double quotes though. Use the [`luarocks path --lr-*`](https://github.com/luarocks/luarocks/wiki/path) variants to get unformatted strings instead.

`lua -l peagisub` enters interactive mode precisely because loading a module generally should not have any side effects. It's useful for testing/using a library manually. When you run a script, interactive mode is disabled by default, because the inverse is true.

**Comment by sosie-js** [comment]
By Executing as a module, i don't need to set extra path, i just have make the module accessible in luarock path, so we have (I have not tested on windows nor mac)
```python
import pexpect
import os


"""
  Wrapper to run a lua command with luarocks env available
  cmd : str  command to run 
"""
def run_luarocks_cmd(cmd : str):
    
    #Load luarocks path  so we can reach the module
    child = pexpect.spawn('luarocks path --lr-path')
    os.environ['LUA_PATH']=child.readline().decode()
    child.close()
    
    cmd=cmd.split(" ")
    
    #force quit interactive mode, enabled by default 
    #even if -i is not set. This is a bug imho
    cmd.append("-e")
    cmd.append('os.exit()')
    
    result = subprocess.check_output(cmd)
    return result
    
print(run_luarocks_cmd('lua -l peagisub'))
```

**Comment by sosie-js** [comment]
I reopened the issue, because this time I tried a lua only solution, if I understood well @sewbacca ,
we can use luke as command  ./build-aux/luke lukefile install all
with a lukefile:
```
package  = 'peagisub'
version  = '$USER'

defines  = {
   PACKAGE           = '"$package"',
   VERSION           = '"$version"',
   NDEBUG            = 1,
   _FORTIFY_SOURCE   = 2,
}

modules  = {
   ['peagisub']         = 'src/peagisub.lua',
}

```

and this script as peagisub.lua:
```python
#!/usr/bin/env lua

-----------------------------------------------------------------------------
--  This is the wrapper to our lua library trigger it as a command
--  
--  Part of https://github.com/sosie-js/peagisub-vs
--  Discussion on https://github.com/luarocks/luarocks/issues/1694
--  (c) 2024 Sosie (sosie@sos-productions.com)
--
--  License: MIT/X, 
-----------------------------------------------------------------------------


require("os")

-- Detect os to adjust api
local BinaryFormat = package.cpath:match("%p[\\|/]?%p(%a+)")
if BinaryFormat == "dll" then
   --windows
   -- luarocks install winapi ADVAPI32_DIR=c:\windows\system32 ?
   
   stdlib=require("winapi")
   
    function execute(cmd)
        result= stdlib.execute(cmd)
        return result
   end
   
elseif BinaryFormat == "so" or BinaryFormat == "dylib" then
  --[[Install posix.lib so stdlib.setenv is avaiable
   from sources (in /usr/local/lib/lua/5.1)
      wget https://codeload.github.com/luaposix/luaposix/tar.gz/refs/tags/v36.2.1
      tar xvzf luaposix-36.2.1.tar.gz
      cd luaposix-36.2.1
     ./build-aux/luke lukefile install all
   or from apt
      sudo apt install lua-posix
]]
  posix=require("posix")
  stdlib=posix.stdlib
  
  
  --this works in scite but not in shell
  function execute_io(cmd)
        local handle = io.popen(cmd)
      
         -- reads command output.
        local output = handle:read('*a')
        -- replaces any newline with a space
        local result= output:gsub('[\n\r]', ' ')
        handle:close()
        return result
  end
  
  
--this works in shell
   function popen_nonblock(cmd)
       local files = {}
       local tmpfile = '/tmp/stmp.txt'
       os.execute(cmd..' > '..tmpfile)
        local f = io.open(tmpfile)
       if not f then return files end  
       local k = 1
       for line in f:lines() do
          files[k] = line
          k = k + 1
       end
        f:close()
        return files
     end
   
   function execute(cmd)
        local lines =popen_nonblock(cmd)
        local result=table.concat(lines,"\n")
        return result
    end
   
else
   print("Unsupported OS")
end


--[[
  Wrapper to run a lua command with luarocks env available
  cmd : str  command to run 
]]---
function run_luarocks_cmd(cmd)

    local cmd_rock_path='luarocks path --lr-path'
    local LUA_PATH = assert(execute(cmd_rock_path))
    local LUA_PATH2=execute_io(cmd_rock_path)
    assert(LUA_PATH,LUA_PATH2)
    
    stdlib.setenv("LUA_PATH", LUA_PATH)
    assert( os.getenv("LUA_PATH") == LUA_PATH)
    --package.path = package.path .. ';' .. LUA_PATH
    --package.cpath = package.cpath .. ';' .. LUA_CPATH
    return execute(cmd)
end


print(run_luarocks_cmd('lua -l peagisub'))
```

the main problem is when we trigger lua -l peagisub -e "os.exit()", it enters into interactive mode and did not exit.
control-c show it succeed to print as if it was freezed. There is a global problem that still seemed unsolved around io.popen() ...

**Comment by sosie-js** [comment]
Now it's documented in [my module with graphs](https://github.com/sosie-js/peagisub-vs/blob/1.3.0/doc/Usage.md).

**Comment by sewbacca** [comment]
In the script you provided:
```lua
--[[
  Wrapper to run a lua command with luarocks env available
  cmd : str  command to run 
]]---
function run_luarocks_cmd(cmd)

    local cmd_rock_path='luarocks path --lr-path'
    local LUA_PATH = assert(execute(cmd_rock_path))
    local LUA_PATH2=execute_io(cmd_rock_path)
    assert(LUA_PATH,LUA_PATH2)
    
    stdlib.setenv("LUA_PATH", LUA_PATH)
    assert( os.getenv("LUA_PATH") == LUA_PATH)
    --package.path = package.path .. ';' .. LUA_PATH
    --package.cpath = package.cpath .. ';' .. LUA_CPATH
    return execute(cmd)
end


print(run_luarocks_cmd('lua -l peagisub'))
```

You omitted appending `-e 'os.exit()'`. Is that the problem?

**Comment by sosie-js** [comment]
> In the script you provided:
> 
> ```lua
> --[[
>   Wrapper to run a lua command with luarocks env available
>   cmd : str  command to run 
> ]]---
> function run_luarocks_cmd(cmd)
> 
>     local cmd_rock_path='luarocks path --lr-path'
>     local LUA_PATH = assert(execute(cmd_rock_path))
>     local LUA_PATH2=execute_io(cmd_rock_path)
>     assert(LUA_PATH,LUA_PATH2)
>     
>     stdlib.setenv("LUA_PATH", LUA_PATH)
>     assert( os.getenv("LUA_PATH") == LUA_PATH)
>     --package.path = package.path .. ';' .. LUA_PATH
>     --package.cpath = package.cpath .. ';' .. LUA_CPATH
>     return execute(cmd)
> end
> 
> 
> print(run_luarocks_cmd('lua -l peagisub'))
> ```
> 
> You omitted appending `-e 'os.exit()'`. Is that the problem?

Yes a part of the problem, flushing print 

io.stdout:setvbuf("no")
print(run_luarocks_cmd("lua -l peagisub -e 'os.exit()'"))
io.stdout:flush()
os.exit(0)

I discovered also that lua-posix  shipped by ubuntu/debian  has a flaw in stdlib namepace.
if I install the latest with luarock it fixed the blocking problem.
