### ISSUE TITLE
Windows install script sets incorrect runtime if lua was linked against UCRT

### ISSUE THREAD

**Issue by tobil4sk** [luarocks/luarocks#1697]
- **Platform:** Windows, **LuaRocks version:**  3.8.0

- **LuaRocks output from when the issue occurred:**
This is the relevant part of the install.bat output:
```
Headers found, checking runtime to use...
*** WARNING ***: could not analyse the runtime used, defaulting to MSVCR80
Runtime check completed.
```

- **Description:**
  - I ran into this error in a windows-2022 environment on github actions, while using hererocks (`hererocks lua_install -r^ --lua=5.4 --verbose`). Lua binaries that are built with VS 2022 seem to not be linked against any msvcrt.dll file, so the install script reverts to MSVCRT80: https://github.com/luarocks/luarocks/blob/f87568a7cba69e2c19411e7a2b73016c80a14a3b/install.bat#L406
  - This means that the config is set with `variables.MSVCRT = "MSVCR80"`, so this is the library that is linked against. I ran into a problem where a library would fail to load with `require` because of this dll being linked: https://github.com/lunarmodules/luafilesystem/issues/149
  - I did some debugging, these are the dlls that pe-parser.lua does see:
```
KERNEL32.dll
api-ms-win-crt-convert-l1-1-0.dll
api-ms-win-crt-environment-l1-1-0.dll
api-ms-win-crt-filesystem-l1-1-0.dll
api-ms-win-crt-heap-l1-1-0.dll
api-ms-win-crt-locale-l1-1-0.dll
api-ms-win-crt-math-l1-1-0.dll
api-ms-win-crt-private-l1-1-0.dll
api-ms-win-crt-runtime-l1-1-0.dll
api-ms-win-crt-stdio-l1-1-0.dll
api-ms-win-crt-string-l1-1-0.dll
api-ms-win-crt-time-l1-1-0.dll
lua53.dll
KERNEL32.dll
api-ms-win-crt-convert-l1-1-0.dll
api-ms-win-crt-environment-l1-1-0.dll
api-ms-win-crt-filesystem-l1-1-0.dll
api-ms-win-crt-heap-l1-1-0.dll
api-ms-win-crt-locale-l1-1-0.dll
api-ms-win-crt-math-l1-1-0.dll
api-ms-win-crt-private-l1-1-0.dll
api-ms-win-crt-runtime-l1-1-0.dll
api-ms-win-crt-stdio-l1-1-0.dll
api-ms-win-crt-string-l1-1-0.dll
api-ms-win-crt-time-l1-1-0.dll
api-ms-win-crt-utility-l1-1-0.dll
```

**Comment by Tieske** [comment]
the `api-ms-win-crt-xxx` files indicate it uses the universal runtime, which `pe-parser` doesn't recognize. Here's the PR against `pe-parser`: https://github.com/Tieske/pe-parser/pull/7 I created recently.

**Comment by Tieske** [comment]
the main runtime is called `ucrtbase.dll` (or `ucrtbased.dll` for the debug version).

Here's what chatgpt has to offer on the subject:

> The main DLL that applications link to when using the Universal CRT is ucrtbase.dll. The specific DLLs you mentioned (e.g., api-ms-win-crt-convert-l1-1-0.dll, api-ms-win-crt-environment-l1-1-0.dll, etc.) are part of the UCRT and are used internally by ucrtbase.dll.

**Comment by tobil4sk** [comment]
> Here's the PR against pe-parser: https://github.com/Tieske/pe-parser/pull/7 I created recently.

I can confirm that updating the bundled pe-parser here to v0.6 fixes the issue: https://github.com/luarocks/luarocks/pull/1699

Unfortunately, I can only get it to work if I apply this patch to luarocks v3.9.2. With any version from v3.10.0 to master I run into this issue: 

```
Error: Failed finding the Lua library. You can use `luarocks config variables.LUA_LIBDIR <path>` to set the correct location.
```

Running `luarocks` also gives this:
```
      LUA_LIBDIR : D:\a\lua-simdjson\lua-simdjson\lua_install\lib (Lua library
      itself not found)
                   ****************************************
                   Use the command

                      luarocks config variables.LUA_LIBDIR <dir>

                   to fix the location
                   ****************************************
```
With previous versions of luarocks it seems to have used `D:\a\lua-simdjson\lua-simdjson\lua_install\bin` as the default here.
