### ISSUE TITLE
Winget official package

### ISSUE THREAD

**Issue by Andre-LA** [luarocks/luarocks#1717]
Winget is the official package manager from Windows and it's preinstalled already on Windows 11 and I believe on Windows 10 too?

With it, you can install, say, Ninja, with [just one command on powershell](https://github.com/ninja-build/ninja/wiki/Pre-built-Ninja-packages#windows):

`winget install Ninja-build.Ninja`

It would be very cool if we could install luarocks (and Lua by extension I suppose) with a command like

`winget install luarocks.luarocks`

And thus, making luarocks tooling more easily available.

**Comment by alerque** [comment]
I'm sure such a thing would be welcome, but the developers on this repository don't need to be responsible for it. I think the place you need to raise an issue is [winget-pkgs](https://github.com/microsoft/winget-pkgs):

> This repository contains the manifest files for the Windows Package Manager default source. You are highly encouraged to submit manifests for your favorite application.

**Comment by djmattyg007** [comment]
@alerque The reason why it's desirable for the maintainers of the software to be responsible for maintaining the winget package is so that it's kept up to date with automation. It's not strictly required, but it is highly desirable.
