### ISSUE TITLE
Missing multiarch support in cfg.lua

### ISSUE THREAD

**Issue by rrthomas** [luarocks/luarocks#333]
The line

```
   lib_modules_path = "/lib/lua/"..cfg.lua_version,
```

needs multiarch support. You should be able to use `MULTIARCH_SUBDIR` here.

**Comment by hishamhm** [comment]
Can't look at this right now. Could you submit a patch? Thank you!

**Comment by hishamhm** [comment]
`lib_modules_path` can be overridden by the user via configuration. Nowadays this is even possible from the CLI:

```
luarocks config lib_modules_path /lib/<multiarch>/lua/5.3
```

Not sure it's feasible to make this change automatically because it varies by distro (and not everyone wants multiarch subdirs in their rocks trees, especially for non-`system` ones).

**Comment by rrthomas** [comment]
Thanks for this!
