### ISSUE TITLE
Setting to auto-retry downloading a rock

### ISSUE THREAD

**Issue by subnetmarco** [luarocks/luarocks#338]
The default repository is sometimes not very responsive, and `luarocks install` encounters errors like:

```
Error: Failed installing dependency: https://rocks.moonscript.org/ansicolors-1.0.2-3.src.rock - Could not fetch rock file: Error fetching file: Failed downloading https://rocks.moonscript.org/ansicolors-1.0.2-3.src.rock
```

It would be nice if LuaRocks had a setting to retry downloading a rock for `n` times adding a `t` delay between each request.

**Comment by hishamhm** [comment]
Closing this because nowadays LuaRocks supports mirrors
