### ISSUE TITLE
Changing the standard umask in the .profile breaks $ luarocks install

### ISSUE THREAD

**Issue by forflo** [luarocks/luarocks#372]
# Description

If you start your bash with the umask "0077" instead of the standard "0022", luarocks does not automatically adjust the file permission bits. As a consequence, rocks that'll be installed 
this way, won't work.
# Steps to reproduce

```
umask 0077
sudo luarocks install <some rock>
lua < <(echo "r = require[[<some rock>]]")
```
# My current System

Archlinux (latest build)
Latest Version of Luarocks (2.2.2)
Lua 5.3.0

**Comment by siffiejoe** [comment]
There was also [this error][1] some time ago. Maybe LuaRocks *should* explicitly set permissions.

  [1]: http://lua-users.org/lists/lua-l/2014-11/msg00179.html

**Comment by forflo** [comment]
Yes, that would be very helpful! No, sorry, let me put this right: Luarocks must set the right permissions no matter how it's env is configured, because it isn't very uncommon to set umask to a more restricted mode!

**Comment by tomasguisasola** [comment]
My installation uses `umask 0002` among the few developers of the project and we install all rocks in the same directory in order to allow the system be updated by any of us.  But LuaRocks is not respecting the _umask_ and the rocks are being installed with a 755 permission.

**Comment by hishamhm** [comment]
@tomasguisasola What was the expected permissions? I always get confused by `umask` settings. Did you intend for it to be 775 instead?

**Comment by tomasguisasola** [comment]
Yes, 775.  `umask` defines the inverse of what you mean...  Is there a way I can fix this?

**Comment by hishamhm** [comment]
Got it. There is a hardcoded "755" in the LuaRocks source code. If you patch that to "775" I think you'll get the behavior you want, and in theory there's code there to ensure it should still respect a stricter umask (i.e. LuaRocks should honor the umask correctly, whether you use `002` or `022`).

It would be great if you could test that change with different umask values and let me know if just changing 755 to 775 there is sufficient to get the correct behavior. Then I can push that change for the next release.

**Comment by tomasguisasola** [comment]
It worked!

I changed 2 lines in function `tools.set_permissions` in file `luarocks/fs/unix/tools.lua`.  One for the "644" -> "664" and the other for the "755" -> "775".

Anyway, why LuaRocks does not respect the user's configuration?  Is this somewhat tricky?

**Comment by hishamhm** [comment]
> Anyway, why LuaRocks does not respect the user's configuration? Is this somewhat tricky?

No, I was just being too protective by default. LuaRocks does apply your umask, but 002 on top of a 755 means that `(755 | ~002 ) = 755`. If your umask was 077, LuaRocks would set it to 700.

I guess in theory the LuaRocks codebase could even say "777" and fully leave it to the umask, so that `(777 | ~002 ) = 775` and `(777 | ~022) = 755`, but I think "775" might be a more cautious setting, since a umask of 000 is most likely a mistake.

**Comment by tomasguisasola** [comment]
I get your point.  Anyway, I would suggest LuaRocks could be configured to allow a "777" permission to work.

**Comment by hishamhm** [comment]
PR #1673 should fix this issue, as it now honors all umask bits.
