### ISSUE TITLE
LDFLAGS ?

### ISSUE THREAD

**Issue by daurnimator** [luarocks/luarocks#429]
It appears that luarocks does not respect LDFLAGS.
==> you can set them in the config file, but they aren't use for e.g. the built-in backend.

**Comment by daurnimator** [comment]
The the lua workshop this year @hisham mentioned `LIBFLAG` as the solution.

**Comment by alerque** [comment]
Any progress / workarounds for this? Just bumped into it myself with a project that has a garbage Makefile but the rockspec specifies `builtin` as the built time. The build works fine but doesn't respect LDFLAGS, the Makefile has a way to pass the flags but is just chaos in other respects.

**Comment by daurnimator** [comment]
I think the workaround is to use `LIBFLAG="$LDFLAGS -shared"`
e.g. from PKGBUILD for luaossl:
```shell
    luarocks make --pack-binary-rock --lua-version="$v" --deps-mode=none \
      CFLAGS="$CPPFLAGS $CFLAGS -fPIC" \
      LIBFLAG="$LDFLAGS -shared" \
      ../luaossl-"$pkgver"-0.rockspec
```

**Comment by alerque** [comment]
Thanks @daurnimator, that does indeed work as expected. I suppose this bug report should be left open for it to be fixed because just respecting LDFLAGS in the first place seems like the right thing to do. If for some reason that isn't going to happen this workaround could at least be documented.

**Comment by alerque** [comment]
Thanks for this @hishamhm! It will cleanup quite a bit of distro packaging and reduce errors along the way.

**Comment by alerque** [comment]
Gentle nudge, it would be useful to have this in an official tagged release so we can use it for distro packaging without having to patch it in ourselves.

**Comment by hishamhm** [comment]
@alerque I'm shooting for a release this week, I'll get it done within the next couple of days!
