### ISSUE TITLE
Luarocks always fails when I try to install a package

### ISSUE THREAD

**Issue by r-nikhil** [luarocks/luarocks#515]
[This](http://pastebin.com/44UN1iiq) is the output when I try to install "sailor" for example. I resorted to downloading the packages manually and then executing "luarocks make".  I don't get the error when I try to install using a rockspec.

**Comment by ignacio** [comment]
What is the output of `luarocks config --lua-ver` ?

**Comment by rnikhil275** [comment]
5.2

**Comment by ignacio** [comment]
Ok, so you are using a Lua version supported by Sailor.

Let's try `luarocks search sailor --verbose` and paste the output. It seems that it is failing to communicate with the main rocks repository.

**Comment by rnikhil275** [comment]
Yes. It does. I thought it was something to do with curl certificate issue but in spite of fixing that, it fails. 
[This](http://pastebin.com/K2LtP9ZQ) the output you asked for

**Comment by Etiene** [comment]
What's your luarocks version?

**Comment by rnikhil275** [comment]
The latest one. 2.3.0

**Comment by ignacio** [comment]
What is the output of `curl -k -L --user-agent 'LuaRocks/2.3.0 linux-x86_64 via curl' --connect-timeout 30 'https://luarocks.org/manifest-5.2.zip'` ?

**Comment by rnikhil275** [comment]
It mostly garbage and illegible text. Do you think it has something to do with the encoding support ?

**Comment by ignacio** [comment]
Uhm, so curl is working and downloading the manifest just fine. Do you have `unzip` in your path?

**Comment by rnikhil275** [comment]
Yes I do

Date: Fri, 11 Mar 2016 11:13:51 -0800

**Comment by rnikhil275** [comment]
I am going to try a clean install of lua/luarocks now. Hopefully that solves the problem

**Comment by siffiejoe** [comment]
Maybe a permission problem with the cache. Try again after a `rm -rf ~/.cache/luarocks`.

**Comment by rnikhil275** [comment]
I have tried that already. It didn't work. It creates all the necessary files (zips and mainfest) but they are all of  0 bytes. Nothing actually gets downloaded

**Comment by rnikhil275** [comment]
Installing luasec seems to have solved the problem
