### ISSUE TITLE
Failed unpacking rock file

### ISSUE THREAD

**Issue by arkenidar** [luarocks/luarocks#538]
While trying to make Lapis work on Windows.

luarocks install lapis
gives
Error: Failed unpacking rock file

This should not happen.

I am using Windows 7 64 bit
Lua was installed with LuaForWindows_v5.1.4-46.exe (includes luarocks 2.0,2)

FYI for the interested: http://pan.baidu.com/s/1eR1bR9o (to download Openresty_For_Windows_1.9.12.1001_32Bit.zip) should allow running openresty (and then lapis) on MS Windows systems. I'll check this as soon as possible, when lapis will be installed.

**Comment by ignacio** [comment]
2.0.2 is rather old, and a lot has improved in recent releases regarding the Windows platform. Can you try again after installing 2.3.0 ?

**Comment by arkenidar** [comment]
I already tried to install latest (2.3.0) luarocks, but scripts failed.
Should I open another issue for this errors I got? (one case was successful install BUT without version advancement and another was errors in installation with recursive opening of shells!)

**Comment by mpeterv** [comment]
>Should I open another issue for this errors I got?

Please do, if you get 2.3.0 to work most likely this bug will go away, too.
