### ISSUE TITLE
LR is not CTRL+C friendly

### ISSUE THREAD

**Issue by agladysh** [luarocks/luarocks#54]
More than once we had seen corrupted manifest files if we pressed ctrl+c in the middle of rock installation. This is a recurring problem in our case, as our build scripts run LR quite intensively, and people tend to press CTRL+C to stop them if something is wrong. I will collect and provide more detailed diagnostics if necessary.

To fix that, LR should generate all its files in a temporary directory, then atomically move them atop the existing ones.

**Comment by hishamhm** [comment]
> has the fix by @hishamhm helped resolve your issue? if so can this one be closed?

I guess 6.5 years is a good enough timeout :)
