### ISSUE TITLE
Update bundled 7zip for Windows.

### ISSUE THREAD

**Issue by siffiejoe** [luarocks/luarocks#565]
Apparently, there have been fixes for serious security flaws in 7zip. Since we are preparing a new release anyway, it's probably a good idea to update the bundled 7zip binaries to a version that has those bugs fixed.

http://blog.talosintel.com/2016/05/multiple-7-zip-vulnerabilities.html

While we are at it, maybe there is other bundled software that could/should be updated?! (The OpenSSL DLLs seem likely candidates ...)

**Comment by mpeterv** [comment]
Could also upgrade Lua 5.1.4 to 5.1.5 while we are at it.

**Comment by daurnimator** [comment]
Closing this as the current 7z version bundled in the zips is 18.01. (Possibly via #777?)
