### ISSUE TITLE
Update bundled for Windows Lua to 5.1.5

### ISSUE THREAD

**Issue by mpeterv** [luarocks/luarocks#571]
Right now Lua 5.1.4 is bundled. It's not critical to upgrade it, but it does have some bugs fixed. Additionally, it would be great to have some build steps saved in `win32`, or even a build script so that upgrade can be automated.

**Comment by Stanzilla** [comment]
The sad thing is that the Lua for Windows project is pretty much unmaintained and is shipping really old 3rd party binaries, maybe switching to something else would be better.

**Comment by xpol** [comment]
I have working on a prebuilt binary package with multiple Lua versions for windows 32 and 64 bit.

https://github.com/xpol/luavm/releases

**Comment by hishamhm** [comment]
@mpeterv Moreso, I think it's more of an accident that we ship with Lua 5.1 only — that was current when I worked on the original win32.zip, and nobody ever upgraded to Lua 5.2+. I wouldn't even mind shipping all three.

Appveyor has an "artifacts" feature, so we could use it build it (them?) there and produce binary packages of tagged releases.

**Comment by Stanzilla** [comment]
@hishamhm could we get this fixed please?

**Comment by hishamhm** [comment]
Done in 2.4.4.
