### ISSUE TITLE
OpenSSL on MacOSX

### ISSUE THREAD

**Issue by FuriouslyCurious** [luarocks/luarocks#579]
I am using MacOSX.  When I try to install rocks for LuaSec or Lua-openssl or Luacrypto, they all fail citing missing OpenSSL.  

I manually passed OPENSSL_DIR parameter with correct link to OpenSSL binary, but install still fails.

The only workaround I found was to install brew, and do "brew link openssl --force" to create 1600 symlinks before everything works as expected.  Is there any way to remove the brew step?

**Comment by daurnimator** [comment]
Related: https://github.com/daurnimator/lua-http/issues/34

**Comment by mpeterv** [comment]
I looked through related issues in lua-http and luaossl and they are mostly about incorrect linking flags luarocks uses as opposed to luarocks not finding openssl at all. Can you show which commands you've tried and what output is? If you are not using luarocks 2.3.0 try to upgrade to it, it has better messages for missing external dependencies.

**Comment by daurnimator** [comment]
> luarocks not finding openssl at all.

OSX no longer ships openssl headers by default; yet still ships the library (but only version 0.9.8)
If you install openssl via brew, it will install openssl 1.0 both library and headers.

Watch out when you use luarocks though: many people seem to come to me with issues where it turns out they used the openssl 1.0* headers; but are attempting to use the 0.9.8 library that shipped with OSX. IIRC this was due to luarocks not treating LDFLAGS specially? Using `brew link --force` is a workaround for this.

**Comment by mpeterv** [comment]
> IIRC this was due to luarocks not treating LDFLAGS specially?

With which build backend? What's the rockspec? What command does luarocks use when building? What's the expected good command? I don't have a Mac so I can't try it myself.

**Comment by daurnimator** [comment]
> I don't have a Mac so I can't try it myself.

neither do I so I can't test :P

**Comment by campbx** [comment]
I can check anything you guys need and report back the findings.

**Comment by mpeterv** [comment]
@campbx great. For starters, upgrade to Luarocks 2.3.0 if you haven't already and show the commands that you tried and their output. E.g. `luarocks install luasec` and `luarocks install luasec OPENSSL_DIR=<parameter you tried`.

**Comment by robooo** [comment]
What I get 
`
.
.
.
src/ssl.c:827:3: warning: 'SSL_load_error_strings' is deprecated: first deprecated in OS X 10.7
      [-Wdeprecated-declarations]
  SSL_load_error_strings();
  ^
/usr/include/openssl/ssl.h:1432:6: note: 'SSL_load_error_strings' has been explicitly marked
      deprecated here
void    SSL_load_error_strings(void ) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
        ^
61 warnings generated.
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/include -c src/luasocket/buffer.c -o src/luasocket/buffer.o -I/usr/include -Isrc/ -Isrc/luasocket
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/include -c src/luasocket/io.c -o src/luasocket/io.o -I/usr/include -Isrc/ -Isrc/luasocket
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/include -c src/luasocket/timeout.c -o src/luasocket/timeout.o -I/usr/include -Isrc/ -Isrc/luasocket
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/include -c src/luasocket/usocket.c -o src/luasocket/usocket.o -I/usr/include -Isrc/ -Isrc/luasocket
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -bundle -undefined dynamic_lookup -all_load -o ssl.so -L/usr/local/lib src/x509.o src/context.o src/ssl.o src/luasocket/buffer.o src/luasocket/io.o src/luasocket/timeout.o src/luasocket/usocket.o -L/usr/lib -Wl,-rpath,/usr/lib: -lssl -lcrypto
Updating manifest for /usr/local/lib/luarocks/rocks-5.2
luasec 0.6-1 is now built and installed in /usr/local (license: MIT)
`


`
luarocks install luasec OPENSSL_DIR=/opt/local/
Installing https://luarocks.org/luasec-0.6-1.rockspec...
Using https://luarocks.org/luasec-0.6-1.rockspec... switching to 'build' mode
Cloning into 'luasec'...
remote: Counting objects: 116, done.
remote: Compressing objects: 100% (93/93), done.
remote: Total 116 (delta 33), reused 76 (delta 22), pack-reused 0
Receiving objects: 100% (116/116), 68.52 KiB | 0 bytes/s, done.
Resolving deltas: 100% (33/33), done.
Checking connectivity... done.
Note: checking out '20443861ebc3f6498ee7d9c70fbdaa059bec15e1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/include -c src/x509.c -o src/x509.o -I/opt/local/include -Isrc/ -Isrc/luasocket
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/include -c src/context.c -o src/context.o -I/opt/local/include -Isrc/ -Isrc/luasocket
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/include -c src/ssl.c -o src/ssl.o -I/opt/local/include -Isrc/ -Isrc/luasocket
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/include -c src/luasocket/buffer.c -o src/luasocket/buffer.o -I/opt/local/include -Isrc/ -Isrc/luasocket
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/include -c src/luasocket/io.c -o src/luasocket/io.o -I/opt/local/include -Isrc/ -Isrc/luasocket
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/include -c src/luasocket/timeout.c -o src/luasocket/timeout.o -I/opt/local/include -Isrc/ -Isrc/luasocket
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/include -c src/luasocket/usocket.c -o src/luasocket/usocket.o -I/opt/local/include -Isrc/ -Isrc/luasocket
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -bundle -undefined dynamic_lookup -all_load -o ssl.so -L/usr/local/lib src/x509.o src/context.o src/ssl.o src/luasocket/buffer.o src/luasocket/io.o src/luasocket/timeout.o src/luasocket/usocket.o -L/opt/local/lib -Wl,-rpath,/opt/local/lib: -lssl -lcrypto
Updating manifest for /usr/local/lib/luarocks/rocks-5.2
luasec 0.6-1 is now built and installed in /usr/local (license: MIT)
`

**Comment by roachmd** [comment]
This seem to work for me when trying to get Lapis installed.

luarocks-5.1 install luaossl CRYPTO_INCDIR=/usr/local/opt/openssl/include/ OPENSSL_DIR=/usr/local/opt/openssl/ --local

**Comment by decadent** [comment]
Might also need to tack OPENSSL_DIR and OPENSSL_INCDIR on there, with the same paths.

**Comment by abuisman** [comment]
This did it for me:

luarocks install luaossl CRYPTO_INCDIR=/opt/homebrew/opt/openssl@3.2/include OPENSSL_DIR=/opt/homebrew/opt/openssl@3.2 CRYPTO_DIR=/opt/homebrew/opt/openssl@3.2/lib --local
