### ISSUE TITLE
Use versioned manifest file.

### ISSUE THREAD

**Issue by moteus** [luarocks/luarocks#611]
I play with LR with multiple Lua vesions. It works fine except manifest file.
Is it possible use same rock tree to store modules for several Lua versions?

I run 3 environment. All use same LuaRocks (c:/luarocks/x86/LuaRocks) but with separate
`config-*.lua` and `site_config_*.lua` files.
All works well if using separate trees. e.g. `c:/luarocks/x86/5.1/systree`, `c:/luarocks/x86/5.2/systree` and `c:/luarocks/x86/5.3/systree`. But if I try use same tree folder like `c:/luarocks/x86/systree` I have problems. This is my configurations:

```
CONFIGURATION
        Lua version: 5.1
        Configuration files:
                System: c:/luarocks/x86/LuaRocks/config-5.1.lua (ok)
                User  : C:/Users/alexey/AppData/Roaming/luarocks/config-5.1.lua (not found)

        Rocks trees in use:
                C:/Users/alexey/AppData/Roaming/5.1/luarocks ("user")
                c:/luarocks/x86/systree ("system")
```

```
CONFIGURATION
        Lua version: 5.2
        Configuration files:
                System: c:/luarocks/x86/LuaRocks/config-5.2.lua (ok)
                User  : C:/Users/alexey/AppData/Roaming/luarocks/config-5.2.lua (not found)

        Rocks trees in use:
                C:/Users/alexey/AppData/Roaming/5.2/luarocks ("user")
                c:/luarocks/x86/systree ("system")
```

```
CONFIGURATION
        Lua version: 5.3
        Configuration files:
                System: c:/luarocks/x86/LuaRocks/config-5.3.lua (ok)
                User  : C:/Users/alexey/AppData/Roaming/luarocks/config-5.3.lua (not found)

        Rocks trees in use:
                C:/Users/alexey/AppData/Roaming/5.3/luarocks ("user")
                c:/luarocks/x86/systree ("system")
```

Suppose I install `lfs` for Lua 5.1. But if I call `luarocks show luafilesystem` for Lua 5.2 I got

```
Installed in:   c:\luarocks\x86\systree
Modules:
        lfs (c:\luarocks\x86\systree/lib/lua/5.2/lfs.dll)
Depends on:
        lua >= 5.1 (using 5.2-1)
```

Ok. I try rename `manifes` to `manifest-5.1`. Now seems all works. LuaRocks for Lua 5.1 display LuaFileSystem and  LuaRocks for Lua 5.2 display no modules. But after I install any module to Lua 5.2 (e.g. lbase64). New manifest file creates and this new manifest file has luafilesystem module. So now when I call `luarocks list` for Lua 5.2 I got

```
Installed rocks:
----------------
lbase64
   20120807-3 (installed) - c:/luarocks/x86/systree/lib/luarocks/rocks
luafilesystem
   1.6.3-2 (installed) - c:/luarocks/x86/systree/lib/luarocks/rocks
```

But all files stored correctly

```
c:\luarocks\x86\systree\lib\lua\5.1\lfs.dll
c:\luarocks\x86\systree\lib\lua\5.2\base64.dll
```

Also any new changes does not touch `manifest-*` files, but just create new `manifest` file.

**Comment by hishamhm** [comment]
What directory is the `manifest` file being stored in on Windows? 

On my GoboLinux system, when I run `luarocks config --rock trees`, it says

```
/Users/hisham/.luarocks	user
/System/Aliens/LuaRocks	system
```

and this means my `system` manifest is in `/System/Aliens/LuaRocks/lib/luarocks/rocks-5.3/manifest`, so the problem you described doesn't happen. (It's not just the "manifest" that shouldn't conflict, the contents of "rocks-5.x" too, so they need to be separate directories.)

What are the contents of your config-5.1.lua and site_config_5.1.lua files? It looks like the directory structure is "too flat".

**Comment by moteus** [comment]
For test I try use same directory for all version. 
I thought it possible because LuaRocks put mudules to vesioned directory 
```
c:\luarocks\x86\systree\lib\lua\5.1\lfs.dll
c:\luarocks\x86\systree\lib\lua\5.2\base64.dll
```
My system tree for all Lua version is `c:\luarocks\x86\systree`
But problem that luarocks uses not versioned manifest file.
And yes It also stores some other stuff without version
```
c:\luarocks\x86\systree\lib\luarocks\rocks\manifest
```
If I use separate paths for systree all works fine. This is [working config](https://github.com/moteus/lua-windows-environment/blob/master/luarocks/x86/LuaRocks/config-5.1.lua). I try make somethink like portable version of LuaRocks to be able easy install on windows system.

I just think it may works with single tree directory.

**Comment by hishamhm** [comment]
c:\luarocks\x86\systree\lib\luarocks\rocks\manifest

This should have been 

   c:\luarocks\x86\systree\lib\luarocks\rocks-5.1\manifest

Under Unix, `configure` accepts a `--versioned-rocks-dir` flag, and it detects the presence of an existing installation and then uses a versioned dir to avoid conflicts.

For LuaRocks 3, we need to move to always versioned.

**Comment by Alloyed** [comment]
Food for thought: this could be used not only to install different versions of lua side-by-side, but different compile targets/architectures as well, by stuffing extra target info into the version. So instead of having
* lib/lua/5.1
you'd have
* lib/lua/5.1_x86
or getting more complex, something like
* lib/lua/5.1_jit_android_arm

**Comment by hishamhm** [comment]
lib/lua/5.1/ is a Lua standard, defined by the vanilla Lua interpreter. They don't set a lot of standards, so we better follow the few ones that they do set.

**Comment by ildar** [comment]
@Alloyed , on arch-suffixing: you're wrong. Actually UNIX (in [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) ) already divides arch-dependent files higher in fs, e.g. `/usr/lib64/lua/5.1` versus `/usr/lib/lua/5.1` for x86_64 versus x86 (32 bit).

**Comment by ildar** [comment]
@moteus , you missed another problem in your single-LR-tree setup: `rock_manifest` file in every rock has file list and hash-sums that's incompatible with multi-Lua usage - it has to be versioned just like the LR-root manifest file.

**Comment by hishamhm** [comment]
@ildar when the `rocks` subdir is versioned, each rock gets its own `rock_manifest` file:

```
c:\luarocks\x86\systree\lib\luarocks\rocks-5.1\luazip\1.2.4-1\rock_manifest
c:\luarocks\x86\systree\lib\luarocks\rocks-5.3\luazip\1.2.4-1\rock_manifest
```

so no need to have those versioned.

**Comment by ildar** [comment]
I wrote about @moteus 's case: single systree in multi Lua environment
