### ISSUE TITLE
config-5.1.lua (not found)

### ISSUE THREAD

**Issue by Alek-dr** [luarocks/luarocks#614]
CONFIGURATION
    Lua version: 5.1
    Configuration files:
        System: /home/alexander/torch/install/etc/luarocks/config.lua (ok)
        User  : /home/alexander/.luarocks/config-5.1.lua (not found)

```
Rocks trees in use: 
    /home/alexander/.luarocks
    /home/alexander/torch/install
```

I can't install packages and think that is reason  - config-5.1.lua (not found)
If I try ti install something
Error: No results matching query were found.

**Comment by xiahaoyun** [comment]
I meet this,too

**Comment by mpeterv** [comment]
I don't thin that missing config for local tree can be a reason for that error. The error typically means that the package you are trying to install either doesn't exist or doesn't support your version of Lua (5.1) in this case. Which packages exactly are you trying to install?

**Comment by dragonxtek** [comment]
you can search the file in your system with locate. I found it in **/etc/luarocks/config.lua**
After, create the folder with **mkdir ~/.luarock**
Now, copy/paste the file in the path **sudo cp /etc/luarocks/config.lua ~/.luarocks/config-5.1.lua**

**Comment by hishamhm** [comment]
That works, but it's usually not necessary unless you want to modify your configuration and you don't have root permissions.

The "not found" message simply means that a user-specific configuration does not exist, it is not an error.
