### ISSUE TITLE
Install shortcut for user manifests

### ISSUE THREAD

**Issue by leafo** [luarocks/luarocks#619]
We talked about adding user namespacing for package names on gitter the other day. It seemed like the minimal thing we could do without interrupting existing process is add a shortcut for installing from a user's personal manifest on luarocks.org.
## Manifest URLs

Right now the global manifest is available here:
https://luarocks.org/manifest
https://luarocks.org/dev/manifest
https://luarocks.org/manifest-5.3
https://luarocks.org/dev/manifest-5.3
etc.

A user's personal manifest is available here:
https://luarocks.org/manifests/leafo/manifest
https://luarocks.org/manifests/leafo/manifest-5.3
etc.

There currently isn't a dev variant for user manifests, but it shouldn't be difficult to set up on my end.
## Install command changes

Ideally we should be able to run install with some prefix on the module name that switches to the user's manifest from the root manifest. I'm not sure how this would affect people using custom manifest locations, would we always just map:

```
/manifest -> /manifests/leafo/manifest
```

Or would we disable the option when not using luarocks.org as source.

As for the update to install, I propose something like this:

```
luarocks install leafo/moonscript
```

Other options for `/` include `:` `@`, etc. We just need to make sure we don't use a valid package name character. Usernames on luarocks.org are guaranteed to be ascii, including characters `[0-9a-zA-Z_-]`.
## Install location

The package should install using the name in the manifest. The user name doesn't affect the installed name at all. It should work as if you manually specified the manifest in the command line argument.
## Dependencies

Should dependencies be fetched from the user manifest as well? If dependencies are available in both user and default manifest, which should take precedence? I think the user manifest should be available for dependencies, and it should take precedence over the default manifest.

**Comment by hishamhm** [comment]
> There currently isn't a dev variant for user manifests, but it shouldn't be difficult to set up on my end.

That would be welcome, as I'd like to add a `--dev` flag that switches to the corresponding manifest, so it would be orthogonal to have `luarocks install --dev user/package` work

> would we always just map: /manifest -> /manifests/leafo/manifest

I like this approach better than restricting to luarocks.org. It's nice to have the feature work for alternate repositories, and this does not assume any special requirements in the repo other than a path structure (ie, it works even for local file:// repos), and it doesn't make alternate repos second-class citizens.

> The package should install using the name in the manifest. The user name doesn't affect the installed name at all. It should work as if you manually specified the manifest in the command line argument.

Agreed. I think this is the simplest way to go. I think this combined with a convenient way to install in the current directory (I was thinking `--here`) would work well enough.

> Should dependencies be fetched from the user manifest as well? If dependencies are available in both user and default manifest, which should take precedence? I think the user manifest should be available for dependencies, and it should take precedence over the default manifest.

Good questions for which I don't have a defined opinion.

Another possible feature: pinning users in a rockspec's `dependencies` section, so one could write:

```lua
dependencies = {
   "foo/bar 1.2",
   "bla > 2.0"
}
```

I think this would be logical to have once we have `luarocks install foo/bar`. (Being a rockspec incompatibility, this would have to go into LuaRocks 3).
