### ISSUE TITLE
Define `$(LUA)` as variable in config file

### ISSUE THREAD

**Issue by moteus** [luarocks/luarocks#621]
I found that I can not set `LUA` or `LUA_INTERPRETER` in config-XXX.lua file.
I have not `lua` binary but only `lua51`, `lua52` etc. So I need this for each 
Lua version same as `LUA_INCDIR`, `LUA_LIBDIR` e.t.c.
Now I have to edit `site_config.lua` file

``` Lua
LUA_LIBDIR = "$(LUA_LIBDIR)",  -- variable
LUA_BINDIR = "$(LUA_BINDIR)",  -- variable
LUA_INCDIR = "$(LUA_INCDIR)",  -- variable
LUALIB     = "$(LUALIB)",      -- variable
LUA        = "$(LUA)",         -- NOT variable
```

**Comment by hishamhm** [comment]
Yes, this is by design, because these settings are done at installation time (via the `configure` script on Unix and `install.bat` on Windows), so they end up in `site_config.lua`.

The settings in `site_config.lua` are core configurations that every LuaRocks installation needs. The ones in `config-5.x.lua` are user customizations (the `config-5.x.lua` file is optional).

**Comment by moteus** [comment]
On my Windows system I have 3 Lua version. (`lua51`, `lua52` and `ua53`).
And 3 LuaRocks commands like `luarocks-5.1`, `luarocks-5.2` and `luarocks-5.3`
Almost all options I can configure in `config-*.lua` files. Except Lua binary name.
I try build LuaCom Library which require use Lua binary to compile some Lua files.
So now with LuaRocks I have e.g.  `LUALIB=lua53.lib`, but i can not also define `LUA=lua53.exe`
without full copy LuaRocks to separate folder with new site_config.
For now I just patch LuaRocks so I can set  in `config-*.lua`
```Lua
LUALIB           = 'lua' .. LUA_SHORT_VER .. '.lib'
LUA_INTERPRETER  = 'lua' .. LUA_SHORT_VER .. '.exe'
LUA              = LUA_DIR .. [[\bin\]] .. LUA_INTERPRETER
```
So what I whant is to be able handle multiple lua versions without making several copies of LuaRocks
source code. Now I have to have 2 copy of LuaRocks because I need LuaRocks for x86 and x64 Arch.

You can checkout my Installation in [luaenv](https://github.com/moteus/lua-windows-environment) project. I also add Lua/Luarocks installer based on Inno Setup and build it on AppVeyor.
You can ignore all external libs. But you can install both Lua x86 and Lua x64 in same dir e.g. `c:\luaenv` and use `luaenv` command to switch beetween them. Or just install single Lua version and register globally in system.



You ca

**Comment by siffiejoe** [comment]
You can have versioned site config files like `site_config_5_1.lua`, etc. See e.g. [here](https://github.com/siffiejoe/prg-lr4win/tree/master/templates).

**Comment by moteus** [comment]
> You can have versioned site config files like site_config_5_1.lua

In fact I try it when start and had some problems but do not remember which ones.
May be I was wrong and it works.
But I really do not understand why I should define `lua53.lib` in one config file and `lua53.exe` in different file, which even stored in source directory.

Ideally I want to install single instance of luarocks and use it for handle several Lua versions for x86/x64 at same time. Just have several configs for each version and use e.g. bat files + env to do select wich one config use.
