### ISSUE TITLE
Cannot install luasec, needs luasec first

### ISSUE THREAD

**Issue by madmaxoft** [luarocks/luarocks#653]
Not sure if this is the right place for this report, but anyway:

When installing luarocks on a fresh new system, it is impossible to install `luasocket` first and `luasec` second. Doing so fails the `luasec` installation with the following error message:
```
$ sudo luarocks install luasec OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu

Warning: Failed searching manifest: Failed loading manifest: Failed fetching manifest for http://luarocks.org/repositories/rocks - Error fetching file: Failed downloading http://luarocks.org/repositories/rocks/manifest - URL redirected to unsupported protocol - install luasec to get HTTPS support.

Error: No results matching query were found.

sudo luarocks install luasec OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu returned exit code 1
```

I worked around this by installing `luasec` first and then `luasocket` - surprisingly this works okay. I assume this is because until `luasocket` is installed, luarocks defaults to system-provided curl or something similar; as soon as `luasocket` is installed, it tries doing things on its own and fails with TLS connections.

Note that this is a rather new issue, it wasn't present 7 days ago (2016-11-05 9:33 UTC). The OS is Ubuntu Trusty (used on CircleCI). It has been observed while performing CI for Cuberite's Core plugin: https://circleci.com/gh/cuberite/Core , builds 16 - 21

**Comment by mpeterv** [comment]
The issue is new because luarocks.org started redirecting http:// to https://. It's not  a problem for recent versions as since luarocks 2.2.0 default repo URL uses https:// from the start. As an alternative fix, you can use `--server=https://luarocks.org` when installing luasec or use a newer version of Luarocks.

**Comment by madmaxoft** [comment]
Wait, why did GitHub close this issue? I did not fix this issue, I just fixed its symptoms in one of our projects :(

Adding `--server=https://luarocks.org` doesn't help. The error message basically says "install luasec to install luasec", so the only real solution is to install luasec before installing luasocket.

Here's the output:
```
$ sudo luarocks --server=https://luarocks.org install luasec OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu

Warning: Failed searching manifest: Failed loading manifest: Failed fetching manifest for https://luarocks.org - Error fetching file: Failed downloading https://luarocks.org/manifest - Unsupported protocol - install luasec to get HTTPS support.
Warning: Failed searching manifest: Failed loading manifest: Failed fetching manifest for http://luarocks.org/repositories/rocks - Error fetching file: Failed downloading http://luarocks.org/repositories/rocks/manifest - URL redirected to unsupported protocol - install luasec to get HTTPS support.

Error: No results matching query were found.

sudo luarocks --server=https://luarocks.org install luasec OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu returned exit code 1

Action failed: sudo luarocks --server=https://luarocks.org install luasec OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu
```

**Comment by mpeterv** [comment]
Okay, so the old version of luarocks that apt-get installs can't even fall back to wget/curl when luasocket is installed but luasec isn't. That's fixed in newer versions, too.

**Comment by nmfzone** [comment]
Yep, @mpeterv is right. I think ubuntu repo (that contains luarocks) still use the old version. Try to build luarocks by your self ([tutorial](https://github.com/luarocks/luarocks/wiki/Installation-instructions-for-Unix#quick-start)), and the problem should be solved.
