### ISSUE TITLE
Attempt to install LuaRocks (Could not find Lua.) after installing/compiling Lua

### ISSUE THREAD

**Issue by hydroper** [luarocks/luarocks#658]
**Lua version:**
5.3.3

**Install error:**
![image](https://cloud.githubusercontent.com/assets/15965072/21051074/ab2fd18e-be05-11e6-94fe-597b9c861113.png)

**Comment by hishamhm** [comment]
Where is file lua.h in your system?

**Comment by hydroper** [comment]
@hishamhm It's currently located at C:\Lua\lua\include. Its reference path is: C:\Lua\lua\include\lua.h.

**Comment by hishamhm** [comment]
try passing `/INC c:\lua\lua\include` to the installer then (see `install.bat /?` for more options)

**Comment by hydroper** [comment]
brb I'll try to install it again using this `/INC` option, thanx. I did now also note that Lua compiled the `.\include` directory outside `.\bin`.

**Comment by hydroper** [comment]
Thanks! It worked.
