### ISSUE TITLE
[user email update request] User: hsluv

### ISSUE THREAD

**Issue by boronine** [luarocks/luarocks#659]
Is it possible to request an email change here for my organization's luarocks.org account? The reason is that I don't want to see my face on the organization's page via Gravatar. I set up a dedicated email account for this: hsluvcontributors@gmail.com

Thank you. Love this project!

**Comment by hishamhm** [comment]
Hi! Could you post a ticket to the website issue tracker instead? This one is for the luarocks tool itself. Thanks! https://github.com/luarocks/luarocks-site/issues
