### ISSUE TITLE
[SUGGESTION] Windows: Set necesarry environment variables automatically

### ISSUE THREAD

**Issue by birgersp** [luarocks/luarocks#661]
I've been "messing around" a little with LuaRocks installations lately. When running the install script (windows) I'm told what the various evironment variables should contain. I suggest the install script fix these environement variables itself, or atleast provies me the option to do so.

It would also make LuaRocks easier to use for people that might be a bit unfamiliar as to how environment variables work (see [this issue](https://github.com/luarocks/luarocks/issues/622))

Thanks

**Comment by Lord-Helmchen** [comment]
I wouldn't go that far, but having the elevated cmdline window close on _any_ keypress efficiently prevented me from copy-pasting the paths and made me type them all by hand :-/

**Comment by birgersp** [comment]
Same happened to me, which frustrated me enough to raise this issue

**Comment by Tieske** [comment]
I'm not sure about just setting this stuff system wide (besides making it work reliable from a batch/lua file)

Would it help if we'd write some sort of `set_path.bat` file next to the luarocks batch file? So you'd be able to either inspect and copy it, or just call it?

**Comment by birgersp** [comment]
Yes, definitely :)

**Comment by Lord-Helmchen** [comment]
I actually think that setting the paths temporary in (a / the luarocks.bat) batch file is even preferable than setting them system-wide (be it manually or automated).

**Comment by Tieske** [comment]
see #492 which I think is the better solution to this.
