### ISSUE TITLE
How to execute a Lua Rocks package?

### ISSUE THREAD

**Issue by hydroper** [luarocks/luarocks#665]
I want to use [lua-amalg](https://github.com/siffiejoe/lua-amalg) package for LuaRocks, but I don't know how to execute it yet. Its usage example is: `./amalg.lua module1 module2`, but instead this command opens the amalg.lua file in my editor.

**Comment by daurnimator** [comment]
lua-amalg seems to call it's executable "amalg.lua". ==> You'll need to run `amalg.lua` (without the leading `./`).

If you're having issues, make sure you have the correct directories in your `PATH`. `luarocks path --bin` would help here.

**Comment by hydroper** [comment]
@daurnimator Unfortunately I removed the `./` and it still opened my text editor with the `amalg.lua` file :(.

It looks like my paths are correct:

![image](https://cloud.githubusercontent.com/assets/15965072/21961923/e4f9a8c6-dafd-11e6-87f4-5aa76192e454.png)

And I can execute lua codes normally by entering the command `lua`.

**Comment by siffiejoe** [comment]
If you have installed the lua-amalg rock, you should have a `amalg.lua.bat` file in your LuaRocks `bin` directory. If said `bin` directory is in your `PATH`, you should be able to call it via `amalg.lua.bat` or -- unless there is a `amalg.lua` file in your current directory -- via `amalg.lua`. Why are you trying to call `amalg.lua` from within its directory, btw.?

However, if you have `amalg.lua` in your current directory, then `lua amalg.lua module1 module2` should always work, even if the rock has not been installed.

**Comment by hydroper** [comment]
@siffiejoe Thanks for your help. Yes, there's a bat there, but it gives an error saying that amalg.lua doesn't exist. My command: `amalg.lua ..\share\luarocks\rocks\bin\index.lua`, console:

![image](https://cloud.githubusercontent.com/assets/15965072/21963182/fab463d0-db1c-11e6-9427-5b118f2e6e0f.png)

When I try executing amalg.lua itself (the Lua script) it says that my specified files aren't found:

![image](https://cloud.githubusercontent.com/assets/15965072/21963195/408460fe-db1d-11e6-948e-359e7686f874.png)

**Comment by hydroper** [comment]
I've also tried putting the absolute path, but same error occurs. I tried changing `/` to `\` in various different ways, but nothing!

**Comment by siffiejoe** [comment]
The arguments to `amalg.lua` are *module* names not *file* names (except for the `-s` option). So try
```
lua src/amalg.lua testh.index
```
from within the `lua-amalg-master` directory (assuming that your module is supposed to be called `testh.index`).

Regarding the first issue: It seems that the script wasn't installed correctly. But we'll need more detailed information about how you installed the lua-amalg rock, and which version of LuaRocks you use.

**Comment by hydroper** [comment]
Thanks! It works as well. However, the generated output doesn't handle the require function. How can require be emulated?

**Comment by hydroper** [comment]
Also, the Lua ambient of the game I want to run the output code doesn't support the package library.

**Comment by daurnimator** [comment]
Hrm, your `luarock path --bin` output is missing `PATH`: is that a luarocks bug?

**Comment by mpeterv** [comment]
@hydroper by the way, what's the version of Luarocks you are using? What does `luarocks --version` print?

**Comment by hydroper** [comment]
@daurnimator True, it's not. I'm not sure if I installed it fine, anyway it's working now !

@mpeterv 

My version is `2.0.10`. It prints

```
luarocks 2.0.10
LuaRocks main command-line interface

```
as well. I have had some troubles when installing packages, however `amalg.lua` is now executin' fine.

**Comment by siffiejoe** [comment]
@hydroper: amalg.lua handles `require` calls by putting your modules into `package.preload`. Obviously this won't work if you don't have the `package` library available. But in that case you should also be missing `require` anyway. You *could* try to implement a compatible `require` replacement. You only need to have a table at `package.preload`, and one at `package.loaded`, and a `require` function that calls the functions in `package.preload` and puts the resulting modules into `package.loaded`. You can look up the details in the Lua reference manual, and there is also a complete reimplementation of `require` in Lua on GitHub and in LuaRocks.

Anyway, this is probably not a topic for the LuaRocks issue tracker ...

**Comment by hishamhm** [comment]
Closing this since the issue seems solved. Further discussion would be best located indeed in the [lua-amalg tracker](https://github.com/siffiejoe/lua-amalg/issues)
