### ISSUE TITLE
Error while installing dpnn package with luarocks!!

### ISSUE THREAD

**Issue by jKhurana** [luarocks/luarocks#666]
I have installed torch using following link [http://torch.ch/docs/getting-started.html] with lua version 5.2.

I set following in the ~/.bashrc file.

```
    export PATH=$PATH:/home/jkhurana/torch/install/bin
    . /home/jkhurana/torch/install/bin/torch-activate

```
Now I am trying to install dpnn package with luarocks using the following command

`    luarocks install dpnn`
But it gives the following error

```
    Installing https://raw.githubusercontent.com/torch/rocks/master/dpnn-scm-1.rockspec...
    Using https://raw.githubusercontent.com/torch/rocks/master/dpnn-scm-1.rockspec... switching to 'build' mode
    Cloning into 'dpnn'...
    fatal: unable to connect to github.com:
    github.com[0: 192.30.253.113]: errno=Connection timed out
    github.com[1: 192.30.253.112]: errno=No route to host
    
    
    Error: Failed cloning git repository.
```

Following are the output of various commands:

`luarocks search dpnn`

    Search results:
    ===============
    
    
    Rockspecs and source rocks:
    ---------------------------
    
    dpnn
       scm-1 (rockspec) - https://raw.githubusercontent.com/torch/rocks/master

`luarocks list`

    Warning: Failed loading manifest for /home/jkhurana/.luarocks/lib/luarocks/rocks: /home/jkhurana/.luarocks/lib/luarocks/rocks/manifest: No such file or directory
    
    Installed rocks:
    ----------------
    
    argcheck
       scm-1 (installed) - /home/jkhurana/torch/install/lib/luarocks/rocks
    
    cwrap
       scm-1 (installed) - /home/jkhurana/torch/install/lib/luarocks/rocks
    
    dok
       scm-1 (installed) - /home/jkhurana/torch/install/lib/luarocks/rocks
    
    env
       scm-1 (installed) - /home/jkhurana/torch/install/lib/luarocks/rocks
    
    gnuplot
       scm-1 (installed) - /home/jkhurana/torch/install/lib/luarocks/rocks
    
    graph
       scm-1 (installed) - /home/jkhurana/torch/install/lib/luarocks/rocks
    
    image
       1.1.alpha-0 (installed) - /home/jkhurana/torch/install/lib/luarocks/rocks
    
    lua-cjson
       2.1devel-1 (installed) - /home/jkhurana/torch/install/lib/luarocks/rocks
    
    luaffi
       scm-1 (installed) - /home/jkhurana/torch/install/lib/luarocks/rocks
    
    luafilesystem
       1.6.3-1 (installed) - /home/jkhurana/torch/install/lib/luarocks/rocks
    
    moses
       1.4.0-1 (installed) - /home/jkhurana/torch/install/lib/luarocks/rocks
    
    nn
       scm-1 (installed) - /home/jkhurana/torch/install/lib/luarocks/rocks
    
    nngraph
       scm-1 (installed) - /home/jkhurana/torch/install/lib/luarocks/rocks
    
    nnx
       0.1-1 (installed) - /home/jkhurana/torch/install/lib/luarocks/rocks
    
    optim
       1.0.5-0 (installed) - /home/jkhurana/torch/install/lib/luarocks/rocks
    
    paths
       scm-1 (installed) - /home/jkhurana/torch/install/lib/luarocks/rocks
    
    penlight
       scm-1 (installed) - /home/jkhurana/torch/install/lib/luarocks/rocks
    
    qtlua
       scm-1 (installed) - /home/jkhurana/torch/install/lib/luarocks/rocks
    
    qttorch
       scm-1 (installed) - /home/jkhurana/torch/install/lib/luarocks/rocks
    
    sundown
       scm-1 (installed) - /home/jkhurana/torch/install/lib/luarocks/rocks
    
    sys
       1.1-0 (installed) - /home/jkhurana/torch/install/lib/luarocks/rocks
    
    threads
       scm-1 (installed) - /home/jkhurana/torch/install/lib/luarocks/rocks
    
    torch
       scm-1 (installed) - /home/jkhurana/torch/install/lib/luarocks/rocks
    
    trepl
       scm-1 (installed) - /home/jkhurana/torch/install/lib/luarocks/rocks
    
    xlua
       1.0-0 (installed) - /home/jkhurana/torch/install/lib/luarocks/rocks

`which lua th`

    /home/jkhurana/torch/install/bin/lua
    /home/jkhurana/torch/install/bin/th

Please tell me what is the problem. Thanks in advance.

**Comment by hishamhm** [comment]
From http://stackoverflow.com/questions/16298986/unable-to-connect-to-github-com-for-cloning :

You are probably behind a firewall. Try cloning via https – that has a higher chance of not being blocked. 

Try running this command to tell Git to automatically use https:

```
git config --global url."https://".insteadOf git://
```

**Comment by jKhurana** [comment]
Thank you so much. It resolved my issue. Now dpnn is installed perfectly.
