### ISSUE TITLE
luarocks fails to install LuaFileSystem 

### ISSUE THREAD

**Issue by tastyminerals** [luarocks/luarocks#667]
I have two version installed on a linux system, **lua5.1** and **lua5.3**. My distribution uses **lua5.3** by default, `/usr/bin/lua` invokes **5.3** version.

I have a script that requires **LuaFileSystem**.
```
$ sudo luarocks install luafilesystem
Installing https://luarocks.org/luafilesystem-1.6.3-2.src.rock
gcc -O2 -fPIC -I/usr/include -c src/lfs.c -o src/lfs.o
gcc -shared -o lfs.so -L/usr/lib src/lfs.o
luafilesystem 1.6.3-2 is now installed in /usr (license: MIT/X11)
```

However, running the script brings the error:
```
lua: /usr/share/lua/5.3/pl/path.lua:30: pl.path requires LuaFileSystem
stack traceback:
	[C]: in function 'error'
	/usr/share/lua/5.3/pl/path.lua:30: in main chunk
	[C]: in function 'require'
	/usr/share/lua/5.3/pl/import_into.lua:65: in metamethod '__index'
	/usr/local/bin/lua-tinyhelp.lua:9: in main chunk
	[C]: in ?
```

This error has been plaguing me since forever and it is really annoying especially when I tried almost everything I could think of to resolve this.

I tried installing locally into `~/.luarocks` both for `--lua-version=5.3` and `--lua-version=5.1`
I tried doing the same via `sudo` but it looks like I am not doing it correctly. Do I have to add paths for **lua5.1** into `~/.bashrc` so that luarocks would pick them up? Why setting `--lua-version=5.1` explicitly does not work? Does luarocks do any `/usr/share/lua` read, because if it did, it would notice that the directory contains **5.1** and **5.3** and `--lua-version` flags should then be working.  

```
$ luarocks path
luarocks path
export LUA_PATH='/home/tastyminerals/.luarocks/share/lua/5.3/?.lua;/home/tastyminerals/.luarocks/share/lua/5.3/?/init.lua;/usr/share/lua/5.3/?.lua;/usr/share/lua/5.3/?/init.lua;/usr/lib/lua/5.3/?.lua;/usr/lib/lua/5.3/?/init.lua;./?.lua;./?/init.lua;/home/tastyminerals/.lua-tinyhelp/?.lua'
export LUA_CPATH='/home/tastyminerals/.luarocks/lib/lua/5.3/?.so;/usr/lib/lua/5.3/?.so;/usr/lib/lua/5.3/loadall.so;./?.so'
```

**Comment by mpeterv** [comment]
OK, you installed luafilesystem successfully into `/usr` with the first command (`luarocks install luafilesystem`). What does `luarocks show luafilesystem` print? Does `lua -llfs` work?

**Comment by tastyminerals** [comment]
Here you go
```
[tastyminerals@dell-tasty ~]$ luarocks show luafilesystem

LuaFileSystem 1.6.3-2 - File System Library for the Lua Programming Language

LuaFileSystem is a Lua library developed to complement the set of functions
related to file systems offered by the standard Lua distribution. LuaFileSystem
offers a portable way to access the underlying directory structure and file
attributes.

License: 	MIT/X11
Homepage: 	http://keplerproject.github.io/luafilesystem
Installed in: 	/usr

Modules:
	lfs (/usr/lib/lua/5.3/lfs.so)

Depends on:
	lua >= 5.1 (using 5.3-1)

[tastyminerals@dell-tasty ~]$ lua -llfs
lua: error loading module 'lfs' from file '/usr/lib/lua/5.3/lfs.so':
	/usr/lib/lua/5.3/lfs.so: undefined symbol: luaL_register
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	[C]: in ?
[tastyminerals@dell-tasty ~]$ 
```

**Comment by mpeterv** [comment]
What does `grep LUA_VERSION /usr/include/lua.h` print?

**Comment by tastyminerals** [comment]
```
grep LUA_VERSION /usr/include/lua.h
#define LUA_VERSION_MAJOR	"5"
#define LUA_VERSION_MINOR	"3"
#define LUA_VERSION_NUM		503
#define LUA_VERSION_RELEASE	"3"
#define LUA_VERSION	"Lua " LUA_VERSION_MAJOR "." LUA_VERSION_MINOR
#define LUA_RELEASE	LUA_VERSION "." LUA_VERSION_RELEASE
```

**Comment by mpeterv** [comment]
That's strange, the error message for `lua -llfs` implied that luafilesystem was compiled with headers for Lua 5.1. The contents of `/usr/include` couldn't change, right?

**Comment by tastyminerals** [comment]
Never messed around `/usr/include`.
I am frequently using **[Torch](http://torch.ch)** which comes with it's own version of `luarocks`. **Torch** uses **lua5.1** by default and since I was using **Torch** luarocks to install some dependencies for this library, maybe something went wrong? However, before using **Torch** luarocks, I am running `torch-activate.sh`, which just exports `LUA_PATH`. So, it should be an issue, right?

```
[tastyminerals@dell-tasty ~]$ cat ~/torch/install/bin/torch-activate 
export LUA_PATH='/home/tastyminerals/.luarocks/share/lua/5.1/?.lua;/home/tastyminerals/.luarocks/share/lua/5.1/?/init.lua;/home/tastyminerals/torch/install/share/lua/5.1/?.lua;/home/tastyminerals/torch/install/share/lua/5.1/?/init.lua;/usr/share/lua/5.3/?.lua;/usr/share/lua/5.3/?/init.lua;/usr/lib/lua/5.3/?.lua;/usr/lib/lua/5.3/?/init.lua;./?.lua;./?/init.lua;/home/tastyminerals/.lua-tinyhelp/?.lua'
export LUA_CPATH='/home/tastyminerals/.luarocks/lib/lua/5.1/?.so;/home/tastyminerals/torch/install/lib/lua/5.1/?.so;/usr/lib/lua/5.3/?.so;/usr/lib/lua/5.3/loadall.so;./?.so'
export PATH=/home/tastyminerals/torch/install/bin:$PATH
export LD_LIBRARY_PATH=/home/tastyminerals/torch/install/lib:$LD_LIBRARY_PATH
export DYLD_LIBRARY_PATH=/home/tastyminerals/torch/install/lib:$DYLD_LIBRARY_PATH
export LUA_CPATH='/home/tastyminerals/torch/install/lib/?.so;'$LUA_CPATH
```

**Comment by tastyminerals** [comment]
Also, despite the fact that I was installing LuaFileSystem locally for both versions via `--local` and `--lua-version`, `.luarocks` does not contain anything that might belong to **5.1**.

```
[tastyminerals@dell-tasty .luarocks]$ lls -z
lib (2 dirs, 0 files)
:	\__lua (1 dirs, 0 files)
	:	\__5.3 (0 dirs, 2 files)
	\__luarocks (1 dirs, 0 files)
	:	\__rocks-5.3 (3 dirs, 1 files)
	:	:	\__luafilesystem (1 dirs, 0 files)
	:	:	:	\__1.6.3-2 (2 dirs, 2 files)
	:	:	:	:	\__doc (1 dirs, 0 files)
	:	:	:	:	:	\__us (0 dirs, 6 files)
	:	:	:	:	\__tests (0 dirs, 1 files)
	:	:	\__luautf8 (1 dirs, 0 files)
	:	:	:	\__0.1.1-1 (1 dirs, 2 files)
	:	:	:	:	\__doc (0 dirs, 1 files)
	:	:	\__penlight (1 dirs, 0 files)
	:	:	:	\__1.4.1-1 (1 dirs, 2 files)
	:	:	:	:	\__doc (1 dirs, 1 files)
	:	:	:	:	:	\__manual (0 dirs, 9 files)
share (1 dirs, 0 files)
:	\__lua (1 dirs, 0 files)
	:	\__5.3 (1 dirs, 0 files)
	:	:	\__pl (0 dirs, 39 files)
```

**Comment by mpeterv** [comment]
It's "lfs", not "lsf".

I'm not sure I understand how lfs compiled against Lua 5.3 headers can use luaL_register. If you re-run `sudo luarocks install luafilesystem` and `lua -llfs` immediately after each other the issue is reproducible?

**Comment by tastyminerals** [comment]
Yes, same error as above. I tried `sudo luarocks-5.3 install luafilesystem` and `lua -llfs`.

Archlinux distro has separate luarocks for all versions of lua.
```
[tastyminerals@dell-tasty ~]$ yaourt luarocks
1 community/luarocks 2.4.2-1 [installed]
    Deployment and management system for Lua 5.3 modules
2 community/luarocks5.1 2.4.2-1 [installed]
    Deployment and management system for Lua 5.1 modules
3 community/luarocks5.2 2.4.2-1
    Deployment and management system for Lua 5.2 modules
4 aur/openresty_luarocks 2.3.0-2 (3) (0.03)
    Deployment and management system for Openresty Luajit 2.1 modules
==> Enter n° of packages to be installed (ex: 1 2 3 or 1-3)
==> -------------------------------------------------------
==> 
```

**Comment by mpeterv** [comment]
By the way, to use same Luarocks tree (e.g. `~/.luarocks`) for several Lua versions Luarocks has to be configured with --versioned-rocks-dir, see #611.

**Comment by mpeterv** [comment]
Does it work if you create an isolated environment, e.g. using [hererocks](https://github.com/mpeterv/hererocks)?

**Comment by tastyminerals** [comment]
Now, what I would try is removing distro based `luarocks` and compile `luarocks` from current branch.
Can you advise some useful flags?

**Comment by mpeterv** [comment]
`./configure --versioned-rocks-dir --prefix=(luarocks installation path) --with-lua=(lua installation path) && make build && make install` should work. I am still not sure what is going on though. I'd like to try and debug further, e.g. by compiling luafilesystem manually and checking where it goes wrong, but if you work around the issue completely it's fine, too.

**Comment by tastyminerals** [comment]
Ok, I tried `hererocks`, installed `luafilesystem` and activated the environment. I had to comment out the `LUA_PATH` from `~/.bashrc` and reload. Inside `hererocks` environment I can successfully cal `lua -e "require 'lfs'" without errors.

**Comment by mpeterv** [comment]
If you want to debug the initial issue, can you run these commands to compile luafilesystem manually?

```bash
git clone https://github.com/keplerproject/luafilesystem
cd luafilesystem/src
git checkout v1_6_3
cp /usr/include/{lua.h,lauxlib.h,lualib.h,luaconf.h} .
gcc -shared -O2 -fPIC -I. lfs.c -o lfs.so
lua -e 'print(_VERSION); package.cpath="?.so"; require "lfs"'
```

**Comment by tastyminerals** [comment]
Debugging with `luafilesystem` clone.
```
[tastyminerals@dell-tasty src]$ lua -e 'print(_VERSION); package.cpath="?.so"; require "lfs"'
Lua 5.3
lua: error loading module 'lfs' from file 'lfs.so':
	lfs.so: cannot open shared object file: No such file or directory
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	(command line):1: in main chunk
	[C]: in ?
```

**Comment by tastyminerals** [comment]
Now, recompiling `luarocks` and installing didn't help. The error persists. 
```
lua: error loading module 'lfs' from file '/usr/lib/lua/5.3/lfs.so':
	/usr/lib/lua/5.3/lfs.so: undefined symbol: luaL_register
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	(command line):1: in main chunk
	[C]: in ?
```

**Comment by mpeterv** [comment]
From the `luafilesystem/src` directory where there is manually compiled `lfs.so` can you run `lua -e 'print(_VERSION); package.cpath="./?.so"; require "lfs"'` instead?

**Comment by tastyminerals** [comment]
from `src` it works without errors

**Comment by mpeterv** [comment]
Ok, can you try installing lfs by running `sudo luarocks make` from `luafilesystem` directory? It should produce `lfs.so` in current directory (`luafilesystem`), can you compare it with the one built manually in `luafilesystem/src`?

**Comment by tastyminerals** [comment]
Well, all I can say, they are not the same.
```
objdump -d lfs.so > 1.txt
objdump -d src/lfs.so > 2.txt
```
[diffuse 1.txt 2.txt](http://i.imgur.com/9YQhCxZ.png)

**Comment by mpeterv** [comment]
But `lfs.so` and `/usr/lib/lua/5.3/lfs.so` are the same, right? And trying to load `lfs.so` fails with the same error? (`lua -e 'print(_VERSION); package.cpath="./?.so"; require "lfs"'` from `luafilesystem` directory)?

**Comment by tastyminerals** [comment]
Yep, just checked with diffuse, same files.

**Comment by mpeterv** [comment]
If you build another version manually using same commands luarocks does, (`gcc -O2 -fPIC -I/usr/include -c src/lfs.c -o src/lfs.o && gcc -shared -o lfs2.so -L/usr/lib src/lfs.o` from `luafilesystem` directory), is resulting `src/lfs2.so` same as `lfs.so` (from luarocks make) or `src/lfs.so` (working, built manually)?

**Comment by tastyminerals** [comment]
`~/luafilesystem/lfs.so` and `~/luafilesystem/lfs2.so` are the same when build from `luafilesystem`.
`~/luafilesystem/lfs.so` is different from `~/luafilesystem/src/lfs.so`.

**Comment by mpeterv** [comment]
OK, so these two commands produce different results:

* `gcc -O2 -fPIC -I/usr/include -c src/lfs.c -o src/lfs.o && gcc -shared -o lfs2.so -L/usr/lib src/lfs.o` from `luafilesystem`.
* `gcc -shared -O2 -fPIC -I. lfs.c -o lfs.so` from `luafilesystem/src`.

I guess we can keep getting these commands closer until it's clear why there is a difference causing errors on load for the first command.

**Comment by mpeterv** [comment]
For example, can you try building with these commands (from `luafilesystem`) and checking after each one if `lfs.so` and `src/lfs.so` are different?

1. `gcc -shared -O2 -fPIC -Isrc src/lfs.c -o src/lfs.so`
2. `gcc -shared -O2 -fPIC -I/usr/include src/lfs.c -o src/lfs.so`
3. `gcc -O2 -fPIC -I/usr/include -c src/lfs.c -o src/lfs.o && gcc -shared -o src/lfs.so src/lfs.o`
4. `gcc -O2 -fPIC -I/usr/include -c src/lfs.c -o src/lfs.o && gcc -shared -o src/lfs.so -L/usr/lib src/lfs.o`

**Comment by tastyminerals** [comment]
Running the commands above and then `objdump -d src/lfs.so > 2.txt && diffuse 1.txt 2.txt`
1. different
2. same
3. same
4. same

**Comment by siffiejoe** [comment]
Can you run `sudo luarocks make CC="gcc -save-temps"` from within the `luafilesystem` directory again and `grep 'lua\.h' lfs.i`? This should tell us which Lua include files are actually used.

**Comment by tastyminerals** [comment]
Here you go
```
[tastyminerals@dell-tasty luafilesystem]$ sudo luarocks make CC="gcc -save-temps"
[sudo] password for tastyminerals: 
gcc -save-temps -O2 -fPIC -I/usr/include -c src/lfs.c -o src/lfs.o
gcc -shared -o lfs.so -L/usr/lib src/lfs.o
luafilesystem cvs-3 is now installed in /usr/local

[tastyminerals@dell-tasty luafilesystem]$ grep 'lua\.h' lfs.i
# 1 "/usr/local/include/lua.h" 1 3
# 12 "/usr/local/include/lua.h" 3
# 13 "/usr/local/include/lua.h" 2 3
# 14 "/usr/local/include/lua.h" 2 3
# 17 "/usr/local/include/lua.h" 2 3
# 50 "/usr/local/include/lua.h" 3
# 99 "/usr/local/include/lua.h" 3
# 230 "/usr/local/include/lua.h" 3
# 298 "/usr/local/include/lua.h" 3
# 326 "/usr/local/include/lua.h" 3
# 1 "/usr/local/include/lua.h" 1 3
```

**Comment by mpeterv** [comment]
Alright, so you must have Lua 5.1 headers in `/usr/local`...

**Comment by mpeterv** [comment]
What does `grep LUA_VERSION /usr/local/include/lua.h` print?

**Comment by tastyminerals** [comment]
Heh, it prints
```
grep LUA_VERSION /usr/local/include/lua.h
#define LUA_VERSION	"Lua 5.1"
#define LUA_VERSION_NUM	501
```

**Comment by mpeterv** [comment]
Right. I totally forgot that `-I/usr/include` doesn't put `/usr/include` in front of other paths in the header seach path list because it is already on the default list, just behind `/usr/local/include`.

**Comment by mpeterv** [comment]
So, the moral is that having different Lua versions installed in `/usr` and in `/usr/local` is a bad idea.

**Comment by tastyminerals** [comment]
Yep, so should I just wait for a fix or is there something I need to do on my end?

**Comment by mpeterv** [comment]
You could remove Lua 5.1 from `/usr/local` or replace it with `Lua 5.3`. Or you could just copy a version of lfs.so that works into `/usr/lib/lua/5.3`, but then the same problem will pop up for most C modules. You could also just use the isolated hererocks environment for now =)

@siffiejoe as far as I understand, using `-isystem` instead of `-I` when compiling C modules should be a good fix, is that correct?

**Comment by tastyminerals** [comment]
@mpeterv  Thanks a lot for helping out with this!

**Comment by mpeterv** [comment]
@tastyminerals no problem, thanks for debugging!

**Comment by siffiejoe** [comment]
@mpeterv: `-isystem` seems to work, but I'm not sure how portable that flag is to Unix C compilers other than gcc ...

Maybe the portable thing to do is to make a private copy of the Lua include files (either once during LuaRocks installation or directly before compiling the C modules).

**Comment by mpeterv** [comment]
@siffiejoe I like copying include files once during LuaRocks installation. Where should they be stored? Probably in some versioned location inside `(prefix)/include/luarocks/`.

**Comment by siffiejoe** [comment]
@mpeterv Looks ok to me.

**Comment by hishamhm** [comment]
I'm missing something here. How would this fix things? If we add headers in
a private path then do `-I/private_path/` it looks to me that we'd go back
to square one, right? It would still end up catching lua.h from
/usr/local/include.

**Comment by siffiejoe** [comment]
@hishamhm: No, the directories from `-I` are (mostly) prepended to the search path, *except* when the argument to `-I` is a system include directory, in which case the `-I` is ignored. The private copy would help if it's not (directly) in a system include directory

**Comment by hishamhm** [comment]
My worry then would become users upgrading Lua and LuaRocks sticking with outdated headers. (I know that, supposedly, minor upgrades of Lua shouldn't bring substantial changes to the headers, but still.)

I think _maybe_ passing `-isystem` (as well as `-I`?) when the `CC` variables contains `gcc` could work for `builtin` modules, but it would still be a kind of guesswork (and we'd have to do this for all incdirs, not just Lua? what if I have libfoo in both /usr and /usr/local and I'm binding luafoo to use the one in /usr/local?)

( Unix paths are a mess. Someone should try to fix that m—oh wait :) )
