### ISSUE TITLE
Cannot install any package - Windows 8.1

### ISSUE THREAD

**Issue by francois-1989** [luarocks/luarocks#670]
When attempting to install any package using the following command as an example:

`luarocks install lbase64`

I am getting the following error message and the package is not installed:
```
Setting environment for using Microsoft Visual Studio 2010 x64 tools.
The directory name is invalid.
Installing https://luarocks.org/lbase64-20120807-3.src.rock
cl /nologo /MD /O2 -c -Folbase64.obj -IC:/CS-dev/SVNCommsEngine/Katana/trunk/Toolkit/lua-5.3.2/src lbase64.c
lbase64.c
link -dll -def:base64.def -out:base64.dll C:/tools/lua/lua53.lib lbase64.obj
Microsoft (R) Incremental Linker Version 10.00.40219.01
Copyright (C) Microsoft Corporation.  All rights reserved.

   Creating library base64.lib and object base64.exp
Warning: C:\tools\lua\systree/lib/lua/5.3/base64.dll is not tracked by this installation of LuaRocks. Moving it to C:\tools\lua\systree/lib/lua/5.3/base64.dll~
The directory name is invalid.
The directory name is invalid.

Error: Failed move: could not delete C:\tools\lua\systree/lib/luarocks/rocks/lbase64/20120807-3/lib/base64.dll after copy.
```

The problem seems to be that the function `fs_lua.move ` successfully copies the file; however when attempting to delete the file copied, the file is not deleted. When attempting to delete the file, the following function is called from luarocks/src/luarocks/fs/win32/tools.lua:
```
function tools.delete(arg)
   assert(arg)
   assert(arg:match("^[a-zA-Z]?:?[\\/]"))
   fs.execute_quiet("if exist "..fs.Q(arg.."\\").." ( RMDIR /S /Q "..fs.Q(arg).." ) else ( DEL /Q /F "..fs.Q(arg).." )")
end
```

The script is attempting to delete a file; however it always executes the `RMDIR `command causing the message `The directory name is invalid.`

**Comment by raghur** [comment]
I'm having this exact same problem... looks like windows support is pretty low :(

**Comment by raghur** [comment]
I just switched the if/else actions
```   fs.execute_quiet("if exist "..fs.Q(arg.."\\").." ( DEL /Q /F "..fs.Q(arg).." ) else ( RMDIR /S /Q "..fs.Q(arg).." )")```

at least it lets me install packages now.

**Comment by Tieske** [comment]
trying to run the commands with the `--verbose` output option should shed some light on this.
