### ISSUE TITLE
`write_rockspec` skips `init.lua` file

### ISSUE THREAD

**Issue by martin-eden** [luarocks/luarocks#672]
`write_rockspec` skips `<module_name> / init.lua` file in case of presence `<module_name> .lua` file

To illustrate, in empty directory:

    echo "" > a.lua
    mkdir a
    echo "" > a/init.lua

    luarocks write_rockspec --lua_version=5.3

Resulted "modules" table in rockspec will contain 

    a = "a.lua"

This is a problem as I often have both "a.lua" and "a/init.lua". (And I await that two records will be generated.):

    a = "a.lua",
    ["a.init"] = "a/init.lua"

My offer is 

in case of two files pretending on one module name, spawn two records.

**Comment by pauloue** [comment]
Seems this is fixed.

**Comment by daurnimator** [comment]
Yep.
