### ISSUE TITLE
Luarocks doesn't recognize dependencies with --local

### ISSUE THREAD

**Issue by cmishra** [luarocks/luarocks#674]
I cannot install packages in the global tree due to lack of write permission. When I try to install in the user tree with --local, luarocks doesn't recognize any installed dependencies (at least the globally installed ones, i'm not sure if it does or doesn't recognize locally installed dependencies). 

Any tips? I've tried scouring the internet/github on this to no avail. 

I'm doing this on RHEL 6 with LuaJit 2.1.0-beta1

**Comment by mpeterv** [comment]
By default, when LuaRocks works with a "tree" like `.local` it doesn't look for dependencies in other trees. This can be changed using `--deps-mode` option. In particular, `--deps-mode=all` forces LuaRocks to look for dependencies in all trees defined in luarocks config, most likely just the global one.

**Comment by cmishra** [comment]
Ah thanks! Just tried that and it works.
