### ISSUE TITLE
API key is not saved when ~/.luarocks directory is missing

### ISSUE THREAD

**Issue by bungle** [luarocks/luarocks#676]
I'm not sure if this happens to others, but I found out that using `--api-key=<key>` fails to create `upload_config.lua` when `~/.luarocks` directory is missing. I think that it would be better if that directory would be created if it is missing. It silently goes on without saving the `API key`.

**Comment by bungle** [comment]
And so it seems. This is the code that saves the `upload_config.lua` file:
https://github.com/luarocks/luarocks/blob/9822682e68b252b049e2fa6ef9d052d7ac739378/src/luarocks/persist.lua#L200-L208

**Comment by hishamhm** [comment]
Thank you for the report! Fixed in the `luarocks-3` branch.

**Comment by daurnimator** [comment]
This seems like it could be backported? or are we not backporting?

**Comment by hishamhm** [comment]
I haven't been backporting stuff lately. I don't know if we'll have another 2.x release. LR 3.0 is not meant to be a big release with tons of features, but just the beginning of the next era, so I don't want to take _too_ long to release it (but probably not before late April).

In any case I'm happy to take PRs with backports of stuff that don't break compatibility.
