### ISSUE TITLE
Can I embed LuaRocks in my application?

### ISSUE THREAD

**Issue by vadi2** [luarocks/luarocks#684]
Lua is an embeddable language and I'm wondering if Luarocks can be the same. We use Lua extensively for scripting in [Mudlet](https://github.com/Mudlet/Mudlet), and Mudlet has the notion of packages - .xml or .zip files that embed Lua code within Mudlet objects. There is no package management solution at the moment - scripts can't auto-update, be hosted in a central repository, etc.

Installing a package for Mudlet means running ``installPackage("<path to zip")``, uninstalling means running ``uninstallPackage("<package name>")``.

Would it be feasible to mold LuaRocks to be embedded and work with these different installation concepts?

**Comment by vadi2** [comment]
@hishamhm any ideas about this? How embed-friendly is LuaRocks?

**Comment by hishamhm** [comment]
@vadi2 We started work for an embeddable LuaRocks API with @georgeroman in the `luarocks-api` branch, but we have not completed it at this point. We've had other priorities since but we would like to eventually get it done, though!

**Comment by vadi2** [comment]
OK, thanks!

**Comment by georgeroman** [comment]
At the moment I don't have too much time to work on that, but in a few months time I would happily continue the work we started if it would help you in any way.

**Comment by vadi2** [comment]
No rush! I think we'll go with our own package manager for now since we've already started. Just wanted to make sure we're not doing NIH.

**Comment by GoldsteinE** [comment]
Hi!
Are there any updates on this feature?
