### ISSUE TITLE
[Ubuntu] torch/install/share/lua/5.1/trepl/init.lua:389: module 'libcuda_utils' not found:No LuaRocks module found for libcuda_utils

### ISSUE THREAD

**Issue by senrajjj** [luarocks/luarocks#693]
Please any one solve this problem help me.

**Deep Photo Style Transfer Call**
 th /home/ubuntu/deep-photo-styletransfer/neuralstyle_seg.lua -style_image /var/www/html/down_img/tar16.png -content_image /var/www/html/down_img/in16.png -output_image /var/www/html/latest/chg12_lb_new_3.png -model_file /home/ubuntu/deep-photo-styletransfer/models/nin_imagenet_conv.caffemodel -proto_file /home/ubuntu/deep-photo-styletransfer/models/train_val.prototxt -gpu -1 -seed 123 -content_layers relu0,relu3,relu7,relu12 -style_layers relu0,relu3,relu7,relu12 -content_weight 10 -style_weight 1000 -image_size 512 -num_iterations 1000 -backend cudnn -cudnn_autotune -optimizer lbfgs

**Issue:**
/home/ubuntu/torch/install/bin/luajit: /home/ubuntu/torch/install/share/lua/5.1/trepl/init.lua:389: module 'libcuda_utils' not found:No LuaRocks module found for libcuda_utils
        no field package.preload['libcuda_utils']
        no file '/home/ubuntu/.luarocks/share/lua/5.1/libcuda_utils.lua'
        no file '/home/ubuntu/.luarocks/share/lua/5.1/libcuda_utils/init.lua'
        no file '/home/ubuntu/torch/install/share/lua/5.1/libcuda_utils.lua'
        no file '/home/ubuntu/torch/install/share/lua/5.1/libcuda_utils/init.lua'
        no file './libcuda_utils.lua'
        no file '/home/ubuntu/torch/install/share/luajit-2.1.0-beta1/libcuda_utils.lua'
        no file '/usr/local/share/lua/5.1/libcuda_utils.lua'
        no file '/usr/local/share/lua/5.1/libcuda_utils/init.lua'
        no file '/home/ubuntu/.luarocks/lib/lua/5.1/libcuda_utils.so'
        no file '/home/ubuntu/torch/install/lib/lua/5.1/libcuda_utils.so'
        no file '/home/ubuntu/torch/install/lib/libcuda_utils.so'
        no file './libcuda_utils.so'
        no file '/usr/local/lib/lua/5.1/libcuda_utils.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'error'
        /home/ubuntu/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
        /home/ubuntu/deep-photo-styletransfer/neuralstyle_seg.lua:7: in main chunk
        [C]: in function 'dofile'
        ...untu/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: at 0x00405d50

**Comment by hishamhm** [comment]
This is not a LuaRocks bug, it seems a problem with your Torch installation. Please report at the Torch issue tracker.

**Comment by senrajjj** [comment]
Ok Thanks For Your Quick Reply. But Torch is Working Same Server and I am Using Another Method

th /home/ubuntu/**neural-style/neural_style.lua** -style_image /var/www/html/down_img/tar16.png -content_image /var/www/html/down_img/in16.png -output_image /var/www/html/latest/chg11_lb_new_3.png -model_file /home/ubuntu/neural-style/models/nin_imagenet_conv.caffemodel -proto_file /home/ubuntu/neural-style/models/train_val.prototxt -gpu -1 -seed 123 -content_layers relu0,relu3,relu7,relu12 -style_layers relu0,relu3,relu7,relu12 -content_weight 10 -style_weight 1000 -image_size 512  -num_iterations 1000 -backend cudnn -cudnn_autotune -optimizer lbfgs
example: [output image](http://52.214.152.168/latest/chg11_lb_new_3.png)

Above Command Working Perfectly But Image Quality is not good& Take More Time. So, I have Choose Below Method
th /home/ubuntu/**deep-photo-styletransfer/deepmatting_seg.lua** -style_image /var/www/html/down_img/tar16.png -content_image /var/www/html/down_img/in16.png -output_image /var/www/html/latest/chg12_lb_new_3.png -model_file /home/ubuntu/deep-photo-styletransfer/models/nin_imagenet_conv.caffemodel -proto_file /home/ubuntu/deep-photo-styletransfer/models/train_val.prototxt -gpu -1 -seed 123 -content_layers relu0,relu3,relu7,relu12 -style_layers relu0,relu3,relu7,relu12 -content_weight 10 -style_weight 1000 -image_size 512 -num_iterations 1000 -backend cudnn -cudnn_autotune -optimizer lbfgs
