### ISSUE TITLE
luarocks tries to install same package again

### ISSUE THREAD

**Issue by meisterluk** [luarocks/luarocks#694]
I followed torch's article to [get started](http://torch.ch/docs/getting-started.html) and installing does not work for me at all. `luarocks` does not seem to handle `git://` URLs properly (if I guess correctly).

```
usr@linux ~ % uname -a
Linux linux 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
usr@linux ~ % cat /etc/linuxmint/info 
RELEASE=18.1
CODENAME=serena
EDITION="KDE 64-bit"
DESCRIPTION="Linux Mint 18.1 Serena"
DESKTOP=KDE
TOOLKIT=QT
NEW_FEATURES_URL=http://www.linuxmint.com/rel_serena_kde_whatsnew.php
RELEASE_NOTES_URL=http://www.linuxmint.com/rel_serena_kde.php
USER_GUIDE_URL=`yelp help:linuxmint`
GRUB_TITLE=Linux Mint 18.1 KDE 64-bit
usr@linux ~ % which luarocks
/home/usr/torch/install/bin/luarocks
usr@linux ~ % luarocks install image
Installing https://raw.githubusercontent.com/torch/rocks/master/image-1.1.alpha-0.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/image-1.1.alpha-0.rockspec... switching to 'build' mode
Cloning into 'image'...
fatal: unable to connect to github.com:
github.com[0: 192.30.255.113]: errno=Connection timed out
github.com[1: 192.30.255.112]: errno=Connection timed out


Error: Failed cloning git repository.
```

Cloning the repository is not the issue as proven below:

```
usr@linux ~/dev % git clone https://github.com/torch/image.git                     
Cloning into 'image'...
remote: Counting objects: 1392, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 1392 (delta 0), reused 0 (delta 0), pack-reused 1389
Receiving objects: 100% (1392/1392), 2.76 MiB | 434.00 KiB/s, done.
Resolving deltas: 100% (765/765), done.
Checking connectivity... done.
usr@linux ~/dev % cd image 
usr@linux ~/dev/image % luarocks make --local image-1.1.alpha-0.rockspec

Missing dependencies for image:
sys >= 1.0
dok 
torch >= 7.0
xlua >= 1.0

Using https://raw.githubusercontent.com/torch/rocks/master/sys-1.1-0.rockspec... switching to 'build' mode

Missing dependencies for sys:
torch >= 7.0

Using https://raw.githubusercontent.com/torch/rocks/master/torch-scm-1.rockspec... switching to 'build' mode
Cloning into 'torch7'...
```

Then it tries to clone `torch7` to end up in a dependency cycle. However, it fails again, because cloning does not work.

My point is a different one: Why does luarocks try to install `image` in the first place for `luarocks install image`? It was installed before.

```
usr@linux ~/dev/image % luarocks list | grep -A 1 image
image
   1.1.alpha-0 (installed) - /home/usr/torch/install/lib/luarocks/rocks
```

**Comment by daurnimator** [comment]
What version of luarocks do you have?

> I followed torch's article to get started and installing does not work for me at all.

We do not support torch's installation guide.

**Comment by meisterluk** [comment]
```
LuaRocks 2.3.0, a module deployment system for Lua

NAME
        /home/usr/torch/install/bin/luarocks - LuaRocks main command-line interface

SYNOPSIS
        /home/usr/torch/install/bin/luarocks [--from=<server> | --only-from=<server>] [--to=<tree>] [VAR=VALUE]... <command> [<argument>] 

GENERAL OPTIONS
[...]

CONFIGURATION
        Lua version: 5.1
        Configuration files:
                System: /home/usr/torch/install/etc/luarocks/config.lua (ok)
                User  : /home/usr/.luarocks/config-5.1.lua (not found)

        Rocks trees in use: 
                /home/usr/.luarocks
                /home/usr/torch/install
```

> We do not support torch's installation guide.

Of course, but my question is just about the reinstallation.

**Comment by hishamhm** [comment]
> luarocks does not seem to handle git:// URLs properly

LuaRocks does, but it uses `git://` to git-clone by default, and that's probably what's failing because of your system/network settings.

You can use the same solution as described [here](http://stackoverflow.com/questions/15669091/bower-install-using-only-https#15684898), which is to configure your git to always use https:

```
git config --global url."https://".insteadOf git://
```

> Of course, but my question is just about the reinstallation.

The tool reinstalls because it was explicitly asked to. (Perhaps you installed a new compiler and wanted to rebuild, for example.) When a dependency is already installed, it does not rebuild it.

**Comment by meisterluk** [comment]
The git-config workaround works. All dependencies were downloaded, compiled and installed. Then the `image` package got installed.

Triggering `luarocks install --local image` again, downloads the `image` package (via git clone), compiles and installs it. However, unlike before, the dependencies are not installed again.

I guess for me it works. An option to install package "only if it is not installed yet" would be nice. Anyhow, thank you for helping me out.
