### ISSUE TITLE
attempt to concatenate local 'err' (a nil value) on fresh/clean luarocks install win 8.1

### ISSUE THREAD

**Issue by Tujin** [luarocks/luarocks#695]
Not sure why it's reporting 2.0.2, I downloaded the luarocks-2.4.2-win32 version.

>luarocks install 30log
Installing http://luarocks.org/repositories/rocks/30log-1.3.0-1.rockspec...

Error: LuaRocks 2.0.2 bug (please report at luarocks-developers@lists.luaforge.n
et).
...\Program Files (x86)\Lua\5.1\lua/luarocks\fs\lua.lua:526: attempt to concaten
ate local 'err' (a nil value)
stack traceback:
        ...\Program Files (x86)\Lua\5.1\lua/luarocks\fs\lua.lua:526: in function
 'download'
        ...:\Program Files (x86)\Lua\5.1\lua/luarocks\fetch.lua:33: in function
'fetch_url'
        ...:\Program Files (x86)\Lua\5.1\lua/luarocks\fetch.lua:70: in function
'fetch_url_at_temp_dir'
        ...:\Program Files (x86)\Lua\5.1\lua/luarocks\fetch.lua:263: in function
 <...:\Program Files (x86)\Lua\5.1\lua/luarocks\fetch.lua:248>
        (tail call): ?
        ...:\Program Files (x86)\Lua\5.1\lua/luarocks\build.lua:127: in function
 <...:\Program Files (x86)\Lua\5.1\lua/luarocks\build.lua:97>
        (tail call): ?
        (tail call): ?
        (tail call): ?
        (tail call): ?
        [C]: in function 'xpcall'
        ...am Files (x86)\Lua\5.1\lua\luarocks\command_line.lua:143: in function
 'run_command'
        C:\Program Files (x86)\Lua\5.1\luarocks.lua:20: in main chunk
        [C]: ?

**Comment by mpeterv** [comment]
You are in fact running luarocks 2.0.2, judging by the traceback and the suggested report address.

**Comment by Tujin** [comment]
The older version was sitting in my base lua (5.1) folder. It's entirely possible that I installed Lua at some point in the past and forgot about it. In any case, I removed it and used the new version and everything is working fine. Thanks!

**Comment by ldurniat** [comment]
@Tujin: What exactly you do? Did you remove folder `...\Program Files (x86)\Lua\5.1\lua/luarocks` with old version of luarocks or something else?
