### ISSUE TITLE
LuaRocks 2.4.2 cannot make directory

### ISSUE THREAD

**Issue by spc476** [luarocks/luarocks#696]
On a slightly older Linux system, when trying to upload a new rock, I got:

Sending org.conman.cbor-1.2.4-1.rockspec ...
Packing org.conman.cbor

Error: Failed creating temporary directory.

Attempting to install said rock, I got:

Installing http://rocks.moonscript.org/org.conman.cbor-1.2.3-1.src.rock

Error: Could not fetch rock file: Failed creating temporary directory luarocks-rock-org.conman.cbor 1.2.3-1: 'mkdtemp' is not implemented by host C library

**Comment by spc476** [comment]
Interesting, said system does include mkdtemp().  I just tested it.  The test program ran.  I'm not sure what's going on here ...

**Comment by spc476** [comment]
Found out the issue---it was with luaposix.  Removing that fixed the issue.

**Comment by daurnimator** [comment]
> Interesting, said system does include mkdtemp(). I just tested it. The test program ran. I'm not sure what's going on here ...

Looks like luaposix only binds it if your system declares itself as posix 2008 compliant: https://github.com/luaposix/luaposix/blob/bcd10b458ba41e27c81d7c8e7c47eea74fd2e0f5/ext/posix/stdlib.c#L115

Unfortunately there doesn't seem to be a way to override it (e.g. with a `HAVE_MKDTEMP` define)

**Comment by spc476** [comment]
I only installed luaposix to check something out---normally I don't use it at all.

**Comment by gvvaughan** [comment]
for the sake of my rewrite of the configure stage, what does `uname -s` return on your system?

I'm not at a computer right now, but there will be an autoconf cache variable you can set in the shell environment for ./configure to override the detected value - something like ac_cv_func_mkdtemp if you grew through ./configure.

**Comment by gvvaughan** [comment]
grep!

**Comment by spc476** [comment]
uname -s returns "Linux".  uname -a returns 

Linux lucy.roswell.conman.org 2.6.9-100.EL.plus.c4smp #1 SMP Fri Feb 18 03:46:19 EST 2011 i686 i686 i386 GNU/Linux

**Comment by gvvaughan** [comment]
The autoconf cache variable overide is double nonsense:
1. luaposix avoids #ifdef hell by asking the host libc headers whether it supports POSIX.2008, and conforms by not trying to bind any of the 2008 APIs if not.
2. luaposix doesn't even use autoconf any more :-/

If luarocks cares about portability to POSIX.2001 systems, and needs to use POSIX.2008 APIs, maybe it (or luaposix?) could provide an `os.system` call fallback when there's no C binding on the host?

I made some additional suggestions at https://github.com/luaposix/luaposix/issues/269 too.

**Comment by daurnimator** [comment]
> If luarocks cares about portability to POSIX.2001 systems, and needs to use POSIX.2008 APIs, maybe it (or luaposix?) could provide an os.system call fallback when there's no C binding on the host?

That would be suitable (it even already has the fallback). However it's hard to do feature detection with luaposix, as instead of the function *missing*, it is a stub that returns an error message.
