### ISSUE TITLE
Lua version number not available to make backend

### ISSUE THREAD

**Issue by craigbarnes** [luarocks/luarocks#698]
I have a Lua C module project that uses `make` to build separate object files for each supported Lua API (`build/lua{5.1,5.2,5.3}/module.so`). Each version can be built individually via `make build-lua{5.1,5.2,5.3}`. The problem is, I'm trying to create a rockspec using the `make` backend, but there doesn't seem to be any way to detect the version of Lua that LuaRocks is building for.

Is there any variable that would allow me to do something like this:

```
build = {
    type = "make",
    build_target = "build-lua$(LUA_API_VERSION)"
}
```
...? It seems [cqueues] has a very similar build system and the [rockspec](https://luarocks.org/manifests/daurnimator/cqueues-20161215.53-0.rockspec) file for that seems resigned to just hardcoding the config for Lua 5.3 and not supporting 5.2 or 5.1, even though the library and makefile support all 3 versions. 

[cqueues]: https://github.com/wahern/cqueues

**Comment by daurnimator** [comment]
> It seems cqueues has a very similar build system and the rockspec file for that seems resigned to just hardcoding the config for Lua 5.3 and not supporting 5.2 or 5.1, even though the library and makefile support all 3 versions.

cqueues has 3 rockspec files for each release: one for each lua version.

**Comment by craigbarnes** [comment]
Oh wow, I'd never even considered that. I just assumed `luarocks install ...` would try the highest version number. Thanks for the pointer.
