### ISSUE TITLE
run lunarocks error

### ISSUE THREAD

**Issue by JoyChou93** [luarocks/luarocks#699]
```
$ luarocks
lua: /usr/bin/luarocks:3: module 'luarocks.loader' not found:
	no field package.preload['luarocks.loader']
	no file '/usr/local/share/lua/5.2/luarocks/loader.lua'
	no file '/usr/local/share/lua/5.2/luarocks/loader/init.lua'
	no file '/usr/local/lib/lua/5.2/luarocks/loader.lua'
	no file '/usr/local/lib/lua/5.2/luarocks/loader/init.lua'
	no file './luarocks/loader.lua'
	no file '/usr/local/lib/lua/5.2/luarocks/loader.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './luarocks/loader.so'
	no file '/usr/local/lib/lua/5.2/luarocks.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './luarocks.so'
stack traceback:
	[C]: in function 'require'
	/usr/bin/luarocks:3: in main chunk
	[C]: in ?
```

**Comment by catwell** [comment]
What distribution is this? And how did you install LuaRocks?

**Comment by JoyChou93** [comment]
before, i used the way of yum install.

now, I download the source code to make install. now is ok.

**Comment by catwell** [comment]
Yes, it looks like the package from your distribution (I still don't know which one, CentOS?) is broken.

**Comment by JoyChou93** [comment]
$ cat /etc/issue
CentOS release 6.5 (Final)
Kernel \r on an \m

**Comment by catwell** [comment]
Where does the LuaRocks RPM come from? I don't have access to a CentOS 6.5 box so I tried with a CentOS 6.9.

```
$ cat /etc/issue               
CentOS release 6.9 (Final)
Kernel \r on an \m
```

There is no `luarocks` package by default so I added EPEL:

    sudo yum install epel-release
    sudo yum install luarocks 

It works (and uses Lua 5.1 by default, so that Lua 5.2 is your logs is suspicious).

**Comment by hishamhm** [comment]
Thanks @catwell for the instructions! Closing this due to lack of user feedback.
