### ISSUE TITLE
[rock file] How to write configuration file for application.

### ISSUE THREAD

**Issue by leetking** [luarocks/luarocks#703]
There is an application not a module writing by lua. and i use lua file to as a configuration, as everyone knows, configuration file shouldn't be 'import'.
I have read the wiki section of build.conf, the description is so brief that i can understand it.
can you give me some help, or make wiki more perfect. 
thanks a lot.

**Comment by rokf** [comment]
If you're asking for a `rockspec` example for an app instead of module you could take a look at https://github.com/leafo/gifine/blob/master/gifine-dev-1.rockspec

**Comment by leetking** [comment]
@rokf tks a lot. for some reason, I make a mistake that forgeting add 'dir' in section 'source'. i have fixed it. I read more instance same as your example.

**Comment by aleclarson** [comment]
@rokf Thank you! Just what I was looking for. Does the filename have to be `[package-name]-[version]` format?

**Comment by hishamhm** [comment]
> Does the filename have to be [package-name]-[package-version]-[rockspec-revision] format?

For `luarocks build` and `luarocks install` yes, for `luarocks make` (which often deals with work-in-progress rockspecs) no.

> What command do I use to install the dependencies from root directory?

You mean as a self-contained tarball which contains the app and its dependencies?

**Comment by aleclarson** [comment]
@hishamhm Maybe? I would be installing the dependencies globally on a provisioned machine.

**Comment by hishamhm** [comment]
> Also, it looks easy enough to just put any dependencies in a plain text file, read them line-by-line, and pass it to luarocks install thru Bash.

That works, but why not in the `dependencies` section of the rockspec itself? You can use `--only-deps` too if you only want to install the dependencies.

**Comment by aleclarson** [comment]
@hishamhm Awesome, thanks!
