### ISSUE TITLE
Pack rockspec and upload sucess, luarocks install fails

### ISSUE THREAD

**Issue by spacingnix** [luarocks/luarocks#710]
I'm having a bit of a problem trying to upload a module to luarocks. Using both the luarocks website to upload a rockspec and pack file works. Packing a rockspec through the command line also works and upload seems fine. My module appears on the luarocks website just as expected. When trying to install it:

```bash
$ sudo luarocks install unsplash-lua
```
I get the following error:
```
Installing https://luarocks.org/unsplash-lua-0.5-2.src.rock

Error: Build error: Failed installing unsplash/init.lua in /usr/local/lib/luarocks/rocks/unsplash-lua/0.5-2/lua/unsplash/init.lua: unsplash/init.lua: No such file or directory
```

Here is the rockspec file:
![rockspec](https://user-images.githubusercontent.com/16018884/27487270-277840f4-582b-11e7-80f3-fcc455a2adcb.jpeg)

And the source code on my repo -> https://github.com/spacingnix/unsplash-lua

**Comment by ignacio** [comment]
It is funny how if you download https://github.com/spacingnix/unsplash-lua/archive/v0.5-2.tar.gz you will see that there is no "unsplash" folder. The packaged sources don't respect the repository structure.

**Comment by ignacio** [comment]
If I change the rockspec to use branch master instead of your tagged version, it works:

~~~~
source = {
   url = "git://github.com/spacingnix/unsplash-lua.git",
   branch = "master"
}
~~~~

**Comment by spacingnix** [comment]
@ignacio I'm tempted to change the rockspec as you suggested to get on to other things but wouldn't targeting a release be better instead of the branch?

I did some poking around and the reason the v0.5-2.tar.gz didn't respect the repo structure was because it was based on an old commit. I figured that was the cause it didn't pack everything properly and bumped it to v0.5-4 and uploaded again. Now the v0.5-4.tar.gz looks fine and targets latest commit in my repo. Upload is fine aswell but - at least on both of my machines - it doesn't copy the package properly when installing it. Running these commands after results in this:

$ luarocks list
```bash
unsplash-lua
   0.5-4 (installed) - /usr/local/lib/luarocks/rocks
```

$ ls /usr/local/lib/luarocks/rocks/unsplash-lua/0.5-4/
```bash
doc  rock_manifest  unsplash-lua-0.5-4.rockspec
```
Doc only contains the license and readme.

**Comment by ignacio** [comment]
Yes, a tag would be better, but then I would suggest to change the rockspec slightly to use archived tarballs instead. I just wanted to point out that the structure of the .tar.gz was odd.

Anyway, I can confirm your last rockspec is working fine for me:

~~~~
C:\TEMP\unsplash-lua>luarocks show unsplash-lua

unsplash-lua 0.5-4 - A wrapper for the Unsplash public API

A Lua package for the Unsplash public API. Only contains public scope methods

License:        MIT License
Homepage:       https://github.com/spacingnix/unsplash-lua
Installed in:   c:\dropbox\lua\5.1\

Modules:
        unsplash (c:\dropbox\lua\5.1\/share/lua/5.1/unsplash/init.lua)
        unsplash.constants.index (c:\dropbox\lua\5.1\/share/lua/5.1/unsplash/constants/index.lua)
        unsplash.methods.categories (c:\dropbox\lua\5.1\/share/lua/5.1/unsplash/methods/categories.lua)
        unsplash.methods.collections (c:\dropbox\lua\5.1\/share/lua/5.1/unsplash/methods/collections.lua)
        unsplash.methods.photos (c:\dropbox\lua\5.1\/share/lua/5.1/unsplash/methods/photos.lua)
        unsplash.methods.search (c:\dropbox\lua\5.1\/share/lua/5.1/unsplash/methods/search.lua)
        unsplash.methods.stats (c:\dropbox\lua\5.1\/share/lua/5.1/unsplash/methods/stats.lua)
        unsplash.methods.users (c:\dropbox\lua\5.1\/share/lua/5.1/unsplash/methods/users.lua)
        unsplash.unsplash (c:\dropbox\lua\5.1\/share/lua/5.1/unsplash/unsplash.lua)
        unsplash.utils.querystring (c:\dropbox\lua\5.1\/share/lua/5.1/unsplash/utils/querystring.lua)

Depends on:
        luasec
        luasocket
~~~~

**Comment by spacingnix** [comment]
Alright, everything is working fine on my end too. Thanks for your help!
