### ISSUE TITLE
Luarocks 2.4.2-win32 is broken

### ISSUE THREAD

**Issue by BoarGules** [luarocks/luarocks#714]
I installed luarocks and now I am trying to use it to install luasocket and lfs.

My commands are (neither works) 

```
luarocks install luasocket-2.0.2-3.win32-x86.rock
luarocks install luafilesystem
```

and the response I get is

`C:\Program Files (x86)\LuaRocks\lua\luarocks\command_line.lua:186: bad argument #1 to 'require' (string expected, got table)`

The line of code in `command_line.lua` giving trouble is

```
if commands[command] then
    local cmd = require(commands[command])
```

and putting trace writes in the code reveals that `commands[command]` is indeed a table, of length zero.

This sort of fundamental runtime error is way beyond anything a Lua novice can be expected to fix. If there is something wrong with the command line (which according to the documentation, there isn't), at the least I expect the program to try and tell me what is wrong. I think an untrapped exception counts as broken.

**Comment by daurnimator** [comment]
> and putting trace writes in the code reveals that commands[command] is indeed a table, of length zero.

A length of zero just means there are no numeric indices. This is expected: the table is a mapping from strings to functions. You could instead inspect the table with:

```lua
for k,v in pairs(commands) do print(k,v) end
```

**Comment by hishamhm** [comment]
Looks like you have leftovers from LuaRocks 2.0.x in your system, mixed with LuaRocks 2.4.2.

How did you install LuaRocks 2.4.2? Did you install LuaRocks 2.0.x first?

**Comment by BoarGules** [comment]
I was only aware of installing LuaRocks 2.4.2. But now that you ask, I see that I also tried and failed to install LuaDist-Batteries 0.9.8, and it had LuaRocks inside it: looks like 2.0.10.  I deleted every trace I could find and reinstalled and it runs, so now the only remaining problem is to set up PATH, INCLUDE and LIB correctly, which is no picnic on a machine not set up for development in C.
