### ISSUE TITLE
`luarocks show luasocket` crashes

### ISSUE THREAD

**Issue by ildar** [luarocks/luarocks#718]
Can you help? version 2.4.2 (also seen on 2.2.2)

> $ luarocks list
> 
> Installed rocks:
> ----------------
> 
> luasocket
>    3.0rc1-1 (installed) - /usr/lib/luarocks/rocks
> 
> $ luarocks show luasocket
> 
> LuaSocket 3.0rc1-1 - Network support for the Lua language
> 
> LuaSocket is a Lua extension library that is composed by two parts: a C core
> that provides support for the TCP and UDP transport layers, and a set of Lua
> modules that add support for functionality commonly needed by applications that
> deal with the Internet.
> 
> License: 	MIT
> Homepage: 	http://luaforge.net/projects/luasocket/
> Installed in: 	/usr
> 
> Modules:
> 	ltn12 (/usr/share/lua/5.1/ltn12.lua)
> 	mime (/usr/share/lua/5.1/mime.lua)
> 	mime.core (/usr/lib64/lua/5.1/mime/core.so)
> 	socket (/usr/share/lua/5.1/socket.lua)
> 	socket.core (/usr/lib64/lua/5.1/socket/core.so)
> 	socket.ftp (/usr/share/lua/5.1/socket/ftp.lua)
> 	socket.headers (/usr/share/lua/5.1/socket/headers.lua)
> 	socket.http (/usr/share/lua/5.1/socket/http.lua)
> 	socket.serial (/usr/lib64/lua/5.1/socket/serial.so)
> 	socket.smtp (/usr/share/lua/5.1/socket/smtp.lua)
> 	socket.tp (/usr/share/lua/5.1/socket/tp.lua)
> 	socket.unix (/usr/lib64/lua/5.1/socket/unix.so)
> 	socket.url (/usr/share/lua/5.1/socket/url.lua)
> 
> Depends on:
> 	lua >= 5.1 (using 5.1-1)
> 
> Error: LuaRocks 2.4.2 bug (please report at https://github.com/keplerproject/luarocks/issues).
> /usr/share/lua5/luarocks/util.lua:340: bad argument #1 to 'pairs' (table expected, got nil)
> stack traceback:
> 	[C]: in function 'pairs'
> 	/usr/share/lua5/luarocks/util.lua:340: in function 'keys'
> 	/usr/share/lua5/luarocks/util.lua:372: in function 'sortedpairs'
> 	/usr/share/lua5/luarocks/show.lua:135: in function </usr/share/lua5/luarocks/show.lua:75>
> 	(tail call): ?
> 	[C]: in function 'xpcall'
> 	/usr/share/lua5/luarocks/command_line.lua:187: in function 'run_command'
> 	/usr/bin/luarocks:33: in main chunk
> 	[C]: ?

**Comment by hishamhm** [comment]
Thanks for reporting! I couldn't reproduce it here as it seems to be caused by a manifest file in a bad state, but I added a sanity check just in case.
