### ISSUE TITLE
Error: No results matching query were found.

### ISSUE THREAD

**Issue by mogui** [luarocks/luarocks#720]
Hi all,
I upload correctly my module on luarocks root manifest

```
luarocks upload --api-key=XXXX external-oauth-1.1-1.rockspec
Sending external-oauth-1.1-1.rockspec ...
Packing external-oauth
  adding: external-oauth-1.1-1.rockspec (deflated 47%)
  adding: kong-external-oauth (deflated 76%)
Sending /Users/sourcenik/develop/kong-external-oauth/external-oauth-1.1-1.src.rock ...

Done: http://luarocks.org/modules/mogui/external-oauth
```

But I don't know where it goes wrong because I cannot install it like it doesn't exists on the manifest
```
luarocks install --local external-oauth

Error: No results matching query were found.
```

I see it present on the root manifest https://luarocks.org/m/root/recent

also it seems to happen for other packages (ie. kong-lapis)

What do I do wrong?

**Comment by daurnimator** [comment]
My first suspected cause is using luarocks configured for lua 5.2 or 5.3, while your package only supports lua 5.1. Could you show the output of `luarocks config --lua-ver`?

**Comment by mogui** [comment]
@daurnimator yep that was the problem I was referencing as ~>5.1 and not >= 5.1
Thanks for the tips, it solved the issue !!
