### ISSUE TITLE
Install rock dependencies of a rockspec without building the rockspec

### ISSUE THREAD

**Issue by agladysh** [luarocks/luarocks#721]
In a development environment I need to install the dependencies of a rock I'm working on, but I don't need to install the rock itself (since I'm working on it).

Is there an oneliner for this that I missed?

NB: If `luarocks show` would work with an uninstalled rockspec file, that would do as well. It wouldn't check the versioning, but close enough.

**Comment by ignacio** [comment]
Hi! I added the flag --only-deps to the install command [a while ago](https://github.com/luarocks/luarocks/commit/6b350de4daaccba8b142c5db0d8fb8fabaa1649b). Is this what you need?

**Comment by agladysh** [comment]
Cool. I looked at `luarocks make`, so I didn't notice this flag :) Should `luarocks make` also support it>

**Comment by daurnimator** [comment]
> Should luarocks make also support it?

I'm not sure that makes sense? `luarocks make` is different from `luarocks install` in that it uses the sources in the current directory to build rather than downloading them from the url in the rockspec.

**Comment by agladysh** [comment]
OK, fair enough. Sorry for the noise.

**Comment by daurnimator** [comment]
> OK, fair enough. Sorry for the noise.

That wasn't a "no": I'm honestly not sure if we should add it or not. I'd like to see arguments for either side.

**Comment by agladysh** [comment]
> That wasn't a "no": I'm honestly not sure if we should add it or not. I'd like to see arguments for either side.

Sure. But since I didn't come up with a strong arguments for that addition either (except increasing visibility of the feature somewhat), I didn't push it :)

**Comment by hishamhm** [comment]
Well, `luarocks make --only-deps` would end up behaving exactly the same as `luarocks install --only-deps`, so it seems a bit redundant. I could take a PR for that if it helps discoverability and doesn't add a lot of code, but it doesn't seem too necessary.

**Comment by agladysh** [comment]
@hishamhm can we simply add a See also like note to the `make` help? It will be enough.
