### ISSUE TITLE
Installation Process overcomplicated

### ISSUE THREAD

**Issue by captain1242** [luarocks/luarocks#727]
I am now trying to Install Luarocks since half an hour and this dam thing won't install properly. I tryed it on Windows and Linux on both I always get a "Fatal error" when I try to install something, like "Install mysql to continue" mysql is installed and working but your thing searches for something that doesen't exists.

So How the hell do I Install this?

**Comment by mpeterv** [comment]
Are you trying to install Luarocks itself or some mysql-related package available via Luarocks? What's the command you are trying to run and what's the output?

**Comment by captain1242** [comment]
I am trying to Install it on linux, and finnaly got it woorking
and I am trying to installl the luasql-mysql package
``` luarocks install luasql-mysql
Installing https://luarocks.org/luasql-mysql-2.3.5-1.rockspec

Error: Could not find header file for MYSQL
  No file mysql.h in /usr/local/include
  No file mysql.h in /usr/include
You may have to install MYSQL in your system and/or pass MYSQL_DIR or MYSQL_INCDIR to the luarocks command.
Example: luarocks install luasql-mysql MYSQL_DIR=/usr/local
```

**Comment by captain1242** [comment]
Where the hell am I supposed to get those files? Mysql does not offer them -.-

**Comment by daurnimator** [comment]
> Where the hell am I supposed to get those files? Mysql does not offer them -.-

What distro do you use? e.g. on debian stretch you need to `apt install libmariadbclient-dev`

**Comment by captain1242** [comment]
I was searching for MySQL libs and just found the mysql client .. nevermind then 

Now last question: 
How do I code with the stuff I downloaded? ^^'
The documentation is unclear to me on anything

**Comment by daurnimator** [comment]
> How do I code with the stuff I downloaded? ^^'

For that you'll have to go read the documentation of the package you downloaded.
e.g. for that luasql-mysql package, you will need to refer to https://keplerproject.github.io/luasql/examples.html

**Comment by captain1242** [comment]
No I mean like:

Lets say I coded x.lua
with the given documentation
Now how do I open and Host the file with luarocks, so that it permanently runs?

**Comment by daurnimator** [comment]
> Now how do I open and Host the file with luarocks, so that it permanently runs?

What do you mean "open and Host"?
luarocks is a package manager. not a daemon manager.

**Comment by captain1242** [comment]
Well Lets say I want to make an Discord bot with lua and have all the libs for it. Now I need to include the downloaded files, how do I do that? And afterwards when I am done, how can I run the lua file permanently?

**Comment by mpeterv** [comment]
You need to get some hosting, install luarocks on your server, install your dependencies using luarocks, then run your discord bot as a daemon. Or at least with `nohup lua bot.lua &`. But it is probably overcomplicated.

**Comment by captain1242** [comment]
You know for a beginner it is :P 
But hey you were born a professional I see
