### ISSUE TITLE
Error when building & using in OpenResty (CentOS): "module 'luarocks.cfg' not found"

### ISSUE THREAD

**Issue by sroccaserra** [luarocks/luarocks#729]
Hi,

I'm trying to use LoaRocks with OpenResty, on CentOS 7.

I install LuaRocks in a Dockerfile like this:

```
ENV LUAROCKS="luarocks-2.4.3"
RUN wget http://luarocks.org/releases/$LUAROCKS.tar.gz
RUN tar -xzvf $LUAROCKS.tar.gz
RUN cd $LUAROCKS/ && \
    ./configure \
        --with-lua=/usr/local/openresty/luajit \
        --lua-suffix=jit \
        --with-lua-include=/usr/local/openresty/luajit/include/luajit-2.1 && \
    make && \
    make install
```

Then, when I try to run luarocks, I have the following error message:

```
# luarocks
lua: /usr/local/bin/luarocks:4: module 'luarocks.cfg' not found:
	no field package.preload['luarocks.cfg']
	no file './luarocks/cfg.lua'
	no file '/usr/share/lua/5.1/luarocks/cfg.lua'
	no file '/usr/share/lua/5.1/luarocks/cfg/init.lua'
	no file '/usr/lib64/lua/5.1/luarocks/cfg.lua'
	no file '/usr/lib64/lua/5.1/luarocks/cfg/init.lua'
	no file './luarocks/cfg.so'
	no file '/usr/lib64/lua/5.1/luarocks/cfg.so'
	no file '/usr/lib64/lua/5.1/loadall.so'
	no file './luarocks.so'
	no file '/usr/lib64/lua/5.1/luarocks.so'
	no file '/usr/lib64/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/local/bin/luarocks:4: in main chunk
	[C]: ?
```

**Comment by sroccaserra** [comment]
Note: luarocks 2.0.13 works fine in the same context.

**Comment by siffiejoe** [comment]
Without explicit prefix LuaRocks is installed into `/usr/local/`. I don't see `/usr/local` anywhere here:

>	no file './luarocks/cfg.lua'
>	no file '/usr/share/lua/5.1/luarocks/cfg.lua'
>	no file '/usr/share/lua/5.1/luarocks/cfg/init.lua'
>	no file '/usr/lib64/lua/5.1/luarocks/cfg.lua'
>	no file '/usr/lib64/lua/5.1/luarocks/cfg/init.lua'
>	no file './luarocks/cfg.so'
>	no file '/usr/lib64/lua/5.1/luarocks/cfg.so'
>	no file '/usr/lib64/lua/5.1/loadall.so'
>	no file './luarocks.so'
>	no file '/usr/lib64/lua/5.1/luarocks.so'
>	no file '/usr/lib64/lua/5.1/loadall.so'

So apparently your `LUA_PATH` does not contain the correct search directories (same for `LUA_CPATH`).

**Comment by mpeterv** [comment]
What are contents of /usr/local/bin/luarocks? Does it work if you pass '--prefix=/usr' to ./configure?

**Comment by mpeterv** [comment]
Actually, it should work if you just run 'make build' instead of plain 'make'.

**Comment by hishamhm** [comment]
Closing due to lack and feedback and misconfigured test case.

**Comment by z7z8th** [comment]
Still have this issue if I set LUA_PATH to 
`export LUA_PATH="?;?.lua;$HOME/.luarocks/share/lua/5.3/?.lua;$LUA_PATH"`

I have to `unset LUA_PATH` to make luarocks work.

Finally I figured it out, should replace the `$LUA_PATH` with `;`, since `;;` means the default path.
e.g.:
`export LUA_PATH="?;?.lua;$HOME/.luarocks/share/lua/5.3/?.lua;;"`

**Comment by smashedtoatoms** [comment]
I just pushed a really small change that might fix it.  Can you pull the latest version of the plugin and try it again?

**Comment by helloJiu** [comment]
解决办法:
ln -s  /usr/local/openresty/luajit/bin/luajit lua
mv lua /usr/bin/
