### ISSUE TITLE
Uninstall LuaRocks

### ISSUE THREAD

**Issue by captain1242** [luarocks/luarocks#731]
I am trying to remove luarocks from my Debian server, I already found the other issue:
https://github.com/luarocks/luarocks/issues/566

but that doesen't help removing the command from the system, so how do I fully remove it with removing the command?

**Comment by hishamhm** [comment]
That depends on how you installed it. If you installed it from the tarball
and you installed into /usr/local, this will suffice:

```
sudo rm -rf /usr/local/bin/luarocks* /usr/local/lib/luarocks
```

**Comment by Querela** [comment]
Just a minor update (I was looking into a slim Dockerfile), I deleted the following:
```bash
# ".../" as placeholder, in my openresty docker image, paths started with "/usr/local/openresty/luajit/" but this depends on your system
# files
.../bin/luarocks
.../bin/luarocks-admin
# folders
.../etc/luarocks
.../lib/luarocks
.../share/lua/5.1/luarocks  # "5.1" might depend on your lua version

# If you installed something, it may also create cache folders:
/tmp/luarocks_local_cache*
```
