### ISSUE TITLE
Site-local luarocks/core/site_config_5_2.lua file not found. Incomplete installation?

### ISSUE THREAD

**Issue by danbcooper** [luarocks/luarocks#735]
Release #734 changes where the site_config_5_2.lua is supposed to be loaded from, but the file is not located in the core directory.  The change that causes this is:

src/luarocks/core/cfg.lua:22

-local ok, site_config = pcall(require, "luarocks.site_config_"..version_suffix)
 +local ok, site_config = pcall(require, "luarocks.core.site_config_"..version_suffix)

**Comment by hishamhm** [comment]
Thanks for the report! The Makefiles have been adjusted accordingly.
