### ISSUE TITLE
Install broken (update Makefile.setup.inc)

### ISSUE THREAD

**Issue by danbcooper** [luarocks/luarocks#738]
Moving luarocks/index.lua to luarocks/admin/index.lus breaks install
Also luarocks/core/type_check.lua moved to luarocks/type_check.lua breaks install
Also luarocks/fun.lua not copied on install
Also luarocks/type/rockspec.lua and luarocks/type/manifest.lua not copied on install
Also luarocks/cmd/which.lua not copied on install

Anyway, it looks like a an update to Makefile.setup.inc was omitted in this latest update...

**Comment by hishamhm** [comment]
Indeed! It seems that the Travis environment is testing the code but is not really testing the installer!

In any case, thanks for the report! It's now fixed.
