### ISSUE TITLE
install with --tree creates wrong wrapper (does not use the tree)

### ISSUE THREAD

**Issue by mikz** [luarocks/luarocks#740]
Steps to reproduce:

```shell
luarocks install --server=http://luarocks.org/dev lua-rover --tree lua_modules
cat lua_modules/bin/rover
```

It will have options like:

```
-e 'package.path="~/.luarocks/share/lua/5.1/?.lua;~/.luarocks/share/lua/5.1/?/init.lua;"..package.path; package.cpath="~/.luarocks/lib/lua/5.1/?.so;"..package.cpath'
```

That means if the there is globally/locally installed package its source will take precedence over the one in the tree.

The problem is that the CLI tries to set the tree: https://github.com/luarocks/luarocks/blob/e46fd3ea1c597c57f69376eb7a136133c3fa393e/src/luarocks/command_line.lua#L41

But the wrapper takes package paths from cfg: https://github.com/luarocks/luarocks/blob/f1473f71235bb89555dea7041b536144d32bac8c/src/luarocks/fs/unix.lua#L73

Which returns all rocks trees: https://github.com/luarocks/luarocks/blob/f1473f71235bb89555dea7041b536144d32bac8c/src/luarocks/core/cfg.lua#L711-L730

I believe `--tree` should offer strict isolation and remove all other rocks trees. But that might be significant change.

Maybe some other flag to turn on isolation and truly override all the trees with just the one passed as --tree.

**Comment by hishamhm** [comment]
Thanks for reporting! This is now fixed.

> I believe --tree should offer strict isolation and remove all other rocks trees. But that might be significant change.

Yes, because a tree may depend on rocks installed outside of it. Adding full isolation for trees would be indeed a significant change beyond the scope of this particular issue.

**Comment by mikz** [comment]
Thank you!
