### ISSUE TITLE
Missing --version flag

### ISSUE THREAD

**Issue by Zamiell** [luarocks/luarocks#742]
Is there a particular reason why `luarocks --version` doesn't work, or is this just an oversight? I want to know which version I have installed...

**Comment by mpeterv** [comment]
Works for me:

```
luarocks --version
/home/mpeterv/lua53/bin/luarocks 2.4.3
LuaRocks main command-line interface
```

What it the first line of `luarocks --help`? It should also have version,

**Comment by Zamiell** [comment]
Oh, help does provide the version.
