### ISSUE TITLE
luarocks + nix questions

### ISSUE THREAD

**Issue by teto** [luarocks/luarocks#743]
I am trying to make lua support on par with other languages on nixos, a linux distribution based on the "nix" package manager. nixos is very peculiar because it doesn't respect the usual fielsystem hierarchy and thus you end up with packages installed  in something like `/nix/store/a7vagy9cz5wnfr8mzl4wh32xpb5a8jk6-lua-5.2.3-lua_cliargs` (for lua_cliargs) so that paths usually have to be explicit.
Right now I've modified luarocks so that it can convert a rockspec to a nix expression (hopefully my fork can be converted to an addon once luarocks addons support is merged).
Here is an example of a nix expression for the package "ansicolors" (the generated code style is not great) 
```
ansicolors = buildLuaPackage rec {
src= fetchurl {
url="https://github.com/kikito/ansicolors.lua/archive/v1.0.2.tar.gz";
sha256="0r4xi57njldmar9pn77l0vr5701rpmilrm51spv45lz0q9js8xps"; 
};
version="1.0.2-3";
name="ansicolors";
propagatedBuildInputs=[ lua];
meta={
homepage="https://github.com/kikito/ansicolors.lua";
description="Library for color Manipulation.";
license=stdenv.lib.licenses.mit; }
; }  
```
`buildLuaPackage` is a function in charge of installing the package and its dependancies. I am now looking into what's the best way to install these packages, knowing that nix should deal with the dependencies itself. Ideally I would to install a single package via `luarocks install --tree $nixPath lua_cliargs` .
So far it generated this kind of error:
`Failed creating temporary cache directory /homeless-shelter/.cache/luarocks/https___luarocks.org`
Sorry for the long introduction but here are more concrete questions:
- would using --force-config be enough to bypass these errors ? can I set the cache folder myself ?
- is it possible for luarocks to install one package without its dependencies ?
- nix fetches/checks/caches https://github.com/kikito/ansicolors.lua/archive/v1.0.2.tar.gz automatically so I would like luarocks to use this binary. Is there any way to do this ? otherwise I can patch the rockspec to use the local archive.
- an alternative could be to record the commands used by luarocks to build/install the package and writes them directly into the nix derivation. This way there is no need to use luarocks and it seems doable via overriding some commands (for instance `builtin.execute(...)`. My concern is that it might make the derivations too big.

**Comment by daurnimator** [comment]
See e.g. https://github.com/luarocks/luarocks/issues/671

Btw, don't forget external_dependencies.

**Comment by teto** [comment]
Good catch about `external_dependencies`.
Is your package manager nix too ? there is one messy post here https://github.com/NixOS/nixpkgs/issues/29957 bottomline is the luarocks fork is https://github.com/teto/nixpkgs/tree/luafix .
Maybe we can work together on this.

**Comment by daurnimator** [comment]
> Is your package manager nix too ?

Nope. I use pacman (Arch Linux)

**Comment by teto** [comment]
Not sure for pacman, but maybe the easiest way might be in my case to rewrite the rockspeck to remove the dependencies, and give a local url.

**Comment by hishamhm** [comment]
> can I set the cache folder myself ?

Yes, that is the `local_cache` variable in the LuaRocks config file.

> is it possible for luarocks to install one package without its dependencies ?

Yes, with `--deps-mode=none`.

> nix fetches/checks/caches https://github.com/kikito/ansicolors.lua/archive/v1.0.2.tar.gz automatically so I would like luarocks to use this binary. Is there any way to do this ? otherwise I can patch the rockspec to use the local archive.

Currently no; patching the rockspec to use the local archive works. The alternative is to unpack the archive yourself, `cd` into it and use `luarocks make` (that ignores `source.url` and uses the code in the current dir).

Note however that the basename of `source.url` is not always the archive name. LuaRocks has some smart rules for dealing with `source.url` due to things like redirects and URLs like `http://example.com/file?query=arg`. Generally, if `source.file` is available that's the filename of whatever is downloaded. LuaRocks also implements heuristics to determine what's the dirname to cd into.

Also, some packages (even stable versions), use `git://`; in those cases the source files are stored in the `.rock` file (or downloaded via `git`).

The simplest approach for you would be to let nix fetch/cache/check `.src.rock` files instead — they contain the upstream sources and LuaRocks knows how to use them.

>  an alternative could be to record the commands used by luarocks to build/install the package and writes them directly into the nix derivation. This way there is no need to use luarocks and it seems doable via overriding some commands (for instance builtin.execute(...). My concern is that it might make the derivations too big.

I think the most robust approach would be to use LuaRocks-as-a-build-system as suggested by @daurnimator in #671. If any of you stumble into any showstoppers to support that, I'll be happy to help fix limitations.

**Comment by teto** [comment]
Thanks for the great information. I had found about luarocks make but not --deps-mode=none which is great. I will work with that and come back if I hit a wall

**Comment by teto** [comment]
"local_cache" is not described in
https://github.com/luarocks/luarocks/wiki/Config-file-format
It would be cool to have a full example of config-5.2.lua in the tree or the wiki. 

I have to override the local_cache because by default it seems to use $HOME but according to nix documentation https://nixos.org/nixos/nix-pills/working-derivation.html
`$HOME is not your home directory, and /homeless-shelter doesn't exist at all. We force packages not to depend on $HOME during the build process. `

```
mkdir: cannot create directory '/homeless-shelter': Permission denied
mkdir: cannot create directory '/homeless-shelter': Permission denied
mkdir: cannot create directory '/homeless-shelter': Permission denied
Warning: Failed searching manifest: Failed creating temporary cache directory /homeless-shelter/.cache/luarocks/https___luarocks.org
```

Also @hishamhm where do you recommend to retrieve the src.rock files ? how can I automate the download url generation ? 

Also how do you advise me to retrieve the list of src.rock available ? I guess I should parse https://luarocks.org/manifest-5.1.json ? How often is it updated ?
Right now I generated nix packages via iterating over moonrocks-mirror *.rockspec but src.rock are more interesting thanks for the tip.

**Comment by daurnimator** [comment]
> I guess I should parse https://luarocks.org/manifest-5.1.json ?

-5.1 is just for lua 5.1 compatible packages.
https://luarocks.org/manifest.json contains packages for all lua versions (as in, some support all lua versions, some only support 5.1, some only support 5.3, etc.).

**Comment by teto** [comment]
The unpack function is really cool, I could get rid my dirty hacks to unpack the thing. There doesn't seem to be a source package for every package. Who decides; the authors ?
So at one point I do 
`luarocks unpack --verbose --force /nix/store/44j6gjvq7xqrvyycn4fv8j2pr2faz2sy-luabitop-1.0.2-1.src.rock`
but apparently luarocks expects the rock.spec name to be the package name. For now I strip the hash so that 's not too much of a problem, just I thought I would share it.
```
os.execute: 	cd '/tmp/nix-build-bitop-1.0.2.drv-9/44j6gjvq7xqrvyycn4fv8j2pr2faz2sy-luabitop-1.0.2-1' && unzip -n '/nix/store/44j6gjvq7xqrvyycn4fv8j2pr2faz2sy-luabitop-1.0.2-1.src.rock'
Archive:  /nix/store/44j6gjvq7xqrvyycn4fv8j2pr2faz2sy-luabitop-1.0.2-1.src.rock
  inflating: luabitop-1.0.2-1.rockspec  
  inflating: LuaBitOp-1.0.2.tar.gz   
Results: 3
  1 (boolean): true
  2 (string): exit
  3 (number): 0

os.execute: 	cd '/tmp/nix-build-bitop-1.0.2.drv-9' && test '-d' '44j6gjvq7xqrvyycn4fv8j2pr2faz2sy-luabitop-1.0.2-1'
Results: 3
  1 (boolean): true
  2 (string): exit
  3 (number): 0

os.execute: 	cd '/tmp/nix-build-bitop-1.0.2.drv-9/44j6gjvq7xqrvyycn4fv8j2pr2faz2sy-luabitop-1.0.2-1' && test '-e' '44j6gjvq7xqrvyycn4fv8j2pr2faz2sy-luabitop-1.0.2-1.rockspec'
Results: 3
```

**Comment by hishamhm** [comment]
> There doesn't seem to be a source package for every package. Who decides; the authors ?

Yes, it's up to them to upload them. `luarocks upload` uploads a .src.rock by default, though. Some .rockspec files don't have a .src.rock by design: "dev" rocks that track the latest HEAD of a repo.

> but apparently luarocks expects the rock.spec name to be the package name. For now I strip the hash so that 's not too much of a problem, just I thought I would share it.

Yes, it enforces that for consistency. Not sure if it does us much good, but since it's been there since day 1 we've just never seen rock/rockspec naming inconsistency issues in the repo.

**Comment by teto** [comment]
Thanks, now I would like to generate a list of all the packages with src.rock available.
`luarocks search --source --all ` sounds like a good start but hte output is not parsing friendly:
It would be cool if  --source could work with --all or as a standalone;
```

   0.1.4-1 (rockspec) - https://luarocks.org
   0.1.4-1 (src) - https://luarocks.org
   0.1.3-1 (rockspec) - https://luarocks.org
   0.1.3-1 (src) - https://luarocks.org
   0.1.2-1 (rockspec) - https://luarocks.org
   0.1.2-1 (src) - https://luarocks.org
   0.1.1-1 (rockspec) - https://luarocks.org
   0.1.1-1 (src) - https://luarocks.org
   0.1.0-1 (rockspec) - https://luarocks.org
   0.1.0-1 (src) - https://luarocks.org
```
I am mostly interested in getting the url to the src so that I can generate the nix derivations automatically.

**Comment by hishamhm** [comment]
@teto For parse-friendly results use `--porcelain`.

**Comment by teto** [comment]
Porcelain is better (though not available in search --help) but (how) can I get the url to download the source, for instance, to compute this link : 
https://luarocks.org/manifests/openresty/lua-cjson-2.1.0-1.src.rock

**Comment by hishamhm** [comment]
Simply concatenate the rock filename with the root manifest URL:
https://luarocks.org/lua-cjson-2.1.0-1.src.rock

**Comment by teto** [comment]
I believe I am close to getting this working, I have one problem during the installation for lua_dir and lib_dir. So for instance the nixos package runs:
`luarocks make --deps-mode=none --verbose --tree /nix/store/1gglq9fhnvsrn6rb70c9nw72plrqhp35-lua-5.2.3-cjson-2.1.0`
that creates
```
/nix/store/1gglq9fhnvsrn6rb70c9nw72plrqhp35-lua-5.2.3-cjson-2.1.0/bin
/nix/store/1gglq9fhnvsrn6rb70c9nw72plrqhp35-lua-5.2.3-cjson-2.1.0/lib
/nix/store/1gglq9fhnvsrn6rb70c9nw72plrqhp35-lua-5.2.3-cjson-2.1.0/share
...
```
So far it is fine. Then nixos tries to populate LUA_(C)PATH with something like LUA_PATH=/nix/store/1gglq9fhnvsrn6rb70c9nw72plrqhp35-lua-5.2.3-cjson-2.1.0/share/lua/5.2/?.lua . 
The problem is that luarocks generates a deep hierarchy such as (for busted):
`/nix/store/c9wz56pgl13p01gqfa8040z79hcxq595-lua-5.2.3-busted-2.0.rc3-0/lib/luarocks/rocks/busted/2.0.rc3-0/.`
I wish it were
`/nix/store/c9wz56pgl13p01gqfa8040z79hcxq595-lua-5.2.3-busted-2.0.rc3-0/lib/`
instead. Nix doesn't need the deep luarocks tree as there is will be only one package in that --tree. I have 3 options:
- appends  `/nix/store/c9wz56pgl13p01gqfa8040z79hcxq595-lua-5.2.3-busted-2.0.rc3-0/lib/luarocks/rocks/busted/2.0.rc3-0/?.lua` to LUA_PATH. It's long, I don't like it. 
- look for the deepest folder in hierarchy and move it closer to the root folder (`mv /nix/store/c9wz56pgl13p01gqfa8040z79hcxq595-lua-5.2.3-busted-2.0.rc3-0/lib/luarocks/rocks/busted/2.0.rc3-0/ * /nix/store/c9wz56pgl13p01gqfa8040z79hcxq595-lua-5.2.3-busted-2.0.rc3-0/lib/`   and add this folder to LUA_PATH
- patch luarocks to install files directly in lib/ and prevent the creation of subfolders. This is the path I favor for now. I guess i have to patch functions in paths.lua but there are quite a few functions I can override, I believe `path.lua_dir(name, version, tree)` is the way to go.

Also another question, how does luarocks check for dependencies ? For now I disable it with  `--deps-mode=none` but does it rely on LUA_PATH or the folder hierarchy (I would tend to say the latter).

**Comment by teto** [comment]
I managed to get basic luarocks integration with nix https://github.com/NixOS/nixpkgs/pull/33903 \o/ Now it needs a lot of polish from my part.
Thanks for your help.

I have another set of questions sorry :) 
1/ Basically on nix, one tree = one package; but if I tell all the trees with  `--rock-trees` to
`make --deps-mode=none --tree $out` then I might be able to remove `--deps-mode=none` ?

2/ Also I wonder what's the status on luarocks addons ? my modifications to luarocks are not invasive so it could easily be an addon IMO

**Comment by teto** [comment]
Since I got the basics working, closing this. Next nixos release is in March and ideally I would like to integrate luarocks before that. Only stopping point so far is https://github.com/luarocks/luarocks/issues/766 .
Thanks
