### ISSUE TITLE
Error: API failure: /upload

### ISSUE THREAD

**Issue by peterbillam** [luarocks/luarocks#744]
luarocks upload http://www.pjb.com.au/comp/lua/ao-1.2.0-0.rockspec    
    . . . all the files get added fine . . .    
    adding: lao/Makefile (deflated 33%)    
    Error: API failure: /upload    
    luarocks --version    
    /usr/local/bin/luarocks 2.4.3    
    Am I doing something wrong ?
[upload_output.txt](https://github.com/luarocks/luarocks/files/1439993/upload_output.txt)

**Comment by daurnimator** [comment]
With `--verbose`?

**Comment by peterbillam** [comment]
Yes, I think so, or at least it looks verbose to me . . .    
luarocks upload --verbose http://www.pjb.com.au/comp/lua/ao-1.2.0-0.rockspec >./tmp/upload_output.txt 2>&1

**Comment by peterbillam** [comment]
The failure point is :    
os.execute:     cd '/home/pjb/lua/ao/1.2.0' && 'curl' -f -k -L --silent --user-a
gent "LuaRocks/2.4.3 linux-x86 via curl" --form "rockspec_file=@http://www.pjb.c
om.au/comp/lua/ao-1.2.0-0.rockspec" --connect-timeout 30 'https://luarocks.org/a
pi/1/\<redacted\>/upload' -o '/tmp/lua_ugbcUg'    
Results: 3    
  1 (nil): nil    
  2 (string): exit    
  3 (number): 26    

Error: API failure: /upload    

Does that mean my \<redacted\> is invalid ?

**Comment by daurnimator** [comment]
You can only upload a local file. Not a remote url....

**Comment by peterbillam** [comment]
Yes :-) It works.      
(perhaps there could be a helpful error message to cover this case?)    
Many thanks.
