### ISSUE TITLE
lua.lua:767: attempt to call field 'getpwuid' (a nil value)

### ISSUE THREAD

**Issue by martin-eden** [luarocks/luarocks#745]
Hello,

I've installed luarocks 2.4.3 from .tar archive. When I'm entering `luarock` I'm getting following error:
```
$ luarocks
lua: /usr/local/share/lua/5.1/luarocks/fs/lua.lua:767: attempt to call field 'getpwuid' (a nil value)
stack traceback:
	/usr/local/share/lua/5.1/luarocks/fs/lua.lua:767: in function 'attributes'
	/usr/local/share/lua/5.1/luarocks/command_line.lua:46: in function 'is_ownership_ok'
	/usr/local/share/lua/5.1/luarocks/command_line.lua:197: in function 'run_command'
	/usr/local/bin/luarocks:33: in main chunk
	[C]: ?
```
Lua version used is 5.1.5. (On the other machine with Lua 5.3.4 luarocks works fine.)

Did you meet such problem? How this can be mitigated?

**Comment by hishamhm** [comment]
What version of luaposix do you have in the machine where the problem happens?

**Comment by martin-eden** [comment]
Good hint, thank you!

`luaposix` module was probably old version `29-1`. Looks like luarocks tries to use `posix` module opportunistically, so I've renamed `/usr/local/share/lua/5.1/posix.lua` to another name and it worked.

Now `$ luarocks` displays usage help.
