### ISSUE TITLE
Luarocks does not work under wine

### ISSUE THREAD

**Issue by ZyX-I** [luarocks/luarocks#749]
I am currently trying to use luarocks to install lua packages under wine (for testing, as it should be easier to setup and require less resources then virtual machine) and found that it for some reason uses syntax which `os.execute` does not accept, specifically `C: & cd C:\… & …`: that fails with `Can't recognize 'c: ' as an internal or external command, or batch script.` (actually, not that, but a message about missing directories and no rights to write, this one comes up when I use `--verbose`). Note that failure message contains trailing whitespace, syntax appears to be fine if I just get rid of spaces around `&`.

**Comment by ZyX-I** [comment]
Something strange is going later, wine is not able to swallow `C:&cd "C:\luarocks"&"C:\luarocks\tools\mkdir" -p  "C:\users\zyx\Local Settings\Application Data\LuaRocks\Cache\http___luarocks.logiceditor.com_rocks"`: it looks like `os.execute` from luajit runs cmd.exe so that it is not able to work with quoted arguments properly.

**Comment by hishamhm** [comment]
> it looks like os.execute from luajit runs cmd.exe

But isn't that the default command interpreter no Windows?

The syntax LuaRocks generates runs fine in Windows boxes (see Appveyor CI)... I wonder if this is a limitation in Wine's cmd.exe instead?

**Comment by ZyX-I** [comment]
@hishamhm It may be powershell as well, but this is not the point: point is that cmd.exe (of at least the wine version I am currently using which is wine-any-2.19 from Gentoo repositories) can’t swallow those spaces, but `c:&…` works as expected. Issue in the next comment is separate and if I would not find a way to workaround it spaces are not worth fixing.

**Comment by hishamhm** [comment]
This does not sound like a bug in LuaRocks at all, but rather a bug in Wine. You should report a bug to them, ideally writing a non-LuaRocks-specific test case that demonstrates a command line with `c: & ` and spaces that works on Windows but fails in Wine.

**Comment by hishamhm** [comment]
Thanks for submitting bug reports to Wine! Closing this issue.
