### ISSUE TITLE
linking problems using external dependencies in MacOSX systems

### ISSUE THREAD

**Issue by amadeubarbosa** [luarocks/luarocks#751]
I'm using LuaRocks 2.4.3 and I got some missing symbols of external dependencies in lua-iconv and org.conman.iconv like that:
```
lua: error loading module 'org.conman.iconv' from file '/usr/local/lib/lua/5.2/org/conman/iconv.so':
	dlopen(/usr/local/lib/lua/5.2/org/conman/iconv.so, 6): Symbol not found: _iconv
  Referenced from: /usr/local/lib/lua/5.2/org/conman/iconv.so
  Expected in: flat namespace
 in /usr/local/lib/lua/5.2/org/conman/iconv.so
```

At installation time, luarocks seems don't put -liconv at linking as following:
```
$ luarocks install org.conman.iconv
Installing https://luarocks.org/org.conman.iconv-2.0.0-1.src.rock
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/include -c iconv.c -o iconv.o
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -bundle -undefined dynamic_lookup -all_load -o org/conman/iconv.so -L/usr/local/lib iconv.o
org.conman.iconv 2.0.0-1 is now installed in /usr/local (license: LGPL)
```

And as otool shows:
```
$ otool -L /usr/local/lib/lua/5.2/org/conman/iconv.so 
/usr/local/lib/lua/5.2/org/conman/iconv.so:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

I add `library = "iconv"` in rockspec of org.conman.iconv and lua-iconv but it doesn't work.

Then I replaced the LDFLAGS using the tip on #429. I forced the link against iconv using LIBFLAG as following:
``` 
$ luarocks install org.conman.iconv LIBFLAG="-bundle -undefined dynamic_lookup -all_load -liconv"
```

And it works as expected:
```
$ otool -L /usr/local/lib/lua/5.2/org/conman/iconv.so 
/usr/local/lib/lua/5.2/org/conman/iconv.so:
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

Have I missed something? I think it's a bug of luarocks builtin build process on MacOSX systems.

**Comment by hishamhm** [comment]
It's a bug in the rockspecs, plus an unintuitive behavior in LuaRocks. In the lua-iconv rockspec, the "iconv" library entry is set on to `cygwin`. You need a similar subtable for `macosx`.

The unintuitive behavior is that adding the library entry in the `external_dependencies` section does not request linking the library. That is because some rocks may contain multiple modules and only some of them may need the dependency. So one needs both `external_dependencies.ICONV.library = "iconv"` and `build.modules.iconv.libraries = {"iconv"}`

**Comment by hishamhm** [comment]
I uploaded an updated rockspec for `lua-iconv`, which includes the fixes mentioned above. Feel free to reopen if it doesn't fix the issue. Thanks!!

**Comment by amadeubarbosa** [comment]
Thanks @hishamhm ! It works!

Sean ( @spc476 ), please check this luarocks issue. The rockspec of org.conman.iconv also needs be updated to fix the linking against iconv system library correctly in some platforms.

**Comment by spc476** [comment]
Sorry this took so long (waiting for Xmas vacation, then forgot), but I finally uploaded a modified rockspec for org.conman.iconv.
