### ISSUE TITLE
Using custom interpretor

### ISSUE THREAD

**Issue by Hydroque** [luarocks/luarocks#753]
https://github.com/Hydroque/LuaConsole

So I am the author of this interpreter that is being built to supersede lua's console. It can be built with 5.1 5.2 and 5.3. I use windows 7 64 bit and I have mingw32 and mingw64. I ran `install /F /MW /L` because I couldn't get luarocks to let me use my custom interpreter. So all is fine when I `luarocks install luasocket` and use the built in 5.1 interpreter to run the code - it loads DLLs nicely and everything.

What constitutes working:
* ability to load rocks and use them
* no very weird hackery

Some things I tried:
* I tried replacing the object archives with a fresh install of liblua.a including includes
* Ensuring everything was 32 bit
* Ensuring everything was built with the same liblua.a
* Ensuring that LUA_PATH and LUA_CPATH pointed properly to `luarocks path --bin`
* a = require("luarocks.loader")

The errors I am getting:
![image](https://user-images.githubusercontent.com/7494772/34088568-20dbca94-e378-11e7-9c78-aba054e52b1e.png)

Using the script 
```
local lrSocket = require("socket")

local host = "*"
local port = 8080

local socket = assert(lrSocket.bind(host, port))
local i, p = socket:getsockname()
assert(i, p)

print("Waiting for connection...")
local conn = socket:accept()

print("Connected.")
```

**Comment by Hydroque** [comment]
Okay so I figured out after extensive testing that its luasocket which is having issues. However, the lack of support for easily using luarocks's stuff is problematic. There should be a wiki page or something explaining what goes into situating the built-in lua 5.1 in a custom interpreter.

**Comment by siffiejoe** [comment]
Have you checked that your interpreter can load binary modules at all? You seem to be using the static Lua library `liblua.a`, which leads to problems on Windows where you have to link the shared Lua library (and the shared C library) to both the extension and your interpreter.

**Comment by Hydroque** [comment]
Everything checks out fine. Lua can be built as dll or packaged in .a and work both ways. LuaRocket isn't at fault, but the 'how to get started' is lacking. I haven't found a setup method or anything for luarocket to be embedded into my lua environment. `luarocket = dofile("luarocket.lua")` seems to work okay, but then it issues a bunch of text to the console. I assume the `luarocket/loader.lua` would fix this as briefly, but indirectly, mentioned in the wiki. One of my biggest complaints has to be the lack of user confirmation of what to include in the build of the .dll - I'd like to set up -D's, however no documentation can be figured out about it easily. However, this doesn't pertain to this problem and the topic should be closed. Me complaining isn't going to do anything on this thread.
