### ISSUE TITLE
LuaRocks refuses to remove rocks if they have missing files

### ISSUE THREAD

**Issue by alexbuzzbee** [luarocks/luarocks#755]
I use luacheck to lint my Lua code. I've had it installed through LuaRocks for a while. When I tried to run it, it failed for an unknown reason. So, I tried to reinstall it. Instead of removing the old, broken copy and installing a new, working one, LuaRocks complained that files were missing from the luacheck rock and failed to uninstall it. I've now been struggling to force LuaRocks to remove it by `touch`ing the files it wants for quite a while. This seems like an obvious problem; if there are files missing from a package, that should not impede removing it, otherwise broken packages could never be fixed!

I'm running LuaRocks 2.4.3 on Lua 5.3. My OS is macOS 10.12.6 on a MacBook Pro. The broken rock is installed in the `/usr/local` tree, and I installed LuaRocks through Homebrew's `lua` package.

**Comment by alexbuzzbee** [comment]
I was able to fix the problem by installing the same version of luacheck in the `~/.luarocks` tree, copying its files to the `/usr/local` tree, making sure there were no "old version" copies of luacheck hanging around from my previous attempts to remove it, and finally doing a plain old `luarocks remove luacheck`.

**Comment by hishamhm** [comment]
This should be fixed in the latest master, please check it out!

**Comment by hishamhm** [comment]
See https://github.com/luarocks/luarocks/commit/a9e5469bcd85e0627576e56ff07aa17203954c31
