### ISSUE TITLE
luarocks should look for "libfoo.lib" when looking for "foo" on Windows

### ISSUE THREAD

**Issue by seishun** [luarocks/luarocks#756]
I'm trying to install the `http` module. I'm getting the following error:

```
Error: Failed installing dependency: https://luarocks.org/cqueues-20171014.51-0.src.rock - Could not
 find library file for OPENSSL
  No file ssl.lib in c:/external/lib
  No file ssl.dll in c:/external/lib
  No file libssl.dll in c:/external/lib
```

However, there are no files named like that in my OpenSSL installation. The closest I have is `libssl.lib`. luarocks should look for this pattern too.

**Comment by daurnimator** [comment]
The libraries have different names on windows.
The cqueues rockspec doesn't include the windows-specific names, as it doesn't support windows.

See https://luarocks.org/manifests/daurnimator/luaossl-scm-0.rockspec for what linking to openssl looks like (pay mind to the windows specific sections)

**Comment by seishun** [comment]
It became clear later than the `http` module doesn't work on Windows at all, so this is no longer relevant to me.
