### ISSUE TITLE
Linux needs shell script instead of shebang luarocks execution

### ISSUE THREAD

**Issue by Hydroque** [luarocks/luarocks#758]
https://github.com/Hydroque/LuaConsole/wiki/LuaRocks-Support-Linux-GCC

If you look at my wiki here, it's really bumming out that a Linux user has to go through this much trouble to compatibly use their interpreter (not just mine). The shebangs don't exactly let you pass parameters and my interpreter allows you to define global variables at two different points in execution of a file and loading of dependencies.

The changes are simple...
1. move luarocks from /usr/bin to install dir /usr/local/etc/lua/5.3/ iirc
2. add a shell script in its place `sudo chmod +x /usr/bin/luarocks`
```
#!/bin/sh

"lua" "/usr/local/bin/luarocks_init.lua" $*

```

However, it might be proper to change "lua" to a direct path based on the configuration.  
If not for me, do it for consistency with windows <3

**Comment by hishamhm** [comment]
It seems most of the complication comes from the fact that your interpreter needs the command argument to be passed as `-Dcommand=arg` instead of just using `arg`. This will cause you compatibility issues with all sorts of scripts, not just LuaRocks. Have you considered instead changing the way you parse command-line arguments to make it compatible with PUC-Lua and LuaJIT?

**Comment by Hydroque** [comment]
`-Dcommand=arg` is a feature used to add support to LuaRocks because of this problem incompatibility. It's how it is being handled.

It's not the fact that `arg` isn't defined - LuaRocks doesn't even use arg in this situation. LuaRocks uses a tuple docked in the lua_State that is passed. However, it is passed very poorly I might add. The fact that native lua interpreter can't use args when doing -e is problem-some - a file must be defined. You only support one way to get your library working here. There is a strong reason why its a push to deprecate PUC-Lua and they are lined out all over the place.  
1. ugly code
2. poorly organized
3. hard to read
4. functionality isn't that good
5. I easily made this program superior to PUC-Lua
6. Idle development
7. lack of features that make programming Lua inhibited
8. lack of common features
9. iffy libraries
10. I just stated a bug in the above paragraph
11. use of `arg` instead of `args`
Just to name a few...  

Globals using -D is a great workaround, don't get me wrong, as it adds ability to customize even further. If you take a look at what I added to the luarocks.lua file, you can see that a string can now be used to pass in commands to LuaRocks when the environment doesn't support passing a tuple to it - especially if they require luarocks.lua while already in REPL mode or building a wrapper.

Support for LuaJIT is pretty easy. Their code is a modified version of the lua interpreter. We both base our code off the same thing. I am actually considering adding it as a dll, but modifying the way the REPL works. Should be a very easy task that takes an hour. Good thing we are keeping the MIT going around. It will be an optional dependency, though, and will have to compile differently. This is no problem of course - people like their JIT. One issue would be how to handle the lua_State and I suppose they should be separate and a parameter -jit would need to be passed. However, I am still to add multiple lua_States support and a manager. Who knows - they could work in unison. All in all it's just merging in a compatible way. Hopefully we don't run out of arguments - there are only 26 letters in the alphabet.

**Comment by hishamhm** [comment]
I'm not sure I was able to understand everything you said. But my point was, if your interpreter is calling `luaw`, why doesn't using `./configure --lua-suffix=w` in LuaRocks just work? Can't your interpreter take command-line arguments the same way as Lua and LuaJIT?

**Comment by Hydroque** [comment]
No. My interpreter accepts arguments different in two forms
`luaw -Dglobal=value`
`luaw -Dtab1.tab2.val=value`
`luaw -n a b c`

whereas a b c gets stored into the arg table. I don't actually force the script to use a tuple upon execution. The way you are supporting it now, the args are getting sent to the script and appearing a tuple due to the nature of variable arguments. It is literally a function(...) end. They are in two places actually and you lack the later so I must resort to editing. I can easily define commands using -n if yours was arg table compliant.

So it bottles down to either you supporting arg table like PUC-lua, making this .sh so I can modify it and being more correctness with win32, or allow a global like command or something. I prefer you go with the args and script both. The script does more justice than arguments.

**Comment by hishamhm** [comment]
> So it bottles down to either you supporting arg table like PUC-lua

Huh? This doesn't make sense. LuaRocks expects a Lua-compatible interpreter, so it's your interpreter's task to support launching scripts via `<intprereter_name> <script_name> <arg1> <arg2> ... <argn>`, and making sure that the script file receives its arguments via both `arg` and `...`.

**Comment by Hydroque** [comment]
Your script doesn't support `arg` and forces the use of ...

**Comment by hishamhm** [comment]
I don't have to, it's the task of a compliant interpreter to support both. You should patch your interpreter instead, or you'll have trouble not only with LuaRocks but with all sorts of Lua scripts that assume that the interpreter works correctly.
