### ISSUE TITLE
PATH only uses unversioned variables

### ISSUE THREAD

**Issue by Tieske** [luarocks/luarocks#760]
When using the `luarocks path` command, it will only respond with variables `LUA_PATH` and `LUA_CPATH` but depending on the target binary, it should use possibly `LUA_PATH_5_2` etc.

If a version `5_2` is already existing, then that existing version will always override whatever LuaRocks produces.

**Comment by hishamhm** [comment]
Good call! That bothered me in the past, and this issue was the necessary push to fix it.
