### ISSUE TITLE
Can't Install Custom Made Luarock

### ISSUE THREAD

**Issue by JesterXL** [luarocks/luarocks#761]
I made [my first Lua rock](https://luarocks.org/modules/JesterXL/lua-fp), and it appears to install locally via `luarocks make` and I can even test it locally, but once I publish to luarocks.org and install from there, it fails. Says a file can't be found. It's not deterministic either because if I immediately try to reinstall, it says another related file can't be found.

Running `luarocks install --tree lua_modules lua-fp` results in:

```bash
Installing https://luarocks.org/lua-fp-1.5-17.src.rock

Error: Build error: Failed installing lua-fp-v1.5.17/luafp/array.lua in /Users/jessewarden/Documents/_Projects/test/lua_modules/lib/luarocks/rocks-5.3/lua-fp/1.5-17/lua/luafp/array.lua: lua-fp-v1.5.17/luafp/array.lua: No such file or directory
```

If I try directly from the site running `luarocks install lua-fp`, it results in:

```bash
Installing https://luarocks.org/lua-fp-1.5-17.src.rock

Error: Build error: Failed installing lua-fp-v1.5.17/luafp/util.lua in /usr/local/lib/luarocks/rocks-5.3/lua-fp/1.5-17/lua/luafp/util.lua: lua-fp-v1.5.17/luafp/util.lua: No such file or directory
```

If you check my commit history, you can see I've tried:
- using the **source.tag**
- using it with/without a dir
- using simple a simple pointer to git vs. a pointer to the binary tar.gz
- using src vs. the tagname + src vs. the dir property AND the tagname + src vs. dir + src
- countless other combinations

I attempted to model my rockspec after [busted](https://github.com/Olivine-Labs/busted)'s but no dice. I'm at a loss what combination/configuration/values I'm supposed to provide to get this to work, or how I can debug the "No such file or directory"; is it in a log somewhere?

### Notes
- on Mac, High Sierra
- installed Lua via Homebrew
- Lua v5.3.4, installed in `/usr/local/bin/lua`
- Luarocks v2.4.3, installed in `/usr/local/bin/luarocks`
- [My source code](https://github.com/JesterXL/lua-fp) (master branch) and [Rockspec](https://raw.githubusercontent.com/JesterXL/lua-fp/master/lua-fp-1.5-17.rockspec)
- [My Luarock](https://luarocks.org/modules/JesterXL/lua-fp) on Luarocks.org

Thanks for reading!

**Comment by mpeterv** [comment]
The message means that when installing the rock and copying over a module, it's not found within the .src.rock in the place it's supposed to be according to rockspec.

I haven't look through all your attempts yet but the first variant added in [this commit](https://github.com/JesterXL/lua-fp/commit/28f842544de2e7bba166537214f040ec55eca58a) should work if you use `git://` or `git+https://` instead of just `https://` in `source.url`. See [the wiki](https://github.com/luarocks/luarocks/wiki/Creating-a-rock#method-1-using-a-repository-such-as-github).

**Comment by JesterXL** [comment]
Dude, I love you, let's get married.

1. You were right, I completely missed the `http://` vs. `git://`.
2. Once I changed that, noticed the publishing actually included all the files in the rock... so that was the second hint I missed.

Things are working now, thanks so much for helping me on creating my first rock!
