### ISSUE TITLE
luarocks path --bin puts /usr/bin in front, thereby breaking the original order

### ISSUE THREAD

**Issue by FSMaxB** [luarocks/luarocks#763]
**Version:** luarocks 2.4.2

Problem
-----------

This can be reproduced like this:
```sh
#!/bin/bash
export PATH='/usr/local/bin:/usr/bin'
luarocks path --bin
```

Expected output:
```
[...]
export PATH='/home/user/.luarocks/bin:/usr/local/bin:/usr/bin
```

Actual output:
```
[...]
export PATH='/home/user/.luarocks/bin:/usr/bin:/usr/local/bin'
```

This is a problem because when using `luarock path --bin` to set my luarocks paths, it breaks my setup and doesn't run the binaries I want to run anymore.

Cause
--------

I did some investigation and found the following:
```lua
cfg = require('luarocks.cfg')

_,_,path = cfg.package_paths()
print(path)
```
When running this lua script, it outputs `/home/user/.luarocks/bin:/usr/bin`.

This explains where this problem is coming from, because the path command first fetches this string:
https://github.com/luarocks/luarocks/blob/4c22bfb86abcd97253c73d2175d0a715c2a2cc12/src/luarocks/cmd/path.lua#L37

Then it appends the PATH environment variable:
https://github.com/luarocks/luarocks/blob/4c22bfb86abcd97253c73d2175d0a715c2a2cc12/src/luarocks/cmd/path.lua#L58

And removes duplicates:
https://github.com/luarocks/luarocks/blob/4c22bfb86abcd97253c73d2175d0a715c2a2cc12/src/luarocks/cmd/path.lua#L76-L78

Because `/usr/bin` is in `cfg.package_paths` already, `util.cleanup_path` removes the duplicate in the correct position.

Possible fixes:
-------------------
* Remove `/usr/bin` from `cfg.package_paths`
* Add an additional flag to `util.cleanup_path` that specifies if the cleanup happens from the right or from the left. If `append` is true, clean up from the left, otherwise clean up from the right.

**Comment by FSMaxB** [comment]
Ping @hishamhm

**Comment by hishamhm** [comment]
@FSMaxB Did you try the `--append` flag for `luarocks path`?

**Comment by FSMaxB** [comment]
With `--append` it doesn't change the order of the existing `PATH` as far as I can tell.

**Comment by FSMaxB** [comment]
But having the luarocks path in front of everything is what I actually want, so that isn't really helpful.

**Comment by andreasvc** [comment]
I also experienced this problem. In my case it was /usr/local/bin which was unexpectedly moved to the front. I now use --append as a workaround, but this is definitely a bug that should be fixed. I just wasted an hour because of this, I had no idea Lua had messed with my path.

**Comment by blueyed** [comment]
I think it would be good if it would keep existing entries in place, i.e. prepend `/home/user/.luarocks/bin` only, if there is `/usr/bin` in there alreay.

A good work around is to use `luarocks path --no-bin` (to not include `$PATH`), and adding/handling `/home/user/.luarocks/bin` yourself (since the `$PATH` is not specific to the selected Lua version anyway).

**Comment by blueyed** [comment]
> * If `append` is true, clean up from the left, otherwise clean up from the right.

Sounds like a good/simple fix.
