### ISSUE TITLE
Package 'say' fails to install

### ISSUE THREAD

**Issue by CoffeeFlux** [luarocks/luarocks#770]
When attempting to install the rock 'say', either from the site with `luarocks install say` or by manually downloading the rockspec file, it returns the error `Error: Error fetching file: Failed downloading https://github.com/Olivine-Labs/say/archive/v1.3-1.tar.gz - v1.3-1.tar.gz`.
It seems to be trying to fetch the URL `https://github.com/Olivine-Labs/say/archive/v1.3-1.tar.gz - v1.3-1.tar.gz`, despite that the rockspec file appears to be fine: https://github.com/Olivine-Labs/say/blob/master/say-1.3-1.rockspec
I'm on Windows 10, using the latest version of LuaRocks, 2.4.3, which was fairly recently installed.
Googling the issue seems to show that it has existed as far as back 2015, and on platforms other than Windows. The same issue seems to occur for a couple other rocks from Olivine-Labs (all of which are dependencies of busted), notably say, lua-term, and mediator_lua.

**Comment by janlazo** [comment]
See https://github.com/luarocks/luarocks/issues/713

**Comment by hishamhm** [comment]
Fixed with the release of LuaRocks 2.4.4!
