### ISSUE TITLE
Are there install --save-deps and install --from-rockspec commands?

### ISSUE THREAD

**Issue by idchlife** [luarocks/luarocks#771]
It seems I cannot quiet grasp the functionality of luarocks except for installing lua packages from repositories and storing module paths in rockspec for unknown for me reason right now.

It is a wonderful library, I must say! With it I can install and work with many libraries and frameworks right now without downloading them by hand and saving files into my project folder.

But. How to exchange code in repository with my friends/colleagues and myself on different machine?

How to install dependencies from rockspec and how to save them in rockspec files in the first place?

I created rockspec via write_rockspec command but it just created my modules structure. I don't see my dependencies which I installed after this with --local

Also, if I use --tree I basically end with hardsaved dependencies into my repository, without chance of updating them or using different versions on different machines etc. Also it takes space in repository and time pushing pulling all dependencies files.

Am I missing something and do not see the proper way to work with luarocks?

Thanks!

**Comment by daurnimator** [comment]
> But. How to exchange code in repository with my friends/colleagues and myself on different machine?

Put dependencies in the dependency section of your rockspec.



> Also, if I use --tree I basically end with hardsaved dependencies into my repository, without chance of updating them

An upgrade/update command is on it's way. See https://github.com/luarocks/luarocks/issues/22

In the mean-time you need to use `luarocks install` again :(

**Comment by idchlife** [comment]
thank you very much for working on that! Looking forward to use upgrade/update!
