### ISSUE TITLE
There is no rocktrees variable in config.lua

### ISSUE THREAD

**Issue by dimka665** [luarocks/luarocks#791]
I want to add one more rocks tree in `~/.luarocks/config.lua`, but there is no `rocktrees` variable that pointed in wiki: https://github.com/luarocks/luarocks/wiki/Config-file-format#external-input

**Comment by hishamhm** [comment]
@dimka665 use `rocks_trees` (see that wiki link for more info). That "rocktrees" was not meant to be a variable name in the documentation. I'll fix it to clarify.
