### ISSUE TITLE
Cannot install Luadns in termux

### ISSUE THREAD

**Issue by bensh4** [luarocks/luarocks#800]
In my Termux,I installed http, thanks @Grimler91 
But now when trying to install ```luadns``` using luarocks,I'm getting this error

![](https://i.imgur.com/MILgAGp.png)

Do we need to port this to termux for working without this error?
Also tried my showing openssl directory. But didn't worked either.

![](https://i.imgur.com/3qRQBxL.png)

**Comment by siffiejoe** [comment]
Seems I'm too late and you figured it out yourself, but for future reference: `luaL_reg` was renamed to `luaL_Reg` in Lua 5.1 (Lua 5.1 with default flags accepted both for compatibility). So it seems that the luadns module has not been updated for less-ancient Lua versions.
