### ISSUE TITLE
Luarocks and Mingw32 can't install luasocket or other libraries

### ISSUE THREAD

**Issue by oliverheldens** [luarocks/luarocks#807]
I have LuaRocks 2.4.4 and Lua 5.3.4; i already install mingw32 with MSYS.

But when i try to install luasocket say me that ERROR_NOT_ENOUGH_MEMORY.

`C:\WINDOWS\system32>luarocks install luasocket
Installing https://luarocks.org/luasocket-3.0rc1-2.src.rock
C:\MinGW\bin\gcc.exe -O2 -c -o src/luasocket.o -IC:/Program Files (x86)/Lua/include src/luasocket.c -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_INET_PTON -DWINVER=0x0501 -DLUASOCKET_API=__declspec(dllexport) -DMIME_API=__declspec(dllexport)
C:\MinGW\bin\gcc.exe -O2 -c -o src/timeout.o -IC:/Program Files (x86)/Lua/include src/timeout.c -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_INET_PTON -DWINVER=0x0501 -DLUASOCKET_API=__declspec(dllexport) -DMIME_API=__declspec(dllexport)
C:\MinGW\bin\gcc.exe -O2 -c -o src/buffer.o -IC:/Program Files (x86)/Lua/include src/buffer.c -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_INET_PTON -DWINVER=0x0501 -DLUASOCKET_API=__declspec(dllexport) -DMIME_API=__declspec(dllexport)
C:\MinGW\bin\gcc.exe -O2 -c -o src/io.o -IC:/Program Files (x86)/Lua/include src/io.c -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_INET_PTON -DWINVER=0x0501 -DLUASOCKET_API=__declspec(dllexport) -DMIME_API=__declspec(dllexport)
C:\MinGW\bin\gcc.exe -O2 -c -o src/auxiliar.o -IC:/Program Files (x86)/Lua/include src/auxiliar.c -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_INET_PTON -DWINVER=0x0501 -DLUASOCKET_API=__declspec(dllexport) -DMIME_API=__declspec(dllexport)
C:\MinGW\bin\gcc.exe -O2 -c -o src/options.o -IC:/Program Files (x86)/Lua/include src/options.c -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_INET_PTON -DWINVER=0x0501 -DLUASOCKET_API=__declspec(dllexport) -DMIME_API=__declspec(dllexport)
C:\MinGW\bin\gcc.exe -O2 -c -o src/inet.o -IC:/Program Files (x86)/Lua/include src/inet.c -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_INET_PTON -DWINVER=0x0501 -DLUASOCKET_API=__declspec(dllexport) -DMIME_API=__declspec(dllexport)
C:\MinGW\bin\gcc.exe -O2 -c -o src/except.o -IC:/Program Files (x86)/Lua/include src/except.c -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_INET_PTON -DWINVER=0x0501 -DLUASOCKET_API=__declspec(dllexport) -DMIME_API=__declspec(dllexport)
C:\MinGW\bin\gcc.exe -O2 -c -o src/select.o -IC:/Program Files (x86)/Lua/include src/select.c -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_INET_PTON -DWINVER=0x0501 -DLUASOCKET_API=__declspec(dllexport) -DMIME_API=__declspec(dllexport)
C:\MinGW\bin\gcc.exe -O2 -c -o src/tcp.o -IC:/Program Files (x86)/Lua/include src/tcp.c -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_INET_PTON -DWINVER=0x0501 -DLUASOCKET_API=__declspec(dllexport) -DMIME_API=__declspec(dllexport)
C:\MinGW\bin\gcc.exe -O2 -c -o src/udp.o -IC:/Program Files (x86)/Lua/include src/udp.c -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_INET_PTON -DWINVER=0x0501 -DLUASOCKET_API=__declspec(dllexport) -DMIME_API=__declspec(dllexport)
C:\MinGW\bin\gcc.exe -O2 -c -o src/wsocket.o -IC:/Program Files (x86)/Lua/include src/wsocket.c -DLUA_COMPAT_APIINTCASTS -DLUASOCKET_DEBUG -DLUASOCKET_INET_PTON -DWINVER=0x0501 -DLUASOCKET_API=__declspec(dllexport) -DMIME_API=__declspec(dllexport)
In file included from src/wsocket.h:11:0,
                 from src/socket.h:18,
                 from src/wsocket.c:10:
src/wsocket.c: In function 'socket_gaistrerror':
src/wsocket.c:417:14: error: 'ERROR_NOT_ENOUGH_MEMORY' undeclared (first use in this function)
         case EAI_MEMORY: return "memory allocation failure";
              ^
src/wsocket.c:417:14: note: each undeclared identifier is reported only once for each function it appears in

Error: Build error: Failed compiling object src/wsocket.o`

Please help!

**Comment by bensh4** [comment]
Installed ```liblua``` and ```liblua-dev``` ?

**Comment by Tieske** [comment]
the error is not that there isn't enough memory, the error is that an identifier called "ERROR_NOT_ENOUGH_MEMORY" is not declared.

How did you install luarocks? from windows, or from mingw?

**Comment by Tieske** [comment]
also how did you install Lua?

**Comment by oliverheldens** [comment]
I could already fix. I install in windows and lua compile with MinGW32 (make mingw), then install luarocks with (install / mw), and all good but the error still appearing.

I dont try to install liblua and liblua-dev.

The solution that works to me is install MinGW64 but the installer that brings by default dont work, so i download manually from [https://sourceforge.net/projects/mingw-w64/files/?source=navbar](url) decompressing the "x86_64- posix-seh". I add to the "Environment Variables" the bin files of MinGW64, change the file nome "mingw64-make.exe" to "make.exe" and do the installation again (compiling) of lua and luarocks and the error solved.

Thanks for your answers!

**Comment by Tieske** [comment]
@oliverheldens next time you might want to have a look at [luawinmake](https://github.com/Tieske/luawinmake) and [luawinmulti](https://github.com/Tieske/luawinmulti)
