### ISSUE TITLE
Luarocks does not distinct dependency libraries with different sonames

### ISSUE THREAD

**Issue by avnik** [luarocks/luarocks#81]
We have luasec rock, built on Ubuntu Natty and linked with libssl.so.0.9.8.
Luarocks refuse tso install it on Ubuntu Precise with libssl0.9.8 installed, and allows it only if we install libssl-dev (it wrong -- it is not needed to install already compiled rock)

Another side of problem -- luarocks can be easy fooled, as it does not check the version the rock binaries is compiled against:
we install libssl-dev and libssl1.0.0 (as dependency of libssl-dev), luarocks checks passed, but luasec shouldn't work:

```
[avn@master:pts/26]~/tmp/pk-foreign-rocks/rocks (git)-[master]-% schroot -r -c test -u root -- ldd /usr/local/lib/lua/5.1/ssl.so          
    linux-gate.so.1 =>  (0xb776b000)
    libssl.so.0.9.8 => not found
    libcrypto.so.0.9.8 => not found
    libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xb75b8000)
    /lib/ld-linux.so.2 (0xb776c000)
```

My luarocks config is:

```
external_deps_dirs = {
   {
      prefix='/',
      include='usr/include',
      lib='lib',
   },
   {
      prefix='/',
      include='usr/include',
      lib='lib/i386-linux-gnu',
   },
   {
      prefix='/usr',
   },
   {
      prefix='/usr',
      lib='lib/i386-linux-gnu',
   },
   {
      prefix='/usr/local',
   },
}
```

And problematic libraries placed by system package manager in /lib/i386-linux-gnu It is not libssl specific issue, we see similiar problem with libuuid.so.1, and I'm affraid it can happen with other libraries too.

**Comment by hishamhm** [comment]
Closing this since the root issue was fixed and we haven't had reports with filename issues in libssl for a long time (the fact that _path_ is often an issue with OpenSSL libraries is a different topic: users often need to enter `OPENSSL_DIR` manually, because OpenSSL is often not installed in standard system locations).
