### ISSUE TITLE
unrecognized filename extension when install a package

### ISSUE THREAD

**Issue by videni** [luarocks/luarocks#826]
luarocks install kong-consumer-route

Error: Couldn't extract archive kong-consumer-route: unrecognized filename extension

I search a lot , seem lots of lua package have this trouble , they have to use `luarocks make` to install from source.

**Comment by videni** [comment]
have to change  the url as `git://github.com/videni/kong-consumer-route`
```
source = {
  url = "git://github.com/videni/kong-consumer-route",
  tag = "1.0.1"
}
```

**Comment by yogiverma007** [comment]
Thanks for the solution. I had the same problem with my rockspec.
