### ISSUE TITLE
Error compiling C module in [ Windows 10 ]  [ MinGW ] 

### ISSUE THREAD

**Issue by sourcevault** [luarocks/luarocks#828]
I have trying to figure out how to attach C modules in `Lua 5.1.5`

I followed the instructions provided in the following stackoverflow answer

https://stackoverflow.com/a/47350675

But I am getting the following error unfortunately
```
> luarocks make
mingw32-gcc -O2 -IC:/lua/bin/../include -c example.cc -o example.o
mingw32-gcc -shared -o example.dll example.o C:/lua/bin/../lib -lmsvcr80
c:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../../mingw32/bin/ld.exe: cannot find C:\lua\bin\..\lib: Permission denied
collect2.exe: error: ld returned 1 exit status

Error: Build error: Failed installing example.dll in C:\lua\bin/../share/luarocks/rocks/lib/luarocks/rocks/example/1.0-1/lib
```

**Comment by Tieske** [comment]
seems odd, there is a flag `-lmsvcr80`, which indicates the Microsoft toolchain, yet you compile using mingw?

How did you install Lua and Luarocks on your system? You might want to try [luawinmulti](https://github.com/Tieske/luawinmulti)

**Comment by sourcevault** [comment]
@hishamhm does using `touch` count ?

<img width="736" alt="untitled" src="https://user-images.githubusercontent.com/20347647/41782366-d9b917d0-765b-11e8-898b-7a7863408591.png">

I also tried using an admin command line - same error.

I installed Lua using  http://luadist.org/

I had issues directly trying to install from source on windows - the build script doesnt take into account that i already had `gcc` installed through `minGW` - and the alterative local version using `tdm-gcc-4.9.2.exe` had some errors. 

http://lua-users.org/wiki/BuildingLuaInWindowsForNewbies

I do have `lua`, `luarocks` and `gcc` on my command line - i managed to install `luajit` with no issues.

@Tieske checking luawinmulti out right now, thanks !

**Comment by sourcevault** [comment]
@Tieske 

Hi, I managed to intall Lua using `luawinmulti` - I have a different easier error that requires a bit of knowledge regarding LuaRock Internals.

 ```
> luarocks make
C:\MinGW\bin\gcc.exe -O2 -c -o example.o -IC:/Lua/include/lua/5.3 example.cc
C:\MinGW\bin\gcc.exe -shared -o example.dll example.o C:/Lua/bin/lua53.dll -lm
example.o:example.cc:(.text+0x13): undefined reference to `lua_pushstring(lua_State*, char const*)'
example.o:example.cc:(.text+0x3c): undefined reference to `lua_createtable(lua_State*, int, int)'
example.o:example.cc:(.text+0x54): undefined reference to `lua_pushcclosure(lua_State*, int (*)(lua_State*), int)'
example.o:example.cc:(.text+0x6c): undefined reference to `lua_setfield(lua_State*, int, char const*)'
collect2.exe: error: ld returned 1 exit status

Error: Build error: Failed compiling module example.dll
```
It seems 

`
#include <lua.h>
`
Is the offending line.

My question is more general - how do I wire up lua source files in sitautions like this ?

Thanks @hishamhm @Tieske for your quick help !

**Comment by sourcevault** [comment]
Running the individual commands give the same errors - for some reason the compiled dll doesnt have the original lua compiled functions. 

<img width="743" alt="untitled" src="https://user-images.githubusercontent.com/20347647/41788705-5d4bd29c-766e-11e8-8a30-46244fadfaea.png">

**Comment by Tieske** [comment]
your file is named `example.cc` instead of `example.c`. Does that file extension make a difference?

**Comment by sourcevault** [comment]
@Tieske  Thanks a lot ! 

Yes you were right. 

```
> luarocks make
C:\MinGW\bin\gcc.exe -O2 -c -o example.o -IC:/Lua/include/lua/5.3 example.c
C:\MinGW\bin\gcc.exe -shared -o example.dll example.o C:/Lua/bin/lua53.dll -lm
No existing manifest. Attempting to rebuild...
example 1.0-1 is now installed in c:\lua\
```

I apologise for it, I have not programmed in `C` for a while. 

Is the process same for `LuaJIT`

**Comment by sourcevault** [comment]
@Tieske Can I just copy the LuaRocks Folder to the `luajit` folder ? or am I being too naive ?
