### ISSUE TITLE
src/bin/luarocks and src/bin/luarocks-admin do not honor --lua-suffix

### ISSUE THREAD

**Issue by mcclure** [luarocks/luarocks#832]
`src/bin/luarocks` begins with `#!/usr/bin/env lua`
`src/bin/luarocks-admin` does also.
There is no `lua` binary on my system, because I installed lua via Homebrew.
Instead there is a `lua-5.1` binary.
For this reason when I build luarocks myself, the build `luarocks` will not run.
I build with `./configure --lua-suffix=-5.1` but it seems to ignore my plea to suffix `-5.1`.
**Expected behavior**: `--lua-suffix` should determine the binary hashbanged in `luarocks` and `luarocks-admin`.

**Comment by hishamhm** [comment]
> I build with ./configure --lua-suffix=-5.1 but it seems to ignore my plea to suffix -5.1.

Which step did you do after configure? If you do `make build` (as suggested by `make`) it does rewrite the hash-bang.

**Comment by mcclure** [comment]
I run `make install`.

Testing, this is the problem. If I `make build` then `make install` then my suffix is inserted correctly.

I don't know if this is a problem or not. It seems surprising to me that `make install` does not have `make build` as a dependency.

**Comment by hishamhm** [comment]
> It seems surprising to me that make install does not have make build as a dependency.

Good catch, fixed!
