### ISSUE TITLE
Install luarocks for Lua without `lua` prefix.

### ISSUE THREAD

**Issue by moteus** [luarocks/luarocks#836]
I use some custom version of Lua which name of interpreter has no `lua` prefix.
Now I have to `patch` install script to be able install and use LuaRocks.

**Comment by hishamhm** [comment]
@moteus the LR3 build system dropped `LUA_SUFFIX` and uses `LUA_INTERPRETER` instead. If anything, it makes it _easier_ to use a non-`lua`-prefixed name :)

If I follow correctly, the bit that is missing is a `--with-lua-interpreter` flag in `./configure`, is that correct?

**Comment by moteus** [comment]
Yes. I have to remove `lua` prefix inside configure script to be able to install LR.
Also after install I edit shebang in luarocks script as whell

**Comment by hishamhm** [comment]
@moteus please give this branch a try, and let me know if it solves your issue:
https://github.com/luarocks/luarocks/tree/with-lua-interpreter

**Comment by hishamhm** [comment]
Closing this: LuaRocks 3.0 includes `--with-lua-interpreter`
