### ISSUE TITLE
win32/tools way out of date

### ISSUE THREAD

**Issue by cup** [luarocks/luarocks#839]
I noticed here:

http://github.com/luarocks/luarocks/tree/d9f09ba/win32/tools

However you are using coreutils version 5.3.0 which is 13 years old:

http://gnuwin32.sourceforge.net/packages/coreutils.htm

and you are using findutils 4.2.20 which is also 13 years old:

http://gnuwin32.sourceforge.net/packages/findutils.htm

these packages could be updated from the Cygwin project, for example with a
script like this:

~~~pl
<<eof xargs ldd | awk 'index($0, "/usr/") && !q[$0]++ {print $3}'
/usr/bin/cp.exe
/usr/bin/find.exe
/usr/bin/ls.exe
/usr/bin/md5sum.exe
/usr/bin/mkdir.exe
/usr/bin/mv.exe
/usr/bin/pwd.exe
/usr/bin/rmdir.exe
/usr/bin/test.exe
/usr/bin/uname.exe
eof
~~~

Result:

~~~
/usr/bin/cygattr-1.dll
/usr/bin/cygwin1.dll
/usr/bin/cygintl-8.dll
/usr/bin/cygiconv-2.dll
~~~

Then you just copy the Cygwin EXE and DLL to replace the current ones.

**Comment by hishamhm** [comment]
LuaRocks 3.0 ships with an all-in-one statically-built binary which is built against up-to-date libraries and does not require these third-party tools. Get it here:

http://luarocks.github.io/luarocks/releases/

The legacy package is, as the name implies, legacy. Thanks to the HN commenter to reminding me about this issue. The Windows installation instructions need to be updated at the LuaRocks wiki, but that's a separate issue.

**Comment by cup** [comment]
i was the commenter :) - cheers for pointing this out

frankly this was my sole reason for not using the Lua language - i will reconsider that now

**Comment by cup** [comment]
https://github.com/luarocks/luarocks/issues/976
