### ISSUE TITLE
Error while installing LuaSec

### ISSUE THREAD

**Issue by Choonster** [luarocks/luarocks#850]
LuaRocks version: 3.0.0
OS: WIndows 10 x64

While attempting to install LuaSec with `luarocks install luasec`, I got the following error:
```
Error: LuaRocks 3.0.0 bug (please report at https://github.com/luarocks/luarocks/issues).
[string "src/luarocks/manif.lua"]:140: attempt to concatenate a nil value (local 'err')
stack traceback:
        [string "src/luarocks/manif.lua"]:140: in function 'luarocks.manif.load_manifest'
        [string "src/luarocks/search.lua"]:111: in function <[string "src/luarocks/search.lua"]:101>
        (...tail calls...)
        [string "src/luarocks/search.lua"]:155: in function 'luarocks.search.search_repos'
        [string "src/luarocks/search.lua"]:240: in function 'luarocks.search.find_suitable_rock'
        [string "src/luarocks/cmd/install.lua"]:208: in function 'luarocks.cmd.install.command'
        (...tail calls...)
        [C]: in function 'xpcall'
        [string "src/luarocks/cmd.lua"]:444: in function 'luarocks.cmd.run_command'
        [string "luarocks"]:35: in main chunk
        [C]: in ?
```

**Comment by hishamhm** [comment]
@Choonster this was running luarocks.exe, right?

Could you give this build a try to see if this fixes the issue? https://hisham.hm/win32/luarocks-dev-windows-32-8734df1.zip

Thank you!

**Comment by Choonster** [comment]
Yes, it was running luarocks.exe.

That fixed the issue, thanks.

However, I'm having another issue where running the linked build of LuaRocks in the Visual Studio command prompt tries to compile LuaSec using `mingw32-gcc` instead of using the Microsoft compiler toolchain.

Is there anything I need to post to help diagnose this? Should I open another issue?

**Comment by hishamhm** [comment]
luarocks attempts to detect the VS command prompt checking if the VCINSTALLDIR environment variable exists. Do you have that env var when you run `set` from the command prompt? What MSVC version are you running?

**Comment by Tieske** [comment]
and what Visual Studio or Windows SDK version?

**Comment by daurnimator** [comment]
@Choonster I found https://gist.github.com/teeks99/627dce6f298ba02592643f03fe36a68b which indicates it should be present: can see how yours might differ?

**Comment by murillow** [comment]
@Choonster how did you manage to run `luarocks.exe` on Windows 10 x64? Whenever I try to run it, I get the following error: `Error: Current directory does not exist. Please run LuaRocks from an existing directory.`

For instance:
```
C:\luarocks-3.0.0-windows-32>luarocks install luasocket
Error: Current directory does not exist. Please run LuaRocks from an existing directory.
```

What am I doing wrong?

**Comment by Choonster** [comment]
@murillow I installed it over the top of an existing LuaRocks 2 installation from [LuaWinMulti](https://github.com/Tieske/luawinmulti) and moved the **config-5.3.lua** file to **C:\Program Files (x86)\LuaRocks**. I haven't tried a completely fresh installation.

**Comment by murillow** [comment]
@Choonster wow I didn't even know about [LuaWinMulti](url)! OMG, It's so handy! Thanks!!!

**Comment by hishamhm** [comment]
@Choonster @murillow please give this new build a try:

https://hisham.hm/win32/luarocks-dev-windows-32-8734df1.zip

it should detect MSVC correctly when `VCINSTALLDIR` is set.

**Comment by Choonster** [comment]
@hishamhm That build worked, thanks. I managed to install LuaSocket and LuaSec using it.

**Comment by Bayu12345677** [comment]
help
