### ISSUE TITLE
luarocks.loader import fails from interactive interpreter

### ISSUE THREAD

**Issue by Zash** [luarocks/luarocks#852]
Importing `luarocks.loader` from a REPL where `_G.arg` apparently doesn't exist causes a traceback.

```
~$ lua -lluarocks.loader
lua: /usr/local/share/lua/5.2/luarocks/core/cfg.lua:541: attempt to index global 'arg' (a
nil value)
stack traceback:
        /usr/local/share/lua/5.2/luarocks/core/cfg.lua:541: in function 'init'
        /usr/local/share/lua/5.2/luarocks/loader.lua:19: in main chunk
        [C]: in function '_G.require'
        [C]: in ?
```

LuaRocks 3.0.0

**Comment by hishamhm** [comment]
@Zash thanks for the report, I had a similar one on Gitter... pushing a fix to `master` now. But just curious as I don't have a 5.2 install handy right now to check it locally: the standalone interpreter doesn't ever define `_G.arg` or does it do it only when launching a script?

Trying both 5.3 and LuaJIT 2.1, both define `arg` even in the REPL.

**Comment by hishamhm** [comment]
Indeed, Lua 5.1 and 5.2 do not define `arg` for the REPL :( http://www.lua.org/source/5.2/lua.c.html#handle_script

**Comment by Zash** [comment]
Nor does LuaJIT 2.0.4

**Comment by hishamhm** [comment]
Good to know.

The luarocks.loader functionality doesn't need lua_bindir, so I think the changes pushed to master in 66b2816 should be sufficient for the `lua -lluarocks.loader` usecase.
