### ISSUE TITLE
How do you remove a bootstrapped luarocks?

### ISSUE THREAD

**Issue by THofstee** [luarocks/luarocks#853]
I have a bit of a problem. I installed luajit from source, as well as luarocks. When I attempt to do anything in luarocks I get the following error:

```
~/s/luajit master · luarocks remove luarocks
/usr/local/bin/luajit: ...cal/lib/luarocks/rocks-5.1/luarocks/3.0.0-1/bin/luarocks:6: loop or previous error loading module 'luarocks.loader'
stack traceback:
        [C]: in function 'require'
        ...cal/lib/luarocks/rocks-5.1/luarocks/3.0.0-1/bin/luarocks:6: in main chunk
        [C]: at 0x59d566df04f0
```

So I can't use luarocks to remove itself, or install anything, or even call it with no arguments. I'm not sure if the issue is on the luarocks side or the luajit side, but in any case it would help if I knew a complete list of things to remove.

I know I need to remove `/usr/local/bin/luarocks`, but is there anything else that I should remove to avoid conflicts with future installations?

**Comment by daurnimator** [comment]
We should add a `make uninstall` target.

**Comment by hishamhm** [comment]
@daurnimator can we do that without keeping a list of all `luarocks.*` modules inside the Makefile? (I was happy to have gotten rid of that)

**Comment by daurnimator** [comment]
The `make uninstall` now exists. Can this be closed?

**Comment by THofstee** [comment]
Yes go ahead, I am sadly no longer actively using Lua but I trust that this is done.
