### ISSUE TITLE
Installation weirdness

### ISSUE THREAD

**Issue by Zash** [luarocks/luarocks#857]
When installing (from current git) the files in `/usr/local/share/lua/5.3/luarocks/` have ownership `zash:zash` (ie me). I'm guessing that this is because the Makefile uses `cp -a` when installing, which preserves the ownership and permissions on the files in my git clone.
That doesn't seem right, normally I would expect `root:root rw-r--r--` on files installed system-wide.

**Comment by hishamhm** [comment]
@Zash thanks for the report! It was indeed an oversight!

@daurnimator you mentioned you would look at the Makefile, while you're at it could you take a look at this as well?

**Comment by hishamhm** [comment]
This is going to be fixed alongside #863!
