### ISSUE TITLE
site_config.lua is ARCH-dependent and should be put into lib_dir

### ISSUE THREAD

**Issue by ildar** [luarocks/luarocks#86]
This supposed to be ARCH-independent dir. It can be safely moved to: lib_modules_path.."/luarocks". Like mine:

> mkdir -p %buildroot%lua_modulesdir/%name
> # Arch-dependant parts
> 
> mv %buildroot%lua_modulesdir_noarch/%name/site_config.lua %buildroot%lua_modulesdir/%name

**Comment by daurnimator** [comment]
Closing as site_config is no longer part of luarocks
