### ISSUE TITLE
luarocks-api: cfg.rocks_trees not showing all available trees

### ISSUE THREAD

**Issue by jiteshpabla** [luarocks/luarocks#874]
The cfg table in ```init.lua``` does not include all the rock-trees that are currently configured on my system.
My installation of luarocks has the 2 default rock-trees: ```system``` and ```user```. But cfg.rocks_trees only includes the ```user``` rock-tree.

the cfg table includes both the rock-trees in ```cmd.lua```

**Comment by hishamhm** [comment]
minimal script to reproduce the issue:

```
local pretty = require("pl.pretty")
local cfg = require("luarocks.core.cfg")
cfg.init()
print(pretty.write(cfg.rocks_trees))
```
