### ISSUE TITLE
Ship completion files for shells

### ISSUE THREAD

**Issue by daurnimator** [luarocks/luarocks#879]
e.g. for bash+zsh

**Comment by daurnimator** [comment]
I'm wondering if this should be done after an overhaul of command line argument handling.
At the moment, flags are stored in a central list: there is no per-module data (outside of help output) about which flags are used for each command.

@hishamhm how would you feel about new argument parsing for luarocks? Things I'd like it to do:
  - auto generate help text
  - validate arguments and display help if wrong
  - be introspectable for generating completion data

**Comment by nightwarrior-xxx** [comment]
@daurnimator Can I work on this issue for GSOC 2019 . 
I have been wrtiting  lua and bash scripts for some time  and have idea how to do this.

**Comment by daurnimator** [comment]
> Can I work on this issue for GSOC 2019 .

@nightwarrior-xxx I assume you saw my comment here? https://github.com/luarocks/luarocks/issues/962#issuecomment-460884004

> I have been wrtiting lua and bash scripts for some time and have idea how to do this.

Could you share your ideas? :)

**Comment by nightwarrior-xxx** [comment]
@daurnimator Will ping you on gitter
