### ISSUE TITLE
Installing on windows failes with "recipe for target 'copy_site_config' failed"

### ISSUE THREAD

**Issue by JonasJurczok** [luarocks/luarocks#880]
Hi,

I'm the author of [Faketorio](https://github.com/JonasJurczok/faketorio) and currently switchting to my windows work enviornment. I'm using luarocks for its compression ability.
I tried to install luarocks using `luarocks install luarocks` both with the 2.4.4 as well as with the 3.0.0 version of luarocks. Both times it tries to install the 2.4.4 rock, which is fine for me as it should work (at least it has worked on Linux).

Both times I get similar but different errors.

The output for 2.4.4 installation is here: 
[output.txt](https://github.com/luarocks/luarocks/files/2264070/output.txt)

This error stayed the same both with the originaly installed version as with a version installed using [luawinmulti](https://github.com/Tieske/luawinmulti).

I then tried luarocks 3.0.0. The verbose log is attached here [output3.0.txt](https://github.com/luarocks/luarocks/files/2264051/output3.0.txt).

Installing other rocks works with 2.4.4, with 3.0.0 I get some strange "cannot create directory" errors that might be a permission issue (I'll check that now).

I'm sure the problem is something minor I did wrong but after a long while of trying I'm out of ideas :)

Thanks,
Jonas

**Comment by hishamhm** [comment]
Bootstrap mode with `luarocks install luarocks` is not yet supported on Windows. Please use the regular installers — I recommend giving the all-in-one package containing a stand-alone `luarocks.exe` package a try: https://luarocks.github.io/luarocks/releases/luarocks-3.0.1-rc1-windows-32.zip
