### ISSUE TITLE
Problem with mkdir on windows

### ISSUE THREAD

**Issue by JonasJurczok** [luarocks/luarocks#881]
I've just installed 3.0.0 and run into a problem.

Installing rocks fails because none of the directories can be created.

I tried to manually create the failing directories with the mkdir.exe included in the installation folder (I'm not using the all in one solution).

Luarocks tries to create a folder with `mkdir c:/lua/luarocks/lib/luarocks/rocks-5.1/....` this fails on windows 7.

What works is if you esape the path like this `mkdir "c:/lua/luarocks/...."`, then it successfully creates the directory.

If you need more info I'll happily provide it.

**Comment by daurnimator** [comment]
Could you show us the output when you run the luarocks command with `--verbose`?

**Comment by daurnimator** [comment]
Im on mobile at the moment so I might have a bad view. But I can't see any failure in your logs there?

**Comment by JonasJurczok** [comment]
Thats interesting. It seems the error messages are missing from the output.

Anyhow I created two new logfiles produced with the same command `luarocks install luarocks`, one verbose, one not. And then copied the error messages at the end.

[output3.0.min.txt](https://github.com/luarocks/luarocks/files/2265515/output3.0.min.txt)
[output3.0.txt](https://github.com/luarocks/luarocks/files/2265516/output3.0.txt)

**Comment by JonasJurczok** [comment]
Okay some more data points. For all the following I used the mkdir.exe from the luarocks\tools directory.

````
mkdir.exe c:/lua/luarocks/lib/luarocks/.../conf -> fails
mkdir.exe "c:/lua/luarocks/lib/luarocks/.../conf" -> works

mkdir.exe c:\\lua\\luarocks\\lib\\luarocks\\...\\conf -> fails
mkdir.exe "c:\\lua\\luarocks\\lib\\luarocks\\...\\conf" -> fails

mkdir.exe -p "c:\\lua\\luarocks\\lib\\luarocks\\...\\conf" -> works
mkdir.exe -p "c:\lua\luarocks\lib\luarocks\...\conf" -> works
````

It seems with 3.0 the behaviour is more unix like than before.

**Comment by hishamhm** [comment]
@JonasJurczok hi, please give release 3.0.1-rc1 a try, it should fix this issue: https://luarocks.github.io/luarocks/releases/

**Comment by JonasJurczok** [comment]
Will do, thx.

>

**Comment by JonasJurczok** [comment]
That fixed the issue. Thanks
