### ISSUE TITLE
Installing LuaRocks 3.0.x as root results in a warning

### ISSUE THREAD

**Issue by helpermethod** [luarocks/luarocks#901]
Hi,

I'm trying to install LuaRocks 3.0.x within a Docker container. By default all commands in Docker are run as root. This results in the following problem: 

> Warning: The directory '/root/.cache/luarocks' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing /build/luarocks-3.0.1/src/bin/luarocks with sudo, you may want sudo's -H flag.

Is this the expected behaviour?

**Comment by helpermethod** [comment]
This seems to make the cache unusable. Is there any workaround for this?

**Comment by hishamhm** [comment]
Let's try to diagnose the problematic environment: so the command is running as root but `/root` (or `/root/.cache`) is not owned by the root user? Does `/root` even exist?

Could you check the ownership/permissions of these directories? Thanks!

(paging @daurnimator here as he mentioned he's interested in this)

**Comment by daurnimator** [comment]
You can see the issue with this docker container: 
```
$ sudo docker run --rm registry.gitlab.com/daurnimator/docker-hererocks/lua5.3 luarocks install fifo
Warning: The directory '/root/.cache/luarocks' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing /lua5.3/bin/luarocks with sudo, you may want sudo's -H flag.
Installing https://luarocks.org/fifo-0.2-0.all.rock
No existing manifest. Attempting to rebuild...
fifo 0.2-0 is now installed in /lua5.3 (license: MIT/X11)
```

```
$ sudo docker run --rm registry.gitlab.com/daurnimator/docker-cks/lua5.3 ls -la /root/.cache
total 0
drwxr-xr-x 1 root root  18 Sep  2 04:33 .
drwx------ 1 root root  62 Sep  2 04:33 ..
drwxr-xr-x 1 root root 238 Sep  2 04:35 hererocks
```

**Comment by ti-mo** [comment]
Also seeing this exact behavior when running `luarocks make` on image `kong:0.14`.

```
~ # id
uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video)
~ # luarocks make
Warning: The directory '/root/.cache/luarocks' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing /usr/local/bin/luarocks with sudo, you may want sudo's -H flag.
```

Though in this case, `/root/.cache/` does not exist, nor is it created by luarocks automatically. All directories up to the filesystem root are owned by `root`.

**Comment by italomaia** [comment]
If I may, got this error while using --local install; USER=<root or current user> didn't solve the issue. 

```
~/code $ whoami
nonroot
~/code $ USER=nonroot luarocks install --local moonscript   
Warning: Failed searching manifest: Failed fetching manifest for https://luarocks.org - Failed downloading https://luarocks.org/manifest - /home/nonroot/.cache/luarocks/https___luarocks.org/manifest
Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/ - Failed downloading https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/manifest - /home/nonroot/.cache/luarocks/https___raw.githubusercontent.com_rocks-moonscript-org_moonrocks-mirror_master_/manifest
Warning: Failed searching manifest: Failed fetching manifest for http://luafr.org/moonrocks/ - Failed downloading http://luafr.org/moonrocks/manifest - /home/nonroot/.cache/luarocks/http___luafr.org_moonrocks_/manifest
Warning: Failed searching manifest: Failed fetching manifest for http://luarocks.logiceditor.com/rocks - Failed downloading http://luarocks.logiceditor.com/rocks/manifest - /home/nonroot/.cache/luarocks/http___luarocks.logiceditor.com_rocks/manifest

Error: No results matching query were found.
```

Above was tested in a docker container.

**Comment by hishamhm** [comment]
@italomaia these error messages are typical of connectivity errors. Did the container have internet access?

**Comment by italomaia** [comment]
@hishamhm yes, the container had internet access. You can try it in your end with this dockerfile: https://github.com/italomaia/docker-resty-lapis/blob/master/web/Dockerfile

**Comment by italomaia** [comment]
Tried out luarocks in debian and alpine; problem only happens in alpine, compiled or apk package. Could this be a distro related issue?

**Comment by helpermethod** [comment]
@italomaia As @daurnimator said, setting the USER env variable fixes the problem. I expect Debian do set the variable but Alpine to not set it.

**Comment by ti-mo** [comment]
@italomaia `USER=root /usr/bin/luarocks-5.1 install moonscript` would be the equivalent of that, no need to call `export`

**Comment by Deepak123bharat** [comment]
I get the same warning
```
root@f9d7c9e6fccb:~# luarocks install luasocket
Warning: The directory '/root/.cache/luarocks' or its parent directory is not owned by the current user and the cache has been disabled. 
Please check the permissions and owner of that directory. If executing /usr/local/bin/luarocks with sudo, you may want sudo's -H flag.
```
but after 
``` 
root@f9d7c9e6fccb:~# su
```
command It is working perfectly on my environment

**Comment by helpermethod** [comment]
@hishamhm Any chance to release this fix?
