### ISSUE TITLE
Win. LuaRocks can not find config in custom directory.

### ISSUE THREAD

**Issue by moteus** [luarocks/luarocks#903]
After install luarocks with 
`install /P d:\luarocks\luarocks /TREE d:\luarocks\5.1\tree /LV 5.1 /LUA c:\luaenv\x64\5.1 /MSVC /F /NOREG /NOADMIN`
On Windows system LuaRocks can not find its config
```
luarocks-admin.bat
....
CONFIGURATION
        Lua version: 5.1

        Configuration files:
                System  : C:/Program Files/luarocks/config-5.1.lua (not found)
                User    : C:/Users/alexey/AppData/Roaming/luarocks/config-5.1.lua (not found)

        Rocks trees in use:
                C:/Users/alexey/AppData/Roaming/luarocks ("user")
                d:/luarocks/luarocks ("system")
```

I think installer should add `SYSCONFDIR` to hardcoded table.

**Comment by blueyed** [comment]
Have you found a solution for this?
Is there any config in `d:\luarocks\luarocks` ?

**Comment by hishamhm** [comment]
@moteus I followed your suggestion and made `install.bat` always set `SYSCONFDIR` in `hardcoded.lua`.
