### ISSUE TITLE
luarocks 2.2 fail to install any package if luasec 0.6 is installed

### ISSUE THREAD

**Issue by mpalmier74** [luarocks/luarocks#909]
Those two steps work fine in sequence:
sudo luarocks install luafilesystem 1.6.2
sudo luarocks install luasec 0.6

Those two steps do not work:
sudo luarocks install luasec 0.6
sudo luarocks install luafilesystem 1.6.2

Error: LuaRocks 2.2.0 bug (please report at luarocks-developers@lists.sourceforge.net).
/usr/share/lua/5.1/ssl.lua:125: bad argument #1 to 'setfd' (number expected, got nil)
stack traceback:
        [C]: in function 'request'
        /usr/share/lua/5.1/ssl/https.lua:133: in function 'request'
        /usr/share/lua/5.1/luarocks/fs/lua.lua:557: in function 'request'
        /usr/share/lua/5.1/luarocks/fs/lua.lua:621: in function 'http_request'
        /usr/share/lua/5.1/luarocks/fs/lua.lua:659: in function 'download'
        /usr/share/lua/5.1/luarocks/fetch.lua:40: in function 'fetch_url'
        /usr/share/lua/5.1/luarocks/manif.lua:97: in function 'fetch_manifest_from'
        /usr/share/lua/5.1/luarocks/manif.lua:135: in function 'load_manifest'
        /usr/share/lua/5.1/luarocks/search.lua:175: in function 'manifest_search'
        /usr/share/lua/5.1/luarocks/search.lua:208: in function 'search_repos'
        /usr/share/lua/5.1/luarocks/search.lua:284: in function 'find_suitable_rock'
        /usr/share/lua/5.1/luarocks/install.lua:146: in function </usr/share/lua/5.1/luarocks/install.lua:122>
        (tail call): ?
        [C]: in function 'xpcall'
        /usr/share/lua/5.1/luarocks/command_line.lua:208: in function 'run_command'
        /usr/bin/luarocks:33: in main chunk
        [C]: ?

It appears like luasec installed prevents installation or uninstallation of any package.
If luasec is removed than a package can be installed or removed.

**Comment by daurnimator** [comment]
LuaRocks 2.2 is end-of-life; there's not much we can do to fix it at this point.
Please update to Luarocks 3.0 or at least the slightly older 2.4.4

**Comment by hishamhm** [comment]
Yes, please upgrade! Closing this for now — feel free to reopen if the bug persists in the latest version.
