### ISSUE TITLE
path command puts in `$LUA_PATH` local lua files last instead of first

### ISSUE THREAD

**Issue by doronbehar** [luarocks/luarocks#919]
Possibly related to #428 and #558 which seem old and outdate (and possibly fixed in latest versions?) I think the command `luarocks path`'s output is wrong:

```
$ luarocks path
export LUA_PATH='/home/doron/.luarocks/share/lua/5.3/?.lua;/home/doron/.luarocks/share/lua/5.3/?/init.lua;/usr/share/lua/5.3/?.lua;/usr/share/lua/5.3/?/init.lua;/usr/lib/lua/5.3/?.lua;/usr/lib/lua/5.3/?/init.lua;./?.lua;./?/init.lua'
export LUA_CPATH='/home/doron/.luarocks/lib/lua/5.3/?.so;/usr/lib/lua/5.3/?.so;/usr/lib/lua/5.3/loadall.so;./?.so'
```

The only problem with this IMO is that `./?.lua` and `./?/init.lua` appear last and not first. Even if I run the same command with after I `unset LUA_PATH` in my shell, they don't appear first.

I have fixed it and I can request a pull but I'd like to know your opinions first.

### `luarocks --version`:

```
/usr/bin/luarocks 2.4.4
LuaRocks main command-line interface
```

**Comment by daurnimator** [comment]
The output is correct and intended: the intention is avoid files in your local directory from overriding system-wide libraries: that should be opt-in not opt-out.
You can see that lua itself puts the relative forms last:
https://www.lua.org/source/5.3/luaconf.h.html#LUA_PATH_DEFAULT

Or with:
```
lua5.3 -E -e 'print(package.path)'
```

**Comment by doronbehar** [comment]
I understand. If so, then what is the proper way to test libraries in the interpreter when they are already installed with `luarocks` in their stable version?

**Comment by daurnimator** [comment]
It depends on your tooling and preferred flow. E.g. busted supports `lpath` in its project config file https://github.com/daurnimator/lua-http/blob/ea12beba8647adaf9ab7fbe151850104714d2577/.busted#L3
