### ISSUE TITLE
luarocks init: created lua script missed project path

### ISSUE THREAD

**Issue by imolein** [luarocks/luarocks#924]
Hi,

when I create a new project with `luarocks init`, the project path is not included into `LUA_INIT` in the newly created lua script. I have to run `luarocks init --reset`, which recreate the lua script and then the project path is correct.

### Steps to reproduce

* `mkdir /tmp/test && cd /tmp/test`
* `luarocks init`
* `cat lua`
```
#!/bin/sh

LUAROCKS_SYSCONFDIR='/usr/local/etc/luarocks' LUA_INIT='package.path="/root/.luarocks/share/lua/5.3/?.lua;/root/.luarocks/share/lua/5.3/?/init.lua;/usr/local/share/lua/5.3/?.lua;/usr/local/share/lua/5.3/?/init.lua;"..package.path;package.cpath="/root/.luarocks/lib/lua/5.3/?.so;/usr/local/lib/lua/5.3/?.so;"..package.cpath' exec '/usr/bin/lua5.3'  "$@"
```
* `luarocks init --reset`
* `cat lua`
```
#!/bin/sh

LUAROCKS_SYSCONFDIR='/usr/local/etc/luarocks' LUA_INIT='package.path="/tmp/test/lua_modules/share/lua/5.3/?.lua;/tmp/test/lua_modules/share/lua/5.3/?/init.lua;/root/.luarocks/share/lua/5.3/?.lua;/root/.luarocks/share/lua/5.3/?/init.lua;/usr/local/share/lua/5.3/?.lua;/usr/local/share/lua/5.3/?/init.lua;"..package.path;package.cpath="/tmp/test/lua_modules/lib/lua/5.3/?.so;/root/.luarocks/lib/lua/5.3/?.so;/usr/local/lib/lua/5.3/?.so;"..package.cpath' exec '/usr/bin/lua5.3'  "$@"
```

### System

**luarocks version:** 3.0.3
**OS:** Reproduced on Ubuntu 16.04, 18.04 and Arch Linux

Greetings
Sebastian

**Comment by nightwarrior-xxx** [comment]
```luarocks init --reset``` is not working for me.

**Comment by imolein** [comment]
This problem still exists in version 3.1.2.

@nightwarrior-xxx In my case `init --reset` correct the created lua bash script and it works afterwards

**Comment by imolein** [comment]
I tested it today, after installing luarocks 3.3.1 and now `luarocks init --reset` is not working for me too.

**Comment by imolein** [comment]
I looked into this today. The problem is that on the first run of `luarocks init` the table `cfg.rocks_trees` has no entry for the directory where the command ran, but the function `path.map_trees()` uses this table to generate the lua path for the lua wrapper script.

**Comment by andrewstarks** [comment]
I'm having this issue in mac osx

After

```
sudo luarocks init --reset

Initializing project 'xxx' for Lua 5.3 ...
-------------------------------------------------

Checking your Lua installation ...
Adding entries to .gitignore ...
Preparing ./.luarocks/ ...


LuaRocks dev bug (please report at https://github.com/luarocks/luarocks/issues).
Arch.: macosx-x86_64
/usr/local/share/lua/5.3/luarocks/fs/unix/tools.lua:96: assertion failed!
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.3/luarocks/fs/unix/tools.lua:96: in function 'luarocks.fs.unix.tools.delete'
	(...tail calls...)
	/usr/local/share/lua/5.3/luarocks/cmd/init.lua:97: in function 'luarocks.cmd.init.command'
	(...tail calls...)
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.3/luarocks/cmd.lua:661: in function 'luarocks.cmd.run_command'
	/usr/local/bin/luarocks:38: in main chunk
	[C]: in ?
```

**Comment by imolein** [comment]
@andrewstarks This seems like a separate issue which is mac osx specific as far as I can tell. The function `tools.delete` of `fs.unix.tools` only accepts a absolute path:
https://github.com/luarocks/luarocks/blob/c52a5c57ccffa5a0929593cd94fa5f87e795efd7/src/luarocks/fs/unix/tools.lua#L90-L98

But in the init command, `fs.delete` is called with a relative path.

**Comment by Mehgugs** [comment]
On windows `luarocks init --reset` gives me the same assertion failed when trying to delete `lua.bat`

**Comment by imolein** [comment]
> On windows `luarocks init --reset` gives me the same assertion failed when trying to delete `lua.bat`

As far as I can see my last answer to @andrewstarks is also valid for windows. And as I wrote, I think this problem is different from the one I describe in my issue description - it is a new ticket imo.

**Comment by sewbacca** [comment]
I am having the same issue on Win10, is there a workarround?
