### ISSUE TITLE
Config/command line option to turn off documentation installation

### ISSUE THREAD

**Issue by james-callahan** [luarocks/luarocks#926]
To keep container sizes small, I'd like a way to turn off copying documentation into the tree.

**Comment by pauloue** [comment]
I think this is done (https://github.com/luarocks/luarocks/commit/b096e35e29f5406f74c5cf7bdb86eff8ebf3b526)?

**Comment by georgeroman** [comment]
@pauloue Yes, this was done.

**Comment by james-callahan** [comment]
Thanks @georgeroman!
