### ISSUE TITLE
luarocks doesn't find lua5.3-dev package

### ISSUE THREAD

**Issue by tuxd3v** [luarocks/luarocks#929]
Hi,
I am trying to create a rockspec file:
when I try it,

luarocks --local build xpto.rockspec
it trows me a error:
"
Missing dependencies for xpto:
   lua5.3-dev >= 5.3 (not installed)

fanctl 0.1-5 depends on lua5.3-dev >= 5.3 (not installed)

Error: Could not satisfy dependency lua5.3-dev >= 5.3: No results matching query were found.
"
The thing is I have lua5.3 and lua5.3-dev installed, BUT throgout the OS packet Manager, nut luarocks..

And they have been installed on:
"
/usr/include/lua5.3
/usr/include/aarch64-linux-gnu/lua5.3-deb-multiarch.h
/usr/lib/aarch64-linux-gnu/pkgconfig/lua5.3-c++.pc
/usr/lib/aarch64-linux-gnu/pkgconfig/lua5.3.pc
/usr/lib/aarch64-linux-gnu/liblua5.3.so
/usr/lib/aarch64-linux-gnu/liblua5.3.so.0
/usr/lib/aarch64-linux-gnu/liblua5.3-c++.so.0.0.0
/usr/lib/aarch64-linux-gnu/liblua5.3-c++.a
/usr/lib/aarch64-linux-gnu/liblua5.3.a
/usr/lib/aarch64-linux-gnu/liblua5.3-c++.so
/usr/lib/aarch64-linux-gnu/liblua5.3.so.0.0.0
/usr/lib/aarch64-linux-gnu/liblua5.3-c++.so.0
/usr/bin/lua5.3
/usr/share/lua5.3
/usr/share/man/man1/lua5.3.1.gz
/usr/share/doc/liblua5.3-0
/usr/share/doc/lua5.3
/usr/share/doc/liblua5.3-dev
"
and NOT on '/usr/local'

How can I tell luarocks that I already have lua5.3 and lua5.3-dev installed?
thanks in Advance

**Comment by tuxd3v** [comment]
I am on:

Ubuntu bionic, with LuaRocks 2.4.2

**Comment by daurnimator** [comment]
What is "lua5.3-dev"? that is not something luarocks knows about. At first glance it seems to be an issue with that rockspec?

**Comment by tuxd3v** [comment]
This is my rockspec:
"
rockspec_format="1.0"
package = "fanctl"
version = "0.1-5"
description = {
	summary = "Active Thermal Service",
	detailed = [[
		This tool, provide support for Rockpro64, Active thermal Service( Fan Control ).
	]],
	homepage = "https://github.com/tuxd3v/fanctl",
	license = "See License..",
	maintainer = "tuxd3v <tuxd3v@sapo.pt>"
}
source = {
	url = "https://github.com/tuxd3v/fanctl.git",
	branch = "master",
	tag = "v0.1.5"
}
dependencies={}
build = {
	type 	= "make",
	modules = {
		sleep = "src/sleep.c"
	}
}
"
The ideia is use a lua file, that requires a C module(sleep.so)
I don't know whats wrong with it..
Does luarocks create some cache that I can clean?

Thanks in Advance
regards
tux

**Comment by daurnimator** [comment]
That is not xpto. That is fanctl.

**Comment by tuxd3v** [comment]
xpto was an example..
The name is not relevant.

Only the way I can solve this problem.

**Comment by tuxd3v** [comment]
> What is "lua5.3-dev"? that is not something luarocks knows about. At first glance it seems to be an issue with that rockspec?

lua5.3-dev is the OS packet that provides the header files and lua3.5.so, so that we can create lua C modules..

It was not installed by luarocks,
I don't know why luarocks complain about it..

Does luarocks create some cache, when I try to build the my tool?
If so maybe better to clean it, but I don't know where it is..
I am new to luarocks..

**Comment by moteus** [comment]
May be problem in dpkg and not in LuaRocks?

**Comment by tuxd3v** [comment]
But, when I try:
luarocks --local build fanctl.rockspec
it trows me a error:
"
Missing dependencies for xpto:
lua5.3-dev >= 5.3 (not installed)

fanctl 0.1-5 depends on lua5.3-dev >= 5.3 (not installed)

Error: Could not satisfy dependency lua5.3-dev >= 5.3: No results matching query were found.
"
The package manager knows ad detect the package, also make compile the module and so on..
but I wanted to use luarocks..

**Comment by moteus** [comment]
Then may be you have installed module which have this deps
And when you build your rockspec luarocks checks all other installed rocks
But in my case just write warnings if found any problem in manifest

**Comment by tuxd3v** [comment]
I don't know what were wrong wiht it sincerelly, what I know is that yesterday night I performed a reboot after upgrade OS, then today, that dependency was not there...
Can't explain, but trying...I have exported some variables first, and maybe, something went wrong..
Aparte from that, I already updated rockspec...after all its my first one, and maybe there are something faulty, but it install nicelly, because he uses make backend..

But, I was digging at it, and ...there are no folder were the code is downloaded...?!
Does it download ans install from temporary folder( /tmp )?
the rockspec is here:
https://github.com/tuxd3v/fanctl/blob/master/fanctl-0.1-5.rockspec

My sincere thanks, to all that tried to help on this.
Best Regards
