### ISSUE TITLE
problems recognizing diferent arch paths..

### ISSUE THREAD

**Issue by tuxd3v** [luarocks/luarocks#937]
Hello,
I am developing a  project with Lua.
I decided to use LuaRocks as a simple way to push the git hub code..
https://github.com/tuxd3v

I use this rockspec file:
https://github.com/tuxd3v/ats/blob/master/ats-master-0.rockspec

The problem is on external dependencies,
external_dependencies = {
	platforms = {
		linux = {
			UNISTD	= { header	= "unistd.h"		},
			STAT	= { header	= "sys/stat.h"		},
			TYPES	= { header	= "sys/types.h"		},
			LUALIB	= { header	= "lualib.h"		},
			LAUXLIB	= { header	= "lauxlib.h"		},
			LUA	= { header	= "lua.h"		},
			LUA53	= { library	= "liblua5.3.so"	}
		}
	}
}

I tried this in /etc/luarocks/config.lua:
local handler = io.popen( "gcc -dumpmachine", "r" )
TRIPLET = handler:read( "l")
handler:close()
variables={
	UNISTD_INCDIR	= "/usr/include",
	STAT_INCDIR	= "/usr/include/" .. TRIPLET,
	TYPES_INCDIR	= "/usr/include/" .. TRIPLET,
	LUALIB_INCDIR	= "/usr/include/lua5.3",
	LAUXLIB_INCDIR	= "/usr/include/lua5.3",
	LUA_INCDIR	= "/usr/include/lua5.3",
	LUA53_LIBDIR	= "/usr/lib/" .. TRIPLET
}
this gives me error..

The problem is, via OS when I install Lua, it could be in different places..
in some places the TRIPLET is 'aarch64-linux-gnu', but it could be something else, like 'arm-linux.gnueabihf' , and so on...

This is machine dependent, how can I tell rockspec to do a 'gcc -dumpmachine', so that it wil create the paths in to install, in advance?

Thanks for your help on this,
Best Regards

**Comment by tuxd3v** [comment]
Hello
I need to contruct paths based on output of 'gcc -dumpmachine',
But I don't know how to tell /etc/luarocks/config.lua, how to execute first 'gcc -dumpmachine'.

I wanted this in config.lua:
TRIPLET = 'gcc -dumpmachine'

variables={
UNISTD_INCDIR	= "/usr/include",
STAT_INCDIR	= "/usr/include/" .. TRIPLET,
TYPES_INCDIR	= "/usr/include/" .. TRIPLET,
LUALIB_INCDIR	= "/usr/include/lua5.3",
LAUXLIB_INCDIR	= "/usr/include/lua5.3",
LUA_INCDIR	= "/usr/include/lua5.3",
LUA53_LIBDIR	= "/usr/lib/" .. TRIPLET
}

Is this possible?
Thanks in Advance
tux

**Comment by tuxd3v** [comment]
At this moment, 

The only Solution I found to resolve all external dependencies are with a heredocument :
cat <<HERE >> /etc/luarocks/config.lua
variables = {
    UNISTD_INCDIR   = "/usr/include",
    STAT_INCDIR     = "/usr/include/$( gcc -dumpmachine )",
    TYPES_INCDIR    = "/usr/include/$( gcc -dumpmachine )",
    LUALIB_INCDIR   = "/usr/include/lua5.3",
    LAUXLIB_INCDIR  = "/usr/include/lua5.3",
    LUA_INCDIR      = "/usr/include/lua5.3",
    LUA53_LIBDIR    = "/usr/lib/$( gcc -dumpmachine )"
}
HERE

But this have to be issued on target machine shell :(
We should be able to issue some commands, and get its return, in that way, we will not need to declare variables in luarocks config, only in rockspec..

**Comment by hishamhm** [comment]
Hi, you shouldn't need to specify Lua libraries or standard C libraries in your external_dependencies. Lua libraries are automatically set as LUA_LIBDIR and LUA_INCDIR and standard C libraries like unistd.h should be automatically found by your compiler (or cross-compiler!) without setting them explicitly.

Did you get any failures that led you to attempt this? It may be a problem in your compiler setup.

**Comment by tuxd3v** [comment]
Hi, 
Thanks for your response,
How can I see, were  LUA_LIBDIR, and LUA_INCDIR are pointing to?

**Comment by hishamhm** [comment]
`luarocks config` should display this.

**Comment by tuxd3v** [comment]
thanks for the help,

# luarocks config --lua-incdir
/usr/include/lua5.3

# luarocks config --lua-libdir
/usr/local/lib

# luarocks config --system-config
/etc/luarocks/config.lua

# luarocks config --user-config
/root/.luarocks/config-5.3.lua
Error: file not found

root@rockpro64:/# luarocks config --rock-trees
/root/.luarocks
/usr/local

The problem here could be /usr/local/lib, not in my case I successfully changed location on my aplication and it doesn't need more the TRIPLET path, because now is in /usr/local.

But my system libraries could be in /usr/lib, instead of /usr/local/lib..
The only way to surpasse this is putting in .bashrc:
something like this:

PREFIX="/usr/local"
export LUA_LIB="${PREFIX}/lib/lua/5.3"
export LUA_SHARE="${PREFIX}/share/lua/5.3"

PREFIX="/usr"
export SYS_LUA_LIB="${PREFIX}/lib/$(gcc -dumpmachine)" <-- in my case "aarch64-linux-gnu"
export SYS_LUA_SHARE="${PREFIX}/share/lua5.3"

But I would like to in Advance( in Rockspec be able to assign some variables, and execute a command in advance ).
The execution of a command ind a assigment of variables, in rockspec could cover a lot of situations, installing in Linux/windows/bsd, and so on..

I am also not aware of LuaRocks in full, I am only a beguining in Lua, that likes a lot of the concepts and simplicity of Lua...maybe for a LuaShell( lsh ) .. :)

**Comment by hishamhm** [comment]
The location of the Lua libraries is the concern of LuaRocks and not the rockspec, nad the location of the system libraries is the concern of your compiler.

If the values or LUA_LIBDIR and LUA_INCDIR aren't set correctly, this is a problem with your LuaRocks installation, not your rockspec. The LuaRocks `configure` script lets you set those values explicitly, but this is usually not necessary because of autodetection.

Also, to be clear, none of these should be in `external_dependencies`:

```
UNISTD = { header = "unistd.h" },
STAT = { header = "sys/stat.h" },
TYPES = { header = "sys/types.h" },
LUALIB = { header = "lualib.h" },
LAUXLIB = { header = "lauxlib.h" },
LUA = { header = "lua.h" },
LUA53 = { library = "liblua5.3.so" }
```

If your code includes those standard C headers with `<>` like `#include <unistd.h>` the compiler will find them. Also, the Lua path locations are detected and handled by LuaRocks, so you shouldn't set them explicitly either.

Looking at your rockspec, what you're missing is a mapping from the LuaRocks variable to your Makefile's library. Remove that `external_dependencies` section and add this to the `build` section:

```
-- LUA_LIBDIR is where the Lua VM library is installed
build_variables = { LUA_LIBDIR = "$(LUA_LIBDIR)" },
-- LUADIR is where Lua modules should be installed (e.g. /usr/local/lib/lua/5.3/
install_variables = { LDIR = "$(LUADIR)" },
```

and in your Makefile, add `LUA_LIBDIR := /usr/local/lib`

**Comment by tuxd3v** [comment]
Hello,
sorry for the late response..
Thanks in Adance..

I updated my Makefile, and added ti the install_variables the Locations I want( I put the files under the rocktree ;) )..
Basically, now all files are under the  LuaRocks rocktree,  :)
With symbolic links to the correct places in the OS..

Thanks a lot, for the help on this subject..
LuaRocks has lots of documentation, but there are some things that happens "magically", and the people( me ), is afraid of experimenting with..

With your help, my RockSpec know is OK!
Regards,
