### ISSUE TITLE
Error: LuaRocks 2.4.3 bug (please report at https://github.com/keplerproject/luarocks/issues).

### ISSUE THREAD

**Issue by AndyWangG** [luarocks/luarocks#940]
[root@localhost resty]# luarocks install lua-resty-nettle
Warning: Failed searching manifest: Failed fetching manifest for https://luarocks.org - Failed downloading https://luarocks.org/manifest - /root/.cache/luarocks/https___luarocks.org/manifest
Installing https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/lua-resty-nettle-0.105-1.src.rock

Error: LuaRocks 2.4.3 bug (please report at https://github.com/keplerproject/luarocks/issues).
/usr/local/share/lua/5.1/luarocks/fs/lua.lua:723: attempt to call field 'sumhexa' (a nil value)
stack traceback:
	/usr/local/share/lua/5.1/luarocks/manif.lua:75: in function 'make_rock_manifest'
	/usr/local/share/lua/5.1/luarocks/build.lua:317: in function 'build_rockspec'
	/usr/local/share/lua/5.1/luarocks/build.lua:359: in function 'do_build'
	/usr/local/share/lua/5.1/luarocks/build.lua:401: in function </usr/local/share/lua/5.1/luarocks/build.lua:390>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/luarocks/command_line.lua:210: in function 'run_command'
	/usr/local/bin/luarocks:34: in main chunk
	[C]: at 0x004051d0

**Comment by ignacio** [comment]
Please take a look at this other issue: https://github.com/luarocks/luarocks/issues/805
It seems you have a md5 module that is totally incompatible.

**Comment by hishamhm** [comment]
Yes, this is caused by an incompatible md5 module installed. @AndyWangG, as a workaround you can add `fs_use_modules = false` to your `~/.luarocks/config-5.1.lua` file (run `luarocks` with no arguments to see the path for your system-wide install).
