### ISSUE TITLE
lua.h not found in ./configure...

### ISSUE THREAD

**Issue by FHGDev** [luarocks/luarocks#942]
Hey! I was installing LuaRocks today! I ran the ./configure file, and it gave me an error: `lua.h not found`.
I'm running Knoppix on a Toshiba Satellite.

**Comment by hishamhm** [comment]
@FHGDev you need to install the Lua development packages for your distro, so that `lua.h` is included. It's usually called something like `lua-devel` or `liblua-dev`, etc.

**Comment by FHGDev** [comment]
ty.

**Comment by khairiGuiri123** [comment]
bash: /data/data/com.termux/files/usr/bin/luarocks: /data/data/com.termux/files/usr/bin/: bad interpreter: Permission denied

**Comment by WinformsWizard** [comment]
Hi. For the Linux Mint Lua package, instead of just "lua.h", it is "lua5.1/lua.h". Is there any way to work around this?
