### ISSUE TITLE
Other build systems than make/cmake

### ISSUE THREAD

**Issue by mokafolio** [luarocks/luarocks#944]
The module I am considering to put on luarocks uses meson & ninja as its build system. What are my best options to make that work with luarocks at this point in time? To only provide binaries?

Is there any way to use other build backends i.e. though maybe custom scripts or the luarocks addon functionality?

Thank you!

**Comment by mokafolio** [comment]
I ended up using the `external_dependencies` field in the rockspec to make sure build dependencies are installed on the platform. I then simply used the command build type to run the meson and ninja related build commands. I am considering getting rid of using external_dependencies at all and just let meson fail if they are not installed instead. I think it would be great to add a custom build example to the docs.

**Comment by psychon** [comment]
@mokafolio Can you share what you ended up with? I'm trying to come up with a way to use meson to build a Lua package + have a rockspec for it. However, meson kind of wants to use pkg-config to find Lua which seems incompatible with luarocks specifying the individual variables.

Also, I wonder if this somehow could be made to work on Windows. Meson certainly works on Windows, but if I use some shell scriptlet in `command`, then that also certainly will not work on Windows.

@hishamhm Do you perhaps know of some example rockspec that builds a Lua package through meson, uses the Lua version as provided by Luarocks, and also works on Windows?

**Comment by mokafolio** [comment]
@psychon  as @hishamhm pointerd out, you need to add `rockspec_format = "3.0"` for this to work. My build command looks something like this:
`build = {
    type = "command",
    build_command = "meson -Dlr_install_lib_dir=$(LIBDIR) -Dlr_install_lua_dir=$(LUADIR) -Ddefault_library=static -Dbuildtype=release build && cd build && ninja",
    install_command = "cd build && ninja install"
}`

hope that helps!

**Comment by psychon** [comment]
Thanks!
