### ISSUE TITLE
Maintainer of the Arch Linux package

### ISSUE THREAD

**Issue by MisterDA** [luarocks/luarocks#946]
Hello,

I know that most of the time, upstream developers don’t care about the downstream packages, but the LuaRocks [package][pkg] in Arch Linux has been lacking a maintainer since July. It has not been updated to LuaRocks 3. A pity!

Should there be an Arch Trusted User around here, could you consider adopting and updating the package?

Thanks.

[pkg]: https://www.archlinux.org/packages/?q=luarocks

**Comment by daurnimator** [comment]
I'm looking to become an Arch TU soon.

**Comment by daurnimator** [comment]
I am now a TU. Will get on it soon :)

**Comment by daurnimator** [comment]
Done. https://www.archlinux.org/packages/community-testing/any/luarocks/
