### ISSUE TITLE
LuaConsole has Matured

### ISSUE THREAD

**Issue by tilkinsc** [luarocks/luarocks#955]
Hey LuaRocks repo, author of [LuaConsole](https://github.com/tilkinsc/LuaConsole) here!

So my CLI has improved a whole lot. The latest release allows a switch with pre-built binaries to be linked locally to the repo. In other words, `luaw -w lua-5.3.5` or `luaw -w luajit` etc. So this enables users to use any lua version they want.

I am wondering about the welcome-ness of pull requests adding the specific ability to configure/install with support for LuaConsole.

**Comment by daurnimator** [comment]
> I am wondering about the welcome-ness of pull requests adding the specific ability to configure/install with support for LuaConsole.

This can be done with `luarocks config lua_interpreter luaw`

**Comment by tilkinsc** [comment]
Could I have some refs to the file in question for this command to parse? My switches are unkosher to that of the original lua executable.

**Comment by daurnimator** [comment]
> Could I have some refs to the file in question for this command to parse?

I don't know what you mean



> My switches are unkosher to that of the original lua executable.

Then trying to use your executable as the `lua_interpreter` won't work. I believe it's used to e.g. call the lua interpeter for generated wrappers shell scripts.
