### ISSUE TITLE
[RFC] Mentoring for the LuaRocks ecosystem at Google Summer of Code

### ISSUE THREAD

**Issue by hishamhm** [luarocks/luarocks#962]
Hello,

The deadline for [Google Summer of Code](https://summerofcode.withgoogle.com) is upon us on February 6. This year, we'll try to do something different, and open the scope of LuaRocks mentoring to the LuaRocks ecosystem at large:

**If you would like to mentor** a Lua-related project (not necessarily on the LuaRocks codebase itself) that contributes to the LuaRocks ecosystem — i.e. something that leverages LuaRocks or is installable via `luarocks install`:

* write a reply here starting with "Mentoring proposal:"
* write a title and short abstract of your project idea
* add your name and a contact email address so that the LuaRocks admins may contact you directly

**If you would like to be a student** it is not time to officially apply yet, but you may also reply here voicing your interest, and also giving suggestions of projects you'd like to be mentored on! You may inspire possible mentors who are out of ideas. :)

What we need now to make a formal application of LuaRocks as an organization to participate in GSoC is a set of mentors and project ideas. We will only apply this year if we get enough critical mass.

I know this all sounds very last-minute, but this was inspired by today's conversation at FOSDEM. And people tend to send last-minute applications, anyway, so let's see if the added urgency gets people moving. :)

**Comment by hishamhm** [comment]
Mentoring proposal: Expression-level coverage analysis for LuaCov

LuaCov only offers line-level coverage analysis, meaning that it can tell if a line executed or not, but not if every possible branch within that line executed. That means, for example, that if a statement like `if x and y > 20 then return 10 end` is written in a single line, we don't have coverage information if it has been tested both with the condition being true and being false. This is due to a limitation in the Lua `debug` library, which only gives traces with at most line granularity. The idea of this project is to patch the Lua VM adding expression-level tracing, and then adjusting LuaCov to make it use it.

Mentor: Hisham Muhammad <hisham@konghq.com>

**Comment by Joycevarg** [comment]
I am a student and I would like to try out this idea.I'm new to Lua but have considerable experience with C and C++.Can I start with the idea before applying for GSoc

> Mentoring proposal: Expression-level coverage analysis for LuaCov
> 
> LuaCov only offers line-level coverage analysis, meaning that it can tell if a line executed or not, but not if every possible branch within that line executed. That means, for example, that if a statement like `if x and y > 20 then return 10 end` is written in a single line, we don't have coverage information if it has been tested both with the condition being true and being false. This is due to a limitation in the Lua `debug` library, which only gives traces with at most line granularity. The idea of this project is to patch the Lua VM adding expression-level tracing, and then adjusting LuaCov to make it use it.
> 
> Mentor: Hisham Muhammad [hisham@konghq.com](mailto:hisham@konghq.com)

**Comment by aryajur** [comment]
### Mentoring Proposal:
Lua graphing library
To create a graphical library possibly using IUP extensible by Lua to allow easy creation of software like a schematic editor/flowchart creator/mind maps/block diagrams in Lua. The library needs to create basic mechanisms and graphic checks to create custom blocks and interconnections and provide an API to use these to create complex interactions like hierarchical schematic editors, etc.
Name: Milind Gupta
Email: milind.gupta@gmail.com

**Comment by aryajur** [comment]
### Mentoring Proposal:
Ngspice bindings to Lua
To create Lua bindings to the Ngspice shared library either using C or using an FFI module like Alien.

Name: Milind Gupta
Email: milind.gupta@gmail.com

**Comment by daurnimator** [comment]
Mentoring proposal:

New command line argument handling and auto-completion for luarocks

  - #879 
  - Last time @hishamhm and I talked we settled on [argparse](https://github.com/mpeterv/argparse)
    I'm not sure if that decision needs revising with the passing of Peter. We may want the luarocks github org to take over the argparse package?
  - Would probably involve implementing https://github.com/mpeterv/argparse/issues/19

**Comment by hishamhm** [comment]
@aryajur That is a very interesting proposal! A particular challenge in it is that IUP is not available in LuaRocks, so to use it as a dependency one would have to build and package it in a LuaRocks-compatible way.

**Comment by Zash** [comment]
### Mentoring proposal: Prosody plugin installer

Brief explanation: This project would produce an easy way to install and manage plugins for the Prosody server.

Involved Technologies: Lua

Mentor(s):

-    Matthew Wild @mwild1 <mwild1@gmail.com>
-    Kim Alvefur @Zash 

Deliverables / Expected Results:

-   Commands to install, update, remove and list installed plugins.
-   Scripts to build and manage a repository of plugins.

Milestones:

 -  Implement command to install a plugin from a repository
 -  Implement commands to remove and update installed plugins
 -  Develop scripts to build a plugin repository.

Prosody has [hundreds of community modules](https://modules.prosody.im/) that provide additional features and extensions to the core server. Currently installing these is a manual process that currently involves a number of manual steps.

The goal of this project would be to produce simple commands to install, update and remove community modules. Rather than inventing a new package manager, the project would ideally build on top of the luarocks project.

**Comment by aryajur** [comment]
> @aryajur That is a very interesting proposal! A particular challenge in it is that IUP is not available in LuaRocks, so to use it as a dependency one would have to build and package it in a LuaRocks-compatible way (if IUP is indeed chosen as a dependency).

I was hoping to use the binaries already packaged by IUP and create a rockspec to get the binary for the right system initially. But even without that this library would be something like LuaCrypto or LuaSec that depend on openssl but openssl is not built or installed by their rockspec.

**Comment by hishamhm** [comment]
@aryajur both approaches makes sense!

**Comment by hishamhm** [comment]
@RussellHaley I'm afraid this would not be a good fit for the scope of GSoC, which is a 3-month full-time project. I'm not sure if writing bindings to an existing C lib would fit the bill (of course, it depends a lot on the library -- binding something like Qt is a huge task; some other libraries are clearly not 3 months of work for a dedicated student). @aryajur, same concern about the Ngspice libraries. Do you think those libraries fit the expectations of work for a GSoC student?

**Comment by hishamhm** [comment]
Thanks everyone! LuaRocks has just applied to be a participating org in Google Summer of Code 2019! I added most of the projects listed here:

https://luarocks.github.io/luarocks/gsoc/ideas2019.html

That page can still be updated with new projects and mentors added. So I'll leave this issue open here for new entries during the application process!

Cheers, and good luck for all of us!

**Comment by hishamhm** [comment]
> Can I start with the idea before applying for GSoc

@Joycevarg great that you're interested! I think according to the rules you can start getting acquainted with the project, yes, though the bulk of the work needs to be done during the program. But note we haven't even been accepted to GSoC yet. :)

**Comment by aryajur** [comment]
> @aryajur, same concern about the Ngspice libraries. Do you think binding those libraries fit the expectations of work for a GSoC student? (3 month, full time, with mentoring). If so we can add those to the ideas list.

For Nspice bindings the work is actually quite simple since they have a well defined C API for their shared library. All that needs to be done is expose it directly in Lua. I have done a couple of calls in Lua using Alien and it seems perfect for new people because it is so well defined.

**Comment by otoharmonics** [comment]
> @RussellHaley I'm afraid this would not be a good fit for the scope of GSoC, which is a 3-month full-time project. I'm not sure if writing bindings to an existing C lib would fit the bill (of course, it depends a lot on the library -- binding something like Qt is a huge task; some other libraries are clearly not 3 months of work for a dedicated student). @aryajur, same concern about the Ngspice libraries. Do you think binding those libraries fit the expectations of work for a GSoC student? (3 month, full time, with mentoring). If so we can add those to the ideas list.

Hi @hishamhm, the bindings already exist in the source package. The project would be to build, test, write the rockspec and possibly port to Windows (it's netbsd code so very portable). The project would be the process of adding the package to LuaRocks. Besides possibly fixing bugs, there would be little to no C coding involved.

**Comment by RussellHaley** [comment]
> @RussellHaley I'm afraid this would not be a good fit for the scope of GSoC, which is a 3-month full-time project. I'm not sure if writing bindings to an existing C lib would fit the bill (of course, it depends a lot on the library -- binding something like Qt is a huge task; some other libraries are clearly not 3 months of work for a dedicated student). @aryajur, same concern about the Ngspice libraries. Do you think binding those libraries fit the expectations of work for a GSoC student? (3 month, full time, with mentoring). If so we can add those to the ideas list.

Hi, Sorry I was accidentally logged in as a different account when I answered. To repeat:

Hi @hishamhm, the bindings **already exist** in the source package. The project would be to build, test, write the rockspec and possibly port to Windows (it's netbsd code so very portable). The project would be the process of adding the package to LuaRocks. Besides possibly fixing bugs, there would be little to no C coding involved.

**Comment by hishamhm** [comment]
@aryajur @RussellHaley thanks for the further descriptions. Based on them, it does seem like the size of the ngspice and netpgp projects would be a bit too small for GSoC.

**Comment by aryajur** [comment]
Luarocks was selected in the GSOC 2019. How does this work now? Does a student select a project and contact the mentor directly?

**Comment by daurnimator** [comment]
GSoC 2019 is has now started; will close this issue :)
