### ISSUE TITLE
Installing old version rocks

### ISSUE THREAD

**Issue by ChungPin** [luarocks/luarocks#969]
I'm now trying to use older version of Torch7
when I'm installing packages using command` luarocks install rnn`  (cnn, optim, cutorch)
it seems to install the package for the latest version for Torch7.

Is there any way to install older packages for older Torch7?

**Comment by daurnimator** [comment]
Torch manages their own luarocks repository. With luarocks you can pass a version to install, e.g. `luarocks install mymodule-0.1.0`, as long as they are still hosting the older versions, that should work.
