### ISSUE TITLE
Cygwin documentation

### ISSUE THREAD

**Issue by cup** [luarocks/luarocks#977]
it seems with Cygwin you actually need to use the Unix instruction

https://github.com/luarocks/luarocks/wiki/Installation-instructions-for-Unix

rather than the Windows one

https://github.com/luarocks/luarocks/wiki/Installation-instructions-for-Windows

i think a note should be added on the Windows wiki explaining this

**Comment by Deepak123bharat** [comment]
https://github.com/luarocks/luarocks/wiki/Installation-instructions-for-Windows is updated.

**Comment by hishamhm** [comment]
Thanks @Deepak123bharat !
