### ISSUE TITLE
newer luarocks makes busted unable to test other lua versions

### ISSUE THREAD

**Issue by edubart** [luarocks/luarocks#980]
Since LuaRocks 3 I am unable to use a busted 5.3 lua install to test 5.1 lua codes. 

## Steps to reproduce:
1. Install LuaRocks 3.0.4, Lua 5.1 and Lua 5.3
2. Remove any installed busted version.
3. Install busted for both lua versions using lua rocks in the following order:
```shell
$ sudo luarocks install --lua-version=5.1 busted
$ sudo luarocks install --lua-version=5.3 busted
```
4. Run busted in any folder:
```shell
$ busted --lua=lua5.3
0 successes / 0 failures / 2 errors / 0 pending : 0.000013 seconds

$ busted --lua=lua5.1
lua5.1: /home/bart/.luarocks/share/lua/5.3/pl/path.lua:28: pl.path requires LuaFileSystem
stack traceback:
	[C]: in function 'error'
	/home/bart/.luarocks/share/lua/5.3/pl/path.lua:28: in main chunk
	[C]: in function 'require'
	/home/bart/.luarocks/share/lua/5.3/busted/runner.lua:3: in main chunk
	[C]: in function 'require'
	.../lib/luarocks/rocks-5.3/busted/2.0.rc13-0/bin/busted:3: in main chunk
	[C]: ?
```

The problem is the new usage of `LUA_INIT` by LuaRocks, because I have compared  LuaRocks 3 and LuaRocks 2 binary of the installed busted, the new one looks like this:
```sh
#!/bin/sh

LUAROCKS_SYSCONFDIR='/etc/luarocks' LUA_INIT='package.path="/home/bart/.luarocks/share/lua/5.3/?.lua;/home/bart/.luarocks/share/lua/5.3/?/init.lua;"..package.path;package.cpath="/home/bart/.luarocks/lib/lua/5.3/?.so;"..package.cpath;local k,l,_=pcall(require,"luarocks.loader") _=k and l.add_context("busted","2.0.rc13-0")' exec '/usr/bin/lua5.3' '/home/bart/.luarocks/lib/luarocks/rocks-5.3/busted/2.0.rc13-0/bin/busted' "$@"
```

While the old installed binary look like this:
```sh
#!/bin/sh

exec '/usr/bin/lua5.3' -e 'package.path="/home/bart/.luarocks/share/lua/5.3/?.lua;/home/bart/.luarocks/share/lua/5.3/?/init.lua;"..package.path;package.cpath="/home/bart/.luarocks/lib/lua/5.3/?.so;"..package.cpath;local k,l,_=pcall(require,"luarocks.loader") _=k and l.add_context("busted","2.0.rc13-0")' '/home/bart/.luarocks/lib/luarocks/rocks-5.3/busted/2.0.rc13-0/bin/busted' "$@"
```

Changing the busted binary to the old style using `-e` instead of `LUA_INIT` makes busted runs fine. The problem is that busted is designed to run itself again using the supplied lua version when using the flag `--lua=lua5.1`, but when doing this the environment variable `LUA_INIT` overrides the package paths of Lua 5.1 causing it to not find any package.

## Workarounds
1. Run `busted~` instead of `busted --lua=lua5.1` to test lua5.1, but this will depend on the order that you install both busted versions.
2. Edit the busted installed binary as above.

## Possible fix
1. LuaRocks could revert `LUA_INIT` usage, because is not uncommon that some packages exec lua binaries, and when doing this the user expects that `LUA_CPATH` and `LUA_PATH` variables is respected.
2. Busted could patch to make `--lua` flag compatible with LuaRocks but I am not sure if asking the package maintainer to unset LUA_INIT environment variable before running any lua binary is the correct choice.

**Comment by Tieske** [comment]
My guess is because there is one `bin` dir holding the `busted` command script, the last install wins.
