### ISSUE TITLE
Windows XP compability?

### ISSUE THREAD

**Issue by ololoe** [luarocks/luarocks#989]
I ran luarocks on XP and it failed with same error as here https://github.com/luarocks/luarocks/issues/866 `luarocks --verbose` said that it tried to rund icacls which is not present on XP. Which version is XP compatible?

**Comment by daurnimator** [comment]
Looks like XP doesn't have icacls; it had its predecessor cacls instead.

Considering that XP is now out of support; should we even try to support it? What are you using XP for?

**Comment by ololoe** [comment]
If lua supports XP you should support it too. Why do you need to change rights at all?

**Comment by hishamhm** [comment]
> Which version is XP compatible?

LuaRocks 2.x, which is no longer supported — if you don't mind using an unsupported operating system, I guess you don't mind using an unsupported package manager.

**Comment by ololoe** [comment]
AFAIK XP is supported by latest Lua version. So why do you have to change permissions?
