### ISSUE TITLE
Are "Installation instructions for windows" up to date ?

### ISSUE THREAD

**Issue by hriekehof** [luarocks/luarocks#990]
Hi there. I had a luarocks 2.4.4 installation for quite a while and wanted to update to luarocks 3.0.4 recently. When i read the installtion instructions for windows they seem not to match what i'm getting from the package i download. 
One of the first paragraphs says:
`
The package includes an installer script, INSTALL.BAT, which provides a number of options for customizing your installation. Run INSTALL /? for details.
`
The install.bat script is not present int the `luarocks-3.0.4-windows-32.zip ` package. 

Also all the options seem to apply to the older way of installing luarocks. Do i miss a link or something or is the Doku outdated ?

**Comment by Deepak123bharat** [comment]
The install.bat script is present in luarocks-3.0.4-win32.zip(Windows package) not in luarocks-3.0.4-windows-32.zip (Windows binary)

**Comment by hriekehof** [comment]
ah thanks. Personal i was confused by the added text: `(legacy Windows package, includes Lua 5.1)`
so i thought this i not the way go with the new version. 
It would be nice if the Installation docu would be updated with a small addition that there are two ways of installing it ? Legacy like this: ..... New way like this: .....

**Comment by vikyd** [comment]
@hriekehof  can you paste an example url of `luarocks-3.0.4-win32.zip(Windows package)`  here?
