### ISSUE TITLE
Incorrect handling of all-negative supported_platforms rockspec value

### ISSUE THREAD

**Issue by slact** [luarocks/luarocks#993]
The [documentation](https://github.com/luarocks/luarocks/wiki/Rockspec-format) for the `supported_platforms` field states:
>  If only negative entries are listed, the rock is assumed to be portable to any platform except those listed. 

However, in luarocks 3.0.4, a rockspec with an all-negative `supported_platforms` is always treated as on an unsupported platform.

**Comment by Checksum** [comment]
Ran into this with `openresty:alpinel-fat` as well. Any known workarounds?

**Comment by daurnimator** [comment]
This should have been fixed with #994
