### ISSUE TITLE
How to preserve /tmp/ files?

### ISSUE THREAD

**Issue by d9k** [luarocks/luarocks#997]
Do luarocks have cli switch to preserve temporary files after install?

I have an installation error with broken files during `luarocks install --local ...`  but I can't debug it because log file referenced in `See also "/tmp/luarocks_.../...log"` message is being deleted after luarocks stops it's work.

I couldn't find information about the switch in google.

**Comment by hishamhm** [comment]
There is no switch for that — what was the full message? LuaRocks does not keep log files in /tmp.
