### ISSUE TITLE
 module 'luasql.mysql' not found:,I need help,how to install luarocks in windows

### ISSUE THREAD

**Issue by LiuSteamedBuns** [luarocks/luarocks#999]
D:\touchsprite_6560\TouchSprite\bin\lua52.exe: ...hsprite_6560\TouchSprite\workspace\connectMysql\main.lua:1: module 'luasql.mysql' not found:
	no field package.preload['luasql.mysql']
	no file 'D:\touchsprite_6560\TouchSprite\bin\lua\luasql\mysql.lua'
	no file 'D:\touchsprite_6560\TouchSprite\bin\lua\luasql\mysql\init.lua'
	no file 'D:\touchsprite_6560\TouchSprite\bin\luasql\mysql.lua'
	no file 'D:\touchsprite_6560\TouchSprite\bin\luasql\mysql\init.lua'
	no file '.\luasql\mysql.lua'
	no file './luasql\mysql.lua'
	no file './luasql\mysql/init.lua'
	no file './lua/luasql\mysql.lua'
	no file './lua/luasql\mysql/init.lua'
	no file 'D:\touchsprite_6560\TouchSprite\lualibs/luasql\mysql/luasql\mysql.lua'
	no file 'D:\touchsprite_6560\TouchSprite\lualibs/luasql\mysql.lua'
	no file 'D:\touchsprite_6560\TouchSprite\lualibs/luasql\mysql/luasql\mysql/init.lua'
	no file 'D:\touchsprite_6560\TouchSprite\lualibs/luasql\mysql/init.lua'
	no file 'D:\touchsprite_6560\TouchSprite\bin\luasql\mysql.dll'
	no file 'D:\touchsprite_6560\TouchSprite\bin\loadall.dll'
	no file '.\luasql\mysql.dll'
	no file 'D:\touchsprite_6560\TouchSprite\bin/luasql\mysql.dll'
	no file 'D:\touchsprite_6560\TouchSprite\bin/clibs/luasql\mysql.dll'
	no file 'D:\touchsprite_6560\TouchSprite\bin\luasql.dll'
	no file 'D:\touchsprite_6560\TouchSprite\bin\loadall.dll'
	no file '.\luasql.dll'
	no file 'D:\touchsprite_6560\TouchSprite\bin/luasql.dll'
	no file 'D:\touchsprite_6560\TouchSprite\bin/clibs/luasql.dll'
stack traceback:
	[C]: in function 'require'
	...hsprite_6560\TouchSprite\workspace\connectMysql\main.lua:1: in main chunk
	[C]: in ?

**Comment by Tieske** [comment]
an easy start would be to use LuaWinMulti, see https://github.com/Tieske/luawinmulti
